### ISSUE TITLE
[face detection] Difference of cpm module between the code and description in Figure 2.(b) in original paper?

### ISSUE THREAD

**Issue by YongtaoGE** [PaddlePaddle/models#1019]
I find the implentation of cpm module is different from the original paper [here](https://github.com/PaddlePaddle/models/blob/8761ab3d1d35d07d47767fad7fa380ffdeba3da7/fluid/face_detection/pyramidbox.py#L165-L199). 
 Could you tell the reason for that?

**Comment by takecareofbigboss** [comment]
hi, we have two versions of implementation of cpm. This implementation is actually somewhat different from the paper because it cost less time for training the model and testing, and the performance is nearly the same. So in paddle repo, i release the advanced version.

**Comment by YongtaoGE** [comment]
Thanks, it helps! @takecareofbigboss
