### ISSUE TITLE
youtube recall: infer_user.py 疑惑

### ISSUE THREAD

**Issue by zachzh** [PaddlePaddle/models#1025]
请教下，infer_user.py中，为啥将load的model的中以下字段初始化为0呢?
是指仅保留userid 作为featue？
线下是不是也做knn的检索就行？
    

# load the trained model.
    with gzip.open(args.model_path) as f:
        parameters = paddle.parameters.Parameters.from_tar(f)
    parameters.set('_proj_province', \
            np.zeros(shape=parameters.get('_proj_province').shape))
    parameters.set('_proj_city', \
            np.zeros(shape=parameters.get('_proj_city').shape))
    parameters.set('_proj_phone', \
            np.zeros(shape=parameters.get('_proj_phone').shape))
    parameters.set('_proj_history_clicked_items', \
            np.zeros(shape= parameters.get('_proj_history_clicked_items').shape))
    parameters.set('_proj_history_clicked_categories', \
            np.zeros(shape= parameters.get('_proj_history_clicked_categories').shape))
    parameters.set('_proj_history_clicked_tags', \
            np.zeros(shape= parameters.get('_proj_history_clicked_tags').shape))

**Comment by guoshengCS** [comment]
infer_user.py看上去是希望只使用userid 作为featue进行预测，@Bella-Zhao 能否帮助解答下~

**Comment by Bella-Zhao** [comment]
是的，infer_user.py只使用userid 作为featue进行预测。
不考虑性能的话，可以线下就用knn暴力搜素。

**Comment by zachzh** [comment]
@Bella-Zhao  多谢解答。
如果只使用userid进行预测，会得到靠谱的结果吗? 毕竟扔掉了很多feature。

**Comment by Bella-Zhao** [comment]
@zachzh  在训练样本充分的情况下，可以预测出uid对应的用户的兴趣。但是这样做的话，对模型没有训练到的uid，就只能预测出一个全局热门的结果了。
