### ISSUE TITLE
ocr识别问题请教，感谢

### ISSUE THREAD

**Issue by fisipro** [PaddlePaddle/models#1043]
各位老师：

我用/models/ocr_recognition训练了模型，并且可以正确识别任意文字（使用与训练数据相同尺寸的图片），但是当我使用任意尺寸的图片时，例如700x68，就无法正确识别。

我看到ctc_reader代码里有个DATA_SHAPE = [1, 48, 512]，不知是否与此有关？我将其改成[1,68,700]运行：
 env CUDA_VISIBLE_DEVICE=0 python infer.py     --model_path="models/model_330000" --input_images_list="/home/dataset/predict.list" --input_images_dir="/home/dataset/predict_images"

后直接报错：

paddle.fluid.core.EnforceNotMet: enforce x_mat_dims[1] == y_mat_dims[0] failed, 1152 != 768
First matrix's width must be equal with second matrix's height. at [/paddle/paddle/fluid/operators/mul_op.cc:59]

请问如何可以识别不定尺寸图片的文字？非常感谢！

**Comment by ktlichkid** [comment]
我感觉这个应该是因为你训练的时候用的尺寸和识别的时候图片尺寸不一致导致的。因为神经网络参数的数目是根据你训练时图片的尺寸决定的，如果数目对不上就做不了卷积等等操作。建议重新用新尺寸的图片训练。

如果没有合适的训练图片的话，可能只能把图片裁剪成一样的大小。比如padding等等

**Comment by fisipro** [comment]
感谢您的回复，如果真实场景中识别无规则长文本的话，是否都需要截断成固定尺寸的图片？真实场景中文字大小、多少也不确定，有什么好的思路吗，谢谢

**Comment by wanghaoshuang** [comment]
@fisipro hi, 预测所用图片的高度必须和训练用图片的高度保持一致，宽度可以随意。因为，在将[image转为sequence的步骤](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition/crnn_ctc_model.py#L82) filter_size为[height, 1], 如果height变化了，[sliced_feature](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition/crnn_ctc_model.py#L79:5)的feature length就会变，也就是这个[fc layer](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition/crnn_ctc_model.py#L98)的input size变了，显然，这样就和这个`fc layer`原来的weight不兼容了。

建议解决办法：
训练的时候用缩放策略A将图片高度缩放至一致；测试的时候用同样的缩放策略A将待预测图片高度缩放至与训练图片一致。
可以尝试opencv提供的各种resize策略。

**Comment by fisipro** [comment]
非常感谢您的回复，我试试

**Comment by ktlichkid** [comment]
The issue seems to be resolved. If there still exists any problem, please fill free to reopen it.
