### ISSUE TITLE
[fluid/object_detection] 用模型提供的训练脚本训练不出任何模型

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/models#1070]
在 Fluid 里面的 Object Detection 中，运行提供的 `train.py`，在输出文件夹里没有任何 `__model__` 文件。 输出日志在这里：

[output_10pass.txt](https://github.com/PaddlePaddle/models/files/2220607/output_10pass.txt)

**Comment by qingqing01** [comment]
@daming-lu  

现在是用[`fluid.io.save_persistables`](https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/train.py#L132)保存的模型，确实没有 `__model__`文件，但在Python里，相应的使用[fluid.io.load_vars](https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/infer.py#L63)是可以load模型的。 如果想保存`__model__`文件，使用[fluid.io.save_inference_model](http://paddlepaddle.org/docs/0.14.0/api/fluid/en/io.html#permalink-7-save_inference_model)保存就可以。
