### ISSUE TITLE
face_detection

### ISSUE THREAD

**Issue by Fairydetail** [PaddlePaddle/models#1076]
https://github.com/PaddlePaddle/models/tree/develop/fluid/face_detection
这个我直接运行train.py报错了，定位在fluid.ParallelExecutor(),说找不到libnccl.so这个动态库。然后我把parallel设置成false了之后就报下面的错了
File "/home/daimin/.conda/envs/py27new/lib/python2.7/site-packages/paddle/fluid/executor.py", line 443, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10244596957 > 1133575936
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
PaddlePaddle Call Stacks: 
0       0x7f2c07a2e2f6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f2c088a65bep paddle::platform::GpuMaxChunkSize() + 766
2       0x7f2c087d668cp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 444
3       0x7f2c087cbd42p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace

**Comment by ktlichkid** [comment]
找不到库的问题可以看下这个，但不一定和您的是同一个问题：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/new_docs/faq/faq.rst

后面的那个错误是说GPU显存不足，fluid版目前要求任务必须占用一块完整的显卡，该显卡上不能有其他任务。所以您可能需要设置一下CUDA visible device环境变量，选择一块空闲的显卡使用。
