### ISSUE TITLE
coco dataset obj detection num_class=81?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/models#1077]
https://github.com/PaddlePaddle/models/blob/a56d95e65c775caacff86f681d616d5444cca180/fluid/object_detection/train.py#L53

**Comment by xingyuanbu** [comment]
Hi Youngstu,
COCO num_class is 81 indeed, while its class ids are not continuous, specifically, the max COCO class id is 90.
So we can use the COCO id as the label, or use a reordered continuous id as the label. To match with [TensorFlow Detection API](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_resnet152_coco.config#L9), we choose the former one.
