### ISSUE TITLE
带gpu跑object_detection时遇到错误

### ISSUE THREAD

**Issue by smallhaes** [PaddlePaddle/models#1078]
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 7433255387 > 366608128
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]

**Comment by ktlichkid** [comment]
这个错误一般是GPU显存不够。目前paddle fluid版本必须使用一整块完整的GPU，上面不能有其他任务。麻烦试试用一块空闲的GPU运行

**Comment by smallhaes** [comment]
显存是8G，没有跑其他任务，只是单独运行train.py，然后就出现 allocating <= available
运行时的参数如下：
ap_version: 11point
apply_distort: True
apply_expand: True
batch_size: 64
data_dir: data/pascalvoc
dataset: pascalvoc
for_model_ce: False
is_toy: 0
iterations: 120
learning_rate: 0.001
mean_value_B: 127.5
mean_value_G: 127.5
mean_value_R: 127.5
model_save_dir: model
nms_threshold: 0.45
num_passes: 120
parallel: False
pretrained_model: pretrained/mobilenet_v1_imagenet/
resize_h: 300
resize_w: 300
skip_batch_num: 5
use_gpu: True
我把parallel设为False也不行
难道最少需要两块8G的显卡吗 /紧张

**Comment by smallhaes** [comment]
难道最少需要两块8G的显卡吗   /紧张

**Comment by ktlichkid** [comment]
麻烦您先试试减小batch_size，例如减小到1看看行不行；
另外可以设置环境变量减小显存使用：export FLAGS_fraction_of_gpu_memory_to_use=0.50
如果有多张显卡的话还可以export CUDA_VISIBLE_DEVICES=2 这样来选择使用的卡
但不一定能彻底解决，您先试试看吧？

**Comment by smallhaes** [comment]
谢啦，调小batch_size就可以，刚开始学，还不熟悉

**Comment by sanwushuosi** [comment]
thx，实测batch_size设置32，刚刚好可以在6G显存下运行，占用6G显存。
另外，parallel不需要设为False也可以。

**Comment by ktlichkid** [comment]
好的，能解决就好~
