### ISSUE TITLE
使用se_resnext训练时遇到问题，麻烦解答

### ISSUE THREAD

**Issue by jxingm** [PaddlePaddle/models#1084]
训练集共近三万张图片，使用se_resnext网络训练过程中，遇到这个问题，
![image](https://user-images.githubusercontent.com/26138842/43385064-59d3db0c-9412-11e8-9787-49c0bad0926f.png)
是什么原因？此外之前用别的数据集别的网络的时候也经常遇到类似的貌似是说内存不够的问题？但数据集并不大，觉得很奇怪。
![image](https://user-images.githubusercontent.com/26138842/43385166-9c2f10f2-9412-11e8-8817-089b7976b080.png)这是我们用的卡。

**Comment by yeyupiaoling** [comment]
@ffmm123456 
这个错误的确是显存不够的，数据集不大，但是网络深度的话，占用的显存也会很大的。
还有Fluid版本要求是要独占显存的。

**Comment by jxingm** [comment]
@yeyupiaoling 谢谢解答。se_resnext用的是50层的，之前用vgg或resnet或SSD也都有这样的问题，fluid版本框架是不是对显存要求比较高呢，或者内存优化不够呢？

**Comment by yeyupiaoling** [comment]
@ffmm123456 
>fluid版本框架是不是对显存要求比较高呢

这个没有经过官方证实，但我测试的时候，的确存在这个问题。
你在训练的时候，不要启动其他占用显卡的的程序会报错吗？

**Comment by jxingm** [comment]
@yeyupiaoling谢谢回复。 恩是的，用的就是空的一张卡，而且我觉得我们那个卡足够跑一个程序了。。你觉得我们用百度AIStudio可以跑吗？那个是只有4G的显存吗？

**Comment by luotao1** [comment]
可以试试 `export FLAGS_fraction_of_gpu_memory_to_use=0.1` (用户自己设定)

**Comment by yeyupiaoling** [comment]
@luotao1 
>fluid版本框架是不是对显存要求比较高呢

这个是事实吗？

**Comment by jxingm** [comment]
@luotao1 谢谢，我试一下

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/4b8ae523c43575ac5411e198f399c9b76889fc36/paddle/fluid/platform/gpu_info.cc#L22-L24

默认启动即占用92%的显存。

**Comment by yeyupiaoling** [comment]
@luotao1 好的，我明白了，谢谢。
