### ISSUE TITLE
face_detection跑一段时间后出现nan

### ISSUE THREAD

**Issue by rockstone533** [PaddlePaddle/models#1087]
Pass 0, batch 4750, face loss 6.25504875183, head loss 5.29047966003, time 41.6653439999
Pass 0, batch 4760, face loss nan, head loss nan, time 42.216219902
Pass 0, batch 4770, face loss nan, head loss nan, time 42.0139110088

face_detection跑一段时间后出现nan，这是为什么？

**Comment by YueXiNPU** [comment]
Hi, my bro. When training PyramidBox, we encountered the same issue. So the issue is solved?

**Comment by neverland0621** [comment]
同问+1

**Comment by qingqing01** [comment]
从您的日志Batch Id和coss来看，您使用了较小的bach size， 似乎使用脚本batch size时该模型容易出nan。建议按照我们教程来，单机4卡，每个3-4batch size，总共12或16的batch size训练， 我们跑过多次都用的该参数，没有nan。
