### ISSUE TITLE
You have error in image_classification/train.py

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/models#1088]
### error message
```
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main()
  File "train.py", line 232, in main
    train(args)
  File "train.py", line 160, in train
    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=avg_cost.name)
  File "/home/sfraczek/paddle/build/python/paddle/fluid/parallel_executor.py", line 97, in __init__
    for i in xrange(core.get_cuda_device_count()):
AttributeError: 'module' object has no attribute 'get_cuda_device_count'
```
### the cause
if use_gpu is False, you still pass use_cuda=True and cause the above error
```
    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=avg_cost.name)
```

### additional note
I compiled with `-DWITH_GPU=OFF`

**Comment by luotao1** [comment]
> if use_gpu is False, you still pass use_cuda=True

If use_gpu is False, why do you pass use_cuda=True? 
What should you want us to do: enhance the API or error report?

**Comment by sfraczek** [comment]
I'm just reporting an error. Leaving the fix to you.
I think it should be
`use_cuda=True if args.use_gpu else False`

**Comment by sfraczek** [comment]
Here: https://github.com/PaddlePaddle/models/blob/53937db0f1a29c90cd4e23c1198d34c81bfed1b2/fluid/image_classification/train.py#L160

**Comment by luotao1** [comment]
Thanks for your pointing, I will fix it.
