### ISSUE TITLE
train language model Segmentation fault

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/models#109]
```
python train.py 
prepare vocab...
Segmentation fault
```
train.txt 1.8GB - chinese UTF-8 Unicode text

cat /proc/meminfo |grep MemTotal
MemTotal:        4048124 kB

**Comment by llxxxll** [comment]
but  default data no problem

**Comment by wanghaoshuang** [comment]
Please paste your train.py?

**Comment by llxxxll** [comment]
default train.py  @wanghaoshuang 
https://github.com/PaddlePaddle/models/blob/develop/language_model/train.py

**Comment by wanghaoshuang** [comment]
You can use [gdb](https://www.cs.cmu.edu/~gilpin/tutorial/) to get more information about the error.
And，I guess the encode of your train data is not right. You can change an English train data to check  the problem.

**Comment by llxxxll** [comment]
the simple data is utf-8 unicode . new data is utf-8 unicode.
I'll look at gdb

**Comment by llxxxll** [comment]
finish！
Edit config.py 

 `build_vocab_method = 'fixed_size'  >>  build_vocab_method = 'frequency'`
