### ISSUE TITLE
能支持局部参数更新么

### ISSUE THREAD

**Issue by chenbblei** [PaddlePaddle/models#1144]
我想做个自适应模型，能否做到前面基层参数不更新，只更新后面几层的呢

**Comment by oraoto** [comment]
我知道的两个方法：

1. 设置Variable的stop_gradient为True: http://paddlepaddle.org/documentation/api/zh/0.14.0/fluid.html#permalink-2-variable
2. Optimizer的minimize方法指定要更新的参数parameter_list:  http://paddlepaddle.org/documentation/api/zh/0.14.0/optimizer.html#permalink-18-optimizer

**Comment by chenbblei** [comment]
@oraoto 有使用的实例么

**Comment by oraoto** [comment]
1. 用到stop_gradient的例子：https://github.com/oraoto/learn_ml/blob/master/paddle/pretrained.ipynb

**Comment by chenbblei** [comment]
@oraoto 好的，多谢
