### ISSUE TITLE
I CANOT download the ssd model.

### ISSUE THREAD

**Issue by wenyawei** [PaddlePaddle/models#1154]
I CANOT download the ssd model.
The pretrained model link is http://paddlepaddle.bj.bcebos.com/model_zoo/detection/ssd_model/vgg_model.tar.gz.

The SSD page link is https://github.com/PaddlePaddle/models/tree/develop/ssd

**Comment by qingqing01** [comment]
@wenyawei https://github.com/PaddlePaddle/models/pull/1411 这里已修复，多谢。另外，也建议使用Fluid训练。
