### ISSUE TITLE
Chinese Ner inference profiling appears linear_chain_crf_grad op

### ISSUE THREAD

**Issue by bingyanghuang** [PaddlePaddle/models#1176]
When I downloaded the latest models and ran the train.sh , infer.sh in fluid/chinese_ner/scripts folder, I got the following profiling results:
![image](https://user-images.githubusercontent.com/33643817/44344485-61baa500-a4c3-11e8-97b9-9961e984874a.png)
linear_chain_crf_grad op should not appear in the inference program. In fact, in the train.py script, it saved "target"  as the feed data with    
` fluid.io.save_inference_model(save_dirname, ['word', 'mention', 'target'], [crf_decode], exe)`
and load models in inference with
`feeder = fluid.DataFeeder(feed_list=[word, mention, target], place=place)`
which doesn't make sense to load label data while doing the inference. 
After I modified the infer.py ,train.py and let it neither save nor load "target", I got the following profiling results:
![image](https://user-images.githubusercontent.com/33643817/44345112-fb368680-a4c4-11e8-9d77-cfd0f1f7657d.png)

which seems correct.

**Comment by Sand3r-** [comment]
Closed as of merging #1180.
