### ISSUE TITLE
Train error about ParamidBox

### ISSUE THREAD

**Issue by DaleAG** [PaddlePaddle/models#1179]
I use 
`pip install paddlepaddle-gpu==0.14.0.post85` 
to install paddlepaddle.
When I run train.py

> Traceback (most recent call last):
>   File "train.py", line 178, in <module>
>     train(args, config, train_file_list, optimizer_method="momentum")
>   File "train.py", line 52, in train
>     sub_network=use_pyramidbox)
>   File "/home/daguo/code/PaddlePaddle_models/fluid/face_detection/pyramidbox.py", line 76, in __init__
>     self._pyramidbox()
>   File "/home/daguo/code/PaddlePaddle_models/fluid/face_detection/pyramidbox.py", line 243, in _pyramidbox
>     face_loc = permute_and_reshape(face_loc, 4)
>   File "/home/daguo/code/PaddlePaddle_models/fluid/face_detection/pyramidbox.py", line 227, in permute_and_reshape
>     np.array([0, -1, last_dim]).astype("int32"))
> TypeError: assign() takes exactly 2 arguments (1 given)

But, I alter 
`            run_shape = fluid.layers.assign(
                np.array([0, -1, last_dim]).astype("int32"))
`
to
`           run_shape = fluid.layers.create_tensor(dtype='int32')`
`            fluid.layers.assign(
                np.array([0, -1, last_dim]).astype("int32"),run_shape)
`

run error is:
> Traceback (most recent call last):
>   File "train.py", line 178, in <module>
>     train(args, config, train_file_list, optimizer_method="momentum")
>   File "train.py", line 81, in train
>     optimizer.minimize(loss)
>   File "/home/daguo/anaconda2/envs/paddle-py27/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 255, in minimize
>     [error_clip_callback])
>   File "/home/daguo/anaconda2/envs/paddle-py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 549, in append_backward
>     grad_to_var, callbacks)
>   File "/home/daguo/anaconda2/envs/paddle-py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 334, in _append_backward_ops_
>     op.desc, no_grad_dict[block.idx], grad_sub_block_list)
> paddle.fluid.core.EnforceNotMet: grad_op_maker_ should not be null
> Operator GradOpMaker has not been registered. at [/paddle/paddle/fluid/framework/op_info.h:61]
> PaddlePaddle Call Stacks: 
> 0       0x7fd0da959736p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
> 1       0x7fd0da95bfe9p paddle::framework::OpInfo::GradOpMaker() const + 137
> 2       0x7fd0da955222p
> 3       0x7fd0da969604p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
> 4       0x7fd1cf7122a3p PyEval_EvalFrameEx + 23091
> 5       0x7fd1cf713dbep PyEval_EvalCodeEx + 2190
> 6       0x7fd1cf7123fap PyEval_EvalFrameEx + 23434
> 7       0x7fd1cf713dbep PyEval_EvalCodeEx + 2190
> 8       0x7fd1cf7123fap PyEval_EvalFrameEx + 23434
> 9       0x7fd1cf713dbep PyEval_EvalCodeEx + 2190
> 10      0x7fd1cf7123fap PyEval_EvalFrameEx + 23434
> 11      0x7fd1cf713dbep PyEval_EvalCodeEx + 2190
> 12      0x7fd1cf7123fap PyEval_EvalFrameEx + 23434
> 13      0x7fd1cf713dbep PyEval_EvalCodeEx + 2190
> 14      0x7fd1cf713ed2p PyEval_EvalCode + 50
> 15      0x7fd1cf733e10p PyRun_FileExFlags + 176
> 16      0x7fd1cf733fefp PyRun_SimpleFileExFlags + 239
> 17      0x7fd1cf7498f4p Py_Main + 3236
> 18      0x7fd1ce947f45p __libc_start_main + 245
> 19            0x400649p

How to solve this problem?

**Comment by ktlichkid** [comment]
I have checked the face detection model but it looks correct. The assign layer could take either 1 or 2 arguments as input. Please try update your paddle version to the latest.

**Comment by hdjsjyl** [comment]
@ktlichkid @DaleAG  I meet the same error here. And I install paddle by using "pip install paddlepaddle-gpu", do I still need to update paddle? And I do not find paddle version for CUDA91, so this command "pip install paddlepaddle-gpu" works for me? Thanks

**Comment by hdjsjyl** [comment]
@ktlichkid  On the official website, it says that "pip install paddlepaddle-gpu" for CUDA9, but when I use this command, it installs paddlepaddle-gpu=0.14.0-post87, which is for CUDA8. I do not know the reason. It is very strange. Thanks

**Comment by hdjsjyl** [comment]
@ktlichkid  On the official document, "fluid.layers.assign" function only has one argument.

**Comment by hdjsjyl** [comment]
@ktlichkid  I have installed paddlepaddle-gpu-0.14.0, it still hows this error, how to solve this problem? Any advice will be appreciated. Thank you very much!

**Comment by qingqing01** [comment]
Need to update paddle version.
