### ISSUE TITLE
resnet101 pretrained model?

### ISSUE THREAD

**Issue by xialeiliu** [PaddlePaddle/models#1203]
I only found the pretrained model for resnet50, do you have resnet101 pretrained model available?

**Comment by qingqing01** [comment]
@xialeiliu ResNet 101 will be released in the future. If you need it urgently, you can use tools https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid

**Comment by xialeiliu** [comment]
Thanks, I will try the tool.
