### ISSUE TITLE
object detection eval.py issue

### ISSUE THREAD

**Issue by chuanqi129** [PaddlePaddle/models#1217]
I met a problem in object detection eval.py scripts as below, could you help me to have a look on it?

`python eval.py --dataset='pascalvoc' --model_dir='ssd_mobilenet_v1_pascalvoc' --data_dir='data/pascalvoc' --test_list='test.txt' --ap_version='11point' --nms_threshold=0.45 --use_gpu=False`
-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 32
data_dir: data/pascalvoc
dataset: pascalvoc
mean_value_B: 127.5
mean_value_G: 127.5
mean_value_R: 127.5
model_dir: ssd_mobilenet_v1_pascalvoc
nms_threshold: 0.45
resize_h: 300
resize_w: 300
test_list: test.txt
use_gpu: 0
------------------------------------------------
/home/chuanqiw/.local/lib/python2.7/site-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
Traceback (most recent call last):
  File "eval.py", line 127, in <module>
    model_dir=args.model_dir)
  File "eval.py", line 90, in eval
    test()
  File "eval.py", line 82, in test
    for batch_id, data in enumerate(test_reader()):
  File "/home/chuanqiw/.local/lib/python2.7/site-packages/paddle/batch.py", line 33, in batch_reader
    r = reader()
TypeError: 'generator' object is not callable

**Comment by baiyfbupt** [comment]
This issue has been fixed in latest develop branch, please update code to latest `develop`

**Comment by chuanqi129** [comment]
Thanks, It works correctly
