### ISSUE TITLE
能帮忙提供一下tensorflow mobilenet_ssd 模型转fluid 工具么？ 

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/models#1236]
我想转 mobilenet_0.5_ssd 模型转为fluid 作为pretrained model。能帮忙提供一个转换工具么？

https://github.com/PaddlePaddle/models/tree/3f1fddbd3cca73cac6beee3b1dbfa1ac3909ab8d/fluid/object_detection
这里有提到你们的mobilenet_ssd 模型pretrained model 是从tensorflow 转过来的，能否给一些思路。

**Comment by qingqing01** [comment]
没有提供通用的转换工具，当时的做法相对繁碎：
1. 将TF的parameter存成npy格式
2. 建立TF参数名字和Fluid参数名字的对应关系
3. 在Fluid的脚本里load npy参数，然后set到Fluid的参数里，再存储模型：

```
place = fluid.CPUPlace()
w = fluid.global_scope().find_var("xxx").get_tensor()
w.set(w_npy, place)
```
