### ISSUE TITLE
face_detection,单gpu可以跑，多个GPU报错

### ISSUE THREAD

**Issue by fangzong12** [PaddlePaddle/models#1244]
*** Aborted at 1536888942 (unix time) try "date -d @1536888942" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 4956 (TID 0x7f5667200700) from PID 0; stack trace: ***
    @     0x7f5666dfc390 (unknown)
    @                0x0 (unknown)
段错误 (核心已转储)

**Comment by fangzong12** [comment]
就是只有parallel关掉才可以跑

**Comment by qingqing01** [comment]
@fangzong12 本地单机多GPU是可以跑的。 请问这个问题现在解决了吗？
