### ISSUE TITLE
fluid/object_detection 现在可否支持自有数据集(custom dataset)？

### ISSUE THREAD

**Issue by YB17** [PaddlePaddle/models#1248]
我在之前的版本看到过，通过调整 config/vgg_config.py 文件内 vgg 超参数等等，可以支持自有数据集的训练。现在出的版本貌似做了较大调整，请问还支持自有数据集吗？如果支持，应该如何做相应的调整呢？谢谢！

**Comment by qingqing01** [comment]
@YB17 可以支持用户自己的数据，参考 reader里的COCO或者[PascalVOC](https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/reader.py#L231)，依据自己的数据格式，读取图片和groud-truth，调用[preprocess函数](https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/reader.py#L267).
