### ISSUE TITLE
DSSM 的 classification 模型中 source 和 target CNN 网络是否是 share 的？

### ISSUE THREAD

**Issue by Miopas** [PaddlePaddle/models#1253]
我训练了一个 cnn 的 dssm 模型，看文档中 source 和 target 的 cnn 应该是单独的，但是把参数解压出来看发现不太一样。

在 `network_conf.py` 代码中这样创建卷积层：
```
            conv_3 = create_conv(3, self.dnn_dims[1], 'cnn')
            conv_4 = create_conv(4, self.dnn_dims[1], 'cnn')
```

<img width="1029" alt="cnnori" src="https://user-images.githubusercontent.com/10841135/45583041-6bca9a80-b8ed-11e8-8ed3-b5b8c4ca9835.png">

参数文件中没有区分开 source 和 target 的 cnn 网络。

我尝试这样修改代码：
```
            conv_3 = create_conv(3, self.dnn_dims[1], prefix + '_cnn')
            conv_4 = create_conv(4, self.dnn_dims[1], prefix + '_cnn')
```

然后解压出来的参数是这样（我的模型是三塔模型，有两个 source 和一个 target）：
<img width="899" alt="cnndebug" src="https://user-images.githubusercontent.com/10841135/45583077-ff9c6680-b8ed-11e8-8301-31449786c2c9.png">

但是神奇的是上面两种做法最后测试起来没有分别。

可能是我对网络结构不太清楚，原始代码里面 source 和 target 的 cnn 是 share 的吗？

**Comment by mapingshuo** [comment]
你好，你的原始代码在哪里？

**Comment by Miopas** [comment]
> 你好，你的原始代码在哪里？

抱歉忘记回复了。DSSM 模型在 PaddlePaddle v2 版本的 model 代码里，现在版本更新为 fluid 我找不到当时的源文件了。我后来验证了原始代码中的 source 和 target 的 cnn 网络确实是 share 的。
