### ISSUE TITLE
cycle_gan 模型问题，文档问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/models#1281]
> 需要使用develop分支最新的paddle编译版本，可以指明一下~

![image](https://user-images.githubusercontent.com/10734244/45871971-65db2a80-bdc1-11e8-850f-f984bcd45ba7.png)
> **TypeError:** 错误，在https://github.com/PaddlePaddle/Paddle/pull/13509/files/4fbe01ec38fb71afd3bbd8264f2f2c282a63000f 修复，待验证。

![image](https://user-images.githubusercontent.com/10734244/45877613-008f3580-bdd1-11e8-92cb-6c4b72642ed7.png)

>  这个路径在readme里没有说明，需要说明一下，而且路径也是有误，需要在*./data*下，见图

![image](https://user-images.githubusercontent.com/10734244/45877075-41864a80-bdcf-11e8-883b-a3b06035e1df.png)

> 预测的指令参数名称有变，需要修改一下~

![image](https://user-images.githubusercontent.com/10734244/45877259-cc674500-bdcf-11e8-9788-ca3193f57c49.png)

> --model_path 没有这个指令了

![image](https://user-images.githubusercontent.com/10734244/45877271-d5581680-bdcf-11e8-8d0a-3ec5eb445ec2.png)

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/Paddle/pull/13509
