### ISSUE TITLE
支持异步模式

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1299]
https://github.com/PaddlePaddle/models/blob/19b3be8ff6feaab5476a93a6abecd2e3d3fed4fe/fluid/neural_machine_translation/transformer/train.py#L610
sync_mode=args.sync

**Comment by guoshengCS** [comment]
请问是有什么问题，另外分布式异步这个目前Transformer的效果应该是还没有保证的，我个人没有验证过

**Comment by kolinwei** [comment]
这个问题先关了，transformer发布的模型暂不支持异步模式。
