### ISSUE TITLE
example configuration for NER.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#13]
- In this example, we would like to show how to do sequence tagging task in PaddlePaddle. We take NER as an example.
- Please refer to [this configuration](https://github.com/lcy-seso/paddle_confs_v1/tree/master/sequence_tagging_for_ner) file written in old PaddlePaddle API.
- The example **must** include the training and the decoding process.
- Please pull your codes and docs into the [sequence_tagging_for_ner](https://github.com/lcy-seso/paddle_confs_v1/blob/master/sequence_tagging_for_ner/ner.conf) directory.

**Comment by guoshengCS** [comment]
Issue on dataset for NER: Is there any way to access NER labeled data? If not, whether or not testing data can be used for training just like what semantic roles labeling in paddle book do.

**Comment by lcy-seso** [comment]
I recommend to use Conll 2003 NER [dataset](http://www.cnts.ua.ac.be/conll2003/ner/).

**Comment by guoshengCS** [comment]
- What is the meaning of the input "ws" in [this configuration](https://github.com/lcy-seso/paddle_confs_v1/tree/master/sequence_tagging_for_ner)?

- The raw data in Conll 2003 NER dataset needs application to NIST, I have sent a request Email.
![image](https://cloud.githubusercontent.com/assets/14105589/25690099/890be8e4-30c0-11e7-9214-dc94928c69c3.png)
