### ISSUE TITLE
KeyError: 'segmented_paragraphs'

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#1305]
https://github.com/xuezhong/models/tree/machine_reading_comprehesion/fluid/machine_reading_comprehesion/DuReader
数据预处理出错：
$ cat data/raw/trainset/search.train.json | python utils/preprocess.py > data/preprocessed/trainset/search.train.json
Traceback (most recent call last):
  File "utils/preprocess.py", line 218, in <module>
    find_fake_answer(sample)
  File "utils/preprocess.py", line 157, in find_fake_answer
    for p_idx, para_tokens in enumerate(doc['segmented_paragraphs']):
KeyError: 'segmented_paragraphs'

**Comment by xuezhong** [comment]
已经更改处理的脚本
