### ISSUE TITLE
About ‘get_shrink()’ in 'models/fluid/face_detection/widerface_eval.py'

### ISSUE THREAD

**Issue by math-yyj** [PaddlePaddle/models#1308]
in 'models/fluid/face_detection/widerface_eval.py', we have 
`def get_shrink(height, width):
    """
    Args:
        height (int): image height.
        width (int): image width.
    """
    # avoid out of memory
    max_shrink_v1 = (0x7fffffff / 577.0 / (height * width))**0.5
    max_shrink_v2 = ((678 * 1024 * 2.0 * 2.0) / (height * width))**0.5

    def get_round(x, loc):
        str_x = str(x)
        if '.' in str_x:
            str_before, str_after = str_x.split('.')
            len_after = len(str_after)
            if len_after >= 3:
                str_final = str_before + '.' + str_after[0:loc]
                return float(str_final)
            else:
                return x

    max_shrink = get_round(min(max_shrink_v1, max_shrink_v2), 2) - 0.3
    if max_shrink >= 1.5 and max_shrink < 2:
        max_shrink = max_shrink - 0.1
    elif max_shrink >= 2 and max_shrink < 3:
        max_shrink = max_shrink - 0.2
    elif max_shrink >= 3 and max_shrink < 4:
        max_shrink = max_shrink - 0.3
    elif max_shrink >= 4 and max_shrink < 5:
        max_shrink = max_shrink - 0.4
    elif max_shrink >= 5:
        max_shrink = max_shrink - 0.5

    shrink = max_shrink if max_shrink < 1 else 1
    return shrink, max_shrink`

my question is , why there are so many ... 'magic numbers' like 0.1, 0.2, etc. Or in other word, why we do this?

**Comment by takecareofbigboss** [comment]
@mathyyj   hi, this is just a strategy to avoid 'out of memory' when testing. It is not a must to use this magic numbers if the memory of gpu is big enough.

**Comment by scharron** [comment]
However this magic does not work in all cases. In my case, I have a lot of our of memory errors because of images too big after going throw this magic.
It seems that the memory used is proportionnal to the image size (height and width).
So, we could probably have a formula that only depends on image size and available memory to avoid these errors, don't you think ?
