### ISSUE TITLE
Faster RCNN 的相关问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/models#1328]
1、在训练阶段需要cocoapi 可以在readme中注明一下。
2、下载脚本./pretrained/download.sh会把模型下载到./pretrained目录下载，但是train.py会在 . 目录下寻找初始模型，会出现找不到问题，不会报错，但训练loss 为nan，需要修改一下download.sh的下载解压路径
3、训练过程会出现程序卡住，没有报错信息， gpu也占用，但是不输出log数据了。 目前已知大概率是驱动问题，384驱动会出问题，396不会。
4、训练过程中异常。见图。
![image](https://user-images.githubusercontent.com/10734244/46421274-5dd99e00-c764-11e8-8b5c-49c99ab06c01.png)
![image](https://user-images.githubusercontent.com/10734244/46421289-65994280-c764-11e8-9073-34cd26ef85cf.png)
![image](https://user-images.githubusercontent.com/10734244/46421297-692cc980-c764-11e8-9340-0f7ea58aaa43.png)

**Comment by jerrywgz** [comment]
目前cocoapi的说明和pretrained model下载路径已修改提交pr
模型训练过程中出现的浮点报错问题正在排查，目前仍未稳定复现

**Comment by qingqing01** [comment]
该问题已修复~
