### ISSUE TITLE
运行模型出错！

### ISSUE THREAD

**Issue by xiaolv3366** [PaddlePaddle/models#1356]
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/paddle/paddle/fluid/platform/gpu_info.cc:33]
我机器有GPU，跑其他Paddle模型没问题。

**Comment by xiaolv3366** [comment]
百度搜索原因大都是让重新安装CUDA，我也准备重新安装，不过再次检查脚本的时候发现在该脚本中指定了使用的显卡硬件。
export CUDA_VISIBLE_DEVICES="1"
可以通过该命令看到需要使用编号为1的显卡，关于显卡编号一般是从0开始编号的，第一块编号为0，第二块编号为1。之前指定使用第二块显卡，计算机上面只有一块显卡，这样会提示上面的报错信息。
将显卡指定行改为如下：
export CUDA_VISIBLE_DEVICES="0"
或者直接不指定也可以。

**Comment by bb9696aa** [comment]
@xiaolv3366 谢谢，问题解决了。脚本一般默认应该写成0的，这里太坑了。
