### ISSUE TITLE
About PyramidBox, how to match head box with face gt? I could not find the code implementing formula(4) as in the papaer.

### ISSUE THREAD

**Issue by Edwardmark** [PaddlePaddle/models#1371]
About PyramidBox, how to match head box with face gt? I could not find the code implementing formula(4) as in the papar.
Please comment. Thanks.

**Comment by qingqing01** [comment]
In the reader, expand face gt boxes to head box, https://github.com/PaddlePaddle/models/blob/develop/fluid/face_detection/reader.py#L273 . Then in the network, use the head boxes to compute head loss, https://github.com/PaddlePaddle/models/blob/develop/fluid/face_detection/pyramidbox.py#L444

**Comment by Edwardmark** [comment]
@qingqing01 Thanks for you reply, but I cannot find where is the definition of the pyramid loss as:  
https://github.com/PaddlePaddle/models/blob/develop/fluid/face_detection/pyramidbox.py#L444  
where is the fluid.layers.ssd_loss definition? Looking forward to your reply. Thanks.

**Comment by qingqing01** [comment]
@Edwardmark Sorry for the later reply.  The loss in PyramidBox contains face loss and head loss.  The ssd_loss definition is here: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/detection.py#L672 , which contains lots of sub operators and is the same as `multibox_loss_layer` in Caffe https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/multibox_loss_layer.cpp

**Comment by Edwardmark** [comment]
@qingqing01 Thanks, but I want to know what weights assigned to head loss and body loss? How to set them is best in your experiments.

**Comment by qingqing01** [comment]
@Edwardmark The [results in doc](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/face_detection#%E6%A8%A1%E5%9E%8B%E5%8F%91%E5%B8%83), we just use face loss and head loss.  Actually body loss is not used.  If body loss is added, you can try small weights, like 0.1 or 0.5.

**Comment by Edwardmark** [comment]
@qingqing01 Thanks. So the weight for face and head is the same?

**Comment by qingqing01** [comment]
@Edwardmark Yeah.  weight is the same for face and head loss.
