### ISSUE TITLE
多GPU执行问题，多GPU执行时任务挂起无法完成

### ISSUE THREAD

**Issue by duanlin0505** [PaddlePaddle/models#1375]
以/models-develop/fluid/language_model为例，默认执行fluid train.py，任务长时间挂起，GPU的状态也很奇怪：内存和使用率都满的，但是从功率看，GPU芯片又几乎没有工作。如果改为非并行方式，单GPU时则没有问题。
paddle版本1.0.2

**Comment by typhoonzero** [comment]
经验证，该问题和用户运行环境相关，尝试更新nccl2版本，仍然可以复现，请尝试使用其他干净环境测试。或使用docker

**Comment by duanlin0505** [comment]
问题原因已经找到，是机器pcie的一个GPU与GPU Peer to Peer通信的配置问题，修改后，nccl的并行库就可以正常执行了。
