### ISSUE TITLE
SSD训练生成脚本，求共享

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/models#1383]
SSD训练生成脚本，求共享

**Comment by qingqing01** [comment]
@930083287 请问您具体指的是什么脚本？ 是预测吗？如果是Fluid模型，https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection 这里有训练脚本、评估脚本、预测脚本。

**Comment by qingqing01** [comment]
由于长时间未回复，暂且关闭该Issue，有问题可以再打开。
