### ISSUE TITLE
http://paddlepaddle.bj.bcebos.com/model_zoo/detection/ssd_model/vgg_model.tar.gz 下载失败

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/models#1385]
http://paddlepaddle.bj.bcebos.com/model_zoo/detection/ssd_model/vgg_model.tar.gz 下载失败

**Comment by mapingshuo** [comment]
same as #1154

**Comment by qingqing01** [comment]
@930083287 https://github.com/PaddlePaddle/models/pull/1411 这里已修复，多谢。另外，也建议使用Fluid训练。
