### ISSUE TITLE
python3 paddlepaddle1.1版本的language_model的lstm模型报错

### ISSUE THREAD

**Issue by lipanpan03** [PaddlePaddle/models#1423]
在python3 paddlepaddle1.1版本环境下运行language_model的lstm模型时报错，AttributeError: 'str' object has no attribute 'decode'，如图
![default](https://user-images.githubusercontent.com/41904587/47889857-163f5280-de87-11e8-972b-c22c951dec9f.png)

**Comment by phlrain** [comment]
问题已经fix，在等merge
