### ISSUE TITLE
ocr_recognition二次开发应用到车牌识别，原ocr是62个字符，车牌是65个字符包含中文

### ISSUE THREAD

**Issue by xiaoming521** [PaddlePaddle/models#1433]
原ocr是62个字符，包括0-9,a-z,和A-Z；我的车牌数据集是65个字符，包括汉字和0-9和A-Z；生成的车牌数据图片大小和原ocr数据集大小一样，都为【384,48,1】；把车牌数据输入给网络，训练和测试准确率迭代10000词全部都为0，这是不是和model原字典的a对应ASCII-33的值和num_class=95（62+33）有关系呢？任务紧急，感谢各位大神解答
下面是原数据集和我生成的车牌数据集，还有运行参数和结果
![default](https://user-images.githubusercontent.com/29424644/48183975-8a886300-e36b-11e8-939a-868e55615697.png)
![default](https://user-images.githubusercontent.com/29424644/48183986-9116da80-e36b-11e8-9a5e-c724bd320cfa.png)
![default](https://user-images.githubusercontent.com/29424644/48184004-9bd16f80-e36b-11e8-846e-9be3619a11b4.png)
![default](https://user-images.githubusercontent.com/29424644/48184020-a68c0480-e36b-11e8-9c61-218bbc8dcc85.png)

**Comment by xiaoming521** [comment]
由于汉字没法用ASCII-33对应的值表示，所以我车牌字典对应的值不是ASCII-33,就是从0开始设置的，准确率一直为0 ，是不是和字典对应值不和model一致，或者是不是和num_class为65了，不为62有关系呢？还有这个num_class设置为95 表示的是啥意思呢？要是以上都没有关系是不是和我训练集6万张太少，还有迭代次数只迭代1万次有关呢？

**Comment by baihaojie2011** [comment]
使用 GPU训练也存在问题。报错
![1](https://user-images.githubusercontent.com/27996442/48197559-106ad500-e391-11e8-85ac-ed5572eea515.png)
![2](https://user-images.githubusercontent.com/27996442/48197568-12cd2f00-e391-11e8-900e-2673100683d4.png)

**Comment by wanghaoshuang** [comment]
@xiaoming521 和num_class=95没有关系；你的字符数量是65个，确认下你label的编码是严格从0到64么？

**Comment by wanghaoshuang** [comment]
另外你训练的太少了，还不到一个epoch.

**Comment by xiaoming521** [comment]
@输入原来的验证码数据集后，3000次迭代后也是0，所以证明问题可能出在我的训练次数太少了，我把迭代次数设置为720000，训练集扩大到39万张图片试一下，之前一直是6万张，不过源代码GPU好像不能用，cpu跑720000次时间代价又太大
![default](https://user-images.githubusercontent.com/29424644/48201041-f1be0b80-e39b-11e8-87c2-19992be3c66a.png)

@qingqing01

**Comment by qingqing01** [comment]
@baihaojie2011  请问您机器上有几个GPU，以及你使用的Paddle版本是多少？贴下nvidia-smi信息看下呢？ 另外也可以以下方式试下：

```
export CUDA_VISIBLE_DEVICES=0
python train.py --use_gpu=True
```

**Comment by wanghaoshuang** [comment]
以下是我在英文数据上的部分训练loss， 供参考：
```
Time: 1532361306.36; Iter[1200]; Avg loss: 33.759; Avg seq err: 1.000

Time: 1532361450.93; Iter[2400]; Avg loss: 30.808; Avg seq err: 1.000

Time: 1532361595.48; Iter[3600]; Avg loss: 30.681; Avg seq err: 1.000

Time: 1532361739.67; Iter[4800]; Avg loss: 30.336; Avg seq err: 1.000

Time: 1532361884.38; Iter[6000]; Avg loss: 29.988; Avg seq err: 1.000

Time: 1532362029.8; Iter[7200]; Avg loss: 29.723; Avg seq err: 1.000

Time: 1532362176.87; Iter[8400]; Avg loss: 24.779; Avg seq err: 0.997

Time: 1532362325.06; Iter[9600]; Avg loss: 10.931; Avg seq err: 0.819

Time: 1532362473.43; Iter[10800]; Avg loss: 7.660; Avg seq err: 0.646

Time: 1532362622.17; Iter[12000]; Avg loss: 6.684; Avg seq err: 0.568

Time: 1532362708.41; Iter[12481]; Test seq error: 1.0.


Time: 1532362797.9; Iter[13200]; Avg loss: 3.530; Avg seq err: 0.310

Time: 1532362947.16; Iter[14400]; Avg loss: 5.499; Avg seq err: 0.489

Time: 1532363096.72; Iter[15600]; Avg loss: 5.229; Avg seq err: 0.468

Time: 1532363245.46; Iter[16800]; Avg loss: 5.033; Avg seq err: 0.449

Time: 1532363394.38; Iter[18000]; Avg loss: 4.916; Avg seq err: 0.442

Time: 1532363543.42; Iter[19200]; Avg loss: 4.726; Avg seq err: 0.421

Time: 1532363692.78; Iter[20400]; Avg loss: 4.558; Avg seq err: 0.417

Time: 1532363841.43; Iter[21600]; Avg loss: 4.502; Avg seq err: 0.407

Time: 1532363990.61; Iter[22800]; Avg loss: 4.366; Avg seq err: 0.397

Time: 1532364139.35; Iter[24000]; Avg loss: 4.361; Avg seq err: 0.395

Time: 1532364284.83; Iter[24962]; Test seq error: 0.40600002.
```

**Comment by wanghaoshuang** [comment]
建议你统计下你的训练集的label数据，num_class设置为最大的label编码+1。

**Comment by xiaoming521** [comment]
恩恩，问题可能出在训练集6万张太小和迭代次数12000次太少了，看您上边的39万张迭代8400次才err==0.977

**Comment by xiaoming521** [comment]
请问这个代码是fluid最新版1.1版吗?我的版本应该是最新版1.1
![default](https://user-images.githubusercontent.com/29424644/48202696-93dff280-e3a0-11e8-8a7f-0388a9d0e44e.png)
@qingqing01

**Comment by Yipeng-Sun** [comment]
1. 确保原始95类英文数据训练是否可复现？2. 65个类别，check label映射正确，num_class设置正确 3. 车牌合成数据可以扩展到20W，一卡GPU迭代一天，训练正常就可以收敛。建议按1.2.3顺序依次check, 确保环境、数据label等无误

**Comment by xiaoming521** [comment]
感谢各位的解惑，车牌模型已经基本跑通，但是GPU还是提示不能用，不知道是不是paddle底层的问题？
![default](https://user-images.githubusercontent.com/29424644/48254372-d5c27480-e444-11e8-9f11-78b1e64544a4.png)


![default](https://user-images.githubusercontent.com/29424644/48254348-c7745880-e444-11e8-9df9-27921bd52c67.png)

**Comment by qingqing01** [comment]
@xiaoming521 

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/operator.cc#L146

从源码报错地方来看，是安装版本问题，请注意安装GPU版本。
