### ISSUE TITLE
Training-aware INT8 for SSD-MobileNet

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/models#1455]
I would like to try training-aware INT8 for MobileNetSSD. I followed the instructions in https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_quant.md and ran the below command:
 
python main_quant.py --data_dir=/lustre/dataset/VOC/VOCdevkit/VOC2012 --mode='train' --init_model=ssd_mobilenet_v1_pascalvoc --act_quant_type='abs_max' --epoc_num=20 --learning_rate=0.0001 --batch_size=64 --model_save_dir=train_int8
 
It shows the error message:
Traceback (most recent call last):
  File "main_quant.py", line 275, in <module>
    ap_version = args.ap_version)
  File "/home/hshen14/paddle_public_models/fluid/PaddleCV/object_detection/reader.py", line 45, in __init__
    for line in open(label_fpath):
IOError: [Errno 2] No such file or directory: '/lustre/dataset/VOC/VOCdevkit/VOC2012/label_list'

I attached the structure under /lustre/dataset/VOC/VOCdevkit/VOC2012/ for your reference:
Annotations/        JPEGImages/         SegmentationObject/
ImageSets/          SegmentationClass/

From the error message, looks like there is no label_list file. Could you please show the full structure at you side? Thanks.

@qingqing01 @Superjomn

**Comment by qingqing01** [comment]
@hshen14  `label_list` is in `https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection/data/pascalvoc`.

You can put `label_list` in `/lustre/dataset/VOC/VOCdevkit/VOC2012`.

In our doc, we tell users to download data in `data/pascalvoc/` and create `trainval.txt` and `test.txt` in `data/pascalvoc/`. The `label_list` is also in this path. So there is no problem.

**Comment by qingqing01** [comment]
```
 pwd
/home/users/dangqingqing/data/PascalVOC
 tree -L 2
.
|-- label_list
|-- test.txt
|-- trainval.txt
`-- VOCdevkit
    |-- VOC2007
    `-- VOC2012

3 directories, 4 files
```

**Comment by hshen14** [comment]
Thanks @qingqing01. There are two issues:
* the script does not import multiprocessing python library - should fix it.
* after fixing, I met the below issue - does it support CPU training?

```
[hshen14@mlt-skx054 object_detection]$ python main_quant.py --data_dir=data/pascalvoc/ 
--mode='train' --init_model=ssd_mobilenet_v1_pascalvoc --act_quant_type='abs_max' --epoc_num=20 --learning_rate=0.0001 --batch_size=64 --model_save_dir=train_int8 --use_gpu=False
-----------  Configuration Arguments -----------
act_quant_type: abs_max
ap_version: 11point
batch_size: 64
confs_threshold: 0.5
data_dir: data/pascalvoc/
epoc_num: 20
image_path:
image_shape: 3,300,300
init_model: ssd_mobilenet_v1_pascalvoc
learning_rate: 0.0001
lr_decay_rates: 1,0.1,0.01
lr_epochs: 30,60
mean_BGR: 127.5,127.5,127.5
mode: train
model_save_dir: train_int8
parallel: True
use_gpu: 0
------------------------------------------------
/home/hshen14/.local/lib/python2.7/site-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
Load init model ssd_mobilenet_v1_pascalvoc.
Traceback (most recent call last):
  File "main_quant.py", line 278, in <module>
    train(args, data_args, train_parameters[dataset], train_list, val_list)
  File "main_quant.py", line 131, in train
    use_cuda=use_gpu, loss_name=loss.name)
  File "/home/hshen14/.local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 115, in __init__
    exec_strategy.use_cuda = use_cuda
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: paddle.fluid.core.ExecutionStrategy, arg1: bool) -> None

Invoked with: <paddle.fluid.core.ExecutionStrategy object at 0x5ab4990>, 0
```

**Comment by qingqing01** [comment]
@hshen14 Thanks very much. Fixed in https://github.com/PaddlePaddle/models/pull/1457
