### ISSUE TITLE
How the accumulative MAP is calculated?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/models#1469]
I have a MobileNet-SSD model with trained parameters from Baidu. Also, I have generated a model with the `DetectionMAP` layer saved. However, I can see the `DetectionMAP` requires some parameters which are not present with the model from Baidu. These parameters are used for calculation of the accumulative MAP. 
How the accumulative MAP is calculated?
Can it be calculated without those missing parameters? (e.g. as an average of bach MAPs)
Do you have also trained parameters for the `DetectionMAP` layer?

**Comment by qingqing01** [comment]
> How the accumulative MAP is calculated?
> Can it be calculated without those missing parameters? (e.g. as an average of bach MAPs)

See the [Python API](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/metrics.py#L666) . It's a litte complicated, not average bach mAPs simply.  ( see [source code](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection_map_op.h) ).  The accumulative needs some state from previous mini-batch, then merge them and calculate current mAP. 

Actually we always use python source code with network description, not serialized binary program-desc for train.

Why do you use the serialized binary program-desc for train or evalution?

>  Do you have also trained parameters for the DetectionMAP layer?

This is not available now.  Maybe can use `evaly.py` and `save_persistable` to save them.

**Comment by sfraczek** [comment]
>Why do you use the serialized binary program-desc for train or evalution?

We use it for CAPI.

**Comment by wojtuss** [comment]
@qingqing01 , Thank you!

I use a MobileNet-SSD model with the `DetectionMAP` layer, generated using the `save_inference_model()` method (as described in https://github.com/PaddlePaddle/models/issues/1459#issuecomment-439877157), with parameters taken from an already trained model from Baidu (http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz).
In our C-API application we get the accumulative MAP accuracy different from the one we get from python `eval.py` script (57.28% vs. 73.25%). I wondered if the parameters of the `DetectionMAP` layer are important here, but now I think they are not.
Actually it turned out that the batch MAP also differs between C-API and python for corresponding iterations, so the accumulative MAP cannot also be equal :-(
We have to find the reason of the difference and fix it.

**Comment by sfraczek** [comment]
We've got it working now :)

**Comment by qingqing01** [comment]
@sfraczek How to solve it?

**Comment by wojtuss** [comment]
It turned out that we were doing different image preprocessing. With unified preprocessing the accuracy results are very similar.
