### ISSUE TITLE
object-detection train VOC dataset error

### ISSUE THREAD

**Issue by dreamonezero** [PaddlePaddle/models#1495]
Epoc 119, batch 480, loss 1.927295, time 0.40952
Epoc 119, batch 500, loss 2.137074, time 0.45071
Batch 0, map [0.76862]
Batch 10, map [0.75564057]
Batch 20, map [0.7315956]
Batch 30, map [0.7257414]
Batch 40, map [0.731006]
Batch 50, map [0.7274335]
Batch 60, map [0.73014474]
Batch 70, map [0.72777504]
Batch 80, map [0.7303445]
Batch 90, map [0.72797]
Batch 100, map [0.7287172]
Batch 110, map [0.7259103]
Batch 120, map [0.72657454]
Batch 130, map [0.72408175]
Batch 140, map [0.7239978]
Batch 150, map [0.7226571]
Epoc 119, test map [0.72133386]
Best test map 0.723139166832
save models to model/119
*** Aborted at 1543875979 (unix time) try "date -d @1543875979" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 6048 (TID 0x7feafe425700) from PID 8; stack trace: ***
    @     0x7feb5b6ac390 (unknown)
    @           0x4bd6b0 PyEval_EvalFrameEx
    @           0x4b9b66 PyEval_EvalCodeEx
    @           0x4d57a3 (unknown)
    @           0x4a587e PyObject_Call
    @           0x4be51e PyEval_EvalFrameEx
    @           0x4c141f PyEval_EvalFrameEx
    @           0x4c141f PyEval_EvalFrameEx
    @           0x4b9b66 PyEval_EvalCodeEx
    @           0x4d5669 (unknown)
    @           0x4eef5e (unknown)
    @           0x4a587e PyObject_Call
    @           0x4c5ef0 PyEval_CallObjectWithKeywords
    @           0x589662 (unknown)
    @     0x7feb5b6a26ba start_thread
    @     0x7feb5b3d841d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by qingqing01** [comment]
@dreamonezero In fact, there is no problem in your training. The final error doest affect the training. It is some error when Python muliti-process existing at last.

**Comment by abcdvzz** [comment]
> @dreamonezero In fact, there is no problem in your training. The final error doest affect the training. It is some error when Python muliti-process existing at last.

So how to fix this ？

**Comment by qingqing01** [comment]
@abcdvzz Sorry, I don't find a solution now.  Although it desn't affect the results, the output is not elegant.  Maybe we will change other multi-process reader later.  :(
