### ISSUE TITLE
使用save_inference_model()保存crnnctc的__model__文件

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/models#1496]
1. 在models/fluid/PaddleCV/ocr_recognition, 我想使用train.py的def test()里添加以下下面的代码来保存crnn_ctc的__model__文件

fluid.io.save_inference_model(args.save_model_dir,["image","label"],test_seq_error,exe,main_program=inference_program)

但运行有错误  ValueError: 'target_vars' should be a list of Variable.
也尝试了 fluid.io.save_inference_model(args.save_model_dir,["image","label"],[test_seq_error[0]],exe,main_program=inference_program)，还是一样的错误，请问怎么存啊？

2. 如果可以，能否提供crnn_ctc的__model__可以参考下，如果是有accuracy layer就更好了，没有的话我也可以自己存。 谢谢

**Comment by luotao1** [comment]
Maybe you can find the intel internal help https://github.com/PaddlePaddle/Paddle/issues/14342#issuecomment-438538424

**Comment by ghost** [comment]
We solved it by fluid.io.save_inference_model(args.save_model_dir, ["pixel","label"], fetch_vars, exe, main_program=inference_program) . fetch_vars is declared earlier in train.py,     fetch_vars = [sum_cost] + error_evaluator.metrics
