### ISSUE TITLE
ShuffleNet Pre-trained model and accuracy

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/models#1506]
shufflenet_v2.py is one of image classification models. Could you please share the pre-trained model and the corresponding accuracy?

**Comment by shippingwang** [comment]
@hshen14  In progress.

**Comment by shippingwang** [comment]
already released in version 1.4,
feel free to reopen this issue if still have suggestions.

**Comment by zzchust** [comment]
> already released in version 1.4,
> feel free to reopen this issue if still have suggestions.

Is there pre-trained shhufflenetv2x0.5 and shufflenetv0.25, since it is important for mobile application ?
