### ISSUE TITLE
【自定义图像分类infer时出现错误】EnforceNotMet: Enforce failed. Expected in_dims[1] == filter_dims[1] * groups, but received in_dims[1]:4 != filter_dims[1] * groups:3.

### ISSUE THREAD

**Issue by 315536712** [PaddlePaddle/models#1510]
问题描述：自定义图像数据集训练的是时候都没有问题，模型也都保存了，但是在进行预测的时候报错。
使用的模型：vgg
参照的代码：03.image_classification
详细报错：
---------------------------------------------------------------------------
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-11-e5f85816241b> in <module>
     61 
     62 
---> 63 infer(use_cuda=False, params_dirname='/home/aistudio/data2187/model')
     64 print('over')

<ipython-input-11-e5f85816241b> in infer(use_cuda, params_dirname)
     44             inference_program,
     45             feed={feed_target_names[0]: img},
---> 46             fetch_list=fetch_targets)
     47 
     48         transpiler_results = exe.run(

/opt/conda/envs/py35-paddle1.0.0/lib/python3.5/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    468 
    469         self._feed_data(program, feed, feed_var_name, scope)
--> 470         self.executor.run(program.desc, scope, 0, True, True)
    471         outs = self._fetch_data(fetch_list, fetch_var_name, scope)
    472         if return_numpy:

EnforceNotMet: Enforce failed. Expected in_dims[1] == filter_dims[1] * groups, but received in_dims[1]:4 != filter_dims[1] * groups:3.
The number of input channels should be equal to filter channels * groups. at [/paddle/paddle/fluid/operators/conv_op.cc:60]
PaddlePaddle Call Stacks: 
0       0x7f3fe209e426p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f3fe290d616p paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const + 5622
2       0x7f3fe2c121edp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 77
3       0x7f3fe2c0e7bfp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 255
4       0x7f3fe215f2eap paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 298
5       0x7f3fe215fce0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7f3fe2085cddp
7       0x7f3fe20d0be4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7f401de1f199p PyCFunction_Call + 233
9       0x7f401deba3f9p PyEval_EvalFrameEx + 33545
10      0x7f401debc4b6p
11      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
12      0x7f401debc4b6p
13      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
14      0x7f401debc4b6p
15      0x7f401debc5a8p PyEval_EvalCodeEx + 72
16      0x7f401debc5ebp PyEval_EvalCode + 59
17      0x7f401deafc5dp
18      0x7f401de1f179p PyCFunction_Call + 201
19      0x7f401deb9dbep PyEval_EvalFrameEx + 31950
20      0x7f401ddf3410p _PyGen_Send + 128
21      0x7f401deb8953p PyEval_EvalFrameEx + 26723
22      0x7f401ddf3410p _PyGen_Send + 128
23      0x7f401deb8953p PyEval_EvalFrameEx + 26723
24      0x7f401ddf3410p _PyGen_Send + 128
25      0x7f401deb9d60p PyEval_EvalFrameEx + 31856
26      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
27      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
28      0x7f401debc4b6p
29      0x7f401debc5a8p PyEval_EvalCodeEx + 72
30      0x7f401ddfbc33p
31      0x7f401ddca33ap PyObject_Call + 106
32      0x7f401deb46eep PyEval_EvalFrameEx + 9726
33      0x7f401debc4b6p
34      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
35      0x7f401ddf26bap
36      0x7f401deadaf6p
37      0x7f401de1f179p PyCFunction_Call + 201
38      0x7f401deb9dbep PyEval_EvalFrameEx + 31950
39      0x7f401debc4b6p
40      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
41      0x7f401ddf26bap
42      0x7f401deadaf6p
43      0x7f401de1f179p PyCFunction_Call + 201
44      0x7f401deb9dbep PyEval_EvalFrameEx + 31950
45      0x7f401debc4b6p
46      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
47      0x7f401ddf26bap
48      0x7f401deadaf6p
49      0x7f401de1f179p PyCFunction_Call + 201
50      0x7f401deb9dbep PyEval_EvalFrameEx + 31950
51      0x7f401debc4b6p
52      0x7f401debc5a8p PyEval_EvalCodeEx + 72
53      0x7f401ddfbb56p
54      0x7f401ddca33ap PyObject_Call + 106
55      0x7f401deb46eep PyEval_EvalFrameEx + 9726
56      0x7f401ddf3410p _PyGen_Send + 128
57      0x7f401deb9d60p PyEval_EvalFrameEx + 31856
58      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
59      0x7f401debc4b6p
60      0x7f401debc5a8p PyEval_EvalCodeEx + 72
61      0x7f401ddfbc33p
62      0x7f401ddca33ap PyObject_Call + 106
63      0x7f401deb46eep PyEval_EvalFrameEx + 9726
64      0x7f401debc4b6p
65      0x7f401debc5a8p PyEval_EvalCodeEx + 72
66      0x7f401ddfbb56p
67      0x7f401ddca33ap PyObject_Call + 106
68      0x7f401df2fccap
69      0x7f401ddca33ap PyObject_Call + 106
70      0x7f401deb64c5p PyEval_EvalFrameEx + 17365
71      0x7f401debc4b6p
72      0x7f401debc5a8p PyEval_EvalCodeEx + 72
73      0x7f401ddfbb56p
74      0x7f401ddca33ap PyObject_Call + 106
75      0x7f401deb46eep PyEval_EvalFrameEx + 9726
76      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
77      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
78      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
79      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
80      0x7f401deba1d0p PyEval_EvalFrameEx + 32992
81      0x7f401debc4b6p
82      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
83      0x7f401debc4b6p
84      0x7f401debc5a8p PyEval_EvalCodeEx + 72
85      0x7f401debc5ebp PyEval_EvalCode + 59
86      0x7f401deafc5dp
87      0x7f401de1f179p PyCFunction_Call + 201
88      0x7f401deb9dbep PyEval_EvalFrameEx + 31950
89      0x7f401debc4b6p
90      0x7f401deb95b5p PyEval_EvalFrameEx + 29893
91      0x7f401debc4b6p
92      0x7f401debc5a8p PyEval_EvalCodeEx + 72
93      0x7f401ddfbb56p
94      0x7f401ddca33ap PyObject_Call + 106
95      0x7f401df08ba1p
96      0x7f401df094a5p Py_Main + 1493
97            0x400b54p main + 356
98      0x7f401ce7d830p __libc_start_main + 240
99            0x400c01p

**Comment by wzzju** [comment]
根据您的报错信息可知`in_dims[1]:4 != filter_dims[1] * groups:3`，在进行卷积时，您的输入特征图通道数（in_dims[1]:4）与卷积核的通道数（` filter_dims[1] * groups:3`）不相等，请检查您的输入。或者既然训练时没问题，您可以尝试使用训练数据作为输入，看看是否还有此问题。

**Comment by 315536712** [comment]
多谢
