### ISSUE TITLE
Face detection run error

### ISSUE THREAD

**Issue by abcdvzz** [PaddlePaddle/models#1511]
Something went wrong when I ran the code:

> -----------  Configuration Arguments -----------
batch_size: 16
data_dir: data
epoc_num: 160
learning_rate: 0.001
mean_BGR: 104., 117., 123.
model_save_dir: output
parallel: True
pretrained_model: vgg_ilsvrc_16_fc_reduced
resize_h: 640
resize_w: 640
use_gpu: True
use_pyramidbox: True
with_mem_opt: True

 ------------------------------------------------

>Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train(args, config, train_parameters, train_file_list)
  File "train.py", line 133, in train
    exe.run(startup_prog)
  File "/home/yzzc/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
PaddlePaddle Call Stacks: 
0       0x7f6868e8bb16p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f6869c9e8e2p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 658
2       0x7f6868f57140p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
3       0x7f6868f57840p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
4       0x7f6868e7997bp
5       0x7f6868ea9ba0p
6             0x4ea137p PyCFunction_Call + 119
7             0x53c176p PyEval_EvalFrameEx + 23030
8             0x53fc97p
9             0x53b83fp PyEval_EvalFrameEx + 20671
10            0x5401efp
11            0x53bc93p PyEval_EvalFrameEx + 21779
12            0x53fc97p
13            0x5409bfp PyEval_EvalCode + 31
14            0x60cb42p
15            0x60efeap PyRun_FileExFlags + 154
16            0x60f7dcp PyRun_SimpleFileExFlags + 444
17            0x640256p Py_Main + 1110
18            0x4d0001p main + 225
19      0x7f68c7758830p __libc_start_main + 240
20            0x5d6999p _start + 41

**Comment by wzzju** [comment]
Please describe your question in detail, not just copy the log.

**Comment by qingqing01** [comment]
```
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
```

Please ensure your env can run Paddle normly on GPU.
