### ISSUE TITLE
models/legacy/ctr 下 执行报错 （尝试了 paddlepaddle1.1.0 和 1.2.0 都报错）

### ISSUE THREAD

**Issue by jackyhawk** [PaddlePaddle/models#1519]
+ /data0/home/jy/python_installed/bin/python train.py --train_data_path /data0/home/jy/models/legacy/ctr/output/train.txt --test_data_path /data0/home/jy/models/legacy/ctr/output/test.txt --data_meta_file /data0/home/jy/models/legacy/ctr/output/data.meta.txt --model_type=0                                                             
I1211 17:36:28.149034 48067 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1                                                                              
INFO:paddle:dnn input dim: 61                                                                                                                                          
INFO:paddle:lr input dim: 10040001                                                                                                                                     
I1211 17:36:28.244935 48067 GradientMachine.cpp:94] Initing parameters..                                                                                               
I1211 17:36:28.840200 48067 GradientMachine.cpp:101] Init parameters done.                                                                                             
INFO:paddle:load trainset from /data0/home/jy/models/legacy/ctr/output/train.txt                                                                                       
WARNING:paddle:Pass 0, Samples 0, Cost 0.686135, {}                                                                                                                    
INFO:paddle:load testset from /data0/home/jy/models/legacy/ctr/output/test.txt                                                                                         
end___before                                                                                                                                                           
before                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                     
  File "train.py", line 114, in <module>                                                                                                                               
    train()                                                                                                                                                            
  File "train.py", line 110, in train                                                                                                                                  
    num_passes=args.num_passes)                                                                                                                                        
  File "/data0/home/jy/python_installed/lib/python2.7/site-packages/paddle/v2/trainer.py", line 206, in train                                                          
    gm=self.__gradient_machine__))                                                                                                                                     
  File "train.py", line 92, in __event_handler__                                                                                                                       
    feeding=reader.feeding_index)                                                                                                                                      
  File "/data0/home/jy/python_installed/lib/python2.7/site-packages/paddle/v2/trainer.py", line 247, in test                                                           
    evaluator=evaluator, cost=total_cost / num_samples)                                                                                                                
ZeroDivisionError: float division by zero                                                                                                                              
~

**Comment by jackyhawk** [comment]
貌似 在 train() 里边加一个 print('start') 会 去load data，而不再报  WARNING:paddle:Pass 0, Samples 0, Cost 0.686135, {}

**Comment by Hizhaoyuan** [comment]
ZeroDivisionError: float division by zero 这提示很明显啊，分母出现零了

**Comment by jackyhawk** [comment]
是的，但是 我就按照正常的流程跑的，怎么会 出现 分母是 0 呢？ 多谢 @zhaoyuanGItHub

**Comment by jackyhawk** [comment]
这个是  官方输入：

/data0/home/jy/python_installed/bin/python train.py --train_data_path /data0/home/jy/models/legacy/ctr/output/train.txt --test_data_path /data0/home/jy/models/legacy/ctr/output/test.txt --data_meta_file /data0/home/jy/models/legacy/ctr/output/data.meta.txt --model_type=0

数据也都在了（确认过n遍了），大伙有遇到过吗？

**Comment by jackyhawk** [comment]
发现官方 在数据准备的时候，默认参数是 100，导致的。。。。

**Comment by Yve-Neal** [comment]
@jackyhawk 你好，请问这个要怎么解决呢？我也遇到了这个问题
