### ISSUE TITLE
有没有各种模型在paddlepaddle上占用显存的信息可供参考以便设置batch_size?

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#1521]
如题，类似于[caffe-model](https://github.com/soeaver/caffe-model)，里面提供了各种经典模型所需显存大小已经训练的速度等参考信息.

**Comment by colourful-tree** [comment]
已经在群里回复。显存默认是用满的。也可以根据实际显存情况调一下batch_size
