### ISSUE TITLE
fluid/PaddleNLP/sequence_tagging_for_ner 预测问题

### ISSUE THREAD

**Issue by zzulike** [PaddlePaddle/models#1534]
用ner模型在预测的时候发现，给预测数据随意标记的label会影响到最终的预测结果；当把数据减少一些(比如10w)后，这个问题就没有了，数据比较大的时候term的预测结果就会往这个随意标记的类别大量倾斜。。。

定义term的类别只有1和0， 预测是时候任意定义所有label=2，发现用较大预测数据集时候，大部分term的标签被预测为2，数据量较少时候，则是正常的

预测结果正常：
![image](https://user-images.githubusercontent.com/19464821/49934978-c2566d80-ff0a-11e8-8726-091f6b1a7549.png)

预测结果出现问题：
![image](https://user-images.githubusercontent.com/19464821/49934993-cf735c80-ff0a-11e8-8fb0-0a8bb720777c.png)

**Comment by jshower** [comment]
问题已收到，追查定位后会尽快反馈。

**Comment by jshower** [comment]
问题已修复，参见https://github.com/PaddlePaddle/models/pull/1540
