### ISSUE TITLE
什么时候提供图像分类中mobilenet v2的预训练模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1546]
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification#supported-models-and-performances

官方提供了不少的预训练模型，但没有我需要的mobilenet v2，什么时候能够提供呢？

希望越来越丰富？

**Comment by qingqing01** [comment]
感谢关注，最近1-2星期会提供训练好的模型~

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，谢谢青青姐。
