### ISSUE TITLE
fasterRCNN infer 维度不匹配

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/models#1548]
您好，我在使用paddle github上的代码看的时候，使用了cocoval2017中的一张图片做infer，运行的时候提示报错
```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims.size() == filter_dims.size(), but received in_dims.size():4 != filter_dims.size():1.
```
我查了图片的维度这一块，图片的大小被resize成(3, 800, 1190)，在infer.py里面，buildmodel的时候，设置的image size是[3, 1333, 1333]，默认配置我都没有修改，只改动了infer的图片，不知道是否跟模型的默认配置有关系呢？谢谢！

我没有修改infer.py其他的代码，只是将cocoval2017修改为了cocoval2014，infer的脚本如下：

```
python infer.py \
  2               --dataset=coco2014 \
  3               --pretrained_model=./pretrained/imagenet_resnet50_fusebn  \
  4               --image_path=./dataset/coco/val2014/  \                                                                            
  5               --image_name=COCO_val2014_000000184613.jpg \
  6               --draw_threshold=0.6
```

**Comment by jerrywgz** [comment]
您好，图像的维度应该是不会有影响的，build model的时候设置的size会被实际读进来的图像大小覆盖。您这个问题应该是模型没有正确加载导致的，您可以检查一下模型加载路径是否正确。另外infer阶段请使用我们release出来的模型，在文档中有相关链接，imagenet_resnet50_fusebn是预训练模型。

**Comment by littletomatodonkey** [comment]
恩恩好的，我加载了release模型，跑通了infer的代码，谢谢您！
