### ISSUE TITLE
gru4rec 在gpu下报个错   (cuda 版本不对，cudnn6 也按照  cudnn5 安装即可

### ISSUE THREAD

**Issue by jackyhawk** [PaddlePaddle/models#1560]
执行命令为：CUDA_VISIBLE_DEVICES=0 /data0/jy/py27/bin/python train.py --train_dir train_data/ --use_cuda 1

865 Traceback (most recent call last):
866   File "train.py", line 124, in <module>
867     train()
868   File "train.py", line 75, in train
869     exe.run(fluid.default_startup_program())
870   File "/data0/jy/py27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
871     self.executor.run(program.desc, scope, 0, True, True)
872 paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
873 PaddlePaddle Call Stacks:
874 0       0x7f143f665986p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
875 1       0x7f144047a7f2p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlac
    e, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, b
    oost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::de
    tail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::va
    riant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 658
876 2       0x7f143f733090p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) +
    224
877 3       0x7f143f733790p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
878 4       0x7f143f65400bp
879 5       0x7f143f69f7c0p
880 6       0x7f14c88f6918p PyEval_EvalFrameEx + 25016
881 7       0x7f14c88f9e2dp PyEval_EvalCodeEx + 2061
882 8       0x7f14c88f70a5p PyEval_EvalFrameEx + 26949
883 9       0x7f14c88f71c0p PyEval_EvalFrameEx + 27232
884 10      0x7f14c88f9e2dp PyEval_EvalCodeEx + 2061
885 11      0x7f14c88f9f62p PyEval_EvalCode + 50
886 12      0x7f14c8922d22p PyRun_FileExFlags + 146
887 13      0x7f14c89240b9p PyRun_SimpleFileExFlags + 217
888 14      0x7f14c8939f6dp Py_Main + 3149
889 15      0x7f14c7b26b35p __libc_start_main + 245
890 16            0x40071ep
891

**Comment by jackyhawk** [comment]
大伙有遇到过吗？

**Comment by wanghaoshuang** [comment]
> 869 exe.run(fluid.default_startup_program())

你这里的`exe`用的是`ParallelExecutor`么？`startup_program`不能用`ParallelExecutor`执行。
可以参考这里： https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/train.py#L128
