### ISSUE TITLE
The backbone for face detection.

### ISSUE THREAD

**Issue by Sun-Fan** [PaddlePaddle/models#1580]
Thanks for releasing the codes. I want to ask in the pyramidbox, if you have done the experiment on the backbone, such as the res50 and res101.And if this will be helpful for the wider_face val results.Thanks again.

**Comment by qingqing01** [comment]
@Sun-Fan We only do experiments on the VGG backbone.  See some experiments on SSD model (PyramidBox is also based on SSD) in TensorFlow https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md , maybe accuray of the backbone of ResNet 50/101 is better, but we don't do experiments.  And the heavier backbone needs more GPU memory.
