### ISSUE TITLE
在Fluid版本的图像分类中能否提供更多的没有指定参数的预训练模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1592]
在图像分类模型中： https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification#supported-models-and-performances
提供不少的预训练模型，不过没有指定parameter names的模型很少，我一般是不命名的，我决定模型的命名已经很好了，但是提供的模型是指定命名的，我又得修改网络的命名，这样很不好。能否尽快提供无指定parameter names的预训练模型吗？特别是MobieNet V1和MobileNet V2

**Comment by qingqing01** [comment]
预训练模型通常用于其他任务的初始化，用于其他任务，可能会增减若干层、调整顺序等，会导致一些需要加载的参数名字改变，因此才提供了很多指定参数名字的模型。您是觉得用指定名字的模型，会麻烦一些吗？

**Comment by yeyupiaoling** [comment]
@qingqing01 您这样说也有道理，因为我是完全使用模型的，结构是一致的，所以指定名字反而是一个累赘。

**Comment by yeyupiaoling** [comment]
@qingqing01 顺便问一下青青姐，提供了两种图像预处理方式的结构，分别是`top-1/top-5 accuracy(PIL)`和`top-1/top-5 accuracy(CV2) `。难道不同的处理工具，效果而也会不一样吗？如果图像增强的方式都一样。

**Comment by shippingwang** [comment]
@yeyupiaoling cv2和PIL主要是速度上的区别，cv2要略快一点

**Comment by qingqing01** [comment]
@yeyupiaoling 速度有差别外，python-cv2和PIL对图像得解码也有区别，可能一些操作输出可能也会有微小的输出。比如你可以打印python-cv2和PIL解码之后的图片，可能就有像素点的差异。

**Comment by yeyupiaoling** [comment]
哦哦，是这样子，好的。谢谢您们。
