### ISSUE TITLE
去掉MobileNet中的batch_norm层是否会影响模型的性能

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1594]
如果我去掉MobileNet V1的batch_norm层，如下：
https://github.com/PaddlePaddle/models/blob/5c6f919e36d4b849a787a6e4df5693ce86252b5f/fluid/PaddleCV/image_classification/models_name/mobilenet.py#L163-L169

和MobileNet V2的batch_norm层，如下：
https://github.com/PaddlePaddle/models/blob/5c6f919e36d4b849a787a6e4df5693ce86252b5f/fluid/PaddleCV/image_classification/models_name/mobilenet_v2.py#L111-L116

是否会影响这个网络的性能，因为我电脑用不了CUDNN，我也不知道为什么，我在这里提了问题：https://github.com/PaddlePaddle/Paddle/issues/15140
同时我conv和pool都设置了不使用cudnn，但是batch_norm层设置不了。我也提了问题：https://github.com/PaddlePaddle/Paddle/issues/15151

**Comment by xuezhong** [comment]
建议还是使用batch_norm，一般batch_norm都是有效果的。不过你可以验证下，在你的数据上能不能正常收敛

**Comment by yeyupiaoling** [comment]
@xuezhong 好的，谢谢回答。
