### ISSUE TITLE
deeplabv3修改类别后，出现错误

### ISSUE THREAD

**Issue by busyboxs** [PaddlePaddle/models#1608]
机器环境：ubuntu16.04 + CUDA8 + cudnn5.1 + paddlepaddle1.1（post85）+ anaconda(py2.7)

如果不改类别数目，导入预训练模型可以正常运行；

如果修改类别数目，不导入预训练模型可以正常运行；

如果修改类别数目，导入预训练模型则会报错；

错误为

```
Traceback (most recent call last):
  File "./train.py", line 169, in <module>
    fetch_list=[pred, loss_mean])
  File "/home/yangshun/anaconda2/envs/paddle1.2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims.size() == filter_dims.size(), but received in_dims.size():4 != filter_dims.size():1.
Conv input dimension and filter dimension should be the same. at [/paddle/paddle/fluid/operators/conv_op.cc:50]
```

很奇怪，调试半天也不知道为什么，

**Comment by qingqing01** [comment]
> paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims.size() == filter_dims.size(), but received in_dims.size():4 != filter_dims.size():1.

这个问题是load的某个conv的weights shape不对，或者没有对startup_program初始化。 但我看代码https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/train.py#L167 已经run了startup_program了。

你是用的原本的xception65的模型吗？

**Comment by busyboxs** [comment]
我使用的是README链接中给的模型。如果下载代码只是修改`--num_class`，能在你们的电脑上正常运行么？有没有什么方法能查看`deeplabv3plus_xception65_initialize.params`里面的数据？然后这个初始化模型是怎么得到的？

**Comment by busyboxs** [comment]
找到原因了，问题出在`fluid.io.load_vars(exe, dirname="", filename=args.init_weights_path, vars=myvars)`

**Comment by hiudawn** [comment]
> 找到原因了，问题出在`fluid.io.load_vars(exe, dirname="", filename=args.init_weights_path, vars=myvars)`

你好，请问你最后是怎么解决这个问题的

**Comment by freekoy** [comment]
> > paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims.size() == filter_dims.size(), but received in_dims.size():4 != filter_dims.size():1.
> 
> 这个问题是load的某个conv的weights shape不对，或者没有对startup_program初始化。 但我看代码https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/train.py#L167 已经run了startup_program了。
> 
> 你是用的原本的xception65的模型吗？

和楼主一样的错，是xception65的模型
困惑好几天了................
怎么解决这个问题

**Comment by tycallen** [comment]
关注

**Comment by busyboxs** [comment]
首先说一下造成错误的原因：通过分析源码可以发现，保存模型最终都是通过`save_vars`函数（https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L92） 来实现的，而在该函数中，保存变量是有一个对变量进行排序的操作（https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L201） ，所以最终保存的模型变量是以字典顺序排序的变量的值。然后在恢复模型时，只是将模型中的变量的值赋值给你想要赋值的变量，而不会去验证所要赋值的变量的shape是否满足条件，变量名是否相同。因此，针对deeplabv3+模型修改类别，由于在导入预训练模型时，去掉了含有“logit”的两个变量，而“logit”在所有变量的字典顺序中排在中间，所以赋值时会把“logit”变量的值赋值给其他变量，使得所有“logit”变量之后的变量赋值错位，同时shape也改变了。这就导致了问题中的维度不相等的错误。

----

具体的解决方法（只能说是没有办法的办法吧）：我觉得有两种，一种是在原来19类的情况下导入预训练模型之后，重新保存一个不含“logit”变量的模型；另一种是在随机初始化模型之后，单独保存“logit”变量为一个模型，然后导入预训练模型，导入预训练模型之后立马导入刚才保存的“logit”变量的模型。

这是第二种方法对应的`load_model()`函数：

```python
def load_model():
    logit_params = [x for x in test_program.list_vars() if isinstance(x, fluid.framework.Parameter)
                    and x.name.find('logit') != -1]
    # save logit param
    fluid.io.save_vars(exe, dirname="", filename='logit.params', vars=logit_params)
    myvars = [x for x in test_program.list_vars() if isinstance(x, fluid.framework.Parameter)]

    if args.init_weights_path.endswith('/'):
        if args.num_classes == 19:
            fluid.io.load_params(
                exe, dirname="", filename=args.init_weights_path, main_program=test_program)
        else:
            fluid.io.load_vars(exe, dirname=args.init_weights_path, vars=myvars)
    else:
        if args.num_classes == 19:
            fluid.io.load_params(
                exe, dirname="", filename=args.init_weights_path, main_program=test_program)
        else:
            fluid.io.load_vars(exe, dirname="", filename=args.init_weights_path, vars=myvars)
            fluid.io.load_vars(exe, dirname="", filename='logit.params', vars=logit_params)
```

感觉paddlepaddle真的很神奇，导入模型后，变量的shape和变量值的shape竟然可以不相等。
