### ISSUE TITLE
Faster rcnn profile运行nan

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/models#1610]
![image](https://user-images.githubusercontent.com/13645332/50773747-9d1c0b80-12cc-11e9-98f2-5bc3d60fe306.png)

跑了下profile， loss有点问题

**Comment by jerrywgz** [comment]
应该加载paddle release出来的model，在文档中有相关链接

**Comment by shippingwang** [comment]
@jerrywgz OK
