### ISSUE TITLE
icnet项目中trian.py和infer.py 中images大小不一致，导致windows下预测报错

### ISSUE THREAD

**Issue by WangTaoSpace** [PaddlePaddle/models#1614]
train.py中
```
data_shape = (3, 720, 720)
images = fluid.layers.data(name='image', shape=data_shape, dtype='float32')
```
infer.py中
```
data_shape = [3, 1024, 2048]
images = fluid.layers.data(name='image', shape=train_shape, dtype='float32')
```
我是在windows上的paddlepaddle，infer时会报错。按照我的常识，infer中的data_shape应该和train中的一致，改成一致，infer能够执行，但是预测结果很差，这里就是应该不一致吗？

**Comment by wanghaoshuang** [comment]
训练的时候data_shape 设置为`(3, 720, 720)`是为了对图片进行random crop的数据增广，预测的时候data_shape要和实际图片保持一致。如果预测的时候将data_shape设置为`(3, 720, 720)`的话，相当于预测是也在做random crop了，所以预测效果很差。

如果你训练用的图片比较多的话，可以将训练时的data_shape 设置为图片实际大小，预测的时候data_shape也用图片实际大小。

**Comment by WangTaoSpace** [comment]
我使用windows上paddlepaddle，data_shape设置成实际图片大小报错如下，这是因为windows平台的原因吗？
```
File "F:/train_data/lane_line/cluster_icnet/infer.py", line 359, in infer
    fetch_list=[predict])
  File "G:\python 3.6.3\lib\site-packages\paddle\fluid\executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:106 != y_dims[i]:107.
Broadcast dimension mismatch. at [E:\dist\Paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:63]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
```
训练的时候 random crop是在代码这里做的
![image](https://user-images.githubusercontent.com/20881549/50874646-d2754600-13ff-11e9-9d61-972bc52dfaab.png)
我预测的时候没有random crop 直接 image = cv2.resize(image, train_shape[1:])进行了缩放。

我现在的训练数据大约有3万。关于模型效果，有下面几个问题？
1. 如果我的输入是原始图片大小，网络的训练计算量会不会变的过大？
2.关于icnet这个模型，输入是一个图片的所有像素，但是只有很小一部分是相关像素（我只检测里面的车道线），这样会导致网络训练时隐藏层几乎是一样的值？

**Comment by geng007** [comment]
> 训练的时候data_shape 设置为`(3, 720, 720)`是为了对图片进行random crop的数据增广，预测的时候data_shape要和实际图片保持一致。如果预测的时候将data_shape设置为`(3, 720, 720)`的话，相当于预测是也在做random crop了，所以预测效果很差。
> 
> 如果你训练用的图片比较多的话，可以将训练时的data_shape 设置为图片实际大小，预测的时候data_shape也用图片实际大小。

>我预测的时候data_shape也用图片实际大小,依然报错
![default](https://user-images.githubusercontent.com/38428867/50880185-7539be80-1418-11e9-9bc3-25744c721f80.png)
![default](https://user-images.githubusercontent.com/38428867/50880228-a1edd600-1418-11e9-93e7-5233d73bf36e.png)

**Comment by wanghaoshuang** [comment]
1. 关于报错问题：
这个错误和你环境无关。
你将[这一行](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/icnet/icnet.py#L168) 改为`  tmp = max_pool(tmp, 3, 3, 2, 2, padding=[1, 1])` 试试？因为目前的icnet的网络配置是对输入图片size的奇偶敏感的，目前只兼容了cityscape的数据，如果用自己的数据的话，需要适当调整网络。

>File "F:/train_data/lane_line/cluster_icnet/infer.py", line 359, in infer
    fetch_list=[predict])
  File "G:\python 3.6.3\lib\site-packages\paddle\fluid\executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:106 != y_dims[i]:107.
Broadcast dimension mismatch. at [E:\dist\Paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:63]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.

从上述错误日志来看，应该是某个加操作的输入的尺寸不匹配，可以用[fluid.layers.Print](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py#L146)和二分查找的思路来定位出错的op，然后再修改padding参数使加操作的输入尺寸匹配。

**Comment by wanghaoshuang** [comment]
>如果我的输入是原始图片大小，网络的训练计算量会不会变的过大？

单次迭代的计算量肯定会增大的。对于整体任务来说，不好评估。

>关于icnet这个模型，输入是一个图片的所有像素，但是只有很小一部分是相关像素（我只检测里面的车道线），这样会导致网络训练时隐藏层几乎是一样的值？

隐藏层的值的分布和你要检测目标像素的比例没有直接关系。目标像素占比例小只会导致最终的predict输出很容易几乎全为背景。

**Comment by WangTaoSpace** [comment]
谢谢。关于报错的问题，我觉得是图像会在模型中关于它的shape进行resize，所以输入图像的大小是16的整数倍就可以了。
```
def scale_label(self, label, factor):
        """
        Scale label according to factor.
        """
        h = label.shape[0] // factor
        w = label.shape[1] // factor
        return cv2.resize(
            label, (h, w), interpolation=cv2.INTER_NEAREST)[:, :, np.newaxis]
```
上面代码 resize 这里参数应该是（w,h）吧。

我现在能够预测成功了，但是还是有点问题。
1.我预测的所有图片的有效像素点都集中在了图片的右边缘如下图，我正在找原因，您有遇到过吗？
![171206_064839744_camera_6_result](https://user-images.githubusercontent.com/20881549/50941992-f8631f00-14c1-11e9-9d80-488d45c9ee7c.png)
2.目标像素占比例小只会导致最终的predict输出很容易几乎全为背景。这个问题，您有什么建议吗？我是不是可以通过增加目标像素在损失函数中的权重来解决，比如训练分两步，第一步锁定目标像素的区域，第二步再进行更近一步的识别。

**Comment by wanghaoshuang** [comment]
>1.我预测的所有图片的有效像素点都集中在了图片的右边缘如下图，我正在找原因，您有遇到过吗？

没遇到过这种情况

> 2. 2.目标像素占比例小只会导致最终的predict输出很容易几乎全为背景。这个问题，您有什么建议吗？我是不是可以通过增加目标像素在损失函数中的权重来解决，比如训练分两步，第一步锁定目标像素的区域，第二步再进行更近一步的识别。

这种小目标检测或分割问题，我们也没有好的方案，目前也是在探索中，你说的方法值得试一下。

**Comment by geng007** [comment]
@WangTaoSpace 
我的预测结果全都为背景了，你预测成功了吗

**Comment by WangTaoSpace** [comment]
我的预测结果也很差，而且同一个图片，多次预测，结果差别很大。

**Comment by wanghaoshuang** [comment]
> 我的预测结果也很差，而且同一个图片，多次预测，结果差别很大。

预测的时候，图片是不是有随机处理的操作？

**Comment by WangTaoSpace** [comment]
没有，我把随机处理都去掉了，而且转换成了二分类，也就是背景和车道线，图片也弄成灰度单通道了。是不是我训练的时间不够呀，我只训练了一个pass。
```
2019-01-12T04:52:50.812155947Z Pass[0];Iter[1370]; train loss: 0.117; sub4_loss: 0.073; sub24_loss: 0.087; sub124_loss: 0.119
```

**Comment by WangTaoSpace** [comment]
@wanghaoshuang 这个是我的代码https://github.com/WangTaoSpace/icnet_hermes/blob/master/icnet_hermes.py

**Comment by universea** [comment]
老铁，报错问题解决了嘛，同求解决方案

**Comment by wanghaoshuang** [comment]
@WangTaoSpace 训练一个pass肯定是不行的，但是同一个图片的多次预测结果应该一样的。

**Comment by WangTaoSpace** [comment]
> @WangTaoSpace 训练一个pass肯定是不行的，但是同一个图片的多次预测结果应该一样的。

这是我的代码https://github.com/WangTaoSpace/icnet_hermes/blob/master/icnet_hermes.py。
有时间帮我看看呗，我现在觉的可能的问题是我PIL和opencv混用了，但是跑的是灰度图，应该是不影响的。
还有一个问题。见下面代码，你们的模型在计算交叉熵的时候，最后直接让卷积的特征通道数等于分类数，用不同特征通道的值，当做softmax的值。这样做有依据吗？
```
    def icnet(self, data, num_classes, input_shape):
        image_sub1 = data
        image_sub2 = self.interp(data, out_shape=input_shape * 0.5)  # resize 0.5

        s_convs = self.shared_convs(image_sub2)
        sub4_out = self.sub_net_4(s_convs, input_shape)
        sub2_out = self.sub_net_2(s_convs)
        sub1_out = self.sub_net_1(image_sub1)

        sub24_out = self.CCF24(sub2_out, sub4_out, input_shape)
        sub124_out = self.CCF124(sub1_out, sub24_out, input_shape)

        conv6_cls = self.conv(
            sub124_out, 1, 1, num_classes, 1, 1, biased=True, name="conv6_cls")
        sub4_out = self.conv(
            sub4_out, 1, 1, num_classes, 1, 1, biased=True, name="sub4_out")
        sub24_out = self.conv(
            sub24_out, 1, 1, num_classes, 1, 1, biased=True, name="sub24_out")

        return sub4_out, sub24_out, conv6_cls
```

**Comment by WangTaoSpace** [comment]
> 老铁，报错问题解决了嘛，同求解决方案

你可以参考下我提供的代码，但是这个代码跑的模型预测结果超级差。

**Comment by wanghaoshuang** [comment]
>还有一个问题。见下面代码，你们的模型在计算交叉熵的时候，最后直接让卷积的特征通道数等于分类数，用不同特征通道的值，当做softmax的值。这样做有依据吗？

图像的语义分割就相当于像素级的分类，所以对于K分类任务，最后一层的卷积需要得到每个像素点在K类上的概率分布，所以就自然的映射到K个channel了。更多细节可以参考以下paper:

https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf
https://arxiv.org/abs/1704.08545

**Comment by universea** [comment]
> > 还有一个问题。见下面代码，你们的模型在计算交叉熵的时候，最后直接让卷积的特征通道数等于分类数，用不同特征通道的值，当做softmax的值。这样做有依据吗？
> 
> 图像的语义分割就相当于像素级的分类，所以对于K分类任务，最后一层的卷积需要得到每个像素点在K类上的概率分布，所以就自然的映射到K个channel了。更多细节可以参考以下paper:
> 
> https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf
> https://arxiv.org/abs/1704.08545

发现最后一层经过softmax后，单个像素的９分类概率和相加不为１．　我的代码如下：
    print('merge9    shape',merge9.shape)
        conv9 = conv_layer(input=merge9, num_filters=64, filter_size=3, stride=1, act='relu')
        print('conv9     shape',conv9.shape)
        conv9 = conv_layer(input=conv9, num_filters=64, filter_size=3, stride=1, act='relu')
        print('conv9     shape',conv9.shape)
        conv9 = conv_layer(input=conv9, num_filters=32, filter_size=3, stride=1, act='relu')
        print('conv9     shape',conv9.shape)
        conv10 = conv_layer(input=conv9, num_filters=16, filter_size=3, stride=1, act='tanh')
        
        modelOut = conv_layer(input=conv10, num_filters=9, filter_size=1, stride=1, act='softmax')
        modelOut = fluid.layers.transpose(x=modelOut, perm=[0, 2, 3, 1])
