### ISSUE TITLE
face_detection和object_detection运行结束报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1617]
face_detection和object_detection运行结束报错，并且object_detection在python2下运行结束会另外报'traceback' is not defined
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
*** Aborted at 1545741303 (unix time) try "date -d @1545741303" if you are using GNU date ***
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
*** SIGTERM (@0x186) received by PID 478 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 472 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 475 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 487 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 484 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 481 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 490 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
*** SIGTERM (@0x186) received by PID 493 (TID 0x7f8e2779d700) from PID 390; stack trace: ***
    @     0x7f90564f3330 (unknown)
    @     0x7f90564f3330 (unknown)
    @     0x7f90564f3330 (unknown)
    @           0x4f8611 PyUnicode_AsEncodedString
    @     0x7f90564f3330 (unknown)
    @     0x7f90564f3330 (unknown)
    @     0x7f90564f3330 (unknown)
    @     0x7f90564f3330 (unknown)
    @           0x5ce5a8 (unknown)
    @           0x513be0 PyUnicode_Format

**Comment by qingqing01** [comment]
感谢反馈，该问题不影响结果，确实影响体验，最近修复下，多谢~

**Comment by YanYan0716** [comment]
请问你的GPU 型号是什么?我运行的人脸检测部分,我的GPU是4G,程序跑不起来

**Comment by xiegegege** [comment]
我的GPU型号是Tesla P40，20多G的

**Comment by YanYan0716** [comment]
好的,谢谢啦

**Comment by xiegegege** [comment]
不客气

**Comment by YanYan0716** [comment]
请问你的CUDA是什么型号?8 9?

**Comment by xiegegege** [comment]
我在cuda8cudnn7和cuda9cudnn7上跑过
