### ISSUE TITLE
video_classification数据路径问题

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1619]
video_classification的train_list文件中定义的数据路径都是当前data路径，无法灵活设置数据。
且需要在data目录下新建一个video_classification文件，并在其中存放train_pkl（readme中没提示）

**Comment by jerrywgz** [comment]
麻烦贴下哪里需要新建video_classification文件吗？我们这边复现起来比较费时

**Comment by SunGaofeng** [comment]
目前确实没有将文件路径作为函数参数传入，而是固定的写在代码里面了，后续我们会陆续发布其他video classification模型，将统一修改这些接口。
如果目前想改变数据路径的话，可以手动修改源代码：
1  修改解码后的文件存放路径，video_decode.py 里面line 20，可以将'./frame'替换成制定目录
                image_folder = './frame/' + folder + '/' + vid.split('.')[0] + '/'              #line 20
2 修改转化后的pkl文件路径，generate_train_data.py 里面 line 16，可以将savepath改成需要设置的目录，train_list和test_list会自动生成新的存放路径
               savepath = '%s_pkl/' % mode        修改为   savepath = '%s/%s_pkl/' % (YOUR_DIR, mode)

**Comment by xiegegege** [comment]
嗯嗯，好的，谢谢解答
