### ISSUE TITLE
object_detection在使用coco数据集时需要修改data_dir

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1620]
object_detection在使用coco数据集时需要修改data_dir（文档没提示）

**Comment by jerrywgz** [comment]
是说默认data_dir和下载的路径不同吗

**Comment by xiegegege** [comment]
对的，默认的data_dir是pascalvoc数据的路径，文档里没说使用coco数据集需要改data_dir，只说要改dataset，然后运行就会报错了。。
