### ISSUE TITLE
neural_machine_translation的read me里的公式格式有问题

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1621]
neural_machine_translation/rnn_search 的read me里的公式格式有问题

**Comment by jerrywgz** [comment]
已经交给相关负责同学，感谢反馈！

**Comment by joodo** [comment]
您好，由于 GitHub 不支持 LaTeX 公式的渲染，导致了格式混乱。这部分内容在官网文档中也有，您可以参考[这里](http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/basics/machine_translation/index.html)。未来我们会对 models 的 README 内容做整体调整，解决公式的显示问题。
