### ISSUE TITLE
faster_rcnn的默认数据路径错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1622]
faster_rcnn的默认数据路径是data/COCO17需要修改为dataset/coco

**Comment by jerrywgz** [comment]
默认数据路径和自身的下载路径有关，一般需要自己设置数据路径

**Comment by xiegegege** [comment]
但faster_rcnn路径下的数据目录是dataset/coco，如果在当前目录下存放数据，运行就会报错了

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/pull/1626
已修复，感谢反馈

**Comment by xiegegege** [comment]
<img width="741" alt="6434a1ee95797ce9fdc090c3cfbf8f3e" src="https://user-images.githubusercontent.com/46314656/50955000-f6658400-14f2-11e9-962a-a7348d108777.png">
似乎没改全。。这些也要改下吧。。
