### ISSUE TITLE
ctr的数据下载链接失效了

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1623]
ctr的数据下载链接失效了

**Comment by Superjomn** [comment]
请增加更多描述哈

**Comment by xiegegege** [comment]
运行ctr/data文件夹中的download.sh后，无法下载数据

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/50888124-e6d13700-142f-11e9-83b8-67ea8a5b5e6e.png)
这个里面？

**Comment by jacquesqiao** [comment]
The url for data now is https://s3-eu-west-1.amazonaws.com/kaggle-display-advertising-challenge-dataset/dac.tar.gz, we will update the download.sh later

**Comment by xiegegege** [comment]
ok
