### ISSUE TITLE
pytorch模型转fluid模型 脚本

### ISSUE THREAD

**Issue by soldier828** [PaddlePaddle/models#1631]
请问可以提供一个 pytorch模型转fluid模型的demo吗？

**Comment by frankwhzhang** [comment]
目前还没有脚本可以从pytorch转fluid

**Comment by soldier828** [comment]
> 目前还没有脚本可以从pytorch转fluid

能给一些 有关的代码文件  参考一下吗？现在一脸懵逼。。。

**Comment by frankwhzhang** [comment]
自动转模型的工具，短期不会支持。建议直接用paddle做训练。在models目录下面有常见的模型，可以参考这些模型的pytorch与fluid版本
