### ISSUE TITLE
图像分类中下载的ImageNet-2012图像数据到底多大？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1633]
>步骤二： 从ImageNet官网下载ImageNet-2012的图像数据。训练以及验证数据集会分别被下载到"train" 和 "val" 目录中。请注意，ImaegNet数据的大小超过40GB，下载非常耗时；已经自行下载ImageNet的用户可以直接将数据组织放置到data/ILSVRC2012。

文档说是超过40GB，我以为是40GB左右，竟然单独训练数据就有138GB了，是脚本问题，还是文档写错了？

**Comment by qingqing01** [comment]
提供的下载脚本，下载的全量数据确实是138GB，指把1000类的数据抽取出来大约40G+吧， 我们去掉文档里数字吧，多谢反馈。

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，谢谢。
