### ISSUE TITLE
face_detection

### ISSUE THREAD

**Issue by YanYan0716** [PaddlePaddle/models#1634]
hello, i want to know if the face_detection model could be used on CUDA8+CUDNN5.1 or it must be used on CUDA9+CUDNN7,thanks

**Comment by qingqing01** [comment]
It can be worked with CUDA8+CUDNN5.1.

**Comment by YanYan0716** [comment]
and my GPU about 4G,could i use the model? i have trid, but it said outof memory?

**Comment by YanYan0716** [comment]
i am looking for you answer

**Comment by qingqing01** [comment]
@yanqian123 4G is not enough. PyramidBox in face detection is memory consuming.

**Comment by YanYan0716** [comment]
how much memory i need?

**Comment by qingqing01** [comment]
@yanqian123 We use P40 (22G)/V100(16G). You'd better to use GPU with memory more than 12G. We use 640x640 input on WIDERFace. You also can reduce the input shape.
