### ISSUE TITLE
dist_train.py文档中的方法如何详解？

### ISSUE THREAD

**Issue by qianledan** [PaddlePaddle/models#1640]
官网的github中的分布训练dist_train.py文档中，append_bn_repeat_ini_op()方法是什么作用？里面有个参数num_repeats，重复次数用于什么？global_block().相关的方法都是什么意思，没有文档看不懂代码。
![qq 20190111092734](https://user-images.githubusercontent.com/45925696/51007828-0b3e2800-1584-11e9-9bc7-4c3921b7c3e9.png)

**Comment by wangguibao** [comment]
请问是哪个网络？

**Comment by wangguibao** [comment]
关于fluid.Program相关的方法，请参考这个文档：http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#permalink-23-program

**Comment by typhoonzero** [comment]
此处相关的代码是为了处理batch merge功能的，用于提高batchsize的情况下，降低显存占用。这些后续会封装到paddle中。只需要理解，batch merge是跑多个batch的前向和反向，然后把gradient merge起来的功能就行。

**Comment by qianledan** [comment]
> 此处相关的代码是为了处理batch merge功能的，用于提高batchsize的情况下，降低显存占用。这些后续会封装到paddle中。只需要理解，batch merge是跑多个batch的前向和反向，然后把gradient merge起来的功能就行。

多谢指点！

**Comment by qianledan** [comment]
> 关于fluid.Program相关的方法，请参考这个文档：http://paddlepaddle.org/documentation/docs/zh/1.2/api_cn/fluid_cn.html#permalink-23-program

谢谢您的回复，不过你的链接里只讲到了fluid.program.global_block，没有涉及到global_block里面的方法。
