### ISSUE TITLE
分布训练是否要求每个node的gpu数量型号要一致？

### ISSUE THREAD

**Issue by qianledan** [PaddlePaddle/models#1641]
分布训练是否要求每个node的gpu数量型号要一致？我有4台一台双K80，一台一块K80，一台p100，1台1080ti，可否允许分布训练？
另外，如果有多台trainer，其中一台用gpu，一台用cpu，是否也可以执行分布训练？

**Comment by typhoonzero** [comment]
使用Pserver 模式是可以在不同的GPU型号上做分布式训练的，pserver使用cpu执行。一些trainer用gpu，一些用cpu也可以。但需要注意的是，如果是同步训练，不同的gpu型号速度不一样，会导致每个batch等待最慢的gpu完成开始下一个batch。可以考虑使用异步模式

**Comment by qianledan** [comment]
> 使用Pserver 模式是可以在不同的GPU型号上做分布式训练的，pserver使用cpu执行。一些trainer用gpu，一些用cpu也可以。但需要注意的是，如果是同步训练，不同的gpu型号速度不一样，会导致每个batch等待最慢的gpu完成开始下一个batch。可以考虑使用异步模式

谢谢您的回答，那么nccl2模式能不能支持不同型号的GPU？

**Comment by typhoonzero** [comment]
nccl2模式不支持。
