### ISSUE TITLE
fluid模型加载外部权重

### ISSUE THREAD

**Issue by soldier828** [PaddlePaddle/models#1642]
fluid使用pytorch模型的问题。
1. pytorch训练好的模型怎么用fluid加载？
2. 或者我这边已经有了每一层的模型参数，怎样生成对应的fluid模型？
请问有什么可以参考的code吗？

**Comment by wangguibao** [comment]
文慧帮忙提供了一个caffe转fluid的工具，用户在参考
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/caffe2fluid

**Comment by wangguibao** [comment]
先关闭了，如需要可再次打开
