### ISSUE TITLE
chinese_ner模型易用性问题

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1646]
<img width="512" alt="5abd8023a19241ee4c0a101ae74d4ada" src="https://user-images.githubusercontent.com/46314656/51097482-5ca61b80-17ff-11e9-9655-b1b597655f20.png">
chinese_ner文档中是通过修改代码来设置参数，但命令行就可以，建议给出主要的参数设置列表，例如：python train.py --train_data_dir=data/train_files ...
另外，为方便用户使用，建议告知用户使用python train.py --help查看参数说明

**Comment by Xreki** [comment]
感谢建议，我们会尽快修复。
