### ISSUE TITLE
text_classification文档中链接失效

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1650]
<img width="866" alt="620f566b2cf1a57c596e7b4e3351aadb" src="https://user-images.githubusercontent.com/46314656/51102054-5cfee080-1818-11e9-9030-03132077f390.png">
链接失效，报404

**Comment by Xreki** [comment]
收到，我们会尽快修复

**Comment by shippingwang** [comment]
Fixed by #1659
