### ISSUE TITLE
face_detection文档格式错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1655]
<img width="925" alt="af50e062e8cdca1c56f078a2b8f64514" src="https://user-images.githubusercontent.com/46314656/51162289-a01c8a80-18d0-11e9-9476-a6e77c212528.png">

1、图中“物体检测SSD算法”链接失效了，报404
2、文档中公式格式错误

**Comment by luotao1** [comment]
@shanyi15 最近有很多文档链接失效，请问能否在travis-ci中加入这项检查呢？
#1650 #1598 #1623

**Comment by shanyi15** [comment]
需求收到

**Comment by shippingwang** [comment]
Fixed by #1659

**Comment by xiegegege** [comment]
只改了链接错误，没改公式格式
