### ISSUE TITLE
fluid textcnn模型训练+预测

### ISSUE THREAD

**Issue by ninegsf** [PaddlePaddle/models#1658]
想要使用fluid textcnn训练模型然后预测
目前有自己的正负样本数据
但是不知道怎么使用模型，
1.数据应该按照什么样的格式
2.数据应该放在哪儿，
3.最终的产出模型在哪儿

**Comment by shippingwang** [comment]
@ninegsf 自己的数据要read进去 麻烦看一下[load自己的数据](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/text_classification/utils.py#L60) ， 谢谢
