### ISSUE TITLE
ctr模型使用自己数据训练，仍需加载meta

### ISSUE THREAD

**Issue by awper361** [PaddlePaddle/models#166]
https://github.com/Superjom/models-1/tree/ctr2/ctr

models-1-ctr2/ctr/train.py:58

dnn_input_dim, lr_input_dim = reader.load_data_meta(args.data_meta_file)
@Superjom

**Comment by awper361** [comment]
@Superjom

**Comment by Superjomn** [comment]
的确不需要 load meta
**TODO** 稍后去除
