### ISSUE TITLE
fluid textcnn模型，结果解读问题

### ISSUE THREAD

**Issue by ninegsf** [PaddlePaddle/models#1660]
paddlepaddle/models-develop/fluid/PaddleNLP/text_classification

这个模型，跑完之后的预测部分，我有点儿疑问，
我想要的预测是我给任意一个预测数据，能够给出正负样本的概率，但现在没有这样的输出，请问要怎么样才能有呢

**Comment by ninegsf** [comment]
1.我不太清楚我这个模型训练的对不对 
2.预测的时候，给的脚本貌似也跟我想要的有出入

**Comment by ninegsf** [comment]
我昨天用自己的数据训练了一下模型，这个模型训练的输出，30个预测

**Comment by heavengate** [comment]
![image](https://user-images.githubusercontent.com/12605721/51232605-500df880-19a2-11e9-8113-71be246b8a38.png)
在save_inference_model的时候第三个参数修改为[acc, prediction]，则inference model会返回acc和prediction两个值
![image](https://user-images.githubusercontent.com/12605721/51232642-6f0c8a80-19a2-11e9-8c45-8e18a6eaf5a9.png)
在 infer.py的L31 返回值获取由acc改为acc, prediction即可获取每条样本的prediction概率，prediction是one-hot的，是一个[N, 2]的numpy array，N是batch size， 2那一维是正负概率,即prediction[i, 0] 就是你batch里面第i个样本的负例的概率，prediction[i, 1]就是第i个样本正例的概率
