### ISSUE TITLE
量化后模型并没有变为原来的1/4

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#1667]
按照[量化](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/README_quant.md)的步骤来的，相关日志可查看[paddlepaddle int8量化](https://mp.csdn.net/postedit/85943850)
正常量化结果应该是类似[mobilenet_v1_ssd](https://github.com/hjchen2/paddle-test/tree/master/fluid_models/mobilenet_v1_ssd)提供的

**Comment by hjchen2** [comment]
@imistyrain 由于paddle fluid中现在只支持float模拟的int8训练，在convert_to_int8之前，模型参数都是float的，只是值在int8的范围内，只有调用了convert_to_int8才会真正将参数转换成int8，并保存。

**Comment by hjchen2** [comment]
@qingqing01 帮忙看一下main_quant.py是否需要加一下convert_to_int8，或者在文档中提示一下。

**Comment by qingqing01** [comment]
可以在文档里加下`convert_to_int8`的提示。
