### ISSUE TITLE
metric_learning 运行结束报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1671]
环境：ubuntu16 Cuda8 Cudnn7 python3.5 paddle的develop分支
metric_learning运行结束后有报错：
<img width="855" alt="f698a4d9e18e21106128bfcd48f0b4af" src="https://user-images.githubusercontent.com/46314656/51363875-f0842a00-1b14-11e9-8f2d-bd702067a0a7.png">

**Comment by qingqing01** [comment]
Fix by https://github.com/PaddlePaddle/models/pull/1663
