### ISSUE TITLE
machine_reading_comprehension 报编码错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1678]
环境：ubuntu16 Cuda8 python3.6 paddle的develop分支
machine_reading_comprehension在运行一段时间后报错：
<img width="885" alt="58ba40ac9e549d58f1a2861efc026f8c" src="https://user-images.githubusercontent.com/46314656/51510771-6ea83f80-1e39-11e9-8688-1be469a4336f.png">

**Comment by xuezhong** [comment]
这个问题之前没有遇到过，可能是特定环境下的默认编码问题。可以尝试在run.py的272-276行，给字符串加个encode("utf-8")调用，统一编码。

我们会尝试复现下问题，如有进展会fix这个issue。

另一方面，可以参考网上的一些类似问题 https://blog.csdn.net/penglei0901/article/details/37494721

**Comment by xuezhong** [comment]
该问题非必现，在我的环境下没有复现此问题，复现后再更新
