### ISSUE TITLE
neural_machine_translation/transformer无法运行

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1680]
环境：ubuntu16 cuda9 python3.6 paddle的develop分支
transformer无法运行，也没有报错信息，卡在了下图所示的状态中：
<img width="822" alt="325439b96b545d8b859a869ee4b0bcd8" src="https://user-images.githubusercontent.com/46314656/51523092-dd9b8d80-1e65-11e9-9482-91cc3ff3d1ca.png">

**Comment by kolinwei** [comment]
GPU类型:P40

**Comment by chengduoZH** [comment]
原因已查明，模型是在运行，但是没有log输出。
在脚本中添加这句话就可以了
```
logging.getLogger().setLevel(logging.INFO)
```
