### ISSUE TITLE
word2vec运行报operator fill_constant error

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1690]
环境：ubuntu16 Cuda8 python2.7 GPU类型: p40
word2vec运行时报operator fill_constant error，截图如下：
<img width="886" alt="71405b9b8aa220e42bcefadbda83bfe0" src="https://user-images.githubusercontent.com/46314656/51655030-d0051580-1fd5-11e9-9054-3f5105452fb0.png">

**Comment by JiabinYang** [comment]
fixed in PR:https://github.com/PaddlePaddle/Paddle/pull/15490/files

**Comment by sneaxiy** [comment]
Fix in PR: https://github.com/PaddlePaddle/Paddle/pull/15496/files
