### ISSUE TITLE
使用官网例程finetune se_resnext50不收敛

### ISSUE THREAD

**Issue by yuanyc06** [PaddlePaddle/models#1712]
请教下，我安装了最新版的paddlepaddle_gpu-1.2.0.post85-cp27-cp27mu-linux_x86_64.whl，之后按照官网的例程（https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification  ）尝试在一个基本网络se_resnext50上用鸟类数据集CUB200来finetune（pretrain用的官网提供的imagenet预训练的模型，），但结果一直不收敛，loss完全不降，acc一致几乎是0，请问这会是什么问题呢？我已经删掉了pretrain里的fc6的文件，base lr=0.001

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification#supported-models-and-performances 

这里提供了两个SE-ResNeXt50模型，请问您用的是哪个？ 注意是否要设置`model_category = models_name`，以及类别数、数据预处理是否正确。

**Comment by yuanyc06** [comment]
谢谢！应该是这个问题。我用的指定名称的，之前model_category=models，现在修改成model_category=models_name后，开始收敛了
