### ISSUE TITLE
怎样由caffe转过来的模型进行微调？

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#1713]
已经使用[caffe2fluid](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/caffe2fluid)工具将caffe训练的模型转成了fluid模型，也使用fluid.io.load_inference_model加载进来获得了program，但是怎样将test的program转为train的program呢？有没有相关的示例演示下后序的步骤？
或者用已有的[models](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification)里面的也成，怎么由save_inference_model的模型进行微调？

**Comment by qingqing01** [comment]
1. caffe2fluid工具如果训练和fine-tune
  
    caffe2fluid转换之后有模型配置Python文件，在这个文件的基础上，加上optimize和backward部分可训练，这部分可以参考 [models分类](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification)。但需要注意下，Python配置文件中一些op，比如BatchNorm/Drop的is_test是否为False，因为训练需要是False。  

2.  使用models提供的模型fine-tune:

  参考下面代码加载参数即可。

https://github.com/PaddlePaddle/models/blob/8fb135da7f8cb3b1b14c15fb7c607265a18f2e93/fluid/PaddleCV/image_classification/train.py#L256-L265

  注意，Paddle保存的模型文件有两种方式，即参数是否合并在一起，可以参考save,load接口: http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/io_cn.html
