### ISSUE TITLE
ZeroDivisionError: long division or modulo by zero

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#1734]
使用[object_detection](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/object_detection)训练mobilenet-ssd, 但是scale设为了0.25，得到
```
  File "train.py", line 338, in <module>
    val_file_list=val_file_list)
  File "train.py", line 183, in train
    is_train=True)
  File "train.py", line 112, in build_program
    locs, confs, box, box_var = mobile_net(class_num, image, image_shape,scale=args.scale)
  File "mobilenet_ssd.py", line 92, in mobile_net
    module14 = extra_block(module13, 256, 512, 1, 2, scale)
  File "mobilenet_ssd.py", line 58, in extra_block
    padding=0)
  File "mobilenet_ssd.py", line 26, in conv_bn
    bias_attr=False)
  File "python2.7/site-packages/paddle/fluid/layers/nn.py", line 1818, in conv2d
    if num_channels % groups != 0:
ZeroDivisionError: long division or modulo by zero
```
经过调试，发现[mobilenet_ssd.py](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/mobilenet_ssd.py)57行处num_groups=int(num_groups * scale),由于传入的num_groups为1,导致计算出的num_groups结果为0.

**Comment by qingqing01** [comment]
@imistyrain 多谢指出，extra_block这块实在MobileNet v1的backone基础上又增加的模块。这块仅仅是个1x1的conv，不应该配置group，我会提个PR修复下。

另外，也在TensorFlow和Caffe的配置里确认了下，确实仅仅是1x1的conv，无group设置。

1. TF，请看tensorflow/models/research/object_detection下面
[` object_detection/models/feature_map_generators.py`](https://github.com/tensorflow/models/blob/31ae57eb8555e51493a4721f6efbea68d98a3d69/research/object_detection/models/feature_map_generators.py#L366)，

```python
if insert_1x1_conv:
        layer_name = '{}_1_Conv2d_{}_1x1_{}'.format(
            base_from_layer, index, depth_fn(layer_depth / 2))
        intermediate_layer = slim.conv2d(
            pre_layer,
            depth_fn(layer_depth / 2), [1, 1],
            padding='SAME',
            stride=1,
scope=layer_name)
```

2. Caffe:  [conv14部分](https://github.com/chuanqi305/MobileNet-SSD/blob/master/train.prototxt#L1939)

```
layer {
  name: "conv14_1"
  type: "Convolution"
  bottom: "conv13"
  top: "conv14_1"
  param {
    lr_mult: 0.1
    decay_mult: 0.1
  }
  convolution_param {
    num_output: 256
    bias_term: false
    kernel_size: 1
    weight_filler {
      type: "msra"
    }
  }
}
```
