### ISSUE TITLE
AutoDL/LRC 模型训练 module 'paddle.fluid.layers' has no attribute 'adaptive_pool2d'

### ISSUE THREAD

**Issue by zzdgit** [PaddlePaddle/models#1749]
我使用版本为：python 3.5.2   paddlepaddle-gpu 1.2.1.post97

执行./models/fluid/AutoDL/LRC/run.sh 时，报错如下：
```
Traceback (most recent call last):
  File "train_mixup.py", line 247, in <module>
    main()
  File "train_mixup.py", line 116, in main
    train(model, args, image_shape, steps_one_epoch)
  File "train_mixup.py", line 153, in train
    steps_one_epoch)
  File "train_mixup.py", line 128, in build_program
    args.batch_size, args.lrc_loss_lambda)
  File "/home/zhouzhengdong/models/fluid/AutoDL/LRC/model.py", line 255, in train_model
    self.logits, self.logits_aux = self.forward(init_channels, True)
  File "/home/zhouzhengdong/models/fluid/AutoDL/LRC/model.py", line 217, in forward
    out = fluid.layers.adaptive_pool2d(s1, (1, 1), "avg")
AttributeError: module 'paddle.fluid.layers' has no attribute 'adaptive_pool2d'
```

我也去官网查了，在fluid.layers这个下面没有adaptive_pool2d方法。
这要怎么解决？

**Comment by shippingwang** [comment]
@zzdgit 1.2版本 ```adaptive_pool2d``` 未合入

**Comment by ZhouFangru** [comment]
@shippingwang 请问哪里能找到adaptive_pool2d方法

**Comment by zzdgit** [comment]
@shippingwang 

![image](https://user-images.githubusercontent.com/27891681/52776524-beff6f80-307c-11e9-801a-261ed9219801.png)

这个安装要求1.2+的版本，我把代码里的adaptive_pool2d这个方法换成pool2d这个方法，这里可以跑通了，

能否注明paddlepaddle不同的版本需要对应的cuda版本。

还有一个问题，这个代码不能cpu版本训练吗？我试了cpu版本，看代码还调了些cuda设置，

**Comment by ZhouFangru** [comment]
@zzdgit 请问你换成pool2d方法，正常训练了吗。我换成pool2d方法，或者直接不用adaptive_pool2d方法。两种更改在训练的时候都会造成损失变成NAN。

**Comment by zzdgit** [comment]
@ZhouFangru 我这里还不能正常训练，报内存不够，我用的是GeForce GTX 1080的显卡，你那边能跑通你用的是什么型号的显卡，这个网络你知道大致有多大吗？

![image](https://user-images.githubusercontent.com/27891681/52777596-24546000-307f-11e9-8613-2eb17db6ae35.png)

**Comment by zzdgit** [comment]
@shippingwang 我把batch_size=10之后，其他参数没变，可以运行了，但是loss值很大，而且波动也很大，但是没有NAN的情况
![image](https://user-images.githubusercontent.com/27891681/52777986-f15e9c00-307f-11e9-914c-c619ca97e96f.png)

**Comment by ZhouFangru** [comment]
@zzdgit 我用的P40
![image](https://user-images.githubusercontent.com/24693920/52778158-4dc1bb80-3080-11e9-9e66-db3f44e6cee4.png)
batch=80, 训练开始loss=3, 然后一直变大，最后变为nan
![image](https://user-images.githubusercontent.com/24693920/52778541-333c1200-3081-11e9-8f6f-4cda06b35b16.png)

**Comment by zzdgit** [comment]
@ZhouFangru 我这里训练一段时间后也是这样，应该是数字太大爆内存了，然后才显示nan， 坐等官方发布`adaptive_pool2d`方法，或者有没有其他方式可以试试@shippingwang

**Comment by shippingwang** [comment]
@zzdgit autodl刚刚release， adaptive_pool2d等下1.3就可以了
