### ISSUE TITLE
图像分类模型使用run.sh 中的超参数训练VGG模型，模型不收敛

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1751]
使用image_classification下run.sh中的指令对VGG模型进行训练，经过40多个eoch后，loss依然无明显降低，模型不收敛
附件为VGG11和VGG13模型的log
[VGG13.log](https://github.com/PaddlePaddle/models/files/2868371/VGG13.log)
[VGG11.log](https://github.com/PaddlePaddle/models/files/2868372/VGG11.log)

**Comment by shippingwang** [comment]
尝试 --model_category=models_name ，解决此问题。
原因：models和models_name的VGG代码有diff
解决方案：下一个release版本，/models_name  /models 统一

**Comment by dashulu** [comment]
@shippingwang AlexNet的配置呢？AlexNet也碰到了同样的问题。 另外，关于其他模型训练的配置参数能一起给一份吗？我想对比INT16、fp16、bf16等几种精度下的收敛效果。

**Comment by shippingwang** [comment]
@dashulu 尝试下--modle_category=models_name
运行参数配置 详见 /run.sh
