### ISSUE TITLE
face_detection模型无法正常退出，ctrl+c退出后还会占用GPU显存

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/models#1752]
执行前
![image](https://user-images.githubusercontent.com/10734244/52845461-23d0cd80-3142-11e9-90d5-2ea76f0079c4.png)
执行后,显存没有释放
![image](https://user-images.githubusercontent.com/10734244/52845565-672b3c00-3142-11e9-9546-b5febd1b88c8.png)
需要手动杀掉进程才行
![image](https://user-images.githubusercontent.com/10734244/52845609-83c77400-3142-11e9-867f-763456afc3b7.png)

**Comment by heavengate** [comment]
该模型中使用了multiprocessing的reader，起了多线程来进行数据读取加速，在ctrl+c强制退出时，reader进程没法正常退出，任务运行完正常退出不会出现这种情况，若是采用ctrl+c强制退出的话，可以使用 kill -15 `ps | grep python | awk '{print $1}'` 退出reader进程

**Comment by DDDivano** [comment]
> 该模型中使用了multiprocessing的reader，起了多线程来进行数据读取加速，在ctrl+c强制退出时，reader进程没法正常退出，任务运行完正常退出不会出现这种情况，若是采用ctrl+c强制退出的话，可以使用 kill -15 `ps | grep python | awk '{print $1}'` 退出reader进程

问题是如果不用ctrl+c退出 它就不会自己退出，它会卡住

**Comment by heavengate** [comment]
> 问题是如果不用ctrl+c退出 它就不会自己退出，它会卡住

是不会启动训练还是训练完成后卡住没退出

**Comment by DDDivano** [comment]
> > 问题是如果不用ctrl+c退出 它就不会自己退出，它会卡住
> 
> 是不会启动训练还是训练完成后卡住没退出

会启动训练，完成后卡住

**Comment by heavengate** [comment]
确认为train读取的sample数与实际train_file_list sample数不一致导致的，修改batch_num可解决
