### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims[1] == filter_dims[1] * groups, but received in_dims[1]:32 != filter_dims[1] * groups:1024.

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#1753]
使用[object_detection](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection)在自己的数据集(仅含两类，背景和物体)上进行微调时报错，与预训练的模型类别不一致。而如果不使用预训练模型的话则可以正常训练.
所用命令为
```
python -u train.py --image_shape=3,$SHAPE,$SHAPE \
--pretrained_model='pretrained/ssd_mobilenet_v1_coco/' \
--model_save_dir=model
```
有没有类似于caffe中更改层的名字以便重新初始化模型参数的方法来在paddle中对最后这些层重新初始化而不是从预训练模型中加载呢？

**Comment by heavengate** [comment]
可以通过get_tensor和tensor.set来加载自定义权重，参考https://github.com/PaddlePaddle/models/blob/921a0ef37fbe948161637aae23b4869615c55129/fluid/PaddleCV/video/models/stnet/stnet.py#L137
