### ISSUE TITLE
video stnet模型在运行开始时异常退出

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1754]
报错如下：
[INFO: train.py:  221]: Namespace(batch_size=None, config='./configs/stnet.txt', epoch_num=60, learning_rate=None, log_interval=10, model_name='STNET', no_memory_optimize=False, no_use_pyreader=False, pretrain=None, resume=None, save_dir='checkpoints', use_gpu=True, valid_interval=1)
W0215 20:03:56.300457 16342 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
W0215 20:03:56.303936 16342 device_context.cc:271] device: 0, cuDNN Version: 7.0.
*** Aborted at 1550261088 (unix time) try "date -d @1550261088" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 16342 (TID 0x7fb0f3df1700) from PID 80; stack trace: ***
    @     0x7fb0f39ce390 (unknown)
    @     0x7faabf695415 (unknown)
    @     0x7faabf68e5b0 (unknown)
    @     0x7faabf69290d ncclCommInitAll
    @     0x7fb08b3ccba8 paddle::platform::NCCLContextMap::NCCLContextMap()
    @     0x7fb08b3c9072 paddle::framework::ParallelExecutor::ParallelExecutor()
    @     0x7fb08b2c4542 _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIIRKSt6vectorIN5boost7variantIN6paddle8platform9CUDAPlaceENS9_8CPUPlaceENS9_15CUDAPinnedPlaceENS6_6detail7variant5void_ESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EESaISG_EERKSt13unordered_setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4hashISR_ESt8equal_toISR_ESaISR_EERKNS8_9framework11ProgramDescERKSR_PNS10_5ScopeERS5_IS17_SaIS17_EERKNS10_7details17ExecutionStrategyERKNS1B_13BuildStrategyEEE7executeINS_6class_INS10_16ParallelExecutorEIEEEIELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderESK_SZ_S13_S15_S17_S1A_S1E_S1H_E_vIS1U_SK_SZ_S13_S15_S17_S1A_S1E_S1H_EINS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorEEEEvOS1N_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES2B_
    @     0x7fb08b284b2d pybind11::cpp_function::dispatcher()
    @           0x60bb6b _PyMethodDef_RawFastCallDict
    @           0x4eaf20 _PyObject_Call_Prepend
    @           0x4eb56e PyObject_Call
    @           0x43f655 (unknown)
    @           0x52ab79 (unknown)
    @           0x4e99ea _PyObject_FastCallKeywords
    @           0x561224 _PyEval_EvalFrameDefault
    @           0x55b39a _PyEval_EvalCodeWithName
    @           0x4eb2e8 _PyObject_Call_Prepend
    @           0x52d667 (unknown)
    @           0x52ab79 (unknown)
    @           0x4e9ad5 _PyObject_FastCallKeywords
    @           0x56164b _PyEval_EvalFrameDefault
    @           0x55b760 _PyEval_EvalCodeWithName
    @           0x4ea963 _PyFunction_FastCallKeywords
    @           0x55c2c9 _PyEval_EvalFrameDefault
    @           0x55b39a _PyEval_EvalCodeWithName
    @           0x55b123 PyEval_EvalCode
    @           0x62ce02 (unknown)
    @           0x62d26a PyRun_FileExFlags
    @           0x62d027 PyRun_SimpleFileExFlags
    @           0x606265 (unknown)
    @           0x605eea _Py_UnixMain
    @     0x7fb0f2ac0830 __libc_start_main
scripts/train/train_stnet.sh: line 2: 16342 Segmentation fault      python train.py --model-name="STNET" --config=./configs/stnet.txt --epoch-num=60 --valid-interval=1 --log-interval=10

**Comment by SunGaofeng** [comment]
QA换了台机器之后没有出现此错误，只在单台机器上报了这个错误

**Comment by xiegegege** [comment]
在GPU没有开启P2P的机子上跑video模型会报这个错误，开启P2P的机子正常，另外还有nlp下的deep_attention_matching_net会报这个错
