### ISSUE TITLE
video tsn loss 下降很慢

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1756]
video 下的tsn模型在运行到大概10个epoch后，loss下降的很缓慢，几乎没有变动，如图所示：
<img width="638" alt="cab56c604bac3a0b03738f0303f0fc5e" src="https://user-images.githubusercontent.com/46314656/52926062-28c69480-336f-11e9-902c-a41d031a5fc4.png">

**Comment by SunGaofeng** [comment]
未加载resnet50预训练权重，加载之后目前已训练13个epoch，与本地测试时趋势一致
