### ISSUE TITLE
video stnet 模型在训练一段时间后loss值变大

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1758]
video stnet 模型在训练一段时间后loss值变大，截图如下：
<img width="359" alt="0b45bbfc7c3d5f1f9f797fa0c98d87f4" src="https://user-images.githubusercontent.com/46314656/52932248-17d74c80-338a-11e9-90af-03e66dac40e8.png">

**Comment by SunGaofeng** [comment]
正在查找原因中

**Comment by SunGaofeng** [comment]
使用cudnn7时bn层moving mean和var计算不对，改成cudnn5时loss正常下降了
