### ISSUE TITLE
场景文字识别中，注意模型为什么要有两个label？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1775]
在场景文字识别中的注意模型，为什么会用到两个label，而是第一个label_in要在前面加[0]，第二个label_out要在后面加[1]。

https://github.com/PaddlePaddle/models/blob/67b52af0eb08a0cb339196971fc9164656250c7e/fluid/PaddleCV/ocr_recognition/data_reader.py#L100

**Comment by qingqing01** [comment]
@yeyupiaoling 注意力模型采用seq2seq结构：

可以参考 https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/README.cn.md#%E7%BC%96%E7%A0%81%E5%99%A8-%E8%A7%A3%E7%A0%81%E5%99%A8%E6%A1%86%E6%9E%B6 这里对encode-decoder的介绍。

这里第一个label_in相等于target的，[SOS]标识起始位置，在训练中作为seq2seq解码部分的输入。在解码部分会预测下一个时刻的输出，会去掉起始标识，同时预测的结尾也会加上 EOS的结尾标识。
第二个label_out是真实的groud-truth，用来和解码部分的预测输出做对比，用来计算损失和评估结果。

**Comment by qingqing01** [comment]
@yeyupiaoling  之前回答觉得有误，更新了~

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，谢谢回答。
