### ISSUE TITLE
在场景文字识别的注意力模型中，为什么图片不都是同一shape

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1776]
在场景文字识别的注意力模型中，图片的shape只是每一个batch相同而已，而不是全部都是同一个shape。
跟`images = fluid.layers.data(name='pixel', shape=data_shape, dtype='float32')`都不是同一个，这是为什么呢？不应该要统一的吗？

https://github.com/PaddlePaddle/models/blob/67b52af0eb08a0cb339196971fc9164656250c7e/fluid/PaddleCV/ocr_recognition/data_reader.py#L92-L94

**Comment by qingqing01** [comment]
@yeyupiaoling  场景文字识别模型提供的例子是按[行识别]文字，这里输入图片的Height是相同的，Width可以不同，真实场景中，图片也是可变长的。 如果要统一，resize成相同的也是可以的，不过由于resize可能使得图片变形，可能对精度有影响。

Paddle正好支持不同batch的变长，可以不统一。

**Comment by yeyupiaoling** [comment]
@qingqing01 回答很棒，很清晰，一下子就懂了。谢谢。
