### ISSUE TITLE
在场景文字识别的注意力模型中，是否可以保存预测模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1777]
场景文字识别的注意力模型，与图片分类的模型不一样，注意力模型要复杂很多，但是如果我想保存预测模型inference_model，是否可以呢？

在图像分类中，可以调用`paddle.fluid.io.save_inference_model`接口保存预测模型，之后需要时再调用`paddle.fluid.io.load_inference_model`预测图片，而且预测代码非常简单，不需要编写之前的模型代码。

注意力模型是否也可以这样，保存预测模型，之后的预测中，只需要加载这预测模型，不需要再编写网络模型代码。

**Comment by wanghaoshuang** [comment]
很赞的问题，答案是：不行。

因为预测模型和训练模型在decoder部分有所不同，所以很难从训练网络直接拆出来预测网络，目前只能重新编写预测网络的模型代码。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 这个回答我很难接受。[伤心]
不过谢谢你了，给我解惑。我主要是想利用PaddleMobile框架迁移到Android手机上，PaddleMobile就是读取预测模型直接预测的。
