### ISSUE TITLE
在场景文字识别中有有一些小问题请教

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#1778]
在场景文字识别中，以下的三个if判断我不是很明白。比如关于停止训练，不是用for循环指定pass数更为直观吗？为啥好这样设计，意义有什么特别之处？

第二个应该是纯粹输出信息，但是应该是有含义的吧？

第三个就更不懂它要干啥了，请问它的作用是什么呢？

https://github.com/PaddlePaddle/models/blob/67b52af0eb08a0cb339196971fc9164656250c7e/fluid/PaddleCV/ocr_recognition/train.py#L140-L146

**Comment by wanghaoshuang** [comment]
这3个if语句是用于分析模型训练速度性能的。
为了更准确的反应训练速度，我们需要把前若干个batch的耗时去掉，所以就有了args.skip_batch_num这个参数。
1. 第一个if是为了把跳过的batch数补回来
2. 第二个if告诉用户当前step(batch)属于warm-up阶段
3. 第三个if是开始统计时间数据

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 好的，谢谢回答，删除它们不影响模型的训练吧？
