### ISSUE TITLE
video 中的模型在单卡时无法正常训练

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1783]
以stnet为例，在单卡时前80个iter训练结果如下：
<img width="801" alt="157f3740384ecbc0a3a4c67b7bbd0560" src="https://user-images.githubusercontent.com/46314656/53311192-d810e780-38ea-11e9-9d78-55cce4be2360.png">
在8卡时正常的训练结果如下：
<img width="879" alt="731cf84aa687b0f658d1ffd555fd1a56" src="https://user-images.githubusercontent.com/46314656/53311252-17d7cf00-38eb-11e9-8e07-5f5fc1612ad9.png">
单卡时无法有效降低loss, 升高acc，8卡时才能正常训练

**Comment by SunGaofeng** [comment]
单卡使用的batch size = 16？
我之前在4卡p40上debug的时候使用batch size = 16，最开始loss也是波动比较大，未见明显下降。

**Comment by xiegegege** [comment]
batch size 使用的是默认的128

**Comment by SunGaofeng** [comment]
是通过export CUDA_VISIBLE_DEVICES=0来设置使用单卡的吗？
程序里面configs/stnet.txt里面的num_gps=8, batch_size=128，是八卡总的batchsize，使用pyreader的时候，会自动计算单张卡上的batch size以创建reader，这样每张卡上的batch size就是16。

**Comment by xiegegege** [comment]
对的，是通过export CUDA_VISIBLE_DEVICES=0设置的，所以如果单卡训练的时候需要设置num_gpus = 1，batch_size=16吗？

**Comment by SunGaofeng** [comment]
需要改batch_size和num_gpus。不过如果使用pyreader的话，会自动计算单卡的batch size，所以最后实际用到的batch size是16.
我之前调试的时候试过batch size=16的情形，开始loss确实不怎么下降，直到1000个iter之后才发现loss显著下降到5.+，之前一直波动比较大。
我觉得这可能是因为batch_size=16的时候，mini batch里面的数据比较少，batch之间数据分布差别比较大，每次进来的数据分布有比较大的差异，导致loss不会显著下降而是有比较大的波动。
