### ISSUE TITLE
图像处理ResNet152，UserWarning: Possibly corrupt EXIF data.  Expecting to read 1835008 bytes but only got 0. Skipping tag 0

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1786]
在使用ResNet152训练的过程中，log中出现

![image](https://user-images.githubusercontent.com/37854899/53318660-f1c22700-390a-11e9-8e4e-b16229da5c50.png)
虽然不影响最后的训练结果，但是用户体验非常不好
附件为训练ResNet152模型的log
[ResNet152.log](https://github.com/PaddlePaddle/models/files/2899227/ResNet152.log)

**Comment by shippingwang** [comment]
PIL==4.0.0
