### ISSUE TITLE
gru4rec infer.py缺少vocab_path参数

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1793]
gru4rec非负采样部分的预测会报错：
<img width="944" alt="c752a62c1645a1f2157f20980551325d" src="https://user-images.githubusercontent.com/46314656/53414412-ae021700-3a09-11e9-9b97-1bfe68f5e100.png">
且infer.py缺少vocab_path参数
<img width="481" alt="83a6e486fd6903f7a9b305a1cb01e574" src="https://user-images.githubusercontent.com/46314656/53414544-f6213980-3a09-11e9-95ee-413ace3d6912.png">

**Comment by frankwhzhang** [comment]
https://github.com/PaddlePaddle/models/pull/1795  已修复合入
