### ISSUE TITLE
ctr 预测错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1794]
ctr预测报错：
<img width="887" alt="cd9e40d4cae5e750a12c21678fa053ef" src="https://user-images.githubusercontent.com/46314656/53462593-4ab2cc00-3a7f-11e9-822e-dda004f376ba.png">

**Comment by jacquesqiao** [comment]
用的是最新的代码么

**Comment by xiegegege** [comment]
是最新的代码

**Comment by jacquesqiao** [comment]
训练能跑么

**Comment by xiegegege** [comment]
能跑的，训练没问题

**Comment by kjfren1985** [comment]
请问有结果了吗，感觉是reader.py里面的代码有问题？

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/models/pull/1798 试试这个

**Comment by kjfren1985** [comment]
test.txt比train.txt少第一列label，而_reader_creator方法里：
`self.continuous_range_ = range(1, 14)`
`self.categorical_range_ = range(14, 40)`
`for idx in self.continuous_range_:`
`...`
`for idx in self.categorical_range_:`
`...`
`label = [int(features[0])]`

直接这么改不太对啊感觉

> #1798 试试这个

**Comment by xiegegege** [comment]
好的，我试下

**Comment by kjfren1985** [comment]
> #1798 试试这个

`fluid infer.py --data_path data/raw/train.txt --model_path models/pass-9 2>&1 | tee test.log &`

Traceback (most recent call last):
  File "infer.py", line 134, in <module>
    infer()
  File "infer.py", line 70, in infer
    feeder = fluid.DataFeeder(feed_list=data_list, place=place)
  File "/home/XXX/paddlepaddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 146, in __init__
    for each_var in feed_list:
TypeError: 'Variable' object is not iterable
