### ISSUE TITLE
在实际数据上运行ner的训练demo，训练时precision,recall,f1都为0是否正常

### ISSUE THREAD

**Issue by hitwangshuai** [PaddlePaddle/models#180]
![f8056b82ec924d17b6337dab466af441](https://user-images.githubusercontent.com/22500910/28709566-6ee42608-73b3-11e7-99d4-bbcb30d13f6d.png)
我在实际数据集上运行了一下ner的demo，训练时截图如上图，怎么感觉有问题，有问题的话会出在哪呢？麻烦您看一下，谢谢啦~~
主要代码和数据：
[music.zip](https://github.com/PaddlePaddle/models/files/1182507/music.zip)

**Comment by lcy-seso** [comment]
建议用非常小的周期保存模型，保存下来模型，然后用crf decoding layer 输出标记结果，check 和 evaluator 的结果不一致。如果是这样，那么就一定是paddle的问题。

**Comment by Yancey0623** [comment]
先关掉这个issue了，如有更新可以随时打开。
