### ISSUE TITLE
cyclegan 跑了训练之后，如何infer

### ISSUE THREAD

**Issue by burness** [PaddlePaddle/models#1801]
infer里的init_model怎么传参？ 我传checkpoints目录， 显示load 错误， 能说明下 infer.py的init_model是啥吗

**Comment by burness** [comment]
我发现源码里面给的代码有bug:

https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/gan/cycle_gan/train.py#L121 这里在训练的时候，是将模型保存在对应的params文件里，而不是以参数分开保存，而https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/gan/cycle_gan/infer.py#L40  在infer.py load中，没有指定filename 参数为params， 会以参数名去查找然后load参数，这里有bug，

修改之后，没有出现找不到参数的问题，但是有这样的报错：

![image](https://user-images.githubusercontent.com/3112825/53553393-8ed5c780-3b78-11e9-9173-15efad7c4f42.png), 提示不能load部分数据，而train.py中确实把g_a, g_b分开保存的，
@qingqing01, 能帮忙看下吧。

**Comment by guoshengCS** [comment]
可以试下使用[load_vars](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/io_cn.html#paddle.fluid.io.load_vars)传入vars这个参数来load部分数据

**Comment by burness** [comment]
@guoshengCS  尝试了 还是不行的 同样的报错
指定main_program:
![image](https://user-images.githubusercontent.com/3112825/53555326-b0d14900-3b7c-11e9-9a84-b448f5527a78.png)
不指定main_program:
![image](https://user-images.githubusercontent.com/3112825/53555614-3ce37080-3b7d-11e9-948f-29fd5d1c0800.png)

**Comment by guoshengCS** [comment]
可以试下训练的时候参数分开保存，infer.py里`load_vars`需要显式的设置vars这个参数为希望load的参数的list

**Comment by burness** [comment]
@guochaorong 之前想过这种可能性，但是耗时比较大 ，那我试试看再反馈

**Comment by wanghaoshuang** [comment]
非常抱歉，因为失误，我们没有保证train.py中save checkpoint和infer中load checkpoint的一致性，给您造成了困扰，我们已经在pr #1829 中修复了该问题。

**Comment by wanghaoshuang** [comment]
另外，我们对infer.py的一次[修改](https://github.com/PaddlePaddle/models/pull/1829/files#diff-d594e13735d2be09491f272ffb0a79e2R78)忘记了同步到文档中，在infer的时候，需要指定对应的input style.

**Comment by burness** [comment]
@wangguibao  input style 这个我在代码中看到了 ，load_vars 可以解决 @guochaorong
