### ISSUE TITLE
word2vec模型代码bug，代码中死循环

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#1804]
train.py 
209行 while True:

**Comment by JiaXiao243** [comment]
是呢，我这边word2vec老是跑不完~ 以为是数据量过大的原因呢~
loss 从36.4降低到30.6基本就不再降低了，一直在重复输出徘徊在31左右的loss数据，感觉这个loss还是挺高的~

**Comment by JiaXiao243** [comment]
word2vec模型在trian.py 将209行 while True注释掉，运行报如下错误：
![image](https://user-images.githubusercontent.com/37854899/53722547-c908d700-3ea0-11e9-99ea-2d47e6507f77.png)

**Comment by frankwhzhang** [comment]
word2vec 代码目前正在修改 预计下周ready
