### ISSUE TITLE
deeplabv3+多卡下训练报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/models#1805]
如下错误:
1. pyreader没有stop函数
Training done. Model is saved to output1
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    py_reader.stop()
AttributeError: 'Variable' object has no attribute 'stop'
2. 多卡时，训练报错
  训练命令
  python train.py --batch_size=4 --train_crop_size=769 --total_step=50 --save_weights_path=output1 --dataset_path=$DATASET_PATH --enable_ce
![image](https://user-images.githubusercontent.com/22165420/53610251-3698d700-3c05-11e9-8687-6fd4326c7575.png)

**Comment by cjld** [comment]
fixed https://github.com/PaddlePaddle/models/pull/1807
