### ISSUE TITLE
tagspace文档中数据链接失效

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#1825]
ag news dataset 链接失效

**Comment by dashulu** [comment]
另外，跑python infer.py之后出现的结果如下， 这个怎么看模型的准确率？
('start index: ', 1, ' last_index:', 10)
start read file
(1000, 0.468)
(2000, 0.46)
(3000, 0.4533333333333333)
(4000, 0.437)
(1000, 0.484)
(2000, 0.48)
(3000, 0.4746666666666667)
(4000, 0.486)
(1000, 0.596)
(2000, 0.558)
(3000, 0.5653333333333334)
(4000, 0.57)
(1000, 0.616)
(2000, 0.61)
(3000, 0.5973333333333334)
(4000, 0.615)
(1000, 0.664)
(2000, 0.628)
(3000, 0.6293333333333333)
(4000, 0.627)
(1000, 0.652)
(2000, 0.616)
(3000, 0.6266666666666667)
(4000, 0.618)
(1000, 0.688)
(2000, 0.682)
(3000, 0.6666666666666666)
(4000, 0.669)
(1000, 0.656)
(2000, 0.646)
(3000, 0.644)
(4000, 0.63)
(1000, 0.704)
(2000, 0.68)
(3000, 0.6626666666666666)
(4000, 0.656)
(1000, 0.7)
(2000, 0.68)
(3000, 0.672)
(4000, 0.66)

**Comment by frankwhzhang** [comment]
文档链接 暂时失效 数据下载可以 wget ftp://10.199.240.57/home/zhangwenhui03/dataset_dir/tagspace/data/train.csv
ftp://10.199.240.57/home/zhangwenhui03/dataset_dir/tagspace/data/test.csv

**Comment by frankwhzhang** [comment]
这个infer.py 括号第二个数是acc

**Comment by frankwhzhang** [comment]
文档链接已经修复 见https://github.com/PaddlePaddle/models/pull/1839
