### ISSUE TITLE
metric learning 无法下载预训练模型

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1836]
<img width="909" alt="e5efa4d5ff5fca7417750aa5aba698dd" src="https://user-images.githubusercontent.com/46314656/53789201-ddaba480-3f5e-11e9-9065-f8d5152a4d2d.png">

**Comment by qingqing01** [comment]
Fixed by https://github.com/PaddlePaddle/models/pull/1891

**Comment by xiegegege** [comment]
还是没法下载的样子～

**Comment by qingqing01** [comment]
@xiegegege 你指的是 Evaluation部分对模型的验证？metric leanring这个模型没有提供已经训练好的模型。

https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/metric_learning#evaluation

**Comment by kebinC** [comment]
@xiegegege  metric leanring 没有提供训练好的模型， 测试的话要根据前面训练好的模型来指定路径
