### ISSUE TITLE
SSD模型按照readme的文档配置后，训练20轮之后，map的值仅为0.02

### ISSUE THREAD

**Issue by dashulu** [PaddlePaddle/models#1837]
如题， map值仅为0.02， 与文档说的训练120轮能到73.2%差了好多，请问这个是什么原因？

**Comment by qingqing01** [comment]
@dashulu 请问下载预训练模型了吗？ 先检查下预训练模型load是否正常。 https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection#download-the-pre-trained-model

**Comment by dashulu** [comment]
@qingqing01 已经下载过了。

**Comment by dashulu** [comment]
预处理模型的路径配置错了。
