### ISSUE TITLE
ocr_recognition 评估、预测错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1846]
1、ocr_recognition CTC model eval.py有函数缺少参数：
<img width="909" alt="e8ec154b99d031a872f8f222e1088e92" src="https://user-images.githubusercontent.com/46314656/53880163-453f1e00-404b-11e9-85c7-8dd84fe81020.png">
2、预测时CTC和attention模型的报错：
<img width="987" alt="93b4cc1a5a0309688355e42a33bddad7" src="https://user-images.githubusercontent.com/46314656/53880294-9e0eb680-404b-11e9-9619-47c6bdaff889.png">

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/models/commit/c765794e0d8bd9e2f93a29962de89560ca1506be#diff-366b354acb1f3c3a449809e462657458R209

**Comment by JiaXiao243** [comment]
下载的是最新版本的models，运行python eval.py 报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/54268250-c2bbde80-45b5-11e9-9c32-133e75759c99.png)
使用文档中提供的ocr_attention_params进行infer报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/54268332-ee3ec900-45b5-11e9-8240-0083a142806c.png)
使用ocr_ctc_params进行infer正确。

**Comment by xiegegege** [comment]
1.attention模型eval报错：
<img width="835" alt="b9efa348f566a44a527fa99d7b50d100" src="https://user-images.githubusercontent.com/46314656/56134632-9551be80-5fc1-11e9-9fe0-1cbb65cf7cc7.png">
2.attention模型infer报错：
Traceback (most recent call last):
  File "infer.py", line 153, in <module>
    main()
  File "infer.py", line 149, in main
    inference(args)
  File "infer.py", line 81, in inference
    feed_dict = get_feeder_data(data, place, need_label=False)
TypeError: get_attention_feeder_for_infer() got an unexpected keyword argument 'need_label'
