### ISSUE TITLE
image classification文档易用性部分汇总

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1849]
1. 点击文档中超连接trian无法链接到文档中Training a model with flexible parameters位置
  
![image](https://user-images.githubusercontent.com/37854899/53927333-807c3400-40c1-11e9-9a0f-c21062f742a8.png)

2. 点击Table of Contents处 Training a model with flexible parameters、Supported models and performances无法跳转到对应文档位置
![image](https://user-images.githubusercontent.com/37854899/53927417-ce913780-40c1-11e9-8bbf-9691e2bc90f1.png)
3. 文档中 installation document链接失效
   
![image](https://user-images.githubusercontent.com/37854899/53927463-f385aa80-40c1-11e9-8c38-9ec8e3e086b3.png)
4. train.py 中参数with_mem_opt默认值为True，文档中写为False，两者不一致。
   
![image](https://user-images.githubusercontent.com/37854899/53927754-c259aa00-40c2-11e9-8d71-51336ceb5f08.png)
![image](https://user-images.githubusercontent.com/37854899/53927791-d9000100-40c2-11e9-8d55-d1f283c83eec.png)
5. 文档中parameter introduction处对训练参数介绍不全
![image](https://user-images.githubusercontent.com/37854899/53927892-2c724f00-40c3-11e9-8a0e-93b75171c904.png)
6.  Evaluation部分：pretrained models链接失效
 
![image](https://user-images.githubusercontent.com/37854899/53928009-91c64000-40c3-11e9-8594-2b09cb13d1fa.png)
7. Models with specified parameters names、Models without specified parameters处介绍不清
文档中提供了(1)Released models: specify parameter names 
                      (2)Released models: not specify parameter names
两种预训练模型，但是并没有阐述modle_catetory=modles/models_name的区别，在使用两种不同预训练模型在精度以及速度方面有何不同，用户不知道该选哪个，也不知道为何要列出这两种不同的预训练模型以供选择。
![image](https://user-images.githubusercontent.com/37854899/53928088-d5b94500-40c3-11e9-855c-895461444aa7.png)

**Comment by shippingwang** [comment]
copy that

**Comment by shippingwang** [comment]
already done by #1880
