### ISSUE TITLE
human_pose_eatimation模型valid && test报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1858]
1.valid报错信息如下
<img width="795" alt="fbdbca570e73b0d09700bc485479bec2" src="https://user-images.githubusercontent.com/37854899/54026246-29b54e00-41d8-11e9-865e-b94274ff5d48.png">
2. test报错信息如下
<img width="794" alt="fa0c6f234c4f180899ed4e10d86d91de" src="https://user-images.githubusercontent.com/37854899/54026259-32a61f80-41d8-11e9-92eb-402ab5b5c5ba.png">
3.文档链接失效
![image](https://user-images.githubusercontent.com/37854899/54026319-64b78180-41d8-11e9-96e0-1b0ff7991bd6.png)
![image](https://user-images.githubusercontent.com/37854899/54026332-6a14cc00-41d8-11e9-96dd-36ddbf5a6153.png)

**Comment by qingqing01** [comment]
@JiaXiao243 多谢反馈，这个模型会在下个版本更新，我们一并修改问题~

**Comment by qingqing01** [comment]
Fixed in https://github.com/PaddlePaddle/models/pull/1912
