### ISSUE TITLE
faste-rcnn 训练代码可以支持VOC数据格式吗？

### ISSUE THREAD

**Issue by soldier828** [PaddlePaddle/models#1861]
models/fluid/PaddleCV/rcnn   目前看faster-rcnn的训练代码reader只支持coco的数据格式，请问是否可以增加对VOC格式reader的支持？

**Comment by Yancey0623** [comment]
Hi @jerrywgz 请问我们有在Faster RCNN上支持多个数据集的计划吗？

**Comment by jerrywgz** [comment]
我们目前faster rcnn还只支持coco数据集，voc数据集可以参考object detection中的ssd模型
