### ISSUE TITLE
fetch StNet pretrained model failed

### ISSUE THREAD

**Issue by xyoungli** [PaddlePaddle/models#1868]
failed to get StNet pretrained model from following url https://paddlemodels.bj.bcebos.com/video_classification/stnet_kinetics.tar.gz as described in https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/video/models/stnet/README.md.
error: {"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"04581481-d584-43c3-9b23-08789ce86f3b"}

**Comment by heavengate** [comment]
Fixed, please try to download again
