### ISSUE TITLE
faster rcnn eval报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1889]
下载文档中的Faster RCNN的预训练模型Fluid RoIPool minibatch padding，执行指令：python eval_coco_map.py --dataset=coco2017 --pretrained_model=./model_pool_minibatch_padding/ --MASK_ON=False
报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/54325883-5f768e80-463f-11e9-8318-e59e59d2f16d.png)
PS:使用MASK RCNN的预训练模型Fluid mask no padding进行eval，得到正确结果。
![image](https://user-images.githubusercontent.com/37854899/54325936-89c84c00-463f-11e9-93eb-e18fc4d86de4.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/pull/1892
