### ISSUE TITLE
transformer infer无输出log

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1894]

**Comment by JiaXiao243** [comment]
在centos6.1_cuda9.0_cudnn7.0的docker 中，paddle为最新develop分支编译安装的，models下载的最新版本。
执行transformer infer指令：python -u infer.py --src_vocab_fpath ./wmt_bpe/vocab_all.bpe.32000 --trg_vocab_fpath ./wmt_bpe/vocab_all.bpe.32000 --special_token '<s>' '<e>' '<unk>' --test_file_pattern ./wmt_bpe/newstest2016.tok.bpe.32000.en-de --token_delimiter ' ' --batch_size 32 model_path trained_models/iter_10000.infer.model beam_size 5 max_out_len 255 
<img width="1302" alt="d95e460f459e536029563ceaf7c35cc1" src="https://user-images.githubusercontent.com/37854899/54345237-9ec3d000-467d-11e9-9e02-e1e62a00c142.png">
如图所示，infer的log中无infer的result。

**Comment by jerrywgz** [comment]
从目前的log来看只是打印了一些warning，这是paddle 1.3版本之后加入的

**Comment by JiaXiao243** [comment]
log中无infer的结果数据~

**Comment by guoshengCS** [comment]
可以先检查下`test_file_pattern`中的数据路径有误导致无数据

**Comment by JiaXiao243** [comment]
检查了一下，输入的数据名称有一些错误，修改后得到infer结果，建议可否加一些输入判断信息，若test_file_pattern数据路径有误，输出一些错误提示信息。
