### ISSUE TITLE
machine_reading_comprehension 模型中定义var使用‘：’分割，在多机中transplier中会挂掉

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1903]
在模型定义中，定义var前缀时候，使用了':'字符，导致在做多机中transplier中挂掉
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/machine_reading_comprehension/rc_model.py#L97

![image](https://user-images.githubusercontent.com/33303691/54605577-8fc98d00-4a84-11e9-85ca-90254c1ffa5f.png)

**Comment by jacquesqiao** [comment]
请不要使用“:”作为var name的一部分
