### ISSUE TITLE
why the net don't have any active function in googlenet.py in backbone?

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/models#1919]
for example:
...        
conv = self.conv_layer(
            input=pool, num_filters=64, filter_size=1, stride=1, act=None)
conv = self.conv_layer(
            input=conv, num_filters=192, filter_size=3, stride=1, act=None)
...

**Comment by SunGaofeng** [comment]
Yes, the lines you listed is just convolution without activation. 
Do you want to add activation after convolution?

**Comment by shippingwang** [comment]
In our googlenet implementation, we don't apply relu activation in some layers.

**Comment by shippingwang** [comment]
Feel free to reopen this issue if still have problems.
