### ISSUE TITLE
object detection使用最新develop分支源码编译paddle训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1921]
环境：使用develop分支，编译安装paddle；
调用训练指令：python -u train.py --batch_size=64 --dataset='pascalvoc' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/' --epoc_num=1 
报错信息如下：
<img width="992" alt="1429eff7a9de8f8e2941cb6574b0ab81" src="https://user-images.githubusercontent.com/37854899/54974812-3d322880-4fd0-11e9-964c-6f6def339292.png">
具体log见附件，paddle==1.3.0、paddle==1.3.1可以正常训练。
[object_detection.log](https://github.com/PaddlePaddle/models/files/3006725/object_detection.log)

**Comment by JiaXiao243** [comment]
PS:运行object detection后，进程hang住，无法正常退出。占用显存。
<img width="547" alt="c2d1973e223b876f4051a5682fbfb426" src="https://user-images.githubusercontent.com/37854899/54975938-af583c80-4fd3-11e9-8e9c-9f173e155094.png">

**Comment by SunGaofeng** [comment]
这里运行的是ssd的代码？

**Comment by JiaXiao243** [comment]
SSD 目标检测

**Comment by qingqing01** [comment]
I found the error is caused by https://github.com/PaddlePaddle/Paddle/pull/16188

**Comment by qingqing01** [comment]
This error is caused by https://github.com/PaddlePaddle/Paddle/pull/16303
