### ISSUE TITLE
PaddlePaddle从源码编译Ngraph问题和建议

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/models#1929]
系统：Ubuntu16.04
[Ngraph文档](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/README_ngraph.md)中的编译语句

```shell
cmake ..  -DCMse -DWITH_GPU=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON  -DWITH_NGRAPH=ON
```

建议修改成：
```shell
cmake .. -DPY_VERSION=3.6 -DCMse -DWITH_GPU=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON  -DWITH_NGRAPH=ON
# DPY_VERSION=3.6（python的版本）
```

**Comment by OliverLPH** [comment]
从GitHub上的Paddle源码编译[Ngraph](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/image_classification/README_ngraph.md）

使用图中的指令
<img width="877" alt="1553679267" src="https://user-images.githubusercontent.com/14963836/55065319-92e10080-50b6-11e9-9ab3-5144e5bcab5d.png">

但是报错，报错信息如下
<img width="984" alt="0ea698fcee46d64cfda9546943d52c91" src="https://user-images.githubusercontent.com/14963836/55069765-c1170e00-50bf-11e9-9bd6-3b69bb19dfea.png">

-- Could NOT find PY_pip (missing: PY_PIP)
在Paddle的issue里面也查到了同样的问题：https://github.com/PaddlePaddle/Paddle/issues/154

原贴建议的是增加 PIP的路径。
```shell
cmake .. -DPY_PIP=/Library/Python/2.7/site-packages/pip
```
但是还是会多出其他问题，仍然会提示其他的XX没找到。

**Comment by qingqing01** [comment]
@OliverLPH 请问问题解决了吗？

**Comment by tensor-tang** [comment]
@OliverLPH 编译中pip等找不到的问题跟ngraph本身无关。
按照你的环境，哪怕去掉cmake后面的选项也应该一样会编译不过，这个应该还是你的机器环境我问题，可以用我们的docker，latest-dev。

**Comment by tensor-tang** [comment]
这是[源码安装](http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Ubuntu.html)的文档，可以先保证文档里面的操作都ok之后再加ngraph的选项。
我们之所以没在这个里面加这个文档路径，是因为有建议这个地址会变，所以改为现在文档你看到的地址。

**Comment by OliverLPH** [comment]
@qingqing01 嗯嗯解决了，是我自己理解错了。

**Comment by OliverLPH** [comment]
@tensor-tang 谢谢，👍
