### ISSUE TITLE
DIN 模型问题汇总

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1934]
**1、数据处理部分**
+ convert_pd.py 脚本依赖pandas，部分用户没有安装会报错，请给出提示；
+  python2.7 下`remap_id.py` 脚本执行报错如下:
    ```bash
   File "remap_id.py", line 4
    from __future__ import print_function
   SyntaxError: from __future__ imports must occur at the beginning of the file
   ```
+ conver_pd 脚本在执行过程中，时间稍长，建议加入提示；
+ python2.7 下 `build_dataset.py` 同样存在 `from __future__ import print_function`的问题；

**2、数据处理部分**
+ 训练超出一定的epoch 后会出现过拟合，建议给出说明

**Comment by hutuxian** [comment]
PR：https://github.com/PaddlePaddle/models/pull/1939

**Comment by ccmeteorljh** [comment]
> PR：#1939
该pr已修复
