### ISSUE TITLE
官网图像分类VGG16例子训练碰到问题

### ISSUE THREAD

**Issue by qianledan** [PaddlePaddle/models#1962]
python train.py \
        --model=VGG16 \
        --batch_size=64 \
        --total_images=50000 \
        --class_dim=10 \
        --image_shape=3,32,32 \
        --model_save_dir=output/ \
        --with_mem_opt=True \
        --lr_strategy=other \
        --lr=0.001 \
        --num_epochs=120 \
        --l2_decay=1.2e-4 \
        --model_category=models_name \

官网中跑ImagNet数据集，我修改为Cifar10数据集跑VGG16 ，其中        
optimizer = fluid.optimizer.Momentum(
            learning_rate=lr,
            momentum=momentum_rate,
            regularization=fluid.regularizer.L2Decay(l2_decay))
设置120pass，大概在20多个pass，loss值接近0，acc为1。。。找不出问题在哪里？请问该实例只能用于ImageNet数据集的训练吗？
![QQ浏览器截图20190402144329](https://user-images.githubusercontent.com/45925696/55381480-e12e4d80-5555-11e9-9d00-5c9b2b9ee558.png)

**Comment by shippingwang** [comment]
@qianledan  具体代码 和 val的结果麻烦给一下

**Comment by qianledan** [comment]
> @qianledan 具体代码 和 val的结果麻烦给一下

我没有val，只跑train。代码基本都没有修改。只修改了一个地方：数据来源代码       
 train_reader = paddle.batch(
            paddle.dataset.cifar.train10(), batch_size=train_batch_size, drop_last=True)
 test_reader = paddle.batch(paddle.dataset.cifar.test10(), batch_size=test_batch_size)

**Comment by shippingwang** [comment]
> paddle.dataset.cifar.train10(),

你没做预处理，在reader里面过一遍试一下

**Comment by shippingwang** [comment]
feel free to reopen this issue if still have problems.
