### ISSUE TITLE
metric learning易用性汇总

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#1964]
1.句子不通顺
![image](https://user-images.githubusercontent.com/37854899/55381215-1edea680-5555-11e9-8925-175e22b5ecc2.png)
2.安装文档链接出错
![image](https://user-images.githubusercontent.com/37854899/55381234-2f8f1c80-5555-11e9-8e2f-ffc874603b0c.png)
![image](https://user-images.githubusercontent.com/37854899/55381237-328a0d00-5555-11e9-9b0a-14395792da03.png)
3. 建议对infer.py输出的log进行优化，不简洁，表述不清；
  
![image](https://user-images.githubusercontent.com/37854899/55381330-7715a880-5555-11e9-9fa9-d84760872058.png)
4. 建议模型训练部分添加ResNet50预训练模型的下载链接，并在文档中添加加载ResNet50预训练模型的表述。在加载ResNet50预训练模型前提下，使用默认超参数设置，才能达到文档中描述的Recall@Rank-1数值。

**Comment by qingqing01** [comment]
Fixed by https://github.com/PaddlePaddle/models/pull/1990
