### ISSUE TITLE
generate_sequence_by_rnn_lm文本预测总是生成太短的句子

### ISSUE THREAD

**Issue by sky-lc** [PaddlePaddle/models#197]
最近在研究paddlepaddle的代码——generate_sequence_by_rnn_lm，用于文本预测的。
但是我实际使用下来，不论是原始代码中的例子还是我自己的语料，最后测试的时候，生成的几个文本，要么就是直接<e>结束，要么就是一个词加<e>结束。和我预想的能预测出一句话的与其不太符合呀？问一下知道是什么原因，应该从什么地方去调节么？
附原始模型的预测结果：
0	我们 不会 伤害 你 的 。 他们 也 这么 说 。
-3.5803	<e>
-7.1343	。 <e>
-7.2209	合法 <e>
-7.2261	这么 <e>
-7.2467	伤害 <e>

1	你 拥有 你 父亲 皇室 的 血统 。 是 合法 的 继承人 。
-3.5302	<e>
-7.0220	。 <e>
-7.2087	合法 <e>
-7.2363	的 <e>
-7.2734	谁 <e>

2	叫 什么 你 可以 告诉 我 。
-3.5723	<e>
-7.0548	完成 <e>
-7.0734	的 <e>
-7.1087	合法 <e>
-7.1976	血统 <e>

3	你 并 没有 留言 说 要 去 哪里 。 是 的 , 因为 我 必须 要 去 完成 这件 事 。
-3.4887	<e>
-7.0560	。 <e>
-7.1366	住 <e>
-7.1659	事 <e>
-7.1768	在 <e>

4	你 查出 是 谁 住 在 隔壁 房间 吗 ?
-3.6060	<e>
-7.1809	。 <e>
-7.2621	在 <e>
-7.3472	并 <e>
-10.7716	在 。 <e>

**Comment by lcy-seso** [comment]
1. 原始例子中没有训练数据，所以是无法训练的。
2. 文本生成任务需要训练时间较长，你的训练数据量级如何，学习曲线如何，收敛情况如何？

**Comment by sky-lc** [comment]
额发现了，的确是我的数据有问题~~0~~多谢提醒了~~
