### ISSUE TITLE
图像分类报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1992]
1.训练时
<img width="785" alt="94bd932cd5ab389f472129e083de5e1c" src="https://user-images.githubusercontent.com/46314656/55553960-33b56880-5714-11e9-83b2-9d3a592125cf.png">
2.评估和预测时，在python3下报错
<img width="898" alt="2dd3c9f40a6658fba9341901fba256ce" src="https://user-images.githubusercontent.com/46314656/55554055-6bbcab80-5714-11e9-833f-3d15e2e427c0.png">

**Comment by Yancey0623** [comment]
Thx, will fix FastImagnet later in py3 later.
