### ISSUE TITLE
human_pose_estimation问题汇总

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2006]
1.在python3下报错：
<img width="896" alt="74c44dd6829460d07833919cd7d5c155" src="https://user-images.githubusercontent.com/46314656/55696298-efb1b480-59ee-11e9-80d7-04d35cc816e7.png">
2.训练时log的显示有延时，建议添加sys.stdout.flush()在print后
3.test时在开始的地方卡住不动，没有报错，保持下图gpu使用率为0%的状态：
<img width="867" alt="6cbcba3855bb2dffb2a1fa2614e0407e" src="https://user-images.githubusercontent.com/46314656/55699293-c009a900-59fc-11e9-88d0-6278e9b22c9c.png">
4.val时在安装nms包后依然报错：
<img width="747" alt="2f708a0833598a8a021e9854a23d7804" src="https://user-images.githubusercontent.com/46314656/55700325-6eafe880-5a01-11e9-9670-bab8edd009b2.png">
5.建议test.py和val.py去除掉不用的参数model_save_dir

**Comment by xiegegege** [comment]
6.建议val示例命令行加上data_root参数，默认是coco数据集的
另外，test时卡住的问题在paddle develop分支发现的，在paddle1.3版本运行正常

**Comment by qingqing01** [comment]
Fixed by https://github.com/PaddlePaddle/models/pull/2019
