### ISSUE TITLE
PaddleRL 运行不起来

### ISSUE THREAD

**Issue by xinnian88** [PaddlePaddle/models#2047]
https://github.com/PaddlePaddle/models/tree/develop/PaddleRL/DeepQNetwork

DeepQNetwork 跑不起来，感觉好像数据不太对。

**Comment by JiabinYang** [comment]
请问您是使用哪一个指令运行的呢

**Comment by TomorrowIsAnOtherDay** [comment]
我们这边定位下问题先：）
另外强化学习这块的模型后续可以参考下官方的RL框架，我们目前主要的工作也在维护这个：
https://github.com/PaddlePaddle/PARL

**Comment by xinnian88** [comment]
> 请问您是使用哪一个指令运行的呢

python train.py --rom ./rom_files/pong.bin --use_cuda
使用的这个

**Comment by TomorrowIsAnOtherDay** [comment]
@zenghsh3已经发起PR fix这个问题，感谢指出。
