### ISSUE TITLE
video non_local模型易用性问题

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2056]
环境：paddle develop分支
non_local模型在某些epoch的训练结束后test之前会有报错，暂时没发现影响训练，但是影响体验
*** Aborted at 1555279287 (unix time) try "date -d @1555279287" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0xca84) received by PID 105196 (TID 0x7f1e86ad8700) from PID 51844; stack trace: ***
    @     0x7f20bf6c57e0 (unknown)
    @     0x7f20bf6c3a00 sem_wait
    @     0x7f20bfa1e5c8 PyThread_acquire_lock
    @     0x7f20bf9d70b6 PyEval_RestoreThread
    @     0x7f20bfa23c1b (unknown)
    @     0x7f20bf9df1fd PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9debf0 PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9debf0 PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9588b5 (unknown)
    @     0x7f20bf926d33 PyObject_Call
    @     0x7f20bf9dbf22 PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9587e0 (unknown)
    @     0x7f20bf926d33 PyObject_Call
    @     0x7f20bf93574d (unknown)
    @     0x7f20bf926d33 PyObject_Call
    @     0x7f20bf992105 (unknown)
    @     0x7f20bf926d33 PyObject_Call
    @     0x7f20bf9db764 PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9debf0 PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9debf0 PyEval_EvalFrameEx
    @     0x7f20bf9ded1e PyEval_EvalFrameEx
    @     0x7f20bf9e11fd PyEval_EvalCodeEx
    @     0x7f20bf9587e0 (unknown)
    @     0x7f20bf926d33 PyObject_Call
    @     0x7f20bf93574d (unknown)
    @     0x7f20bf926d33 PyObject_Call

**Comment by SunGaofeng** [comment]
已经修复，原因在于数据读取开了多进程，在每个epoch结束的时候，调用terminate和join的方式不对。先判断进程is_alive，然后再调用join，可以避免出现上述报错。
