### ISSUE TITLE
fast_imagenet程序出错有BUG

### ISSUE THREAD

**Issue by qianledan** [PaddlePaddle/models#2071]
fast_imagenet程序训练无法正常进行，问题应该出在红框的不能同时，不然就出错：Segmentation fault (core dumped)，请官方检测一下，将bug修复。
![QQ图片20190417180647](https://user-images.githubusercontent.com/45925696/56280720-5fd1e000-613d-11e9-8375-03014ca86ccc.png)

**Comment by qianledan** [comment]
一直停滞在这个界面不动

**Comment by qianledan** [comment]
不用回复了，服务器重启问题解决了。

**Comment by qianledan** [comment]
红框的不能同时，不然就出错：Segmentation fault (core dumped)
![QQ图片20190417180647](https://user-images.githubusercontent.com/45925696/56279932-ad4d4d80-613b-11e9-89bd-bd15dd9b6755.png)

**Comment by qianledan** [comment]
![Uploading QQ图片20190417180647.png…]()

**Comment by Yancey0623** [comment]
看起来是 torch 和 visualdl 同时引用引起的问题，后续会考虑去掉torchvision的依赖，现在的方法可以将日志输出到一个文件，然后用另外一个程序读取日志并画图。

**Comment by qianledan** [comment]
> 看起来是 torch 和 visualdl 同时引用引起的问题，后续会考虑去掉torchvision的依赖，现在的方法可以将日志输出到一个文件，然后用另外一个程序读取日志并画图。

收到，谢谢！

**Comment by qianledan** [comment]
> 看起来是 torch 和 visualdl 同时引用引起的问题，后续会考虑去掉torchvision的依赖，现在的方法可以将日志输出到一个文件，然后用另外一个程序读取日志并画图。

碰到新的问题，训练到4110 batch时就停滞在那里不动了。
![QQ浏览器截图20190418153109](https://user-images.githubusercontent.com/45925696/56344685-99175800-61f0-11e9-894e-cd9214dc0fa8.png)

**Comment by sandyhouse** [comment]
> > 看起来是 torch 和 visualdl 同时引用引起的问题，后续会考虑去掉torchvision的依赖，现在的方法可以将日志输出到一个文件，然后用另外一个程序读取日志并画图。
> 
> 碰到新的问题，训练到4110 batch时就停滞在那里不动了。
> ![QQ浏览器截图20190418153109](https://user-images.githubusercontent.com/45925696/56344685-99175800-61f0-11e9-894e-cd9214dc0fa8.png)

这个问题是随机出现呢，还是每次都会出现？

**Comment by qianledan** [comment]
问题已经解决了，我把线程的queuesize有3072调小一点，变成1024就正常进行了。

**Comment by sandyhouse** [comment]
> 问题已经解决了，我把线程的queuesize有3072调小一点，变成1024就正常进行了。

好的。

**Comment by sandyhouse** [comment]
Closing this issue.
