### ISSUE TITLE
yolov3 训练速度不稳定

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2076]
yolov3模型的训练某些Snapshot偶尔会出现训练速度不稳定的问题
![image](https://user-images.githubusercontent.com/37854899/56267803-7454af00-6122-11e9-8199-b206df8eb29d.png)
![image](https://user-images.githubusercontent.com/37854899/56267813-7ae32680-6122-11e9-94f0-34d112e8a37c.png)

**Comment by heavengate** [comment]
之前使用PaddleCloud和开发机使用paddlepaddle/paddle:latest-dev镜像未发现这个问题，目前使用PaddleCloud和开发机使用latest-dev和paddle_manylinux_devel:cuda8.0_cudnn7尝试复现这个问题

**Comment by heavengate** [comment]
使用PaddleCloud训练未复现该问题，先关闭issue
