### ISSUE TITLE
用图像分类的的例子infer 程序报错

### ISSUE THREAD

**Issue by zhkfu** [PaddlePaddle/models#2082]
系统centos cuda9  加载MobileNetV2做测试，程序执行到exe.run(program.desc, scope, 0, True, True, fetch_var_name)报错：paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.

**Comment by shippingwang** [comment]
您是怎么跑的infer呢？
1. 首先下载/训练得到mobilenetv2 的预训练模型
2. 更新paddle到最新版本
3. 执行infer.py 如下：
![image](https://user-images.githubusercontent.com/13645332/56277535-1b434600-6137-11e9-9b94-c590aec6fa46.png)
* 我这里是shufflenetv2
4. 运行结果如下：
![image](https://user-images.githubusercontent.com/13645332/56277644-52195c00-6137-11e9-9101-3be25e25b091.png)
未能复现您的报错
