### ISSUE TITLE
请教：gru训练语言模型，多GPU速度和单GPU速度基本一致，这是什么原因啊？

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/models#2087]
训练代码：https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/language_model/gru/train.py
使用的上面给代码，稍微做了一些小修改，修改内容如下。
![image](https://user-images.githubusercontent.com/5926307/56338408-7f6c1580-61dc-11e9-91a8-61e39c26eb17.png)
![image](https://user-images.githubusercontent.com/5926307/56338421-90b52200-61dc-11e9-875b-7a26209b34c5.png)

运行脚本:
![image](https://user-images.githubusercontent.com/5926307/56338445-a591b580-61dc-11e9-9801-968a8b0d1a74.png)
训练数据：github提供的ptb数据

paddle版本paddlepaddle-gpu 1.3.0.post85 。

训练速度：Tesla K40，单卡（GPU）一个epoch约100s，2个卡一个epoch约100s，时间几乎一致。

**Comment by gavin1332** [comment]
两个GPU卡的利用率是多少？

**Comment by Melonzhou** [comment]
> 两个GPU卡的利用率是多少？

运行时，都保持在90%以上，最低的时候是85%

**Comment by gavin1332** [comment]
batch size乘以卡数了吗？

**Comment by Melonzhou** [comment]
> batch size乘以卡数了吗？

没有

**Comment by Melonzhou** [comment]
> > batch size乘以卡数了吗？
> 
> 没有

![image](https://user-images.githubusercontent.com/5926307/56351237-3c6f6980-61ff-11e9-8d80-23a75bd6fd44.png)
我用了2张卡跑，但是很奇怪的是num_device=1，这个是哪里要配置吗？

**Comment by gavin1332** [comment]
你对python熟悉吗？python代码里有设置这个参数啊

**Comment by gavin1332** [comment]
> batch size乘以卡数了吗？

如果是多卡同步训练的话是数据并行，一个batch的数据会均摊到多个卡，所以需要扩大batch size

**Comment by Melonzhou** [comment]
> > batch size乘以卡数了吗？
> 
> 如果是多卡同步训练的话是数据并行，一个batch的数据会均摊到多个卡，所以需要扩大batch size

意思是如果单卡的batch_size=20的话，那么多卡的batch_size就应该是卡数*20，如果固定设置成20的话，不管多少张卡都是速度一样的，是吗？

**Comment by gavin1332** [comment]
> 如果固定设置成20的话，不管多少张卡都是速度一样的

并没有“速度一样”这个结论，只是肯定加速不明显。

**Comment by Melonzhou** [comment]
> > 如果固定设置成20的话，不管多少张卡都是速度一样的
> 
> 并没有“速度一样”这个结论，只是肯定加速不明显。

好的，我改改batch_size试试。

**Comment by wangguibao** [comment]
该issue已经超过1个月，先关闭了。如有需要可随时重新open
