### ISSUE TITLE
图像分类加载预训练模型的时候，怎么修改最后全连接的名字，没找到地方修改？

### ISSUE THREAD

**Issue by zhkfu** [PaddlePaddle/models#2088]
用mobilenetv2训练，加载预训练模型，不知道怎么修改最后全连接的名字。Enforce failed. Expected x_dims[1] == labels_dims[1], but received x_dims[1]:1000 != labels_dims[1]:6.

**Comment by shippingwang** [comment]
> 不知道怎么修改最后全连接的名字

你好，修改名字啥意思？是给层添加名字的意思么
若是更改了models的代码训练
请提供下更改过代码

请保证自查过
1. 确保models下代码是最新的
2. FC层有更改？怎么更改的？

**Comment by zhkfu** [comment]
> > 不知道怎么修改最后全连接的名字
> 
> 你好，修改名字啥意思？是给层添加名字的意思么
> 若是更改了models的代码训练
> 请提供下更改过代码
> 
> 请保证自查过
> 
> 1. 确保models下代码是最新的
> 2. FC层有更改？怎么更改的？

我基于mobilenetv2网络做6分类，加载预训练模型的时候 会报Enforce failed. Expected x_dims[1] == labels_dims[1], but received x_dims[1]:1000 != labels_dims[1]:6. 。用caffe 框架的时候，这种情况，改一下最后的全连接层的名字就行了。paddle要改什么地方呢

**Comment by shippingwang** [comment]
维度没对上，删掉预训练模型的的FC再加载
