### ISSUE TITLE
shufflenetV2 预训练模型

### ISSUE THREAD

**Issue by zhkfu** [PaddlePaddle/models#2095]
看公开的shufflenetV2 模型https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#finetuning    没有用PIL库读数据的的top1/top5的准确率，是效果不好，还是没有做。

**Comment by shippingwang** [comment]
图像分类下模型预训练是CV2跑的，PIL精度是测出来的，您可以跑eval.py自测下，

> 是效果不好，还是没有做

不存在不好。两种方式精度差不了多少。

**Comment by zhkfu** [comment]
> 图像分类下模型预训练是CV2跑的，PIL精度是测出来的，您可以跑eval.py自测下，
> 
> > 是效果不好，还是没有做
> 
> 不存在不好。两种方式精度差不了多少。
好的
