### ISSUE TITLE
reading_comprehension 训练报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#2149]
gpu：v100   4卡
python run.py --train 跑Demo数据

Traceback (most recent call last):
  File "run.py", line 647, in <module>
    train(logger, args)
  File "run.py", line 473, in train
    pass_id, "%.10f" % (1.0 * total_loss / total_num)))
ZeroDivisionError: float division by zero

**Comment by HongyuLi2018** [comment]
demo数据有只有100个，如果用4卡 batch_size=32的话 训练一步也要128个数据，所以有一个卡分配不到数据报错  减小batch_size即可运行
