### ISSUE TITLE
models/PaddleCV/yolo3训练时报错

### ISSUE THREAD

**Issue by gentelyang** [PaddlePaddle/models#2156]
一：在用paddle1.4.0和1.4.1训练yolov3时报如下错误：
File "train.py"，line 154，in <module>
          train()
C++ Callstacks:
Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:38 != ins[i][j]:32.

二：在/paddlepaddle_gpu-latest.19.04.25版本上训练yolov3报如下错误：
loading annotations into memory...
Done (t=26.37s)
creating index...
index created!
Load in 80 categories.
F0425 09:12:42.189702  9812 device_context.cc:337] cudaGetLastError  invalid configuration argument errno:9
*** Check failure stack trace: ***
    @     0x7f1a62b49b2d  google::LogMessage::Fail()
    @     0x7f1a62b4d5dc  google::LogMessage::SendToLog()
    @     0x7f1a62b49653  google::LogMessage::Flush()
    @     0x7f1a62b4eaee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1a64772fad  _ZNSt17_Function_handlerIFvvEZNK6paddle8platform17CUDADeviceContext4WaitEvEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f1a64780e04  paddle::platform::TemporaryAllocator::Release()
    @     0x7f1a64775f21  paddle::platform::CUDADeviceContext::Wait()
    @     0x7f1a64708771  paddle::framework::TransDataDevice()
    @     0x7f1a6470780e  paddle::framework::TransformData()
    @     0x7f1a646fe90d  paddle::framework::OperatorWithKernel::PrepareData()
    @     0x7f1a646ffa26  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7f1a646ffed1  paddle::framework::OperatorWithKernel::RunImpl()
    @     0x7f1a646fd54c  paddle::framework::OperatorBase::Run()
    @     0x7f1a6450d84a  paddle::framework::details::ComputationOpHandle::RunImpl()
    @     0x7f1a645001e0  paddle::framework::details::OpHandleBase::Run()
    @     0x7f1a644e9072  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f1a644e93af  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsync
EPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_A
ny_data
    @     0x7f1a637a3253  std::_Function_handler<>::_M_invoke()
    @     0x7f1a62ae3ff7  std::__future_base::_State_base::_M_do_set()
    @     0x7f1b38889e03  __pthread_once_internal
    @     0x7f1a644e58c2  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBase
ESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f1a62ae5574  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f1a80ffc470  (unknown)
    @     0x7f1b38884aa1  start_thread
    @     0x7f1b37f46c4d  clone
    @              (nil)  (unknown)

**Comment by fatwolf** [comment]
random_shape 按照默认值True的话 是无法运行的，改成False应该就好了

**Comment by dingsiyu** [comment]
请问你的第二个问题是怎么解决的呢
