### ISSUE TITLE
video nonlocal 模型kill掉进程后无法自动释放显存

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2170]
video nonlocal 模型kill掉进程后显存无法自动释放，如图所示：
<img width="865" alt="f4924b601212fa146634cb29eef3122f" src="https://user-images.githubusercontent.com/46314656/56884565-c8558100-6a9c-11e9-9443-e6ab2691d593.png">

**Comment by hutuxian** [comment]
可以通过```ps aux | grep yourprocess ```的方式找到没杀干净的进程手动强行kill一下

**Comment by xiegegege** [comment]
嗯嗯，每次都要手动清有点麻烦，有办法让它自动释放吗？

**Comment by hutuxian** [comment]
如果相关进程较多，可以通过脚本，找到相关进程组id（参考命令```ps -o pgid= $$ | grep -o '[0-9]*'```），进行统一kill（注意kill接负数为kill掉进程组）
