### ISSUE TITLE
object_detection中的resize问题

### ISSUE THREAD

**Issue by SunAhong1993** [PaddlePaddle/models#2173]
在object_detection中对图像进行一系列的图像增强操作后，有resize操作，但是只resize了图像，没有resize gt_bboxes（[详细代码](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/object_detection/reader.py#L142)），这样做的意义何在？是否会影响检测结果？

**Comment by yghstill** [comment]
在方法pascalvoc或者coco里对输入的gt_bboxes做了归一化处理（除以了整个图像的高度）。当图像还原时，gt_bboxes精度不会变。所以图像的线性扩大或缩小不会影响gt_bboxes的正确性。[reader详细代码](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/object_detection/reader.py#L254-L257)

> 在object_detection中对图像进行一系列的图像增强操作后，有resize操作，但是只resize了图像，没有resize gt_bboxes（[详细代码](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/object_detection/reader.py#L142)），这样做的意义何在？是否会影响检测结果？
