### ISSUE TITLE
图像分类GoogleNet训练报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2187]
1.输入命令python train.py --model=GoogleNet后运行，120个batch后loss会出现nan
<img width="652" alt="cca65feb541bad8bde2e0c8eca86d4b3" src="https://user-images.githubusercontent.com/46314656/57373852-0143d300-71cc-11e9-8ad9-462afcc179de.png">
2.在paddle develop分支下，跑训练一段时间后有报错(非必现)：
Pass 0, trainbatch 2330, loss nan,                         acc1 0.00000, acc5 0.00781, lr 0.10000, time 0.65 sec
F0505 20:34:00.984820 209240 all_reduce_op_handle.cc:78] cudaStreamSynchronize an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7f7ad2ed07ad  google::LogMessage::Fail()
    @     0x7f7ad2ed425c  google::LogMessage::SendToLog()
    @     0x7f7ad2ed02d3  google::LogMessage::Flush()
    @     0x7f7ad2ed576e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7ad465d503  paddle::framework::details::AllReduceOpHandle::RunAllReduceFuncs()
    @     0x7f7ad465eeee  paddle::framework::details::AllReduceOpHandle::RunImpl()
    @     0x7f7ad46cebc0  paddle::framework::details::OpHandleBase::Run()
    @     0x7f7ad46b6a72  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f7ad46b6daf  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f7ad400d3f3  std::_Function_handler<>::_M_invoke()
    @     0x7f7ad2e6bc77  std::__future_base::_State_base::_M_do_set()
    @     0x7f7bb5b49e03  __pthread_once_internal
    @     0x7f7ad46b32c2  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f7ad2e6d1f4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f7b6995d470  (unknown)
    @     0x7f7bb5b44aa1  start_thread
    @     0x7f7bb4ffec4d  clone
    @              (nil)  (unknown)

**Comment by shippingwang** [comment]
@xiegegege 按照run.sh的超参数 运行呢？

**Comment by shippingwang** [comment]
same as #2150

**Comment by lgone2000** [comment]
1.2可以正常训练1.4有问题 mark一下

**Comment by heavengate** [comment]
两个问题：
1. 报错退出问题为conv2d的cudnn kernel中新引入使用了cudnnGetConvolutionForwardAlgorithm_v7这个接口，这个接口的cudnn底层实现可能bug导致报错退出
2. 出nan的问题定位为是inception的conv3x3和conv5x5如果同时use_cudnn=True的话会出nan，其中一个use_cudnn=False的话就不会出nan，待进一步定位是框架处理的问题还是cudnn底层的问题

**Comment by heavengate** [comment]
Paddle 1.2使用的是cudnn5，经测试cudnn5不存在该问题

**Comment by qingqing01** [comment]
@xiegegege 麻烦再测试下

**Comment by xiegegege** [comment]
收到～

**Comment by xiegegege** [comment]
现在develop下是有报错的：
An exception was thrown!
 Invoke operator conv2d error.
Python Callstacks:
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1776, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2283, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/googlenet.py", line 65, in conv_layer
    name=name)
  File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/googlenet.py", line 148, in net
    name="conv1")
  File "train.py", line 225, in net_config
    out0, out1, out2 = model.net(input=image, class_dim=class_dim)
  File "train.py", line 307, in build_program
    avg_cost, acc_top1, acc_top5 = net_config(image, model, args, label=label, is_train=is_train)
  File "train.py", line 365, in train
    args=args)
  File "train.py", line 612, in main
    train(args)
  File "train.py", line 616, in <module>
    main()
C++ Callstacks:
CUDNN_STATUS_INTERNAL_ERROR at [/ssd1/xiege/Paddle_8.1/Paddle/paddle/fluid/platform/device_context.cc:217]

**Comment by heavengate** [comment]
> 现在develop下是有报错的：
> An exception was thrown!
> Invoke operator conv2d error.
> Python Callstacks:
> File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1776, in append_op
> attrs=kwargs.get("attrs", None))
> File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2283, in conv2d
> 'fuse_relu_before_depthwise_conv': False
> File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/googlenet.py", line 65, in conv_layer
> name=name)
> File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/googlenet.py", line 148, in net
> name="conv1")
> File "train.py", line 225, in net_config
> out0, out1, out2 = model.net(input=image, class_dim=class_dim)
> File "train.py", line 307, in build_program
> avg_cost, acc_top1, acc_top5 = net_config(image, model, args, label=label, is_train=is_train)
> File "train.py", line 365, in train
> args=args)
> File "train.py", line 612, in main
> train(args)
> File "train.py", line 616, in 
> main()
> C++ Callstacks:
> CUDNN_STATUS_INTERNAL_ERROR at [/ssd1/xiege/Paddle_8.1/Paddle/paddle/fluid/platform/device_context.cc:217]

看着是cudnn的问题，试下 https://github.com/PaddlePaddle/Paddle/issues/18885

**Comment by xiegegege** [comment]
单卡可以正常跑，多卡还是会有这个报错；paddle1.5.1下是没这个报错的
