### ISSUE TITLE
window下训练human_pose_estimation，提示不支持'mpii' ‘coco’数据集

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2205]
在window下，正确配置数据路径，分别使用指令python train.py --dataset 'coco' ， python train.py --dataset 'mpii' 进行训练，其他相关配置均正确，报错信息如下：
![4](https://user-images.githubusercontent.com/37854899/57353855-6bdd1a80-719c-11e9-972e-73e3412d1336.PNG)
![5](https://user-images.githubusercontent.com/37854899/57353858-6d0e4780-719c-11e9-8380-a4841b08bf8d.PNG)

**Comment by JiaXiao243** [comment]
windows下使用 python train.py --dataset coco ， python train.py --dataset mpii ，即去掉dataset中的coco/mpii的引号，可以继续正常训练。
linux下--dataset coco，有无引号，无影响，读入字段相同。window下--dataset coco，有无引号，有影响，读入字段不同。
window下object detection的--dataset参数有同样的问题，去掉--dataset=‘pascalvoc’的双引号之后，可以继续正常训练。
![1](https://user-images.githubusercontent.com/37854899/57428669-f9337400-725b-11e9-8585-3f219b62fe71.PNG)

**Comment by gongweibao** [comment]
哦。感谢。我们一般是用linux来测试的。
