### ISSUE TITLE
压缩工具paddleSlim问题

### ISSUE THREAD

**Issue by chenloveheimei** [PaddlePaddle/models#2210]
我刚接触这个工具,想请教下,
1.这个工具压缩的模型是基于paddle所训练的模型吗?
2.能直接对tensorflow,caffe所训练的模型进行压缩吗?
3.如果不能,是否都需要重新用paddle训练才能够压缩?
4.如果不能,是否有tensorflow转paddle的工具?
5.这个caffe转的工具没效了,https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid
谢谢.

**Comment by qingqing01** [comment]
1: 所有模型都是基于Paddle模型。
2:  不能。
3，4，5:  是需要用paddle模型，可以使用 https://github.com/PaddlePaddle/X2Paddle 转换成Paddle模型使用。
