### ISSUE TITLE
window下face_detection训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2211]
windows下调用python -u train.py --epoc_num=1 --batch_size=2 --use_gpu False --parallel False --pretrained_model=vgg_ilsvrc_16_fc_reduced指令对face_detection模型进行训练，log中有多处报错信息，其中两处在windows下训练object_detection也有出现：
![4](https://user-images.githubusercontent.com/37854899/57451782-ce194680-7294-11e9-909b-8f2281f75f99.PNG)
![5](https://user-images.githubusercontent.com/37854899/57451786-cfe30a00-7294-11e9-91e4-5a70f2e17d0d.PNG)
还有一大段报错信息是其特有的：
![8](https://user-images.githubusercontent.com/37854899/57451816-dffae980-7294-11e9-8c57-d8975a1ef139.PNG)
同时，在模型的output\0路径有训练权重输出。

**Comment by yanggb** [comment]
楼主有解决吗？我也是在win10上跑这个demo，我都没修过代码，同样的错误

**Comment by JiaXiao243** [comment]
@yanggb目前还没有解决~
