### ISSUE TITLE
auto_dialogue_evaluation模型finetune训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2218]
在models/PaddleNLP/dialogue_model_toolkit/auto_dialogue_evaluation路径下执行
TASK=human
python -u main.py \
  --do_train True \
  --loss_type L2 \
  --use_cuda \
  --save_path model_files_tmp/${TASK}_finetuned \
  --init_model model_files/matching_pretrained \
  --train_path data/label_data/$TASK/train.ids \
  --val_path data/label_data/$TASK/val.ids \
  --print_step 1 \
  --save_step 1 \
  --num_scan_data 50
对auto_dialogue_evaluation模型进行finetune报错信息如下：
<img width="1001" alt="finetuined_train" src="https://user-images.githubusercontent.com/37854899/57592560-f392a280-7569-11e9-8296-4c2f7fcd4cd0.png">

**Comment by luluxing3** [comment]
请问您对代码有做修改吗？直接拉代码运行，没有出现您截图的问题。

**Comment by JiaXiao243** [comment]
没有对代码做修改，报错运行指令如下：
<img width="543" alt="a54e99ddc2eae8ca9c82cf4ac3ef3ddd" src="https://user-images.githubusercontent.com/37854899/57684595-acd7a200-7668-11e9-83d9-84a772c1c164.png">
环境：ubuntu_1604_gpu_cuda9.0_cudnn7，python2.7
paddle版本：develop分支，编译安装的paddle

**Comment by luluxing3** [comment]
请问你有用多卡吗？

**Comment by JiaXiao243** [comment]
单卡、多卡报错信息相同
![image](https://user-images.githubusercontent.com/37854899/57687124-705a7500-766d-11e9-83af-9cc3bb097f86.png)
