### ISSUE TITLE
deep_attention_matching模型评估加载--model_path路径名称错误

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2220]
1. 在models/PaddleNLP/dialogue_model_toolkit/deep_attention_matching路径中，执行如下指令：
python -u main.py \
  --do_test True \
  --use_cuda \
  --data_path ./data/ubuntu/data_small.pkl \
  --save_path ./model_files/ubuntu/step_372 \
  --model_path ./model_files/ubuntu/step_372 \
  --vocab_size 434512 \
  --_EOS_ 28270 \
  --batch_size 100
对模型进行评估，报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/57599329-df11d280-7588-11e9-8a78-59b5cf14af22.png)
应将--model_path ./model_files/ubuntu/step_372 应修改为./model_files/ubuntu/step_78，加载的model_path应为训练输出的已存在的模型名称，而不是该模型评估结果的存放路径./model_files/ubuntu/step_372,建议step_372修改为 step_eval或其他，而不是没有意义的数字。
 2. 官方文档缺少示例数据
<img width="924" alt="1" src="https://user-images.githubusercontent.com/37854899/57599600-dc63ad00-7589-11e9-9f5b-4105b6cff2cc.png">

**Comment by luluxing3** [comment]
1. 本项目未开源训好的模型，使用模型评估代码时，--model_path 指定需要评估的模型路径（./model_files/ubuntu/step_372只是一个样例，可以根据需要修改），--save_path 为模型输出结果存储路径，也可以根据需要修改
2. 缺少示例图片，后续会更新。
谢谢～
