### ISSUE TITLE
Cannot find variable label_smooth_0.tmp_0@GRAD

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/models#2244]
I want to quantize a MobileNetV2 model with paddle-slim,  the [demo](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/compress.py) works fine. However, I get an error when adding a label_smooth layer before cross_entropy layer,  the error information shows as the following picture.

![image](https://user-images.githubusercontent.com/37564754/57751221-976d8100-7717-11e9-8ef7-ac1413de8c9c.png)

The original demo is [demo](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/compress.py)

And my modified code is：

```
#cost = fluid.layers.cross_entropy(input=out, label=label)

epsilon = 0.1
label_one_hot = fluid.layers.one_hot(input=label, depth=args.class_dim)
smooth_label = fluid.layers.label_smooth(label=label_one_hot, epsilon=epsilon, dtype="float32")
cost = fluid.layers.cross_entropy(input=out, label=smooth_label, soft_label=True)
```

- System: Centos 6.3
- Paddle: 1.4.1
- CUDA: 8.0
- CUDNN: v7

**Comment by phlrain** [comment]
这个是因为one_hot op 没有反向kernel

**Comment by mzchtx** [comment]
> 这个是因为one_hot op 没有反向kernel

http://www.paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#label-smooth

**Comment by mzchtx** [comment]
试了添加 `stop_gradient`，依然不 work
```
#cost = fluid.layers.cross_entropy(input=out, label=label)

epsilon = 0.1
label_one_hot = fluid.layers.one_hot(input=label, depth=args.class_dim)
label_one_hot.stop_gradient = True
smooth_label = fluid.layers.label_smooth(label=label_one_hot, epsilon=epsilon, dtype="float32")
smooth_label.stop_gradient = True
cost = fluid.layers.cross_entropy(input=out, label=smooth_label, soft_label=True)
```

**Comment by wanghaoshuang** [comment]
在PaddleSlim中会对用户传进来的Program进行clone，在clone过程中，variable的stop_gradient属性被丢掉了，所以在添加反向的时候对label_one_hot分支也添加了反向计算逻辑。

解决办法：

为Program添加反向之后，再将Program转给Compressor,

```
opt.minimize(avg_cost) // 添加反向
opt=None
```

![image](https://user-images.githubusercontent.com/7534971/58525969-2a221b80-8200-11e9-8b43-9b2d4703f24b.png)


注意，要将opt置None, 告诉Compressor已为Program添加反向了。具体可以参考这里对optimizer使用的详细解释：https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/docs/usage.md#1123-optimizer

>在不同的使用场景下，用户需要提供0个、1个或2两个optimizer:
>
>0个optimizer: 在模型搭建阶段的train_program已经是一个包含了反向op和模型weight更新op的网络，则不用再提供optimizer
1个optimizer: train_program只有前向计算op, 则需要提供一个optimizer，用于优化训练train_program.
2个optimizer: 在使用蒸馏策略时，且蒸馏训练阶段和单独fine-tune阶段用不同的优化策略。一个optimizer用于优化训练teacher网络和student网络组成的蒸馏训练网络，另一个optimizer用于单独优化student网络。更多细节会在蒸馏策略使用文档中介绍。

**Comment by wanghaoshuang** [comment]
已线下沟通，并安上述方法解决了问题。
