### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by skysunsun** [PaddlePaddle/models#2269]
Can you provide a windows version? Thank you very much!

**Comment by tensor-tang** [comment]
You could find it [here]( http://www.paddlepaddle.org/documentation/docs/en/1.4/beginners_guide/install/index_en.html)

![image](https://user-images.githubusercontent.com/21351065/57999753-19d7b580-7b09-11e9-9310-2109b9ce6b9a.png)

**Comment by skysunsun** [comment]
oh thank you very much!

**Comment by tensor-tang** [comment]
Welcome, any problem please let us know.
