### ISSUE TITLE
动态图Mnist 代码问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/models#2289]
这个mnist模型卷积层激活函数是不是没有传过来？
![image](https://user-images.githubusercontent.com/10734244/58156749-6659f700-7ca9-11e9-85ba-52dba110a078.png)

**Comment by qianledan** [comment]
> 这个mnist模型卷积层激活函数是不是没有传过来？
> ![image](https://user-images.githubusercontent.com/10734244/58156749-6659f700-7ca9-11e9-85ba-52dba110a078.png)

调用这个函数的时候再传进来的啊
self._simple_img_conv_pool_1 = SimpleImgConvPool(self.full_name(), 1, 20, 5, 2, 2, act="relu")

**Comment by DDDivano** [comment]
> > 这个mnist模型卷积层激活函数是不是没有传过来？
> > ![image](https://user-images.githubusercontent.com/10734244/58156749-6659f700-7ca9-11e9-85ba-52dba110a078.png)
> 
> 调用这个函数的时候再传进来的啊
> self._simple_img_conv_pool_1 = SimpleImgConvPool(self.full_name(), 1, 20, 5, 2, 2, act="relu")

传进来没用上。 看https://github.com/PaddlePaddle/models/blob/develop/dygraph/mnist/mnist_dygraph.py

**Comment by phlrain** [comment]
非常感谢关注，我们会马上修复这个问题
