### ISSUE TITLE
动态图resnet（模型结构有修改）训练时内存溢出，是否模型结构有问题，帮忙看一下代码？

### ISSUE THREAD

**Issue by qianledan** [PaddlePaddle/models#2291]
![QQ图片20190522181515](https://user-images.githubusercontent.com/45925696/58167442-8ba53000-7cbe-11e9-8d3f-b4e3531ad1f7.png)
![QQ图片20190522181443](https://user-images.githubusercontent.com/45925696/58167447-8ea02080-7cbe-11e9-9cae-ca4d0d147d3c.png)
用官网给的动态图resnet模型，batch_size设置16，能够正常跑。
本人对该模型结构进行了部分的修改，训练时出现GPU内存溢出
[Desktop.zip](https://github.com/PaddlePaddle/models/files/3206941/Desktop.zip)

**Comment by phlrain** [comment]
能帮忙贴下修改的内容，有可能就是显存超了，我们一直在优化显存占用

**Comment by qianledan** [comment]
> 能帮忙贴下修改的内容，有可能就是显存超了，我们一直在优化显存占用

-------------------------------------------------------------------------------------------------------------------
resnet_DyGraph_SD.py   关键修改的地方：自己封装了个sequence_dropout（）的函数，然后调用在BottleneckBlock（）中

class sequence_dropout(fluid.dygraph.Layer):
    def __init__(self,
                 name_scope,
                 num_channels):
        super(sequence_dropout, self).__init__(name_scope)
        
        
        self.pool = Pool2D(self.full_name(), pool_size=0, pool_type='avg', global_pooling=True)
        stdv = 1.0 / math.sqrt(num_channels * 1.0)
        self.squeeze = FC(self.full_name(),
                          size=num_channels // reduction_ratio,
                          act='relu',
                          param_attr=fluid.param_attr.ParamAttr(
                              initializer=fluid.initializer.Uniform(
                                  -stdv, stdv)))
             
        stdv = 1.0 / math.sqrt(num_channels * 1.0)
        self.excitation = FC(self.full_name(),
                             size=num_channels,
                             act=None,
                             param_attr=fluid.param_attr.ParamAttr(
                                 initializer=fluid.initializer.Uniform(
                                      -stdv, stdv))) 
         
    def forward(self, inputs):
        x=inputs.numpy()
        y=self.pool(inputs)
        y=self.squeeze(y)
        y=self.excitation(y)
        top_values, top_indices = fluid.layers.topk(y, k=int(y.shape[1]*rate))
        top_indices=top_indices.numpy()
        o=np.empty((1,1,1,1))

        for i,ids in enumerate(top_indices):
            t=x[i,ids,:,:]
            t=t[np.newaxis,:,:,:]
            if i == 0:
                o=t
            else:
                o= np.concatenate((o,t),axis=0)   

        x=fluid.dygraph.base.to_variable(o)
        return x

--------------------------------------------------------------------------------------------------------
class sequence_dropout（）这个封装的函数调用在BottleneckBlock（）结构体中如下：

class BottleneckBlock(fluid.dygraph.Layer):
    def __init__(self,
                 name_scope,
                 num_channels,
                 num_filters,
                 stride,
                 sd_con=False,
                 shortcut=True):
        super(BottleneckBlock, self).__init__(name_scope)
        
        if not shortcut:
            self.short = ConvBNLayer(
                self.full_name(),
                num_channels=num_channels,
                num_filters=num_filters * 4,
                filter_size=1,
                stride=stride)

        self.shortcut = shortcut
 #————————修改处————————————       
        if sd_con:            
            self.sd=sequence_dropout(self.full_name(),num_channels=num_channels)
            num_channels=num_channels//2
        self.sd_con=sd_con
   #————————修改处————————————     
        self.conv0 = ConvBNLayer(
            self.full_name(),
            num_channels=num_channels,
            num_filters=num_filters,
            filter_size=1,
            act='relu')
        self.conv1 = ConvBNLayer(
            self.full_name(),
            num_channels=num_filters,
            num_filters=num_filters,
            filter_size=3,
            stride=stride,
            act='relu')
        self.conv2 = ConvBNLayer(
            self.full_name(),
            num_channels=num_filters,
            num_filters=num_filters * 4,
            filter_size=1,
            act=None)
        
        self._num_channels_out = num_filters * 4

    def forward(self, inputs):
  #————————修改处————————————     
        if self.sd_con:
            y=self.sd(inputs)
        else:
            y=inputs
  #————————修改处————————————          
        y = self.conv0(y)
        conv1 = self.conv1(y)
        conv2 = self.conv2(conv1)

        if self.shortcut:
            short = inputs
        else:
            short = self.short(inputs)

        y = fluid.layers.elementwise_add(x=short, y=conv2)

        layer_helper = LayerHelper(self.full_name(), act='relu')
        return layer_helper.append_activation(y)     #激活函数relu操作

**Comment by phlrain** [comment]
能够方便提供下完整的代码。。我们分析下，目前看log 无法定位到问题

**Comment by qianledan** [comment]
> 能够方便提供下完整的代码。。我们分析下，目前看log 无法定位到问题

完整代码在附件里啊，提问题的时候就已经上传到附件了。

**Comment by phlrain** [comment]
目前显存占用确实有一些多，我们在修复中

**Comment by qianledan** [comment]
> 目前显存占用确实有一些多，我们在修复中
好的，幸苦你们了。非常着急的等你们帮忙解决。
