### ISSUE TITLE
Insufficient GPU memory to allocation.

### ISSUE THREAD

**Issue by Sparrow0817** [PaddlePaddle/models#2292]
-----------  Configuration Arguments -----------
batch_size: 8
class_num: 80
data_dir: dataset/coco
dataset: coco2017
debug: False
draw_thresh: 0.5
image_name: 000000000139.jpg
image_path: ./dataset/coco/val2017
input_size: 608
label_smooth: True
learning_rate: 0.001
max_iter: 500200
model_save_dir: checkpoints
nms_posk: 100
nms_thresh: 0.45
nms_topk: 400
no_mixup_iter: 40000
pretrain: weights/darknet53
random_shape: True
snapshot_iter: 2000
start_iter: 0
syncbn: True
use_gpu: True
use_multiprocess: True
valid_thresh: 0.005
weights: 
------------------------------------------------
loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
Load in 80 categories.
Traceback (most recent call last):
  File "infer.py", line 80, in <module>
    infer()
  File "infer.py", line 63, in infer
    feed=feeder.feed(data),
  File "/home/lwd/.local/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 246, in feed
    ret_dict[each_name] = each_converter.done()
  File "/home/lwd/.local/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 95, in done
    t.set(arr, self.place)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected allocating <= available, but received allocating:5403593101 > available:5300944640.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:262]
PaddlePaddle Call Stacks: 
0       0x7eff92634228p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7eff92634577p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7eff9437c706p paddle::platform::GpuMaxChunkSize() + 630
3       0x7eff943510a2p
4       0x7effd8c62827p
5       0x7eff9435074dp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 109
6       0x7eff94351573p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 35
7       0x7eff943519b5p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 389
8       0x7eff94376c6bp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27
9       0x7eff943455b3p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 435
10      0x7eff943456d1p paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 33
11      0x7eff93f835a0p paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 48
12      0x7eff9431796ap paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, paddle::memory::allocation::Allocator::Attr, unsigned long) + 154
13      0x7eff926447efp float* paddle::framework::Tensor::mutable_data<float>(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::memory::allocation::Allocator::Attr, unsigned long) + 79
14      0x7eff92644cb6p
15      0x7eff9268c457p
16      0x7eff926667cep
17            0x565d5cp _PyCFunction_FastCallDict + 860
18            0x503073p
19            0x506859p _PyEval_EvalFrameDefault + 1097
20            0x502209p
21            0x502f3dp
22            0x506859p _PyEval_EvalFrameDefault + 1097
23            0x502209p
24            0x502f3dp
25            0x506859p _PyEval_EvalFrameDefault + 1097
26            0x502209p
27            0x502f3dp
28            0x506859p _PyEval_EvalFrameDefault + 1097
29            0x504c28p
30            0x506393p PyEval_EvalCode + 35
31            0x634d52p
32            0x634e0ap PyRun_FileExFlags + 154
33            0x6385c8p PyRun_SimpleFileExFlags + 392
34            0x63915ap Py_Main + 1402
35            0x4a6f10p main + 224
36      0x7effd8e93b97p __libc_start_main + 231
37            0x5afa0ap _start + 42

 +-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8    11W /  N/A |    579MiB /  5896MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1164      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1198      G   /usr/bin/gnome-shell                          51MiB |
|    0      1472      G   /usr/lib/xorg/Xorg                           214MiB |
|    0      1601      G   /usr/bin/gnome-shell                         189MiB |
|    0      2153      G   ...quest-channel-token=4841798388314319105   103MiB |
+-----------------------------------------------------------------------------+

**Comment by Sparrow0817** [comment]
这是我自己的电脑，参数大概怎么改

**Comment by heavengate** [comment]
看nvidia-smi的信息是由其他任务占了差不多10%的显存，而paddle的FLAGS_fraction_of_gpu_memory_to_use 默认是0.92，会先占用0.92的显存，可以尝试export FLAGS_fraction_of_gpu_memory_to_use=0.8 调小一下再跑infer

**Comment by Sparrow0817** [comment]
> 看nvidia-smi的信息是由其他任务占了差不多10%的显存，而paddle的FLAGS_fraction_of_gpu_memory_to_use 默认是0.92，会先占用0.92的显存，可以尝试export FLAGS_fraction_of_gpu_memory_to_use=0.8 调小一下再跑infer

python3 infer.py    --dataset=coco2017     --weights=${weights/darknet53}      --image_path=./dataset/coco/val2017/      --image_name=000000000139.jpg 
-----------  Configuration Arguments -----------
batch_size: 8
class_num: 80
data_dir: dataset/coco
dataset: coco2017
debug: False
draw_thresh: 0.5
image_name: 000000000139.jpg
image_path: ./dataset/coco/val2017/
input_size: 608
label_smooth: True
learning_rate: 0.001
max_iter: 500200
model_save_dir: checkpoints
nms_posk: 100
nms_thresh: 0.45
nms_topk: 400
no_mixup_iter: 40000
pretrain: weights/darknet53
random_shape: True
snapshot_iter: 2000
start_iter: 0
syncbn: True
use_gpu: True
use_multiprocess: True
valid_thresh: 0.005
weights: 
------------------------------------------------
loading annotations into memory...
Done (t=0.69s)
creating index...
index created!
Load in 80 categories.
W0523 10:56:44.771133 24399 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 9.0
W0523 10:56:44.815012 24399 device_context.cc:269] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "infer.py", line 80, in <module>
    infer()
  File "infer.py", line 64, in infer
    return_numpy=False)
  File "/home/lwd/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/lwd/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks: 
  File "/home/lwd/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lwd/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/lwd/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2073, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/home/lwd/models/PaddleCV/yolov3/models/darknet.py", line 37, in conv_bn_layer
    bias_attr=False)
  File "/home/lwd/models/PaddleCV/yolov3/models/darknet.py", line 98, in add_DarkNet53_conv_body
    name="yolo_input")
  File "/home/lwd/models/PaddleCV/yolov3/models/yolov3.py", line 110, in build_model
    blocks = add_DarkNet53_conv_body(self.image, not self.is_train)
  File "infer.py", line 36, in infer
    model.build_model()
  File "infer.py", line 80, in <module>
    infer()
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:146]
PaddlePaddle Call Stacks: 
0       0x7f99d2ec6288p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f99d2ec65d7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f99d2ec6ccbp paddle::framework::Tensor::type() const + 107
3       0x7f99d328275dp paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 477
4       0x7f99d4b552a3p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 243
5       0x7f99d4b55bb4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
6       0x7f99d4b534dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7f99d30384bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
8       0x7f99d30392ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7f99d2eb596ep
10      0x7f99d2ef876ep
11      0x55744e960ea4p _PyMethodDef_RawFastCallKeywords + 612
12      0x55744e960fc1p _PyCFunction_FastCallKeywords + 33
13      0x55744e9d62cep _PyEval_EvalFrameDefault + 21054
14      0x55744e90f528p _PyEval_EvalCodeWithName + 744
15      0x55744e9606a7p _PyFunction_FastCallKeywords + 903
16      0x55744e9d252ap _PyEval_EvalFrameDefault + 5274
17      0x55744e90f528p _PyEval_EvalCodeWithName + 744
18      0x55744e9606a7p _PyFunction_FastCallKeywords + 903
19      0x55744e9d252ap _PyEval_EvalFrameDefault + 5274
20      0x55744e96041bp _PyFunction_FastCallKeywords + 251
21      0x55744e9d1766p _PyEval_EvalFrameDefault + 1750
22      0x55744e90f528p _PyEval_EvalCodeWithName + 744
23      0x55744e9103a4p PyEval_EvalCodeEx + 68
24      0x55744e9103ccp PyEval_EvalCode + 28
25      0x55744ea2a304p
26      0x55744ea32611p PyRun_FileExFlags + 161
27      0x55744ea32804p PyRun_SimpleFileExFlags + 452
28      0x55744ea3417dp
29      0x55744ea343f0p _Py_UnixMain + 128
30      0x7f9a9f672830p __libc_start_main + 240
31      0x55744e9e0e32p

lwd@ubuntu:~/models/PaddleCV/yolov3$ nvidia-smi
Thu May 23 10:57:15 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0  On |                  N/A |
| 49%   66C    P0    83W / 250W |    566MiB / 11177MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 82%   82C    P2    81W / 250W |   3927MiB / 11178MiB |     44%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:81:00.0 Off |                  N/A |
| 86%   84C    P2   275W / 250W |   3927MiB / 11178MiB |     44%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:82:00.0 Off |                  N/A |
| 64%   78C    P2   260W / 250W |   3927MiB / 11178MiB |     51%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2173      G   /usr/lib/xorg/Xorg                            40MiB |
|    0      2871      G   /usr/lib/xorg/Xorg                           209MiB |
|    0      3059      G   /usr/bin/gnome-shell                         208MiB |
|    1      3992      C   ./darknet                                   3915MiB |
|    2      3992      C   ./darknet                                   3915MiB |
|    3      3992      C   ./darknet                                   3915MiB |
+-----------------------------------------------------------------------------+
I use another computer now , I want to use device 0 so I "export CUDA_VISIBLE_DEVICES=0"
Thank you!  (ps:Sorry I can not type in Chinese without shurufa)

**Comment by heavengate** [comment]
```
holder should not be null
Tensor not initialized yet when Tensor::type() is called.
```
你的权重没有正确加载进来，--weights=${weights/darknet53} 修改为--weights=你的权重所在的路径

**Comment by Sparrow0817** [comment]
> ```
> holder should not be null
> Tensor not initialized yet when Tensor::type() is called.
> ```
> 
> 你的权重没有正确加载进来，--weights=${weights/darknet53} 修改为--weights=你的权重所在的路径

/models/PaddleCV/yolov3/weights/darknet53$ ls
stage.0.0.0.bn.mean              stage.2.4.1.bn.scale             stage.3.4.1.conv.weights
stage.0.0.0.bn.offset            stage.2.4.1.bn.var               stage.3.5.0.bn.mean
stage.0.0.0.bn.scale             stage.2.4.1.conv.weights         stage.3.5.0.bn.offset
stage.0.0.0.bn.var               stage.2.5.0.bn.mean              stage.3.5.0.bn.scale
stage.0.0.0.conv.weights         stage.2.5.0.bn.offset            stage.3.5.0.bn.var
stage.0.0.1.bn.mean              stage.2.5.0.bn.scale             stage.3.5.0.conv.weights
stage.0.0.1.bn.offset            stage.2.5.0.bn.var               stage.3.5.1.bn.mean
stage.0.0.1.bn.scale             stage.2.5.0.conv.weights         stage.3.5.1.bn.offset
stage.0.0.1.bn.var               stage.2.5.1.bn.mean              stage.3.5.1.bn.scale
stage.0.0.1.conv.weights         stage.2.5.1.bn.offset            stage.3.5.1.bn.var
stage.0.downsample.bn.mean       stage.2.5.1.bn.scale             stage.3.5.1.conv.weights
stage.0.downsample.bn.offset     stage.2.5.1.bn.var               stage.3.6.0.bn.mean
stage.0.downsample.bn.scale      stage.2.5.1.conv.weights         stage.3.6.0.bn.offset
stage.0.downsample.bn.var        stage.2.6.0.bn.mean              stage.3.6.0.bn.scale
stage.0.downsample.conv.weights  stage.2.6.0.bn.offset            stage.3.6.0.bn.var
stage.1.0.0.bn.mean              stage.2.6.0.bn.scale             stage.3.6.0.conv.weights
stage.1.0.0.bn.offset            stage.2.6.0.bn.var               stage.3.6.1.bn.mean
stage.1.0.0.bn.scale             stage.2.6.0.conv.weights         stage.3.6.1.bn.offset
stage.1.0.0.bn.var               stage.2.6.1.bn.mean              stage.3.6.1.bn.scale
stage.1.0.0.conv.weights         stage.2.6.1.bn.offset            stage.3.6.1.bn.var
stage.1.0.1.bn.mean              stage.2.6.1.bn.scale             stage.3.6.1.conv.weights
stage.1.0.1.bn.offset            stage.2.6.1.bn.var               stage.3.7.0.bn.mean
stage.1.0.1.bn.scale             stage.2.6.1.conv.weights         stage.3.7.0.bn.offset
stage.1.0.1.bn.var               stage.2.7.0.bn.mean              stage.3.7.0.bn.scale
stage.1.0.1.conv.weights         stage.2.7.0.bn.offset            stage.3.7.0.bn.var
stage.1.1.0.bn.mean              stage.2.7.0.bn.scale             stage.3.7.0.conv.weights
stage.1.1.0.bn.offset            stage.2.7.0.bn.var               stage.3.7.1.bn.mean
stage.1.1.0.bn.scale             stage.2.7.0.conv.weights         stage.3.7.1.bn.offset
stage.1.1.0.bn.var               stage.2.7.1.bn.mean              stage.3.7.1.bn.scale
stage.1.1.0.conv.weights         stage.2.7.1.bn.offset            stage.3.7.1.bn.var
stage.1.1.1.bn.mean              stage.2.7.1.bn.scale             stage.3.7.1.conv.weights
stage.1.1.1.bn.offset            stage.2.7.1.bn.var               stage.3.downsample.bn.mean
stage.1.1.1.bn.scale             stage.2.7.1.conv.weights         stage.3.downsample.bn.offset
stage.1.1.1.bn.var               stage.2.downsample.bn.mean       stage.3.downsample.bn.scale
stage.1.1.1.conv.weights         stage.2.downsample.bn.offset     stage.3.downsample.bn.var
stage.1.downsample.bn.mean       stage.2.downsample.bn.scale      stage.3.downsample.conv.weights
stage.1.downsample.bn.offset     stage.2.downsample.bn.var        stage.4.0.0.bn.mean
stage.1.downsample.bn.scale      stage.2.downsample.conv.weights  stage.4.0.0.bn.offset
stage.1.downsample.bn.var        stage.3.0.0.bn.mean              stage.4.0.0.bn.scale
stage.1.downsample.conv.weights  stage.3.0.0.bn.offset            stage.4.0.0.bn.var
stage.2.0.0.bn.mean              stage.3.0.0.bn.scale             stage.4.0.0.conv.weights
stage.2.0.0.bn.offset            stage.3.0.0.bn.var               stage.4.0.1.bn.mean
stage.2.0.0.bn.scale             stage.3.0.0.conv.weights         stage.4.0.1.bn.offset
stage.2.0.0.bn.var               stage.3.0.1.bn.mean              stage.4.0.1.bn.scale
stage.2.0.0.conv.weights         stage.3.0.1.bn.offset            stage.4.0.1.bn.var
stage.2.0.1.bn.mean              stage.3.0.1.bn.scale             stage.4.0.1.conv.weights
stage.2.0.1.bn.offset            stage.3.0.1.bn.var               stage.4.1.0.bn.mean
stage.2.0.1.bn.scale             stage.3.0.1.conv.weights         stage.4.1.0.bn.offset
stage.2.0.1.bn.var               stage.3.1.0.bn.mean              stage.4.1.0.bn.scale
stage.2.0.1.conv.weights         stage.3.1.0.bn.offset            stage.4.1.0.bn.var
stage.2.1.0.bn.mean              stage.3.1.0.bn.scale             stage.4.1.0.conv.weights
stage.2.1.0.bn.offset            stage.3.1.0.bn.var               stage.4.1.1.bn.mean
stage.2.1.0.bn.scale             stage.3.1.0.conv.weights         stage.4.1.1.bn.offset
stage.2.1.0.bn.var               stage.3.1.1.bn.mean              stage.4.1.1.bn.scale
stage.2.1.0.conv.weights         stage.3.1.1.bn.offset            stage.4.1.1.bn.var
stage.2.1.1.bn.mean              stage.3.1.1.bn.scale             stage.4.1.1.conv.weights
stage.2.1.1.bn.offset            stage.3.1.1.bn.var               stage.4.2.0.bn.mean
stage.2.1.1.bn.scale             stage.3.1.1.conv.weights         stage.4.2.0.bn.offset
stage.2.1.1.bn.var               stage.3.2.0.bn.mean              stage.4.2.0.bn.scale
stage.2.1.1.conv.weights         stage.3.2.0.bn.offset            stage.4.2.0.bn.var
stage.2.2.0.bn.mean              stage.3.2.0.bn.scale             stage.4.2.0.conv.weights
stage.2.2.0.bn.offset            stage.3.2.0.bn.var               stage.4.2.1.bn.mean
stage.2.2.0.bn.scale             stage.3.2.0.conv.weights         stage.4.2.1.bn.offset
stage.2.2.0.bn.var               stage.3.2.1.bn.mean              stage.4.2.1.bn.scale
stage.2.2.0.conv.weights         stage.3.2.1.bn.offset            stage.4.2.1.bn.var
stage.2.2.1.bn.mean              stage.3.2.1.bn.scale             stage.4.2.1.conv.weights
stage.2.2.1.bn.offset            stage.3.2.1.bn.var               stage.4.3.0.bn.mean
stage.2.2.1.bn.scale             stage.3.2.1.conv.weights         stage.4.3.0.bn.offset
stage.2.2.1.bn.var               stage.3.3.0.bn.mean              stage.4.3.0.bn.scale
stage.2.2.1.conv.weights         stage.3.3.0.bn.offset            stage.4.3.0.bn.var
stage.2.3.0.bn.mean              stage.3.3.0.bn.scale             stage.4.3.0.conv.weights
stage.2.3.0.bn.offset            stage.3.3.0.bn.var               stage.4.3.1.bn.mean
stage.2.3.0.bn.scale             stage.3.3.0.conv.weights         stage.4.3.1.bn.offset
stage.2.3.0.bn.var               stage.3.3.1.bn.mean              stage.4.3.1.bn.scale
stage.2.3.0.conv.weights         stage.3.3.1.bn.offset            stage.4.3.1.bn.var
stage.2.3.1.bn.mean              stage.3.3.1.bn.scale             stage.4.3.1.conv.weights
stage.2.3.1.bn.offset            stage.3.3.1.bn.var               yolo_input.bn.mean
stage.2.3.1.bn.scale             stage.3.3.1.conv.weights         yolo_input.bn.offset
stage.2.3.1.bn.var               stage.3.4.0.bn.mean              yolo_input.bn.scale
stage.2.3.1.conv.weights         stage.3.4.0.bn.offset            yolo_input.bn.var
stage.2.4.0.bn.mean              stage.3.4.0.bn.scale             yolo_input.conv.weights
stage.2.4.0.bn.offset            stage.3.4.0.bn.var               yolo_input.downsample.bn.mean
stage.2.4.0.bn.scale             stage.3.4.0.conv.weights         yolo_input.downsample.bn.offset
stage.2.4.0.bn.var               stage.3.4.1.bn.mean              yolo_input.downsample.bn.scale
stage.2.4.0.conv.weights         stage.3.4.1.bn.offset            yolo_input.downsample.bn.var
stage.2.4.1.bn.mean              stage.3.4.1.bn.scale             yolo_input.downsample.conv.weights
stage.2.4.1.bn.offset            stage.3.4.1.bn.var
What should I do next ? --weightes = weights/darknet53 or what ? Thank you for your patience !

**Comment by heavengate** [comment]
darknet53是主干网络预训练权重，要跑infer的话加载全量权重，weights/download.sh 里面有下载的那个yolov3.tar.gz

**Comment by Sparrow0817** [comment]
> darknet53是主干网络预训练权重，要跑infer的话加载全量权重，weights/download.sh 里面有下载的那个yolov3.tar.gz

thank you , I change to --weights=weights/yolov3 ,I got this: 
`-----------  Configuration Arguments -----------
batch_size: 8
class_num: 80
data_dir: dataset/coco
dataset: coco2017
debug: False
draw_thresh: 0.5
image_name: 000000000139.jpg
image_path: dataset/coco/val2017/
input_size: 608
label_smooth: True
learning_rate: 0.001
max_iter: 500200
model_save_dir: checkpoints
nms_posk: 100
nms_thresh: 0.45
nms_topk: 400
no_mixup_iter: 40000
pretrain: weights/darknet53
random_shape: True
snapshot_iter: 2000
start_iter: 0
syncbn: True
use_gpu: True
use_multiprocess: True
valid_thresh: 0.005
weights: weights/yolov3
------------------------------------------------
W0523 11:39:39.777083 23381 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 9.0
W0523 11:39:39.785517 23381 device_context.cc:269] device: 0, cuDNN Version: 7.0.
loading annotations into memory...
Done (t=0.55s)
creating index...
index created!
Load in 80 categories.
Image 000000000139.jpg detect: 
Traceback (most recent call last):
  File "infer.py", line 80, in <module>
    infer()
  File "infer.py", line 74, in infer
    box_utils.draw_boxes_on_image(path, boxes, scores, labels, label_names, cfg.draw_thresh)
  File "/home/lwd/models/PaddleCV/yolov3/box_utils.py", line 169, in draw_boxes_on_image
    print("\t {:15s} at {:25} score: {:.5f}".format(label_names[int(label)], map(int, list(box)), score))
TypeError: unsupported format string passed to map.__format__
`

**Comment by heavengate** [comment]
python3兼容性问题，感谢指出，可参照 https://github.com/PaddlePaddle/models/pull/2298  本地修改下~

**Comment by heavengate** [comment]
python3 兼容性问题已合入develop, 麻烦重新pull一下develop测试下，如果还有问题，请reopen一下这个issue

**Comment by Sparrow0817** [comment]
> darknet53是主干网络预训练权重，要跑infer的话加载全量权重，weights/download.sh 里面有下载的那个yolov3.tar.gz


> python3兼容性问题，感谢指出，可参照 #2298 本地修改下~
thank you! It works!
