### ISSUE TITLE
MAC下gnn下载模型数据失败

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2304]
按照官方文档下载模型数据，执行指令cd data && sh download.sh，报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/58248462-c8d8f300-7d8e-11e9-928d-cfc22c088cb8.png)

**Comment by hutuxian** [comment]
fixed:https://github.com/PaddlePaddle/models/pull/2520
