### ISSUE TITLE
gnn 训练报错

### ISSUE THREAD

**Issue by wangduan023** [PaddlePaddle/models#2306]
macos 执行 CPU_NUM=1 python -u train.py --use_cuda 0 > log.txt 2>&1
日志

2019-05-24 10:01:06,870 - INFO - load data complete
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    train()
  File "train.py", line 104, in train
    feeder = fluid.DataFeeder(feed_list=feed_list, place=place)
  File "/Users/iMac/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 161, in __init__
    each_var.name)
ValueError: ('Variable {0} must has a batch size dimension', 'items')

**Comment by wangguibao** [comment]
请问您具体用的哪个模型，可以发下链接不？

**Comment by wangduan023** [comment]
PaddleRec/gnn

**Comment by wangduan023** [comment]
> 请问您具体用的哪个模型，可以发下链接不？
  PaddleRec/gnn

**Comment by wangduan023** [comment]
@wangguibao 模型  PaddleRec/gnn

**Comment by hutuxian** [comment]
Thanks for your attention.
Please upgrade your paddle version and retry, this error may only occur in the low version.

**Comment by JiaXiao243** [comment]
使用paddle==1.4.1 训练gnn模型可以跑起来
![image](https://user-images.githubusercontent.com/37854899/58316791-f97c6380-7e46-11e9-9696-a20f7e293a51.png)
paddle==1.2.0有这个问题
![image](https://user-images.githubusercontent.com/37854899/58316892-36e0f100-7e47-11e9-8e85-712a3c39672b.png)

**Comment by wangduan023** [comment]
@JiaXiao243 申请了版本后已经没有问题了

**Comment by wangduan023** [comment]
@JiaXiao243 升级了版本后已经没有问题了
