### ISSUE TITLE
基于YOLOv3的实时目标检测

### ISSUE THREAD

**Issue by Sparrow0817** [PaddlePaddle/models#2307]
有人在paddle上做过这个项目吗

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by wangguibao** [comment]
这有一个发布的模型：
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/yolov3

**Comment by Sparrow0817** [comment]
> 这有一个发布的模型：
> https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/yolov3

额，不好意思没表达清楚，我想问的是有没有视频识别的实现。

**Comment by huxianhe0** [comment]
同问，请问楼主实现了吗？基于paddlepaddle的yolov3实时目标检测

**Comment by wangguibao** [comment]
再提个issue问一下吧

**Comment by Sparrow0817** [comment]
我当时是采用的视频流取帧，然后循环调用paddle借口的笨方法，最后把生成的图像合成视频流用窗口显示。事实证明这样的效果很不好，延时久帧率低，不实用。


在 2020年4月1日，18:07，huxianhe0 <notifications@github.com> 写道：

﻿

同问，请问楼主实现了吗？基于paddlepaddle的yolov3实时目标检测
