### ISSUE TITLE
dialogue_general_understanding运行出错memory_optimize is deprecated. Use CompiledProgram and Executor

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#2323]
paddle1.4版本中运行dstc2、mrda报错
memory_optimize is deprecated. Use CompiledProgram and Executor
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.

**Comment by heavengate** [comment]
Paddle fluid 1.4版本中弃用了ParallelExecutor等接口，改用CompiledProgram，所以会报这个warning，不影响模型正确运行，models里的模型从ParallelExecutor迁移到CompiledProgram工作正在进行中。
您可使用当前代码训练，对训练精度，模型正确性等没有影响
