### ISSUE TITLE
PaddleSlim是否支持yolov3等检测模型的剪枝压缩

### ISSUE THREAD

**Issue by herbiezhao** [PaddlePaddle/models#2350]

**Comment by sandyhouse** [comment]
从理论上讲是支持的。

**Comment by herbiezhao** [comment]
那实际上呢？有指导吗，需要自己改源码？

**Comment by sandyhouse** [comment]
应该不需要改源码，只是没在yolov3模型上验证过效果。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by gujingxiao** [comment]
其实我想说，官方应该出一个检测网络剪枝的指导说明，因为当前slim里问题太多，而且目前给的说明都是处理backbone的，如果想要给检测网络做，reader要改，模型结构要改，配置文件要改，保存结果也要改，需要修改不少源码。

**Comment by zzchust** [comment]
同意楼上观点
