### ISSUE TITLE
attention_cluster和lstm预训练的3862类，是youtube8M哪些类？方便提供一下对应关系吗？

### ISSUE THREAD

**Issue by youidol** [PaddlePaddle/models#2351]

**Comment by sandyhouse** [comment]
可参考：https://github.com/google/youtube-8m#ground-truth-label-files，https://research.google.com/youtube8m/download.html

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
