### ISSUE TITLE
[New Feature] 清除paddle控制设备占用存储

### ISSUE THREAD

**Issue by yiakwy** [PaddlePaddle/models#2374]
## 问题背景

在类似AIStudio环境中，包括AIStudio，在启动Paddle程序，是对进程生命周期分配存储，导致第二次运行一个 jupyter code bock，内存未被释放。在某些情况下，我们只能重启Kernel来释放内存。

## 复现场景

```shell
nvidia-smi
nvidia-smi --gpu-reset -i 0 # https://devtalk.nvidia.com/default/topic/958159/cuda-programming-and-performance/11-gb-of-gpu-ram-used-and-no-process-listed-by-nvidia-smi/
```

```txt
Fri Jun  7 22:03:38 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   33C    P0    54W / 300W |  14912MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
PCI device 00000000:00:08.0 must be reset with GPU 0 (00000000:00:07.0).
One or more incomplete sets of NVLink GPUs were specified.
GPU Reset couldn't run because the specified GPUs could not be validated for NVLink reset.
```

我们发现 14/16 的内存被使用，但是找不到[process id](https://github.com/NVIDIA/nvidia-docker/issues/476)， 也不能在paddle中清除显存，只能手动重启Jupyter Kernel. 

## 问题对比

1. 旧版本显存是针对进程生命周期分配的，在新版的Tensorflow 已经可以通过Gpu分配策略Tensorflow api释放gpu
2. Colab从过往使用经验看，似乎没有类似问题

## 可能解决方案和相关问题

- 清除显存：https://stackoverflow.com/questions/39758094/clearing-tensorflow-gpu-memory-after-model-execution
- 和NVIDIA驱动版本有关：https://github.com/tensorflow/tensorflow/issues/1727 
- 使用多进程来解决： https://github.com/tensorflow/tensorflow/issues/17048
- 使用numba.cuda: https://github.com/tensorflow/tensorflow/issues/17048
- 使用Tensorflow gpu memory growth config: https://github.com/keras-team/keras/issues/12625

**Comment by liupluswei** [comment]
感谢您提供的详细说明，可否提供一下这个显存无法被释放的问题的复现步骤？我们这边好定位一下具体的问题

**Comment by yiakwy** [comment]
@liuwei1031 复现步骤，可按下面执行：

在Jupyter或者AIStudio类似的环境中，跑一次模型 

> executor.run(prog, fetch_list=fetch_list, feed=feeder.feed([inp]), return_numpy=False)

即存储分配，后续在此环境中，如重复跑实验，都需要重启jupyter kernel，否则因为对该进程声明周期，分配的内存不会被释放，导致显卡内存溢出。

可以执行 

```shell
# jupyter block
!nvidia-smi
!nvidia-smi --gpu-reset -i 0 # https://devtalk.nvidia.com/default/topic/958159/cuda-programming-and-performance/11-gb-of-gpu-ram-used-and-no-process-listed-by-nvidia-smi/
```

查询信息。发现除了jupyter本身，已经即使训练，推理已经完成，内存仍然残留。导致重复跑模型，实验失败。

**Comment by liupluswei** [comment]
> @liuwei1031 复现步骤，可按下面执行：
> 
> 在Jupyter或者AIStudio类似的环境中，跑一次模型
> 
> > executor.run(prog, fetch_list=fetch_list, feed=feeder.feed([inp]), return_numpy=False)
> 
> 即存储分配，后续在此环境中，如重复跑实验，都需要重启jupyter kernel，否则因为对该进程声明周期，分配的内存不会被释放，导致显卡内存溢出。
> 
> 可以执行
> 
> ```shell
> # jupyter block
> !nvidia-smi
> !nvidia-smi --gpu-reset -i 0 # https://devtalk.nvidia.com/default/topic/958159/cuda-programming-and-performance/11-gb-of-gpu-ram-used-and-no-process-listed-by-nvidia-smi/
> ```
> 
> 查询信息。发现除了jupyter本身，已经即使训练，推理已经完成，内存仍然残留。导致重复跑模型，实验失败。

你好，我这边在jupyter环境下尝试了一下我们paddlepaddle/book下面的训练脚本：
https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/train.py
并没有复现你所描述的这个问题，训练结束以后显存自动释放了，并没有影响后续的运行。

如果方便的话，可否提供一下你的脚本和数据？  
还有你提到aistudio 和 jupyter，如果不用这两个tool，你的任务是否可以正常运行呢？

**Comment by yiakwy** [comment]
@liuwei1031 您好，jupyterbook 文件后缀是 ipynb，那么请问您是以library形式引入到 book 执行，还是以子进程方式处理？

如果是后者，解决方案已经提到tensorflow是针对进程生命周期分配内存，故可以这么做。

请明确执行方式，以及paddle内存分配的生命周期。

具体book代码，我提供了下面的参考：https://aistudio.baidu.com/aistudio/projectdetail/60969

**Comment by liupluswei** [comment]
你好，我这边的疑问其实是您碰到得这个问题是paddle 本身的问题，还是说引入了jupyter和aistudio之后造成的问题。如果抛开jupyter和aistudio不管，您是否有在机器上直接运行您的模型的条件，如果可以的话建议您试一下，确认是否还有这个问题。  因为我平时使用jupyter和aistudio不多，我这边不太好复现您说的这个现象，我会看看有没有其他相关同事了解这个。

**Comment by yiakwy** [comment]
在AIStudio和jupyter环境。

**Comment by liupluswei** [comment]
> 在AIStudio和jupyter环境。

好的，我了解了，我会在工作日咨询一下有没有对这两个比较熟悉的同事讨论一下

**Comment by yiakwy** [comment]
@liuwei1031 实际上虽然是环境暴露的问题，但是这个也是其他网络框架以前存在的问题之一，这引导开发者，和用户思考相关控制设备内存释放问题和生命周期。所以，如果paddle可以提供手动控制，或者进一步更完善生命周期机制，就会彻底解决这类问题。

**Comment by liupluswei** [comment]
> @liuwei1031 实际上虽然是环境暴露的问题，但是这个也是其他网络框架以前存在的问题之一，这引导开发者，和用户思考相关控制设备内存释放问题和生命周期。所以，如果paddle可以提供手动控制，或者进一步更完善生命周期机制，就会彻底解决这类问题。

@yiakwy 之前在忙着发版的事情，所以您这个问题跟PM商量之后稍微搁置了一下。 我今天重新debug了一下这个问题：
1. 首先关于您的疑问Paddle的显存什么时候释放的问题, 正常来讲Paddle的cuda free是在内部的显存Allocator析构的时候调用，而Allocator是在python 进程结束的时候析构. 
2. 目前最简单的workaround应该是调用numba 的cuda接口来主动释放显存：
    from numba import cuda
    cuda.selecte_device(0)
    cuda.close()

    示例：
![image](https://user-images.githubusercontent.com/46661762/60592692-c2995600-9dd3-11e9-99c7-dea29a2b132f.png)

因为相关的Allocator目前处于重构中，目前并不太适合新增一个主动释放显存的接口，现在新增后续还需要修改，而且问题本身也是jupyter kernel的设计导致，所以我们暂时就不作为功能新增来处理了。

总结：
问题本质上是jupyter kernel 始终占据python进程导致，可以用您提到的几种workround 来绕过去：
1）重启kernel
2）用numba 的cuda.close()
3）多进程（没有验证，但按我的理解应该可行，Process结束的时候应该会触发析构）

非常感谢您的反馈！
