### ISSUE TITLE
Non-local模型的参数不能下载

### ISSUE THREAD

**Issue by cjt222** [PaddlePaddle/models#2404]
Non-local模型的参数下载链接为空

**Comment by gongweibao** [comment]
能否给一个入口？

**Comment by cjt222** [comment]
![image](https://user-images.githubusercontent.com/17508662/59581889-fa807800-9108-11e9-9e91-158685d488af.png)
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video/models/nonlocal_model
这里的官方训练好的模型无法下载

@gongweibao

**Comment by shippingwang** [comment]
[It](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleVideo) works so I close this issue now
