### ISSUE TITLE
resnet_vd模型eval报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2418]
在PaddleCV/image_classification目录下执行python eval.py --model=ResNet101_vd --pretrained_model=./ResNet101_vd_pretrained指令，对下载的预训练模型ResNet101_vd进行评估，报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/59574871-87b4d400-90eb-11e9-99aa-ccec8639dcb6.png)

**Comment by shippingwang** [comment]
fixed by #2437
