### ISSUE TITLE
[new feature request]half-precision support

### ISSUE THREAD

**Issue by chenjiasheng** [PaddlePaddle/models#243]
As the DS2 paper mentioned:

> Our deployment system evaluates RNNs in half-precision
> arithmetic, which has no measurable accuracy impact, but
> significantly improves efficiency. We wrote our own 16-bit
> matrix-matrix multiply routines for this task, substantially
> improving throughput for our relatively small batches.

So have you implemented this half-precision arithmetic?
Does it take the advantages of CUDA's half-precision ability 
(https://devblogs.nvidia.com/parallelforall/new-features-cuda-7-5/
https://devblogs.nvidia.com/parallelforall/mixed-precision-programming-cuda-8/)?

**Comment by wangkuiyi** [comment]
Thanks for the questions. PaddlePaddle doesn't have FP16 yet. But we will add this feature soon.

The DS2 paper was referring to another DL framework, known internally in Baidu as SpeechDL.  It was specifically designed for DS and DS2 and is not open sourced.  The SpeechDL team at Baidu Sunnyvale office is contributing some important features from SpeechDL into PaddlePaddle.  We plan to have FP16 in PaddlePaddle in a few months.

**Comment by chenjiasheng** [comment]
Got it. Thank you a lot.
