### ISSUE TITLE
transformer infer报错 

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2468]
在PaddleNLP/unarchived/neural_machine_translation/transformer目录下执行python -u infer.py  --src_vocab_fpath wmt16_ende_data_bpe_clean/vocab_all.bpe.32000 --trg_vocab_fpath wmt16_ende_data_bpe_clean/vocab_all.bpe.32000 --test_file_pattern wmt16_ende_data_bpe_clean/newstest2016.tok.bpe.32000.en-de model_path trained_models/iter_30000.infer.model指令，对训练的模型进行预测，报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/59839061-a1237d80-9382-11e9-8b51-0441cec6efb8.png)

**Comment by guoshengCS** [comment]
这个试下按照这里的 https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/models/neural_machine_translation/transformer/model.py#L882
把 https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/unarchived/neural_machine_translation/transformer/model.py#L878  的 `topk_indices = layers.lod_reset(accu_scores, pre_ids)` 改成 ` accu_scores = layers.lod_reset(accu_scores, pre_ids)` 呢

**Comment by JiaXiao243** [comment]
fix [#2522]( https://github.com/PaddlePaddle/models/pull/2522)
