### ISSUE TITLE
machine reading comprehension多GPU下报错

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/models#2480]
![image](https://user-images.githubusercontent.com/10734244/59903982-f9b35300-9434-11e9-9bf0-0fb11bf8bfd0.png)

**Comment by xyzhou-puck** [comment]
关掉显存优化后就可以了，是个已知问题。

**Comment by xyzhou-puck** [comment]
memory_optimize存在bug，1.5后会废弃，可以通过打卡GC开启显存优化，打开方式为设置flag：

export FLAGS_eager_delete_tensor_gb=0.0
