### ISSUE TITLE
window上deep_attention_matching训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2483]
在window机器上，PaddleNLP/dialogue_model_toolkit/deep_attention_matching目录下，执行
python -u main.py --do_train True --use_cuda --data_path ./data/ubuntu/data_small.pkl --save_path ./model_files/ubuntu  --use_pyreader --vocab_size 434512 --_EOS_ 28270  --batch_size 32对模型进行训练，报错信息如下:
![image](https://user-images.githubusercontent.com/37854899/59914242-8fa6a800-944c-11e9-8eaa-b9d8c7903619.png)

**Comment by wopeizl** [comment]
https://github.com/PaddlePaddle/models/pull/2575
