### ISSUE TITLE
ELMo模型训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2487]
在LARK/ELMo目录下执行sh run.sh对ELMo模型进行训练，报错信息如下：
![image](https://user-images.githubusercontent.com/37854899/59920652-cafda280-945d-11e9-95d0-23267f03bf0f.png)

**Comment by JesseyXujin** [comment]
麻烦提供环境和复现步骤。

**Comment by JiaXiao243** [comment]
paddle:release1.5分支从源码编译安装的paddle；
运行环境：docker_ubuntu1604_cuda9.0_cudnn7_py37
步骤： 在LARK/ELMo目录下执行sh run.sh
bug：
目前定位为ELMo模型未在python3上适配，在python2.7上可以正常训练。

**Comment by JesseyXujin** [comment]
ELMo目前支持python2.7，定位问题是不支持python3.7

**Comment by JesseyXujin** [comment]
在elmo readme补充版本依赖

**Comment by JesseyXujin** [comment]
https://github.com/PaddlePaddle/LARK/pull/176

**Comment by JesseyXujin** [comment]
已merge
