### ISSUE TITLE
运行自动Killed

### ISSUE THREAD

**Issue by huillll** [PaddlePaddle/models#2505]
Killed
run.sh --total_images=4493: not found
image_classification

#Example: SE_ResNext50_32x4d
python train.py \
       --model=SE_ResNeXt50_32x4d \
       --batch_size=400 \
       --total_images=4493 \
       --class_dim=61 \
       --image_shape=3,224,224 \
       --model_save_dir=output/ \
       --with_mem_opt=True \
       --lr_strategy=cosine_decay \
       --lr=0.1 \
       --num_epochs=200 \
       --l2_decay=1.2e-4 \
#      >log_SE_ResNeXt50_32x4d.txt 2>&1 &

**Comment by huillll** [comment]
直接被Killed，不知道什么原因，加载图像的过程中Killed.系统Ubuntu,18.04,内存16G.显卡1078.
用CPU训练

**Comment by JiabinYang** [comment]
请问下您是运行哪个模型呢

**Comment by huillll** [comment]
训练

**Comment by huillll** [comment]
用网络Example: SE_ResNext50_32x4d，训练四千多张病虫害数据

**Comment by JiabinYang** [comment]
请问是运行我们模型库中的模型么，如果是的话麻烦提供下link，如果不是您可以提供下您的代码段么

**Comment by huillll** [comment]
我直接把数据做好，直接用image_classification文件夹里面的run.sh。改了几个参数。前面第一行就有

**Comment by huillll** [comment]
Killed
run.sh --total_images=4493: not found
这个就是错误

**Comment by huillll** [comment]
-------------  Configuration Arguments -------------
               batch_size : 4
               checkpoint : None
                class_dim : 1000
                 data_dir : ./data/ILSVRC2012/
                enable_ce : False
                     fp16 : False
              image_shape : 3,224,224
               is_distill : False
                 l2_decay : 0.0001
  label_smoothing_epsilon : 0.2
              lower_ratio : 0.75
              lower_scale : 0.08
                       lr : 0.1
              lr_strategy : piecewise_decay
              mixup_alpha : 0.2
                    model : SE_ResNeXt50_32x4d
           model_save_dir : output
            momentum_rate : 0.9
               num_epochs : 120
         pretrained_model : None
        resize_short_size : 256
               scale_loss : 1.0
             total_images : 31378
              upper_ratio : 1.3333333333333333
                  use_gpu : 1
      use_label_smoothing : False
                use_mixup : False
             with_inplace : True
             with_mem_opt : False
----------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 591, in <module>
    main()
  File "train.py", line 587, in main
    train(args)
  File "train.py", line 386, in train
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/paddle/paddle/fluid/pybind/pybind.cc:806]
PaddlePaddle Call Stacks: 
0       0x7ff266c95ca8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7ff266c95ff7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7ff266c77654p
3       0x7ff266cc513ep
4             0x565d5cp _PyCFunction_FastCallDict + 860
5             0x5914e1p
6             0x54b985p
7             0x555421p
8             0x5a730cp _PyObject_FastCallKeywords + 412
9             0x503073p
10            0x506859p _PyEval_EvalFrameDefault + 1097
11            0x504c28p
12            0x502540p
13            0x502f3dp
14            0x506859p _PyEval_EvalFrameDefault + 1097
15            0x502209p
16            0x502f3dp
17            0x506859p _PyEval_EvalFrameDefault + 1097
18            0x504c28p
19            0x506393p PyEval_EvalCode + 35
20            0x634d52p
21            0x634e0ap PyRun_FileExFlags + 154
22            0x6385c8p PyRun_SimpleFileExFlags + 392
23            0x63915ap Py_Main + 1402
24            0x4a6f10p main + 224
25      0x7ff290292b97p __libc_start_main + 231
26            0x5afa0ap _start + 42

**Comment by huillll** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   53C    P8    16W / 151W |    158MiB /  8116MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by huillll** [comment]
W0624 20:21:42.128429  3411 dynamic_loader.cc:107] Can not find library: libnccl.so. Please try to add the lib path to LD_LIBRARY_PATH.
这个是要装什么啊。Paddle很多坑啊，希望尽快优化啊

**Comment by huxiaoman7** [comment]
这个不是paddle的问题，是你安装了gpu版本的paddle需要配置一下环境。你需要在 ~/.bashrc 中设置 LD_LIBRARY_PATH 就可以了（如果找不到nccl，可以先安装nccl）

**Comment by JiabinYang** [comment]
```
> ## ------------- Configuration Arguments -------------
> batch_size : 4
> checkpoint : None
> class_dim : 1000
> data_dir : ./data/ILSVRC2012/
> enable_ce : False
> fp16 : False
> image_shape : 3,224,224
> is_distill : False
> l2_decay : 0.0001
> label_smoothing_epsilon : 0.2
> lower_ratio : 0.75
> lower_scale : 0.08
> lr : 0.1
> lr_strategy : piecewise_decay
> mixup_alpha : 0.2
> model : SE_ResNeXt50_32x4d
> model_save_dir : output
> momentum_rate : 0.9
> num_epochs : 120
> pretrained_model : None
> resize_short_size : 256
> scale_loss : 1.0
> total_images : 31378
> upper_ratio : 1.3333333333333333
> use_gpu : 1
> use_label_smoothing : False
> use_mixup : False
> with_inplace : True
> with_mem_opt : False
> Traceback (most recent call last):
> File "train.py", line 591, in 
> main()
> File "train.py", line 587, in main
> train(args)
> File "train.py", line 386, in train
> place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
> paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/paddle/paddle/fluid/pybind/pybind.cc:806]
> PaddlePaddle Call Stacks:
> 0 0x7ff266c95ca8p void paddle::platform::EnforceNotMet::Initstd::string(std::string, char const*, int) + 360
> 1 0x7ff266c95ff7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
> 2 0x7ff266c77654p
> 3 0x7ff266cc513ep
> 4 0x565d5cp _PyCFunction_FastCallDict + 860
> 5 0x5914e1p
> 6 0x54b985p
> 7 0x555421p
> 8 0x5a730cp _PyObject_FastCallKeywords + 412
> 9 0x503073p
> 10 0x506859p _PyEval_EvalFrameDefault + 1097
> 11 0x504c28p
> 12 0x502540p
> 13 0x502f3dp
> 14 0x506859p _PyEval_EvalFrameDefault + 1097
> 15 0x502209p
> 16 0x502f3dp
> 17 0x506859p _PyEval_EvalFrameDefault + 1097
> 18 0x504c28p
> 19 0x506393p PyEval_EvalCode + 35
> 20 0x634d52p
> 21 0x634e0ap PyRun_FileExFlags + 154
> 22 0x6385c8p PyRun_SimpleFileExFlags + 392
> 23 0x63915ap Py_Main + 1402
> 24 0x4a6f10p main + 224
> 25 0x7ff290292b97p __libc_start_main + 231
> 26 0x5afa0ap _start + 42
```

您这个报错应该是安装的paddle是cpu版本的，而不是gpu版本的

**Comment by huillll** [comment]
-------------  Configuration Arguments -------------
               batch_size : 4
               checkpoint : None
                class_dim : 61
                 data_dir : ./data/ILSVRC2012/
                enable_ce : False
                     fp16 : False
              image_shape : 3,224,224
               is_distill : False
                 l2_decay : 0.00012
  label_smoothing_epsilon : 0.2
              lower_ratio : 0.75
              lower_scale : 0.08
                       lr : 0.1
              lr_strategy : cosine_decay
              mixup_alpha : 0.2
                    model : SE_ResNeXt50_32x4d
           model_save_dir : output/
            momentum_rate : 0.9
               num_epochs : 200
         pretrained_model : None
        resize_short_size : 256
               scale_loss : 1.0
             total_images : 31387
              upper_ratio : 1.3333333333333333
                  use_gpu : 1
      use_label_smoothing : False
                use_mixup : False
             with_inplace : True
             with_mem_opt : 1
----------------------------------------------------
memory_optimize is deprecated. Use CompiledProgram and Executor
memory_optimize is deprecated. Use CompiledProgram and Executor
W0624 21:37:30.481963 19704 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 8.0
W0624 21:37:30.705292 19704 device_context.cc:269] device: 0, cuDNN Version: 7.0.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0624 21:37:30.831302 19704 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
W0624 21:37:30.851934 19704 dynamic_loader.cc:107] Can not find library: libnccl.so. Please try to add the lib path to LD_LIBRARY_PATH.

**Comment by JiabinYang** [comment]
这个问题应该是没有正确安装nccl，您可以参考[nvidia官方网站](https://developer.nvidia.com/nccl/nccl-legacy-downloads#a-collapse22b-8)安装nccl

**Comment by huillll** [comment]
install nccl error
sudo dpkg -i nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2_1-1_amd64.deb 
Selecting previously unselected package nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2.
(Reading database ... 197571 files and directories currently installed.)
Preparing to unpack nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2_1-1_amd64.deb ...
Unpacking nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2 (1-1) ...
Setting up nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2 (1-1) ...

The public CUDA GPG key does not appear to be installed.
To install the key, run this command:
sudo apt-key add /var/nccl-repo-2.3.7-ga-cuda9.2/7fa2af80.pub

**Comment by huillll** [comment]
luhui@luhui-System-Product-Name:~/Downloads$ sudo dpkg -i nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2_1-1_amd64.deb 
(Reading database ... 197581 files and directories currently installed.)
Preparing to unpack nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2_1-1_amd64.deb ...
Unpacking nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2 (1-1) over (1-1) ...
Setting up nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2 (1-1) ...
luhui@luhui-System-Product-Name:~/Downloads$ sudo find / -name *libnccl*
find: ‘/run/user/1000/gvfs’: Permission denied
/var/nccl-repo-2.3.7-ga-cuda9.2/libnccl2_2.3.7-1+cuda9.2_amd64.deb
/var/nccl-repo-2.3.7-ga-cuda9.2/libnccl-dev_2.3.7-1+cuda9.2_amd64.deb
luhui@luhui-System-Product-Name:~/Downloads$

**Comment by huillll** [comment]
安装还是出问题，我提交到https://github.com/PaddlePaddle/models/issues/2505
 
------------------
此致！
  
                敬礼！
  
  
                                                                 
   
      


 




------------------ 原始邮件 ------------------
发件人: "Jiabin Yang"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午2:25
收件人: "PaddlePaddle/models"<models@noreply.github.com>; 
抄送: "风吹雪m"<2257878821@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [PaddlePaddle/models] 运行自动Killed (#2505)




这个问题应该是没有正确安装nccl，您可以参考nvidia官方网站安装nccl

**Comment by huillll** [comment]
https://developer.nvidia.com/compute/machine-learning/nccl/secure/v2.3/prod3/nccl-repo-ubuntu1604-2.3.7-ga-cuda9.2_1-1_amd64.deb

**Comment by JiabinYang** [comment]
这是因为nccl需要您的个人账户登录才能下载，您可以参考[nvidia官方网站](https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html)安装nccl：
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/22361972/60080229-0cde5f80-9762-11e9-8c14-fa54f08e1e83.png">

**Comment by huillll** [comment]
python3 train.py \
       --model=SE_ResNeXt50_32x4d \
       --use_gpu=False \
       --batch_size=4 \
       --total_images=31378 \
       #--total_images=4493 \
       --class_dim=61 \
       --image_shape=3,224,224 \
       --model_save_dir=output/ \
       --with_mem_opt=True \
       --lr_strategy=cosine_decay \
       --lr=0.1 \
       --num_epochs=200 \
       --l2_decay=1.2e-4 \
      >log_SE_ResNeXt50_32x4d.txt 2>&1 &
cpu版本训练，几次，就Killed
/home/luhui/longye/trainingset/images/16f4ae2e-0592-4a9b-ba7d-df9db0cc04fc___RS_HL_7688.JPG 0
Pass 0, trainbatch 0, loss 6.93312,                             acc1 0.00000, acc5 0.00000, lr 0.10000, time 10.50 sec
Pass 0, trainbatch 10, loss 6.47955,                             acc1 0.12500, acc5 0.18750, lr 0.10000, time 4.35 sec
Pass 0, trainbatch 20, loss 5.60632,                             acc1 0.06250, acc5 0.25000, lr 0.10000, time 4.43 sec
Pass 0, trainbatch 30, loss 4.71244,                             acc1 0.12500, acc5 0.31250, lr 0.10000, time 4.35 sec
Pass 0, trainbatch 40, loss 4.53608,                             acc1 0.12500, acc5 0.50000, lr 0.10000, time 17.37 sec
Killed

**Comment by huillll** [comment]
top - 20:29:07 up  1:06,  1 user,  load average: 0.34, 0.12, 0.83
Tasks: 231 total,   1 running, 182 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.9 us,  1.7 sy,  0.0 ni, 74.3 id, 20.1 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16365532 total, 14391212 free,  1038356 used,   935964 buff/cache
KiB Swap:  2097148 total,  1568640 free,   528508 used. 14939204 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                   
  902 root      20   0  327452  49196  40776 S   7.6  0.3   0:18.05 /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/1000/gdm/Xauthority + 
 4038 luhui     20   0  976856 168064  15072 S   7.6  1.0   0:08.77 /opt/teamviewer/tv_bin/TeamViewer_Desktop                                 
 1134 root      20   0 1385816  37032   6008 S   5.0  0.2   0:11.34 /opt/teamviewer/tv_bin/teamviewerd -d                                     
 1125 luhui     20   0 4039048 188840  69476 S   1.7  1.2   0:56.57 /usr/bin/gnome-shell                                                      
  906 root     -51   0       0      0      0 S   0.7  0.0   0:09.56 [irq/126-nvidia]                                                          
 2182 luhui     20   0  662556  27736  19360 S   0.7  0.2   0:05.52 /usr/lib/gnome-terminal/gnome-terminal-server                             
    8 root      20   0       0      0      0 I   0.3  0.0   0:02.22 [rcu_sched]                                                               
  961 luhui     20   0  289628  18456  12884 D   0.3  0.1   0:00.93 /usr/bin/fcitx                                                            
 1181 luhui     20   0 2250028 117528  76616 S   0.3  0.7   0:05.82 /opt/teamviewer/tv_bin/TeamViewer                                         
 1604 luhui     20   0  494528   6564   5252 S   0.3  0.0   0:00.08 /usr/lib/gnome-settings-daemon/gsd-xsettings                              
 1606 luhui     20   0  428388   8080   5496 S   0.3  0.0   0:00.09 /usr/lib/gnome-settings-daemon/gsd-wacom                                  
 1611 luhui     20   0  343524   5524   4596 D   0.3  0.0   0:00.06 /usr/lib/gnome-settings-daemon/gsd-clipboard                              
 1624 luhui     20   0  497948   6632   5484 S   0.3  0.0   0:00.07 /usr/lib/gnome-settings-daemon/gsd-keyboard                               
 1989 root      20   0  560460    316      0 S   0.3  0.0   0:00.59 /usr/lib/fwupd/fwupd                                                      
 3327 root      20   0       0      0      0 I   0.3  0.0   0:00.21 [kworker/1:0]                                                             
 3332 luhui     20   0 2343796 303116 165264 S   0.3  1.9   0:24.24 /usr/lib/firefox/firefox -new-window                                      
 3686 luhui     20   0 1686304 189516 133064 S   0.3  1.2   0:16.88 /usr/lib/firefox/firefox -contentproc -childID 4 -isForBrowser -prefsLen+ 
 3924 luhui     20   0   51384   4432   3708 R   0.3  0.0   0:07.38 top -c                                                                    
    1 root      20   0  160092   5128   3620 S   0.0  0.0   0:02.04 /sbin/init splash

**Comment by huillll** [comment]
total        used        free      shared  buff/cache   available
Mem:            15G        1.0G         13G         56M        914M         14G
Swap:          2.0G        515M        1.5G

**Comment by huillll** [comment]
GPU版本，CPU占用达到这么多。PC 内存16G啊
```
top - 23:17:15 up  1:24,  1 user,  load average: 2.68, 4.44, 4.18
Tasks: 214 total,   2 running, 162 sleeping,   2 stopped,   1 zombie
%Cpu(s): 19.2 us,  6.5 sy,  0.0 ni, 60.5 id, 13.6 wa,  0.0 hi,  0.2 si,  0.0 s
KiB Mem : 16365832 total,   542336 free, 15602448 used,   221048 buff/cache
KiB Swap: 16715772 total, 14180608 free,  2535164 used.   448788 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6699 luhui     20   0 35.002g 0.014t 114916 R 126.7 92.3  37:32.70 python3 +
  944 root      20   0  295996  24384  18140 S  33.3  0.1   3:41.15 /usr/lib+
 2444 luhui     20   0  974080  54508   4080 S   6.7  0.3   2:52.99 /opt/tea+
    1 root      20   0  185508    328     28 S   0.0  0.0   0:01.03 /sbin/in+
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [kthread+
```

**Comment by heavengate** [comment]
使用GPU版本跑模型，op在GPU上跑，数据从本地读入，还有数据预处理，image_augment都是在CPU上完成的，这些是需要消耗CPU和内存的

**Comment by huillll** [comment]
training datea 3.5G
my pc memory 16G, %MEM > 90%
why

**Comment by heavengate** [comment]
> training datea 3.5G
> my pc memory 16G, %MEM > 90%
> why

内存使用和数据集大小没有关系，读入数据之后会做一系列的预处理，augment，缓存，这些都会消耗内存，运行中稳定消耗内存是正常的

**Comment by huillll** [comment]
GPU训练，CPU占用也高啊

**Comment by heavengate** [comment]
yolov3这种一阶段的检测器对于图像增强image_augment的要求很高，图像预处理流程非常复杂，程序中默认起了8个reader进程来读数据和预处理，不然的话会导致因数据读取较慢数据而影响训练速度，这是正常现象，如果你不希望CPU使用率高的话可以指定--use_multiprocess=Fasle来关闭多进程reader，但是不建议

**Comment by JiabinYang** [comment]
用户超过3个月没有回复，先行关闭
