### ISSUE TITLE
window上image_classification训练报错

### ISSUE THREAD

**Issue by JiaXiao243** [PaddlePaddle/models#2511]
在window机器上，paddle==1.5, 在PaddleCV\image_classification目录，执行python train.py --model=AlexNet --num_epochs=1  --batch_size 4，对AlexNet模型进行训练，报错信息如下:
![image](https://user-images.githubusercontent.com/37854899/60001944-3764e580-969a-11e9-822c-0e4bfa8f4487.png)

**Comment by wopeizl** [comment]
看起来是读取有问题

**Comment by kolinwei** [comment]
@shippingwang 看看

**Comment by cuicheng01** [comment]
图片没有读进来

**Comment by qingqing01** [comment]
@JiaXiao243 会和图片路径有关系吗？

**Comment by JiaXiao243** [comment]
图片路径设置应该是正确的~
