### ISSUE TITLE
图像分类InceptionV4偶尔会报illegal memory access

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2523]
在paddle1.5分支下，图像分类InceptionV4偶尔会报illegal memory access，截图如下：
Pass 0, trainbatch 470, loss 6.65145,                             acc1 0.00391, acc5 0.01953, lr 0.10000, time 0.47 sec
F0624 09:12:36.741020 50191 device_context.cc:333] cudaStreamSynchronize an illegal memory access was encountered errno:77
*** Check failure stack trace: ***
F0624 09:1F:36.74102662  50194    9:device_context.cc:127336cudaStreamSynchronize .741029egal memory access was encountered errno:7750180 all_reduce_op_handle.cc:73] cudaStreamSynchronize an illegal memory access was encountered
*** Check failure stack trace: ***
F0624 09:1F:36.74102662  50194    9:device_context.cc:127336cudaStreamSynchronize .741029egal memory access was encountered errno:7750180 all_reduce_op_handle.cc:73] cudaStreamSynchronize an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7f7a737c777d  google::LogMessage::Fail()
    @     0x7f7a737c777d  google::LogMessage::Fail()
    @     0x7f7a737c777d  google::LogMessage::Fail()
    @     0x7f7a737cb22c  google::LogMessage::SendToLog()
    @     0x7f7a737cb22c  google::LogMessage::SendToLog()
    @     0x7f7a737cb22c  google::LogMessage::SendToLog()
    @     0x7f7a737c72a3  google::LogMessage::Flush()
    @     0x7f7a737c72a3  google::LogMessage::Flush()
    @     0x7f7a737c72a3  google::LogMessage::Flush()
    @     0x7f7a737cc73e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7a737cc73e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7a737cc73e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7a7544a2ed  _ZNSt17_Function_handlerIFvvEZNK6paddle8platform17CUDADeviceContext4WaitEvEUlvE_E9_M_invokeERKSt9_Any_data

**Comment by shippingwang** [comment]
same as [paddle #18464](https://github.com/PaddlePaddle/Paddle/issues/18464)

**Comment by qingqing01** [comment]
麻烦再在develop上验证下

**Comment by xiegegege** [comment]
好的～

**Comment by xiegegege** [comment]
develop下的报错：
An exception was thrown!
 Invoke operator conv2d error.
Python Callstacks:
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1776, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2283, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/inception_v4.py", line 94, in conv_bn_layer
    name=name)
  File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/inception_v4.py", line 107, in inception_stem
    data, 32, 3, stride=2, act='relu', name="conv1_3x3_s2")
  File "/ssd1/xiege/model_8.1/models/PaddleCV/image_classification/models/inception_v4.py", line 45, in net
    x = self.inception_stem(input)
  File "train.py", line 239, in net_config
    out = model.net(input=image, class_dim=class_dim)
  File "train.py", line 307, in build_program
    avg_cost, acc_top1, acc_top5 = net_config(image, model, args, label=label, is_train=is_train)
  File "train.py", line 365, in train
    args=args)
  File "train.py", line 612, in main
    train(args)
  File "train.py", line 616, in <module>
    main()
C++ Callstacks:
CUDNN_STATUS_INTERNAL_ERROR at [/ssd1/xiege/Paddle_8.1/Paddle/paddle/fluid/platform/device_context.cc:217]
