### ISSUE TITLE
slurm分布式训练使用nccl2会卡在run

### ISSUE THREAD

**Issue by yxzero** [PaddlePaddle/models#2550]
![image](https://user-images.githubusercontent.com/5461637/60102934-3ebaea80-9791-11e9-8a32-c9179b12a045.png)

使用model里面的transformer在集群训练时，发现任务会卡在exe.run，是否现在分布式训练方式变了，需要改成下图paddle文档上的样子么？
![image](https://user-images.githubusercontent.com/5461637/60102925-38c50980-9791-11e9-9f81-9a3a9d64e797.png)

并且集群gpu使用率是40%
![image](https://user-images.githubusercontent.com/5461637/60103035-73c73d00-9791-11e9-9cd1-58f736639269.png)

附slurm任务：http://yq01-sys-hic-v100-box-a225-0015.yq01.baidu.com:8388/v1/slurmjobs/47690/workspace

**Comment by gavin1332** [comment]
是的，需要使用paddle文档上的nccl2配置做初始化才行

**Comment by gavin1332** [comment]
我看你train.py里也有手工写的相关操作，需要移除。同时，build_trategy需要制定allreduce策略：
‘build_strategy.reduce_strategy = fluid.BuildStrategy().ReduceStrategy.AllReduce’

**Comment by yxzero** [comment]
你好，改了之后还是不行
目前我注掉 exec_strategy.use_experimental_executor = True 就能训了

**Comment by gavin1332** [comment]
嗯，因现在分布式训练各模型配置较为混乱，随着时间推移，存在开关新增和弃用的情况，目前缺乏相关的整理。我们正在整理多机训练的建议配置，下个月会提供出来供大家参考
