### ISSUE TITLE
利用stnet模型训练ufc-101数据出现过拟合，没有使用预训练模型。

### ISSUE THREAD

**Issue by stard** [PaddlePaddle/models#2563]
尝试调整学习速率、权重衰减系数、增加了剪切旋转视频输入的帧数据，最终得到的验证集合和训练集的准确率相差很大。
迭代到26代的时候已经相差50%啦。
+ End pass: 26, train_loss: 1.074, train_acc1: 0.705, train_acc5: 0.926
+ End pass: 26, test_loss: 11.127, test_acc1: 0.285, test_acc5: 0.515

+ End pass: 59, train_loss: 0.066, train_acc1: 0.983, train_acc5: 0.999
+ End pass: 59, test_loss: 7.522, test_acc1: 0.432, test_acc5: 0.676

辛苦看下有什么方法可以解决以上过拟合的情况。

**Comment by SunGaofeng** [comment]
跟stnet的原作者，一起建了个群，在讨论中

**Comment by stard** [comment]
loss出现上涨时，将学习速率调更小后解决。

**Comment by gtgtgt1117** [comment]
> 尝试调整学习速率、权重衰减系数、增加了剪切旋转视频输入的帧数据，最终得到的验证集合和训练集的准确率相差很大。
> 迭代到26代的时候已经相差50%啦。
> 
> * End pass: 26, train_loss: 1.074, train_acc1: 0.705, train_acc5: 0.926
> * End pass: 26, test_loss: 11.127, test_acc1: 0.285, test_acc5: 0.515
> * End pass: 59, train_loss: 0.066, train_acc1: 0.983, train_acc5: 0.999
> * End pass: 59, test_loss: 7.522, test_acc1: 0.432, test_acc5: 0.676
> 
> 辛苦看下有什么方法可以解决以上过拟合的情况。

Hello,想知道你是怎么训练的,我想先试一下能否训练,我用了一个3个pkl文件.然后报了这个错,始终不是很明白.希望您能指导一下
[INFO: train_utils.py:  113]: No iteration was executed, please check the data reader

**Comment by gtgtgt1117** [comment]
Thank you for your reply! This is my email 18801046982@163.com
