### ISSUE TITLE
cycle_gan  train.py  训练报错

### ISSUE THREAD

**Issue by hardphp** [PaddlePaddle/models#2591]
我的环境
padddle 版本 1.4.1
python版本：3.7
系统：centos7.4   两核4G 
cpu 模式训练，报错如下，烦请大神给看下
![2569383d19cefb642b75c2d4d62cac5](https://user-images.githubusercontent.com/8262664/60319984-e52e0800-99aa-11e9-9f60-28dbeca1b2ce.png)
![ea8856bbb8e89d85f232d0c4096fd41](https://user-images.githubusercontent.com/8262664/60319985-e5c69e80-99aa-11e9-960b-e7a25c8f0804.png)

**Comment by wangguibao** [comment]
Hi，貌似batch数据里sample个数是2，网络目前只支持单样本，你改下feed数据试试

**Comment by JiaXiao243** [comment]
设置一下这个就可以了:export CPU_NUM=1

**Comment by wangguibao** [comment]
该issue已超过一个月，先关闭。如有需要可随时重新open
