### ISSUE TITLE
Paddle下面的LAC和baidu/lac的区别是什么？ c++版本需要自己根据paddle的接口去实现吗？

### ISSUE THREAD

**Issue by miaozx** [PaddlePaddle/models#2606]
Paddle下面的LAC和baidu/lac的区别是什么？ c++版本需要自己根据paddle的接口去实现吗？

**Comment by wangguibao** [comment]
Paddle下的LAC更新一些，推荐用PaddlePaddle下的LAC

预测的话需要自己根据paddle预测库接口实现

**Comment by wangguibao** [comment]
该issue已超过1个月，先关闭了，如有需要可随时重新open
