### ISSUE TITLE
用的是哪个词典

### ISSUE THREAD

**Issue by githubusr1** [PaddlePaddle/models#2615]
请问一下，OCR模型readme说明中有如下文字，文中说的词典在哪下载，我看了一下80是Q，但是ASII码Q是81，所以猜不出这个词典是哪个，请提供哪里下载。这个词典也应该包括中文。
----------------------------------------------------------------------------------------------------
在训练集中，每张图片对应的label是汉字在词典中的索引。 图1 对应的label如下所示：

80,84,68,82,83,72,78,77,68,67
在上边这个label中，80 表示字符Q的索引，67 表示英文字符D的索引。

**Comment by gavin1332** [comment]
辛苦贴一下你使用的ocr模型的路径

**Comment by githubusr1** [comment]
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ocr_recognition

**Comment by gavin1332** [comment]
@wanghaoshuang 同样是ocr相关问题，辛苦解答

**Comment by wanghaoshuang** [comment]
你好，因为版权问题，我们在models repo下release的是自动生成的英文数据。没有release对应的字典。如果需要，你可以先从train dataset的label里统计出来字典。
@githubusr1
