### ISSUE TITLE
lstm 第一个输出参数

### ISSUE THREAD

**Issue by wshongCola** [PaddlePaddle/models#2619]
我在自己建立的语言模型中,使用了fluid.layers.lstm模块,但是模块的第一个输出和文档描述不同
![Screenshot from 2019-06-25 20-42-59](https://user-images.githubusercontent.com/29620676/60393279-71743280-9b45-11e9-86ff-bde7be402980.png)
![Screenshot from 2019-06-25 20-43-23](https://user-images.githubusercontent.com/29620676/60393280-720cc900-9b45-11e9-99d9-125587ae4118.png)
![Screenshot from 2019-06-25 20-43-39](https://user-images.githubusercontent.com/29620676/60393281-720cc900-9b45-11e9-8cd7-fcd4754bef1f.png)
第一个输出和模型的输入是同一维度的,但是我觉得我的模型使用以及变量都没有问题,请问是哪里出了问题?

**Comment by Xreki** [comment]
您好，我按照您的代码试了一下，得到的结果和您的一样。请问您这个代码能正常训练吗？

另外，issue里面能否直接贴代码，不要截图，这样方便我们复现，谢谢~

**Comment by phlrain** [comment]
这个好像触发了一个bug，当input_size 和 hidden_size 不一致的时候，rnn_out的 shape有问题，我们会马上修复一下

**Comment by wshongCola** [comment]
好的，非常感谢

在2019-07-01 14:29:08，Hongyu Liunotifications@github.com写道：

这个好像触发了一个bug，当input_size 和 hidden_size 不一致的时候，rnn_out的 shape有问题，我们会马上修复一下

**Comment by wshongCola** [comment]
您好，感谢您的测试和回复。现在代码还不能正常使用。以后提交issue我会注意的。发自我的华为手机-------- 原始邮件 --------主题：Re: [PaddlePaddle/models] lstm 第一个输出参数 (#2619)发件人：Yiqun Liu 收件人：PaddlePaddle/models 抄送：biebiewang ,Author 您好，我按照您的代码试了一下，得到的结果和您的一样。请问您这个代码能正常训练吗？

另外，issue里面能否直接贴代码，不要截图，这样方便我们复现，谢谢~

**Comment by phlrain** [comment]
https://github.com/PaddlePaddle/Paddle/pull/18492
