### ISSUE TITLE
真是垃圾！不负垃圾百度之名！

### ISSUE THREAD

**Issue by intgogo** [PaddlePaddle/models#2638]
先说明下，最近刚发现百度这个开源项目，乍一看，CV的各种检测算法、分类模型、分割、文字识别、甚至是YOLO v3的支持，都让我心跳加速，恨没有早发现这个开源项目。怀着激动的心情，我开始了这段旅途~

第一步，自然是源码构建，立马就躺了一坑。因为我习惯是在build目录下，再创建debug和release目录用来分开构建。岂料，死活就是构建不成功，报个什么snappy头文件的错误，来这里找答案也是毫无线索。倒腾来倒腾去，最后竟然是因为这里只能在build目录下进行构建，你们说傻不傻逼的！

第二步，今天测试models/PaddleCV/ocr_recognition，ocr在github上开源的都比较零碎，质量不能说很高，比较好点的都是基于crnn+ctc的实现，但是在这里，我看到attention的实现貌似准确度要高不少，我果断的就先下载过来按照说明进行试验一番。结果立马又是一个坑，报个错`paddle.fluid.core_avx.EnforceNotMet: Invoke operator im2sequence error`，也是倒腾来倒腾去，找不到答案。最后竟然发现是因为图片必须是48像素高的，尼玛的！简直弱智了！

开源不是这么玩的，这些小问题，对于我们新接触的人来说，就是一个个的坎，对于你们这些作者而言就是一句话、两行代码的事情。

如果没有这种态度，还开源尼玛啊！早点滚蛋，不然各种浪费大家时间，你们不是在帮助这个世界，而是在阻碍世界的进展。一如曾经的微软！

**Comment by shippingwang** [comment]
你好，首先感谢你对paddlepaddle的关注，现在PaddleCV支持了更多更优秀的算法模型，

- 在源码构建上，建议参照[编译安装](http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/compile/fromsource.html) 官方流程，我们也在支持更多的安装形式。

- 对于易用性方面，我们会优化报错信息让用户更快的找到解决方案，对于这次出现“坎”的CV方向，我们也在抓紧建设。

让新用户更顺畅的上手paddlepaddle一直是我们努力追求的。
开源项目靠大家的奉献，感谢你的建议。

**Comment by Xreki** [comment]
> 第一步，自然是源码构建，立马就躺了一坑。因为我习惯是在build目录下，再创建debug和release目录用来分开构建。岂料，死活就是构建不成功，报个什么snappy头文件的错误，来这里找答案也是毫无线索。倒腾来倒腾去，最后竟然是因为这里只能在build目录下进行构建，你们说傻不傻逼的！

您是不是哪里操作不对？我们从来没有限定只能在build目录下进行构建。我个人的工作目录是`Paddle`，构建目录在`Paddle/build_paddle`，生成的二进制文件在`Paddle/build_paddle/build_docker`。

**Comment by githubusr1** [comment]
我试过外国人的github下项目，几乎没有一次成功的，也是很多很多问题，为啥对百度说的那么难听，给老外发issue,过几个星期才可能答复你，甚至没有答复，百度回复还是很快的，服务很好。其实还不是过去一两百年中国受到太多的外国的凌辱导致的的内心的民族自卑在作怪。我不是百度公司的。

**Comment by kagome112** [comment]
@intgogo 您好，非常感谢您对飞桨（PaddlePaddle）的关注，抱歉我们给您带来了不好的使用体验，我们非常重视每个用户的提出的问题和建议
针对您遇到的问题，研发团队进行了分析，有以下结论：
1.源码编译的问题
考虑到源码编译对于大部分用户来说需要有一定的门槛（会有较多预想的不到的问题），为了最大程度保证用户能够编译成功，我们提供了一个官方建议方法，即我们在官方文档中建议的方式：在build文件夹之下进行编译，我们之后会在文档中进行更加详细的说明，避免用户产生疑惑
针对您编译不成功的问题，我们的研发同学未能进行复现，如果条件允许，我们希望能与您取得联系（您可以直接同我们的产品同学联系，微信：ifyoucare，或者留下您的手机、微信等联系方式），共同复现从而帮助我们更彻底的解决此问题
2.「attention ocr infer报错」问题
该问题是由于OCR Attention model开发之初，基于业务需求使用了48像素的数据进行训练和预测，所以默认会有这个要求，但实际我们是支持其他像素尺寸的，这个信息没有在文档和报错信息中有很好的体现
所以我们的研发团队会从以下两点进行改进的：
-在Github使用文档中增加【如何使用自定义数据进行训练和预测】的说明  
-当使用用户自定义的数据进行训练预测遇到了错误，报错信息中会明确指明错误并且给出有效的解决方案。
以上两点我们将在未来的1～2周内完成，到时会第一时间通知您解决进展

我们再次对产品给您造成的不好使用体验表示抱歉，同时欢迎您继续向我们提出改进建议
为了能够更加及时的对您的使用问题进行反馈，我们诚挚的邀请你加入官方用户交流群（432676488），群中有研发同学7*24小时及时跟进您的使用问题。
再次感谢您的建议，我们期待与您一起将飞桨（PaddlePaddle）做的更好

**Comment by intgogo** [comment]
@githubusr1 百度开源的paddle单从代码编程、功能涵盖面来看，确实属于国内佳品，也是因为这点我才对paddle跃跃欲试。我上面说得难听，出发点是因为遇到的两个问题，从发现到解决，实在感觉不值得（第一坑花了差不多1天时间，第二坑花了一上午）。
另外，百度搜索的盈利模式，给国人留下了不可磨灭的痛苦，特别对于我们程序猿而言。
并不完全是因为“过去一两百年中国受到太多的外国的凌辱导致的的内心的民族自卑在作怪”，而是作为国家担当的领头羊，竟然也在引领着“作恶”潮流，如何让我们这些内心深处尚怀良知的小程序猿，依然信任、依然自强呢？

**Comment by intgogo** [comment]
@Xreki @kagome112 
不是基于docker的构建，而是直接构建。系统环境centos 7

```
[root@ylzl release]# cmake ../..
-- Found Paddle host system: centos, version: 
-- Found Paddle host system's CPU: 24 cores
-- CXX compiler: /usr/local/bin/c++, version: GNU 4.8.5
-- C compiler: /usr/local/bin/cc, version: GNU 4.8.5
-- AR tools: /usr/bin/ar
-- Do not have AVX2 intrinsics and disabled MKL-DNN
CMake Warning at /usr/local/share/cmake-3.13/Modules/FindProtobuf.cmake:496 (message):
  Protobuf compiler version 3.1.0 doesn't match library version 3.6.1
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:18 (FIND_PACKAGE)
  CMakeLists.txt:138 (include)


-- Protobuf protoc executable: /root/lilw/Paddle/build/release/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /root/lilw/Paddle/build/release/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /root/lilw/Paddle/build/release/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /root/lilw/Paddle/build/release/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- BLAS library: /root/lilw/Paddle/build/release/third_party/install/openblas/lib/libopenblas.a
-- BLAS Include: /root/lilw/Paddle/build/release/third_party/install/openblas/include
-- BOOST_TAR: boost_1_41_0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /root/lilw/Paddle/build/release/third_party/install/warpctc/lib/libwarpctc.so
-- Current cuDNN header is /usr/local/cuda/include/cudnn.h. Current cuDNN version is v7.4. 
-- CUDA detected: 9.0
-- Added CUDA NVCC flags for: sm_61 sm_70
-- add dgc lib.
-- Ccache is founded, use ccache to speed up compile.
-- Paddle version is 0.0.0
CMake Warning at CMakeLists.txt:249 (message):
  On inference mode, will take place some specific optimization.  Turn on the
  ON_INFER flag when building inference_lib only.


-- add pass graph_to_program_pass base
-- add pass graph_viz_pass base
-- add pass lock_free_optimize_pass base
-- add pass fc_fuse_pass inference
-- add pass attention_lstm_fuse_pass inference
-- add pass infer_clean_graph_pass inference
-- add pass fc_lstm_fuse_pass inference
-- add pass embedding_fc_lstm_fuse_pass inference
-- add pass fc_gru_fuse_pass inference
-- add pass seq_concat_fc_fuse_pass inference
-- add pass multi_batch_merge_pass base
-- add pass conv_bn_fuse_pass inference
-- add pass seqconv_eltadd_relu_fuse_pass inference
-- add pass seqpool_concat_fuse_pass inference
-- add pass repeated_fc_relu_fuse_pass inference
-- add pass squared_mat_sub_fuse_pass inference
-- add pass is_test_pass base
-- add pass conv_elementwise_add_act_fuse_pass inference
-- add pass conv_elementwise_add2_act_fuse_pass inference
-- add pass conv_elementwise_add_fuse_pass inference
-- add pass conv_affine_channel_fuse_pass inference
-- add pass transpose_flatten_concat_fuse_pass inference
-- add pass identity_scale_op_clean_pass base
-- add pass sync_batch_norm_pass base
-- add pass runtime_context_cache_pass base
-- add pass quant_conv2d_dequant_fuse_pass inference
-- add pass fillconstant_elementwisemul_fuse inference
-- add pass shuffle_channel_detect_pass inference
-- add pass delete_quant_dequant_op_pass inference
-- commit: 47e2ef3
-- branch: develop
-- WARNING: This is just a warning for publishing release.
      You are building AVX version without NOAVX core.
      So the wheel package may fail on NOAVX machine.
      You can add -DFLUID_CORE_NAME=/path/to/your/core_noavx.* in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local machine.
-- Configuring done
```


```
[root@ylzl release]# make -j 20
[  1%] Built target extern_gflags
[  1%] Built target extern_xbyak
[  1%] Built target extern_gtest
[  1%] Built target extern_warpctc
[  1%] Built target extern_xxhash
[  1%] Performing update step for 'extern_dgc'
[  1%] Built target extern_eigen3
[  2%] Built target extern_pybind
[  2%] Built target extern_openblas
[  2%] Built target extern_snappy
[  2%] Built target extern_dlpack
[  2%] Built target extern_zlib
[  2%] Built target extern_cub
[  3%] Built target profiler_py_proto_init
[  3%] Built target extern_glog
[  3%] Built target extern_boost
[  3%] Built target extern_threadpool
[  3%] Built target framework_py_proto_init
[  3%] Built target extern_gzstream
[  3%] Built target extern_protobuf
Scanning dependencies of target stringpiece
Scanning dependencies of target engine
Scanning dependencies of target version
Scanning dependencies of target zero_copy_tensor_dummy
Scanning dependencies of target imperative_profiler
Scanning dependencies of target memory_block
Scanning dependencies of target pretty_log
Scanning dependencies of target paddle_pass_builder
[  3%] Building CXX object paddle/fluid/imperative/CMakeFiles/imperative_profiler.dir/profiler.cc.o
[  3%] Building CXX object paddle/fluid/framework/CMakeFiles/version.dir/version.cc.o
[  3%] Performing build step for 'extern_snappystream'
Scanning dependencies of target cblas
Scanning dependencies of target boost
Scanning dependencies of target framework_proto
[  3%] Building CXX object paddle/fluid/string/CMakeFiles/pretty_log.dir/pretty_log.cc.o
Copy generated python proto into directory paddle/fluid/proto/profiler.
Scanning dependencies of target timer
Scanning dependencies of target data_feed_proto
[  3%] Building CXX object paddle/fluid/imperative/CMakeFiles/engine.dir/engine.cc.o
[  3%] Building CXX object paddle/fluid/inference/api/CMakeFiles/paddle_pass_builder.dir/paddle_pass_builder.cc.o
[  3%] Built target profiler_py_proto
[  3%] Building CXX object paddle/fluid/platform/CMakeFiles/timer.dir/timer.cc.o
[  3%] Building C object CMakeFiles/cblas.dir/cblas_dummy.c.o
[  3%] Building CXX object paddle/fluid/string/CMakeFiles/stringpiece.dir/piece.cc.o
[  3%] Building CXX object paddle/fluid/memory/detail/CMakeFiles/memory_block.dir/memory_block.cc.o
Scanning dependencies of target imperative_flag
[  3%] Built target trainer_py_proto
Scanning dependencies of target activation_functions
Scanning dependencies of target header
Scanning dependencies of target enforce
[  3%] Building CXX object paddle/fluid/inference/api/details/CMakeFiles/zero_copy_tensor_dummy.dir/zero_copy_tensor_dummy.cc.o
[  3%] Building C object CMakeFiles/boost.dir/boost_dummy.c.o
[  3%] Building CXX object paddle/fluid/framework/CMakeFiles/data_feed_proto.dir/data_feed.pb.cc.o
-- extern_dgc update command succeeded.  See also /root/lilw/Paddle/build/release/extern_dgc-prefix/src/extern_dgc-stamp/extern_dgc-update-*.log
Scanning dependencies of target async_executor_proto
[  3%] No configure step for 'extern_dgc'
[  3%] Building CXX object paddle/fluid/framework/CMakeFiles/framework_proto.dir/framework.pb.cc.o
[  3%] Building CXX object paddle/fluid/framework/CMakeFiles/async_executor_proto.dir/data_feed.pb.cc.o
[  3%] Performing build step for 'extern_dgc'
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  3%] Building CXX object paddle/fluid/imperative/CMakeFiles/imperative_flag.dir/flags.cc.o
[  3%] Building CXX object paddle/fluid/platform/CMakeFiles/enforce.dir/enforce.cc.o
[  3%] Building CXX object paddle/fluid/operators/math/detail/CMakeFiles/activation_functions.dir/avx_functions.cc.o
[  3%] Building CXX object paddle/fluid/recordio/CMakeFiles/header.dir/header.cc.o
[ 16%] Building CXX object CMakeFiles/snappystream.dir/src/osnappystream.cpp.o
[  3%] Performing install step for 'extern_dgc'
[  3%] Completed 'extern_dgc'
[  4%] Built target extern_dgc
[ 33%] Building CXX object CMakeFiles/snappystream.dir/src/isnappystream.cpp.o
[  4%] Linking C static library libboost.a
[  4%] Linking C static library libcblas.a
[  4%] Built target boost
[  4%] Building CXX object paddle/fluid/memory/detail/CMakeFiles/memory_block.dir/memory_block_desc.cc.o
[  4%] Built target cblas
Copy generated python proto into directory paddle/fluid/proto.
[  4%] Building CXX object paddle/fluid/memory/detail/CMakeFiles/memory_block.dir/meta_cache.cc.o
[  4%] Linking CXX static library libimperative_flag.a
/root/lilw/Paddle/build/release/third_party/snappy_stream/src/extern_snappystream/src/isnappystream.cpp:12:20: fatal error: snappy.h: No such file or directory
 #include "snappy.h"
                    ^
compilation terminated.
[  4%] Built target framework_py_proto
[  4%] Linking CXX static library libengine.a
Scanning dependencies of target string_helper
[  5%] Linking CXX static library libzero_copy_tensor_dummy.a
/root/lilw/Paddle/build/release/third_party/snappy_stream/src/extern_snappystream/src/osnappystream.cpp:11:20: fatal error: snappy.h: No such file or directory
 #include "snappy.h"
                    ^
compilation terminated.
[  5%] Building CXX object paddle/fluid/string/CMakeFiles/string_helper.dir/string_helper.cc.o
[  5%] Built target zero_copy_tensor_dummy
[  5%] Built target imperative_flag
[  6%] Linking CXX static library libmemory_block.a
[  6%] Linking CXX static library libimperative_profiler.a
[  6%] Built target engine
make[5]: *** [CMakeFiles/snappystream.dir/src/isnappystream.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
[  6%] Built target imperative_profiler
[  6%] Linking CXX static library libversion.a
[  6%] Linking CXX static library libpretty_log.a
[  6%] Linking CXX static library libtimer.a
make[5]: *** [CMakeFiles/snappystream.dir/src/osnappystream.cpp.o] Error 1
make[4]: *** [CMakeFiles/snappystream.dir/all] Error 2
```

**Comment by kagome112** [comment]
@githubusr1  非常感谢您对飞桨（PaddlePaddle）的支持。飞桨正在快速迭代中，尚有多易用性问题待解决，我们希望和中国的开发者共同努力，打造出世界级的深度学习框架。欢迎和鼓励大家持续向我们反馈使用问题，帮助我们不断优化产品，诚挚的邀请你加入官方用户交流QQ群（432676488），能够与我们更方便的交流。

**Comment by sanfengliu** [comment]
借楼，我想发表一下我的观点。
我用paddlepaddle也已经两个月了，刚一开始跟楼主的观点一样。发现这么多开源的项目像发现宝藏一样，终于觉得说，中国BAT企业上升到了一个新高度。
开始集成验证一下好不好用吧(填坑的开始).....
语音识别因为场景复杂，识别最困难，验证工业级水平再好不过。就先从DeepSpeech2开始。因为我是想集成在tornado上的，看了很多遍README_cn，但是每次看到建议用docker，我就有一种不好的预感，这个坑可能很深。
1.（只支持Python 2.7）  小意思，毕竟python2.7 跟python3.X没什么大差别，忽略不算事
2.（PaddlePaddle最新版本(请参考安装指南)）  巨坑，2017年的项目怎么可能用2019年的最新版本也可以，毕竟只支持python2.7。踩坑多年心里有数，然而就找相应版本。找到相应版本发现，居然项目支持的最高版本和19年的结构上差这么多，19年paddlepaddle最新版本，直接把2年前的结构废掉，进行了整合。怒而尝试:
    尝试1:windows安装paddlepaddle，是怎么安装都会报编译错误。不管是python2,还是python3,安装老paddlepaddle版本还是新padddlepaddle版本都按照文档装不了。没关系，能折腾，为了paddlepaddle把windows改成了linux kali版本(我精于渗透测试开发)，终于安装编译成功，填满。
    尝试2: 用19年paddlepaddle最新版本，集成2年前的应用，发现不行。1.没有任何文档说明，2.官网虽然有版本的接口说明，但对比接口的过程，太痛苦，而且容易出问题。3.虽然有代码能力，但是对于paddlepaddle还是不了解，几天之内很难把项目代码改成最新版本进行验证，遂放弃。
    尝试3:用python2安装paddle老版本，也还是不行,我记得当时还是跑不起来。
    所以现在老老实实用docker跑两年前的项目。
整个尝试过程，从想起来百度还有一个开源人工智能框架到验证语音识别结果，用了两个礼拜。时间无所谓，折腾无所谓，我就是有一点觉得做的不够好就是，如果要推新框架版本，应该要向下兼容以前的项目，假如我今天想了解一下paddlepaddle，或者我有个什么项目，我在github搜到了，我用最新的版本，你告诉我结构变了，最新版跑不了，得用老版本才行，那我会觉得1.这些项目都是基于开源框架的，要么你再推新版本的同时，就应该支持老项目。2.要么你下架老项目，更新后再出2.0。如果不这么做，那我作为一个普通用户，会觉得你兼容性完全不考虑。打个比方有一款APP，5个大功能页，你点击其中一个直接崩溃，然而提示说，你想用这个功能，请去下载2年前的版本，你觉得用户体验会什么样。
    GITHUB虽然不是APP，但是每个项目的成功或者失败也代表了百度，每个版本发布需要像功能上线一样，综合考虑，而不是想上就上，百度不是个人开发者，代表了中国BAT.
    还有楼主我也想说，学习的坑是自己填出来的，填一个坑就是一份收获。不好用，通过代码改好用就行了。跑不起来，多研究研究就跑起来的，毕竟人家轻易不会把跑不起来的放上来。GITHUB不是应用，不会严谨的考虑适配，兼容，BUG什么的，骂人更没必要。

**Comment by intgogo** [comment]
@sanfengliu 有必要解释下我试用paddle的情况。
我开发的一款交通领域的产品(图像检测、分类，文字识别等)，经过半年的努力，使用的算法都是开源精品中的精品（不吹牛，产品已上市，并已成行业标杆），因此比较挑剔，作此尝试也为了更上一层楼；
再者我仅是集成算法，并无算法自研能力，为了达到‘最佳’，同时引入了tensorflow、pytorch、mxnet、darknet等各种框架，打包发布约5G，因此paddle说明书中的各种能力、各种强大，让我着实很想试一试，丢脸的说一句，当时我兴奋得跟身边的伙伴们吹牛逼，终于找到了‘一直寻找的框架’；
结果呢：
原来吹牛逼的不止我一人，还包括闻名天下的百度嘟嘟嘟嘟...

**Comment by adaxi987** [comment]
@sanfengliu 您好，非常感谢您对飞桨（PaddlePaddle）的关注，抱歉我们给您带来了不好的使用体验，我们非常重视每一位用户的提出的问题和建议，针对您遇到的问题，研发团队进行了分析，有以下结论：
1.我们已经在DeepSpeech Repo里的Readme做补充说明，告知当前在使用或之后想要使用DeepSpeech2模型的用户该模型当前的适配环境，目前建议您在Docker容器中运行该项目。之后官方会提供支持飞桨（PaddlePaddle）最新版本的DeepSpeeech模型
2.感谢您对飞桨（PaddlePaddle）的支持，我们也欢迎您届时尝试使用我们基于Paddle最新版本的DeepSpeech2模型，期望您能补充更新使用评价。此外，也诚邀您加入我们飞桨官方技术交流qq群：432676488 ，能够更及时的和我们交互信息，谢谢！

飞桨（PaddlePaddle）开源团队敬上

**Comment by jackaduma** [comment]
入坑ASR，急需一款模型上手，看到百度deepspeech的项目。尤其是质量高的预训练模型，激动万分。
But，代码是废弃的老框架开发，完全没法用。。。。。
docker是gpu的，因为一些环境问题，用不起来。更主要是想研究一下 代码。。。
国外的torch tf 实现的deepspeech的预训练模型都是英文的。。。。
啥时候 能放出来 能用paddle跑起来的代码啊。。。。。。。。！

**Comment by huxianhe0** [comment]
遇到个错误不知道解决先来骂人的喷子，

> 先说明下，最近刚发现百度这个开源项目，乍一看，CV的各种检测算法、分类模型、分割、文字识别、甚至是YOLO v3的支持，都让我心跳加速，恨没有早发现这个开源项目。怀着激动的心情，我开始了这段旅途~
> 
> 第一步，自然是源码构建，立马就躺了一坑。因为我习惯是在build目录下，再创建debug和release目录用来分开构建。岂料，死活就是构建不成功，报个什么snappy头文件的错误，来这里找答案也是毫无线索。倒腾来倒腾去，最后竟然是因为这里只能在build目录下进行构建，你们说傻不傻逼的！
> 
> 第二步，今天测试models/PaddleCV/ocr_recognition，ocr在github上开源的都比较零碎，质量不能说很高，比较好点的都是基于crnn+ctc的实现，但是在这里，我看到attention的实现貌似准确度要高不少，我果断的就先下载过来按照说明进行试验一番。结果立马又是一个坑，报个错`paddle.fluid.core_avx.EnforceNotMet: Invoke operator im2sequence error`，也是倒腾来倒腾去，找不到答案。最后竟然发现是因为图片必须是48像素高的，尼玛的！简直弱智了！
> 
> 开源不是这么玩的，这些小问题，对于我们新接触的人来说，就是一个个的坎，对于你们这些作者而言就是一句话、两行代码的事情。
> 
> 如果没有这种态度，还开源尼玛啊！早点滚蛋，不然各种浪费大家时间，你们不是在帮助这个世界，而是在阻碍世界的进展。一如曾经的微软！

遇到个错误不知道想办法解决却先来骂人的喷子，纯属傻逼

**Comment by huxianhe0** [comment]
> 先说明下，最近刚发现百度这个开源项目，乍一看，CV的各种检测算法、分类模型、分割、文字识别、甚至是YOLO v3的支持，都让我心跳加速，恨没有早发现这个开源项目。怀着激动的心情，我开始了这段旅途~
> 
> 第一步，自然是源码构建，立马就躺了一坑。因为我习惯是在build目录下，再创建debug和release目录用来分开构建。岂料，死活就是构建不成功，报个什么snappy头文件的错误，来这里找答案也是毫无线索。倒腾来倒腾去，最后竟然是因为这里只能在build目录下进行构建，你们说傻不傻逼的！
> 
> 第二步，今天测试models/PaddleCV/ocr_recognition，ocr在github上开源的都比较零碎，质量不能说很高，比较好点的都是基于crnn+ctc的实现，但是在这里，我看到attention的实现貌似准确度要高不少，我果断的就先下载过来按照说明进行试验一番。结果立马又是一个坑，报个错`paddle.fluid.core_avx.EnforceNotMet: Invoke operator im2sequence error`，也是倒腾来倒腾去，找不到答案。最后竟然发现是因为图片必须是48像素高的，尼玛的！简直弱智了！
> 
> 开源不是这么玩的，这些小问题，对于我们新接触的人来说，就是一个个的坎，对于你们这些作者而言就是一句话、两行代码的事情。
> 
> 如果没有这种态度，还开源尼玛啊！早点滚蛋，不然各种浪费大家时间，你们不是在帮助这个世界，而是在阻碍世界的进展。一如曾经的微软！

遇到个错误不知道想办法解决却先来骂人的喷子，纯属傻逼

**Comment by AmadeusSys** [comment]
> @sanfengliu 有必要解释下我试用paddle的情况。
> 我开发的一款交通领域的产品(图像检测、分类，文字识别等)，经过半年的努力，使用的算法都是开源精品中的精品（不吹牛，产品已上市，并已成行业标杆），因此比较挑剔，作此尝试也为了更上一层楼；
> 再者我仅是集成算法，并无算法自研能力，为了达到‘最佳’，同时引入了tensorflow、pytorch、mxnet、darknet等各种框架，打包发布约5G，因此paddle说明书中的各种能力、各种强大，让我着实很想试一试，丢脸的说一句，当时我兴奋得跟身边的伙伴们吹牛逼，终于找到了‘一直寻找的框架’；
> 结果呢：
> 原来吹牛逼的不止我一人，还包括闻名天下的百度嘟嘟嘟嘟...

用人家东西，听人吹几个牛能怎样，自古以来拿人手短，觉得不适合心里骂两句得了，没必要来社区骂街。
什么是开源精神？非要别人把最顶尖最好的免费给你才行吗？请问你分又分享什么出来了呢？您那么牛逼的行业标杆项目咋不开源出来呢？让我们学习学习。
开源是分享，相互学习，不是你项目的垫脚石。
年轻人劝你耗子尾汁。

**Comment by fzl8888** [comment]
典型的又蠢又坏类型

**Comment by intgogo** [comment]
从2019年7月发的这个骂贴，如今又是4年多过去了，这些年发生了一个惊天巨变，就是chatgpt的问世，借此再谈谈。

先说下个人，我是2011年毕业的纯种程序猿，什么水平各位自行脑补。

楼上有人鄙视说，我是因为搞不定坑才开骂，实际上是因为搞定坑的代价让我觉得很不值而破防，因为项目基本信息的缺失，我们新接触的人要填补起来，代价会有多大可想而知，但是对项目开发者而言真的不值一提，有时候或许就是没有真正为我们考虑、真正为开源考虑，但如果是因为项目某个阶段还不完美，那开骂确实是错误的。

另外，当时还有一个原因，就是被百度搜索恶心到了，我相信，百度搜索，对于任何一个有追求的人来说都是无法接受的，我不知道百度那些清华北大的员工为何能忍受！这个情况，到现在依然没有任何改变！如今，除了某些特殊不得已的情况，我几乎都是chatgpt或者google或者bing，这是一个可悲的结局，毕竟对于一个有情怀的中国人来说，我当然希望看到国家百度更加强大、甚至伟大。至于文心一言，有chatgpt的情况下，你觉得我们还有多少时间和精力来陪你玩？

顺便说下自动驾驶，当年百度领着国内一大批顶部巨头，走的是基于激光雷达的线路。当时都是信心满满，而依据就是特斯拉为了省钱所以不用激光雷达，然后动不动就用算力来忽悠消费者，而今，基于端到端大模型的纯视觉自动驾驶即将完全成熟落地，一旦真正落地，将是另一个chatgpt的爆炸性时刻，而我们国内这些捣鼓在另一条路上的基于if-else+多个算法模型组合的自动驾驶技术，其结局会有多惨真的无法想象。留下的时间已经无多，而百度和华为的自动驾驶这一次又该怎么办？

社会资源是有限的，这些资源被你们占用，却无法产生与之匹配的社会贡献，那么就是时代的罪人，就如曾经的土地主！这里我特别想顺便大吼一句，辣鸡联想！

**Comment by AIMSK** [comment]
linux 内核那么多 bug，有的能直接把你系统干 crash，你指着 linus 鼻子去骂垃圾吗？
一个伸手党，还是个满嘴喷粪的伸手党，居然还奢谈什么”开源“，懂什么是开源精神吗，可笑。

**Comment by intgogo** [comment]
> linux 内核那么多 bug，有的能直接把你系统干 crash，你指着 linus 鼻子去骂垃圾吗？ 一个伸手党，还是个满嘴喷粪的伸手党，居然还奢谈什么”开源“，懂什么是开源精神吗，可笑。

百度搜索中铺天盖地的医疗广告、弹窗广告、手机百度强制下载app等等，你用的很爽是吧？

奴性思想印刻在你祖宗十八代的基因里，至今依然深入了你的骨髓与灵魂，你这种天生奴才也有脸来互联网上发言？

何为伸手党？我给百度网盘贡献了6年VIP会员费，而你呢？自己看看自己什么德行和档次再来批判。

**Comment by tdynlildjl528** [comment]
@intgogo 哥如果你提了pr被拒，我十分里一百分认同您的说法，同为开源人那叫批判，如果没提过PR，那我就有话说了，你给百度付费和开源精神有啥关系，我还交过个税呢，我骄傲了嘛。吃饱喝饱骂大哥的角色，小区的野狗吃了我的剩菜剩饭也不会因为菜凉了骂两句，可见你是什么角色，综上，如果你是开源人，你可以批判，你也有资格批判，如果你是白嫖，连我们小区的狗都不如。谢谢大哥

**Comment by intgogo** [comment]
> @intgogo 哥如果你提了pr被拒，我十分里一百分认同您的说法，同为开源人那叫批判，如果没提过PR，那我就有话说了，你给百度付费和开源精神有啥关系，我还交过个税呢，我骄傲了嘛。吃饱喝饱骂大哥的角色，小区的野狗吃了我的剩菜剩饭也不会因为菜凉了骂两句，可见你是什么角色，综上，如果你是开源人，你可以批判，你也有资格批判，如果你是白嫖，连我们小区的狗都不如。谢谢大哥

先说下，paddle现在很不错了，批判应该仅局限于某一个时间、某一个问题点上，我有点扩大化了，我认！顺便提下，百度搜索，现在集成了文心一言大模型，没那么可恶了，虽然不管是不是主观，但客观上依然把无数的病毒、仿冒、作恶程序搜索排前，让单纯的网民们大受其害。时代一直在变，可能未来某一天，百度搜索也能变成正义化身。

最终，认知决定一切！你的举例，也只是你认知范畴内的正常表现而已，我不怪你。

**Comment by intgogo** [comment]
> @intgogo 哥如果你提了pr被拒，我十分里一百分认同您的说法，同为开源人那叫批判，如果没提过PR，那我就有话说了，你给百度付费和开源精神有啥关系，我还交过个税呢，我骄傲了嘛。吃饱喝饱骂大哥的角色，小区的野狗吃了我的剩菜剩饭也不会因为菜凉了骂两句，可见你是什么角色，综上，如果你是开源人，你可以批判，你也有资格批判，如果你是白嫖，连我们小区的狗都不如。谢谢大哥

先说下，paddle现在很不错了，批判应该仅局限于某一个时间、某一个问题点上，我有点扩大化了，我得认！顺便提下，百度搜索，现在集成了文心一言大模型，没那么可恶了，虽然不管是不是主观，但客观上依然把无数的病毒、假冒、作恶程序搜索排前，让单纯的网民们大受其害。时代一直在变，可能未来某一天，百度搜索也可以变成正义化身。

最后，认知决定一切！你的举例，也只是你认知范畴内的正常表现而已，我不怪你。
