### ISSUE TITLE
paddleslim有基于检测模型进行量化的例子吗？

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2641]
[PaddleSlim](https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim)里提供了不少诸如剪切、量化和蒸馏的案例，但他们都是分类的，有没有基于检测的案例，量化后map会降多少？有实验数据吗？

**Comment by wanghaoshuang** [comment]
非常抱歉，我们暂时没有做分类任务之外的实验，后续我们会添加相关benchmark.

**Comment by imistyrain** [comment]
看到[PaddleDetection](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection)todo list中提到int8的支持，这个有时间表了没？

**Comment by qingqing01** [comment]
@imistyrain 这个我们还在计划，抱歉，暂时无法给出明确的时间~

**Comment by wanghaoshuang** [comment]
提了个pr，但是还没有merge: https://github.com/PaddlePaddle/models/pull/2773
