### ISSUE TITLE
训练及so预测时报错fuse_relu_before_depthwise_conv

### ISSUE THREAD

**Issue by sherylwang** [PaddlePaddle/models#2648]
paddle fluid版本1.3. so预测时报错： in conv2d 'fuse_relu_before_depthwise_conv': False
![image](https://user-images.githubusercontent.com/10609885/60425142-7b209780-9c24-11e9-88d6-18de4520181e.png)

**Comment by shippingwang** [comment]
@sherylwang 什么模型？

**Comment by sherylwang** [comment]
> @sherylwang 什么模型？

ResNet50_vd

**Comment by shippingwang** [comment]
Note：更新了paddle后好用了
