### ISSUE TITLE
gnn工程里network的batch_size 问题

### ISSUE THREAD

**Issue by Alucardmini** [PaddlePaddle/models#2660]
![image](https://user-images.githubusercontent.com/8130720/60478239-87543580-9cb4-11e9-81e4-ddf9e5219f62.png)

现在这个batch_size 需要外面传参数进来， 为什么不可以像Tensorflow一样 传None或者-1根据数据量来动态适应。    因为我在使用预测的时候 可能一条数据一条数据的进行预测。

**Comment by heavengate** [comment]
您好，由于模型构建过程中需要使用reshape等操作需要batch size信息，所以这里传入了batch size，如果你是在预测时，infer脚本有--batch_size操作，可以通过python infer.py --batch_size=1来指定进行一条数据一条数据的预测

**Comment by Alucardmini** [comment]
> 您好，由于模型构建过程中需要使用reshape等操作需要batch size信息，所以这里传入了batch size，如果你是在预测时，infer脚本有--batch_size操作，可以通过python infer.py --batch_size=1来指定进行一条数据一条数据的预测

感谢您的回答。
但是我在测试数据上训练的时候batch_size设置为30， 在执行infer.py时设置batch_size 为1的时候报错：
![image](https://user-images.githubusercontent.com/8130720/60480661-f0d84200-9cbc-11e9-9863-0ceb37ab0554.png)
设置成30才能执行成功

**Comment by Alucardmini** [comment]
而且我发现单条数据*30后也可以执行，不过这样好蠢啊
![image](https://user-images.githubusercontent.com/8130720/60480764-5fb59b00-9cbd-11e9-9906-04f1895f6acf.png)

**Comment by hutuxian** [comment]
Thanks for your attention.
We plan to optimize this sooner after fully testing.
For variable batch size, you can refer to: https://github.com/PaddlePaddle/models/pull/2676/files
Any further questions are welcome and appreciated.
