### ISSUE TITLE
PaddleDetection中的Mask-RCNN-FPN训练出的模型可能效果很差

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2661]
在paddle1.5分支下，Cuda9 Cudnn7下训练Mask-RCNN-FPN模型，训练最后的log会有些异常，loss_bbox值很小。训练得到模型test效果很差。
<img width="634" alt="e6c8cfdc0b1f13c3fc83f89eeba51a83" src="https://user-images.githubusercontent.com/46314656/60479064-16624d00-9cb7-11e9-903e-a7983fdf34ea.png">

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/Paddle/pull/18284 目前通过该pr不再出现训练异常的情况
