### ISSUE TITLE
PaddleSlim中的compress.py是基于哪个train.py改写的？

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2662]
目前image_classification和ssd的[train.py](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/train.py)均使用了py_reader进行异步读取的，而[compress.py](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/compress.py)中使用的Compressor其内部实现还是同步的方式，如何将预训练模型中的py_reader节点改造成能适应同步读入的方式？

**Comment by wanghaoshuang** [comment]
Compressor里支持py_reader. 这个例子用的就是py_reader: https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/light_nas/search.py#L44
