### ISSUE TITLE
win 10根据文档描述启动train.py 断言报错

### ISSUE THREAD

**Issue by liuzengzhen1** [PaddlePaddle/models#2668]
-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 64
data_dir: data/pascalvoc
dataset: 'pascalvoc'
enable_ce: False
epoc_num: 120
image_shape: 3,300,300
learning_rate: 0.001
mean_BGR: 127.5,127.5,127.5
model_save_dir: model
parallel: True
pretrained_model: 'pretrained/ssd_mobilenet_v1_coco/'
use_gpu: 0
------------------------------------------------

Traceback (most recent call last):
  File "D:\untitled\pratice\ssd\train.py", line 332, in <module>
    main()
  File "D:\untitled\pratice\ssd\train.py", line 292, in main
    assert dataset in ['pascalvoc', 'coco2014', 'coco2017']
AssertionError

**Comment by heavengate** [comment]
感觉像是编码格式的问题
1. 可以在train.py 292行前把dataset print出来看下，dataset被解析成了啥
2. configuration arguments有些奇怪，model_save_dir: model和data_dir: data/pascalvoc没有带‘’符号，dataset: 'pascalvoc'的pascal带了''，确认下是否改动了代码

**Comment by JiaXiao243** [comment]
window上加载模型进行训练的时候，需要去掉--dataset=‘pascalvoc’的双引号

**Comment by liuzengzhen1** [comment]
是哒，解决了谢谢各位
