### ISSUE TITLE
请问预训练模型后缀的vc,vd是什么意思？

### ISSUE THREAD

**Issue by cassiaaaaaa** [PaddlePaddle/models#2674]
比如ResNet50_vd

**Comment by jerrywgz** [comment]
ResNet_vd相当于ResNet-D，是ResNet原始结构的变种，不同版本的resnet可以参考下图：
![image](https://user-images.githubusercontent.com/22989727/60495066-a4076200-9ce2-11e9-8888-b70230a17f17.png)

**Comment by jerrywgz** [comment]
paper地址：https://arxiv.org/pdf/1812.01187.pdf

**Comment by cassiaaaaaa** [comment]
多谢解答！

**Comment by cassiaaaaaa** [comment]
> paper地址：https://arxiv.org/pdf/1812.01187.pdf

好人一生平安

**Comment by heavengate** [comment]
> 多谢解答！

鉴于问题已经解决，当前issue关闭，感谢对PaddlePaddle的支持~

**Comment by byhwdy** [comment]
> ResNet_vd相当于ResNet-D，是ResNet原始结构的变种，不同版本的resnet可以参考下图：
> ![image](https://user-images.githubusercontent.com/22989727/60495066-a4076200-9ce2-11e9-8888-b70230a17f17.png)
感谢

**Comment by byhwdy** [comment]
> ResNet_vd相当于ResNet-D，是ResNet原始结构的变种，不同版本的resnet可以参考下图：
> ![image](https://user-images.githubusercontent.com/22989727/60495066-a4076200-9ce2-11e9-8888-b70230a17f17.png)

感谢

**Comment by cww97** [comment]
那么v是什么意思呢

**Comment by XEric7** [comment]
> 那么v是什么意思呢

version?
