### ISSUE TITLE
视频库中CTCN训练ctr+c退出后显卡无法释放

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2680]
视频库中CTCN模型在训练时ctr+c退出后，显卡占用无法自动释放，且kill不掉相关进程。
<img width="669" alt="39156a3cfe2c63eb11b4cee114f679c0" src="https://user-images.githubusercontent.com/46314656/60511957-daa2a400-9d05-11e9-896b-077a7ba32153.png">

**Comment by SunGaofeng** [comment]
Yes, this should be fixed by killing process group when receive signal.SIGINT

**Comment by imistyrain** [comment]
ps aux | grep python 找到相关的进程，一个个杀掉
