### ISSUE TITLE
翻译模型/rnn_search在paddle1.4版本上运行报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#2687]
文档：
[运行本目录下的范例模型需要安装PaddlePaddle Fluid 1.0版。]

paddle1.4版本运行报错：
 python train.py --src_lang en --tar_lang vi --attention True --num_layers 2 --hidden_size 512 --src_vocab_size 17191 --tar_vocab_size 7709 --batch_size 128 --dropout 0.2 --init_scale 0.1 --max_grad_norm 5.0 --train_data_prefix data/en-vi/train --eval_data_prefix data/en-vi/tst2012 --test_data_prefix data/en-vi/tst2013 --vocab_prefix data/en-vi/vocab --use_gpu True --max_epoch 2
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    from base_model import BaseModel
  File "/home/paddle/zhengya01/paddle-ce/local/rnn_search/base_model.py", line 24, in <module>
    from paddle.fluid.contrib.layers import basic_lstm, BasicLSTMUnit
ImportError: No module named layers

**Comment by kolinwei** [comment]
@phlrain 
https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/unarchived/neural_machine_translation/rnn_search
readme里面得改下

**Comment by kuke** [comment]
Fixed
