### ISSUE TITLE
PaddleSlim 量化检测 代码

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2692]
基于[ssd](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/train.py)和[quant_low_level_api](https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/quant_low_level_api)改的，大佬帮忙看下有啥问题没?

**Comment by wanghaoshuang** [comment]
看起来没什么问题
