### ISSUE TITLE
icnet 存在的几个问题

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2725]
[icnet](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/icnet)里存在诸多问题:
1.文档有误，--model_path="./cnkpnt/100"应该是--model_path="./chkpnt/100"
2.训练时没有输出中间过程信息，仅在最后输出几个loss信息
3.文档中给的预训练模型无法用于infer，能提供下训好的cnkpnt/100模型吗？

**Comment by wanghaoshuang** [comment]
>1.文档有误，--model_path="./cnkpnt/100"应该是--model_path="./chkpnt/100"
2.训练时没有输出中间过程信息，仅在最后输出几个loss信息

多谢反馈，已提PR修复。

>3.文档中给的预训练模型无法用于infer，能提供下训好的cnkpnt/100模型吗？

pretrain model目的是加快用户在自定义数据上的训练，暂时只提供了backbone network的权重，没有最后fc layer的权重
