### ISSUE TITLE
hub run lac和  “AI开放平台-词法分析“线上体验输出结果不一样？

### ISSUE THREAD

**Issue by fupeng** [PaddlePaddle/models#2765]
hub run lac --input_text "美批准售台百辆M1A2坦克 价值20亿美元"
[{'word': ['美批准', '售', '台', '百辆', 'M1A2坦克', ' ', '价值', '20亿美元'], 'tag': ['ORG', 'v', 'n', 'm', 'nz', 'w', 'n', 'm']}]

AI开放平台-词法分析 线上体验 https://ai.baidu.com/tech/nlp/lexical
输出： 美 ns 批准 v 售 v 台 n 百辆 m M1A2坦克 nz 价值 n 20亿美元 m

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub Module Lac 和 AI开放平台的词法分析模型确实不一样，所以出现预测结果不一致的问题是正常的。如果觉得这个是一个bad case，可以试试PaddleHub Module Lac最新版本支持词典干预功能。欢迎在PaddleHub仓库 https://github.com/PaddlePaddle/PaddleHub 下提意见。

**Comment by fupeng** [comment]
是不是说PaddleHub Module比AI开放平台的效果要差一些？


模型 | Precision | Recall | F1-score
-- | -- | -- | --
Lexical Analysis | 88.0% | 88.7% | 88.4%
BERT finetuned | 90.2% | 90.4% | 90.3%
ERNIE finetuned | 92.0% | 92.0% | 92.0%

能否使用PaddleHub的ERNIE达到同样的结果？

我是看到lac介绍网页的源码指向这个仓库，所以issue提这里了。

**Comment by Steffy-zxf** [comment]
由于PaddleHub Module Lac 和 AI开放平台的词法分析模型预训练数据集以及词汇表不相同等因素，所以会造成一定的差异。同样地，AI开放平台的词法分析模型也会存在一些bad case。目前PaddleHub还没有开放基于ERNIE FineTune的LAC，不过您可以尝试下我们PaddleHub Module Lac最新版本支持词典干预功能，同样可以解决上述bad case。

**Comment by fupeng** [comment]
感谢回复！我试试词典干预功能。
