### ISSUE TITLE
SE_ResNeXt101_32x4d网络修改图像尺寸修改

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/models#2796]
请问，使用SE_ResNeXt101_32x4d网络，不想采用224*224*3的图片尺寸，想扩大图片尺寸，都需要改哪些？

**Comment by zhhsplendid** [comment]
要扩大图片尺寸，首先，你需要更改输入的尺寸为你的图片尺寸。随着尺寸更改，你的网络一些层的参数也会扩大。例如conv层的输出size变大了。你需要把接收这些输出的相应网络层参数也进行改变。

**Comment by 930083287** [comment]
你好，是否有相应例子？

**Comment by zhhsplendid** [comment]
Models repo下有一些CV相关的models，你可以参照着搭模型。据我所知，暂时paddle models里应该没有扩大图片尺寸的教程，你可以自己计算需要的各个层节点。
