### ISSUE TITLE
PaddleDetection 训练同时做eval，fpn实现问题

### ISSUE THREAD

**Issue by gilbert1989** [PaddlePaddle/models#2799]
版本：
paddlepaddle/models release1.5分支
操作：
python tools/train.py --config=configs/retinanet_r101_fpn_1x.yml --eval

报错：
assertionError

原因：
train和eval共用一个model实例。
model.train时  models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py 174行修改了实例的self.spatial_scale属性。
导致model.eval时 models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py 151行的分支进不去，特征没叠加。

**Comment by zhaoyuchen2018** [comment]
麻烦model的同学看下这个

**Comment by qingqing01** [comment]
Fixed in https://github.com/PaddlePaddle/models/pull/2790 . 另外，我们也在文档里说明了，在SSD上，训练中的eval是充分验证了的。COCO数据的下个版本提供充分验证的。
