### ISSUE TITLE
test过程中如何输出中间结果

### ISSUE THREAD

**Issue by zhouchunyi** [PaddlePaddle/models#2805]
想load模型参数后，打印出中间结果，可是executor.run的output执行中，在对应的网络层并不能打印出来。想知道怎么才能把中间结果输出

**Comment by zhhsplendid** [comment]
可以用paddle.fluid.layers.Print打印中间变量值

相关API文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/control_flow_cn.html#print
