### ISSUE TITLE
[PyramidBox] Questions about the conv_fc layers in the VGG backbone

### ISSUE THREAD

**Issue by fengyuentau** [PaddlePaddle/models#2808]
The PyramidBox paper indicates that,
> We use the base convolution layers and extra convolutional layers in S^3FD as our backbone layers, which keep layers of VGG16 from conv1_1 to pool5, then convert fc6 and fc7 of VGG16 to conv_fc layers, and then add more convolutional layers to make it deeper.

However, from [this line of source code](https://github.com/PaddlePaddle/models/blob/33d384b47ae1436a6de4f01fec4317daf9760d39/PaddleCV/face_detection/pyramidbox.py#L122) and [the definition of conv_block](https://github.com/PaddlePaddle/models/blob/33d384b47ae1436a6de4f01fec4317daf9760d39/PaddleCV/face_detection/pyramidbox.py#L35), we can tell that the dilation conv is not applied as [S^3FD](https://arxiv.org/abs/1708.05237) or [DeepLabv1](https://arxiv.org/abs/1412.7062).

Is it a miss or dilation conv not working well?

**Comment by qingqing01** [comment]
In the PyramidBox model, we do not use dilation conv.   Dilation conv works well in other model, like DeepLab v3.

**Comment by fengyuentau** [comment]
@qingqing01 Thanks. Could you futher explain why you don't use dilation conv?

**Comment by qingqing01** [comment]
We just follow PyramidBox implementation,  I think there is no special reason. :)

**Comment by fengyuentau** [comment]
OK, thanks anyway.
