### ISSUE TITLE
PaddleDetection CascadeRCNN  中 num_classes 硬编码 bug

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/models#2816]
此处 [code](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/roi_heads/cascade_head.py#L200) 使用了针对 COCO 数据集（num_classes = 81）的硬编码，对于自定义数据预测将出现下述错误：

![image](https://user-images.githubusercontent.com/37564754/61270462-5572c100-a7d4-11e9-8891-7214f589b755.png)

需要将：
```
bbox_pred_new = fluid.layers.expand(bbox_pred_new, [1, 81, 1])
```

修改为：
```
bbox_pred_new = fluid.layers.expand(bbox_pred_new, [1, self.num_classes, 1])
```

**Comment by ysh329** [comment]
@mzchtx 非常感谢您的反馈，我们后续版本将会修正这个问题！

**Comment by qingqing01** [comment]
Thanks! Fixed in https://github.com/PaddlePaddle/models/pull/2817
