### ISSUE TITLE
windows下CPU运行RCNN的infer.py出错

### ISSUE THREAD

**Issue by hong3731** [PaddlePaddle/models#2821]
在windows下CPU运行RCNN的infer.py出错,下载的权重是按照pretrained里面的download.sh的地址下载的,使用的paddle 1.5版本,报错的信息如下:
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [E:\release_cuda87\paddle\paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
配置里面已经把设置了使用CPU
  add_arg('use_gpu',          bool,  False,      "Whether use GPU.")
请问这个是什么问题呢?这个不支持windows的?

**Comment by FDInSky** [comment]
这是在PaddleDetection下出的错误吗？

**Comment by hong3731** [comment]
不是，运行的是models /PaddleCV/rcnn/infer.py

**Comment by FDInSky** [comment]
经过测试，可以正常运行；根据你的报错信息，请检查下预训练权重的加载路径信息；

**Comment by hong3731** [comment]
感谢回复，我检查了一下模型路径，代码中有以下的路径检查的吧，运行中没有报这个错误，是不是可以说明模型路径没有问题的呢？
exe = fluid.Executor(place)
    # yapf: disable
    if not os.path.exists(cfg.pretrained_model):
        raise ValueError("Model path [%s] does not exist." % (cfg.pretrained_model))

**Comment by JiaXiao243** [comment]
请问您具体的python版本是？我这边CPU跑infer，运行python infer.py --dataset=coco2017 --pretrained_model=model_iter179999 --image_path=dataset/coco/val2017/000000000139.jpg --draw_threshold=0.6 --MASK_ON=true --use_gpu false，运行结果如下：
![image](https://user-images.githubusercontent.com/37854899/61435329-cb109580-a96a-11e9-9575-22a668438a39.png)

**Comment by hong3731** [comment]
你好,pretrained_model是要自己训练的么?预训练的不行不能直接使用?
我下载了三个模型:
1.wget http://paddlemodels.bj.bcebos.com/faster_rcnn/imagenet_resnet50_fusebn.tar.gz
2.https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
3.https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_se154_vd_fpn_s1x.tar

第一个预训练的权重报
C++ Callstacks:
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [E:\release_cuda87\paddle\paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.

第二个预训练可以运行,但是结果貌似是错误的
![image](https://user-images.githubusercontent.com/47878003/61439761-b0dbb500-a974-11e9-8f8b-edd821022be4.png)

第三个预训也是报和第一个一样的错误
    infer()
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [E:\release_cuda87\paddle\paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
请教一下模型在那里下载的呢?
