### ISSUE TITLE
len(feed_target_names) 出错 

### ISSUE THREAD

**Issue by lylyhs** [PaddlePaddle/models#2824]
运行NLP模型里面的对话理解预测脚本
保存模型报feed_target_names 为None 没长度

feed_target_names = pred_results.get('feed_target_name', None)

查看define_paradigm.py里面的
results = {"probs": probs, "feed_targets_name": feed_targets_name}

这个里面的KEY值是不是错了？
改成feed_targets_name就可以了

**Comment by 0YuanZhang0** [comment]
是的哈，这个key需要改成feed_targets_name，感谢提出的意见哈，我们会尽快修复这个问题；
