### ISSUE TITLE
请教2个问题: 关于冻结训练层和获取网络信息的功能

### ISSUE THREAD

**Issue by greatjinyun** [PaddlePaddle/models#2829]
请教2个问题：
1） 我们从预训练的模型中迁移学习时，需要在不同的训练阶段，冻结模型中的某些层，譬如先把特征提取层冻结设置为Trainable=False.  请问paddle中有相关函数吗？
2）另外一个相关的问题是，冻结时可能会需要写明 层的名字， paddle是否有函数可以方便地打印出所有层的名称；另外冻结时是否支持 正在表达式 表示，以便设置一下子冻结多个层

**Comment by MRXLT** [comment]
您好，冻结是想要使这一层的参数不可训练吗，不同阶段指的是什么情形

**Comment by greatjinyun** [comment]
是的，希望让这一层的参数在这一轮训练时不可修改。 

等到这一轮训练结束后，再冻结另外一些层进行训练。

**Comment by MRXLT** [comment]
1、可以使用paramattr op来设置参数trainable=false
文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/fluid_cn.html#paramattr
2、可以通过打印pargram.to_string查看所有层和variable，但是冻结时需要指定要冻结的参数，不支持一次冻结多个层
文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/fluid_cn.html#to_string
