### ISSUE TITLE
用Paddlepaddle训练的模型，用paddlehub推理时缺少module_desc.pb文件

### ISSUE THREAD

**Issue by lambert-lan** [PaddlePaddle/models#2834]
用Paddlepaddle训练的模型，用paddlehub加载做推理时缺少module_desc.pb文件，有解决方法吗
还是用paddlehub加载的模型必须用paddlehub训练?

**Comment by MRXLT** [comment]
您好，我看到您在paadlehub下提了相同的issue，并且已经有同学在解答，所以将这个issue关闭，请关注paddlehub下的issue
https://github.com/PaddlePaddle/PaddleHub/issues/81
