### ISSUE TITLE
fasterrcnn跑voc数据集

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#2835]
有人尝试过fasterrcnn在voc数据集训练嘛，训练的报显存不够了，但是在coco训练集下是可以的，是因为.yml配置不对导致的嘛

**Comment by qingqing01** [comment]
@dbcool 我们没尝试过VOC数据，请问您是怎么样配置的？

**Comment by dbcool** [comment]
在PaddleCV/PaddleDetection测试train，修改.yml的中的
metric: VOC
以及
FasterRCNNTrainFeed:
  batch_size: 16
  use_process: true
  dataset:
    dataset_dir: dataset/voc
    annotation: VOCdevkit/VOC_all/ImageSets/Main/train.txt
    image_dir: VOCdevkit/VOC_all/JPEGImages
    use_default_label: true

**Comment by jerrywgz** [comment]
我这边测试了下，是可以正常跑的，
![image](https://user-images.githubusercontent.com/22989727/61844765-301c3c00-aed3-11e9-8f72-68aa980339a3.png)，
配置如下：
![image](https://user-images.githubusercontent.com/22989727/61844979-0ca5c100-aed4-11e9-8877-15448379d475.png)

显存不足的问题有如下解决方法：
1. 首先查看下显卡上是否有其他任务占用显存
2. 减小batch size，官方给出的coco数据集上batch size为2，你这里16太大了
3. 另外可以通过设置两个环境变量
- export FLAGS_eager_delete_tensor_gb=0.0
- export FLAGS_fast_eager_deletion_mode=1

**Comment by dbcool** [comment]
好滴，非常感谢！
