### ISSUE TITLE
MobileNet-SSD 的 backbone 存在 bug

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/models#2868]
如下图1， 2中，`_extra_block` 函数调用的地方已经写死 `num_groups` 为 1，而 `scale` 参数为传入的，假设 `scale` < 1，比如 0.5 或者 0.25，则会出现调用 `self._conv_norm` 的时候 `num_groups` 为 0 的情况。

![image](https://user-images.githubusercontent.com/37564754/61533480-a1856600-aa5f-11e9-821a-f29add347860.png)

![image](https://user-images.githubusercontent.com/37564754/61533542-c679d900-aa5f-11e9-86e4-a2d895aa87d1.png)

具体代码位于：
[code](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/backbones/mobilenet.py#L122-L146) 和 [code](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/backbones/mobilenet.py#L188-L195)

**Comment by qingqing01** [comment]
@mzchtx 感谢指出，在 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/mobilenet_ssd.py  中实际不支持更换scale。 我们会在PaddleDetection中改进下。
