### ISSUE TITLE
文档缺失

### ISSUE THREAD

**Issue by char256** [PaddlePaddle/models#2889]
在ocr的代码中有[fluid.evaluator.EditDistance](https://github.com/PaddlePaddle/models/blob/0bd09f6433ee934c415a2e2a7599eb9f1dc2cf11/PaddleCV/ocr_recognition/crnn_ctc_model.py#L194)，但是查阅文档的时候，只有[fluid.metrics.EditDistance](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/metrics_cn.html#editdistance)，看完文档后感觉这两个不是一个类，而且文档中找evaluator.EditDistance的时候是找不到的，可以在官网的docs中说明一下吗?
还有文档中reset的用法没有说，就贴上来一个代码，看不懂什么意思啊
![image](https://user-images.githubusercontent.com/16537232/61630900-82831000-acbb-11e9-864f-bb130a454ecf.png)

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/0ae45f0b53f13bedadc90f2d6195c45c9e29285e/python/paddle/fluid/evaluator.py#L220

fluid.evaluator.EditDistance 将会被废弃，所以文档隐藏了
