### ISSUE TITLE
language_model训练完了怎么使用计算一句话的PPL

### ISSUE THREAD

**Issue by jtyoui** [PaddlePaddle/models#2899]

**Comment by phlrain** [comment]
需要自己参考eval 的函数，实现相应的功能

**Comment by jtyoui** [comment]
> 需要自己参考eval 的函数，实现相应的功能

意思是，没有现成的实现过程、

**Comment by jtyoui** [comment]
> 需要自己参考eval 的函数，实现相应的功能

这个模型训练保存之后，在那个方法加载调用训练好的模型

**Comment by phlrain** [comment]
save_params  保存模型，load_params 加载模型

**Comment by jtyoui** [comment]
> > 需要自己参考eval 的函数，实现相应的功能
> 
> 这个模型训练保存之后，在那个方法加载调用训练好的模型


训练中文的话，是将每一个字分开，还是将句子进行分词分开？（图1）
![image](https://user-images.githubusercontent.com/28988355/61769203-0d7b1c00-ae1c-11e9-8dfa-79fd88bc2245.png)

> ------------------------------------------------------------------------------

还是（图2）
![image](https://user-images.githubusercontent.com/28988355/61769285-50d58a80-ae1c-11e9-9bc2-0bb9b8337210.png)

**Comment by guoshengCS** [comment]
> 训练中文的话，是将每一个字分开，还是将句子进行分词分开

这个其实基于字和词的都有的

**Comment by gezimonkey** [comment]
> _No description provided._

HI,请问你实现了计算PPL了吗?

**Comment by igfuns** [comment]
> > _No description provided._
> 
> HI,请问你实现了计算PPL了吗?

https://aistudio.baidu.com/aistudio/projectDetail/122290 ipython的infer.py 有参考实现。
