### ISSUE TITLE
ssd use_multiprocess设置为True后，训练过程会出现停止的情况

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#2918]
如题，环境AI STUDIO GPU:V100 16GB  CPU：32GB，'use_multiprocess', bool,  True时训练不到一个epoch就停止不动了，设置为False后读取变慢，但是不会出现停止假死的情况

**Comment by wanghaoshuang** [comment]
可以把workers设置的小点试试：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py#L287

**Comment by universea** [comment]
谢谢，我尝试一下

**Comment by universea** [comment]
> 可以把workers设置的小点试试：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py#L287

谢谢，已经解决啦！
