### ISSUE TITLE
paddleSlim在压缩yolo3后遇到的问题

### ISSUE THREAD

**Issue by FocueAI** [PaddlePaddle/models#2922]
1.  我使用的是keras-yolo3的代码，之后使用 X2paddle 转换成了paddle的格式，并且经过测试，生成的paddle代码可以用来做预测，之后在压缩项目中对yolo3代码做出微调具体如下
![图1](https://user-images.githubusercontent.com/49752023/61844504-41187d80-aed2-11e9-8b4b-740e9b955ab4.png)
![2](https://user-images.githubusercontent.com/49752023/61844737-0bc05f80-aed3-11e9-95dd-6c4eb4454a9b.png)
2.  压缩工程中 yolo3(paddle版本)的输出是：
![A{3)UP@E UKJ)7Z~~@ P@E](https://user-images.githubusercontent.com/49752023/61844847-89846b00-aed3-11e9-889e-a5e9252cb04c.png)
3. 取到压缩模型的地方
![ER$(W2_%{7G{C9L)WB)64G4](https://user-images.githubusercontent.com/49752023/61844915-c94b5280-aed3-11e9-9cc0-5ad4b62d37f2.png)
![V2BKZTHHBO@(% N8ASLZ%L4](https://user-images.githubusercontent.com/49752023/61844922-ccded980-aed3-11e9-984a-1441e0dc538a.png)
4. 加载压缩模型对应的输出信息
![ZYJFRUP` FF~XW7W_3`ETZ6](https://user-images.githubusercontent.com/49752023/61844948-eb44d500-aed3-11e9-9b0f-2e011532468d.png)
5. 疑问：压缩前后，模型的输出，怎么会有差异呢？！望各位大佬们能给出一定的指导。。

**Comment by Yipeng-Sun** [comment]
请问：这个模型是怎么压缩的，用什么方法，怎样的参数，压缩输出log有哪些信息？

**Comment by FocueAI** [comment]
1. 压缩的配置参数
![image](https://user-images.githubusercontent.com/49752023/61847183-54c8e180-aedc-11e9-83b0-a9921a57e2de.png)
2. 压缩输出的log
  a . 压缩最后面的log
![image](https://user-images.githubusercontent.com/49752023/61847321-d1f45680-aedc-11e9-9348-958f7487fdc1.png)
  b. 完整的log文件（不能发上去）

**Comment by FocueAI** [comment]
b. 这就就是完整的log文件
[nohup .txt](https://github.com/PaddlePaddle/models/files/3429817/nohup.txt)

**Comment by wanghaoshuang** [comment]
你好，感谢反馈，最近同事在yolo v3上跑了量化训练的策略没有出现您描述的情况。我会再尝试复现下您说的问题，然后再给您反馈。

**Comment by FocueAI** [comment]
你方便把你们的代码发出来看看吗？

**Comment by FocueAI** [comment]
> 你好，感谢反馈，最近同事在yolo v3上跑了量化训练的策略没有出现您描述的情况。我会再尝试复现下您说的问题，然后再给您反馈。
你方便把你们的代码发出来看看吗？
