### ISSUE TITLE
PaddleDetection train.py:设置resume_checkpoint

### ISSUE THREAD

**Issue by suyali** [PaddlePaddle/models#2951]
加载预训练模型时：设置resume_checkpoint为home/user/.cache/paddle/weightd/ResNet50_cos_pretrained/报错：
paddle.fluid.core_avx.EnforceNotMet:Invoke operator load error

Cannot open file home/user/.cache/paddle/weightd/ResNet50_cos_pretrained/conv_rpn_w for load op at [/paddle/paddle/fluid/operators/load_op.h]

**Comment by suyali** [comment]
或者说，如何使用resume_checkpoint

**Comment by JiaXiao243** [comment]
默认下载预训练模型的保存路径是:home/user/.cache/paddle/weights/ResNet50_cos_pretrained，应该将weightd修改为weights就可以了

**Comment by xiegegege** [comment]
resume_checkpoint能接着跑之前中断的训练，用法是命令行里-r加要恢复训练的checkpoint路径，预训练模型默认是会自己加载的，路径通过configs里.yml文件的pretrain_weights参数配置

**Comment by suyali** [comment]
weightd是打印错误，代码中输入的就是weights，

**Comment by suyali** [comment]
你说的这个我测试了一下，是可行的，但我想知道，为什么不能用这个命令加载./cache中的预训练模型
@xiegegege

**Comment by heavengate** [comment]
pretrain和resume的逻辑是不一样的，pretrain只需要load backbone的weight，resume需要load全量的weight和训练过程中的momentun、velocity等参数，二者不可通用
