### ISSUE TITLE
gpu并行训练时batch_size设置问题

### ISSUE THREAD

**Issue by 904281665** [PaddlePaddle/models#2960]
reader在yield数据时，要求batch_size必须能够整除gpu_num。但是却没有加断言，建议作者加入断言。

**Comment by heavengate** [comment]
您好，请问是哪个模型呢

**Comment by 904281665** [comment]
Image-classification 


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Kaipeng Deng <notifications@github.com>
发送时间: 2019年7月30日 12:04
收件人: PaddlePaddle/models <models@noreply.github.com>
抄送: Nku_dong <904281665@qq.com>, Author <author@noreply.github.com>
主题: 回复：[PaddlePaddle/models] gpu并行训练时batch_size设置问题 (#2960)




您好，请问是哪个模型呢

**Comment by heavengate** [comment]
感谢您的反馈，我们马上修复~

**Comment by 904281665** [comment]
嗯嗯，辛苦啦


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Kaipeng Deng <notifications@github.com>
发送时间: 2019年7月30日 12:18
收件人: PaddlePaddle/models <models@noreply.github.com>
抄送: Nku_dong <904281665@qq.com>, Author <author@noreply.github.com>
主题: 回复：[PaddlePaddle/models] gpu并行训练时batch_size设置问题 (#2960)

**Comment by heavengate** [comment]
与相关RD确认，image_classification近来在代码重构，代码重构中会对这种情况做处理
