### ISSUE TITLE
Cannot malloc 6652.83 MB GPU memory

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#2963]
When i try to infer many images in a dir, it occured follow problem:
Cannot malloc 6652.83 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.92. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0
F0729 21:37:01.823541 108811 legacy_allocator.cc:201] Cannot allocate 112.500000MB in GPU 0, available 632.937500MBtotal 7981694976GpuMinChunkSize 256.000000BGpuMaxChunkSize 6.496908GBGPU memory used: 6.412701GB

I also try to use multi-gpu to do infer, bu still appear this problem

**Comment by endy-see** [comment]
I had resolved it. do:
FLAGS_eager_delete_tensor_gb=0 
before run your infer command, details as follows:

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/best_practice/memory_optimize.html

**Comment by parap1uie-s** [comment]
> I had resolved it. do:
> FLAGS_eager_delete_tensor_gb=0
> before run your infer command, details as follows:
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/advanced_usage/best_practice/memory_optimize.html

Works for me, thanks!
