### ISSUE TITLE
paddle实现的Transformer翻译模型解码速度如何？

### ISSUE THREAD

**Issue by huchinlp** [PaddlePaddle/models#2972]
在知乎上看到你们宣传训练速度，特别想知道paddle实现的transformer在解码速度上面对比其他框架有无优势。这是[WNMT2018](https://docs.google.com/spreadsheets/d/1wZQegK-9CKY378eAWRlahg23Fq155WTm4TQ8ikf8_6E/)的结果，里面是WMT14 En-De任务上各个框架的性能对比，包括解码时间、显存占用和内存占用等。

**Comment by guoshengCS** [comment]
解码速度的话目前在大batch时会有一些优势，有一些额外的优化加入：一是在对历史解码内容计算结果进行cache之外，又加入了对encoder output在decoder中计算结果的cache，避免解码每一步都重新计算；二是beamsearch时会有batch-reduce，对已经解码完成度句子会从batch中去掉，batch会动态减小。

**Comment by huchinlp** [comment]
感谢回复，目前paddle对低精度的支持如何？

> 解码速度的话目前在大batch时会有一些优势......

**Comment by heavengate** [comment]
Paddle框架已支持fp16，目前各模型正在适配fp16混合精度训练
压缩和量化的也已支持，见https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim
