### ISSUE TITLE
SSD Inconsistent function call 

### ISSUE THREAD

**Issue by XFeiF** [PaddlePaddle/models#2980]
In your `eval_coco_map.py` file, you imported one function [`mobile_net `](https://github.com/PaddlePaddle/models/blob/8d7328017dc50c4b82d25733cc7a4cd14ad4469f/PaddleCV/ssd/eval_coco_map.py#L10) that do not exist in the `mobilenet_ssd.py` file.  And the function call [below](https://github.com/PaddlePaddle/models/blob/8d7328017dc50c4b82d25733cc7a4cd14ad4469f/PaddleCV/ssd/eval_coco_map.py#L52) should be modified too.

**Comment by XFeiF** [comment]
Can I make some contributions?

**Comment by qingqing01** [comment]
@XFeiF Thanks! we will fix soon. You also can use https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection
