### ISSUE TITLE
使用PaddleSlim进行SSD剪枝结果不正常

### ISSUE THREAD

**Issue by gujingxiao** [PaddlePaddle/models#2985]
我在训练好SSD模型后，尝试使用Slim进行剪枝和量化训练。在使用量化训练时，效果良好，没有遇到任何问题，但是在进行剪枝时，出现了完全没有效果的问题，具体描述如下：
![微信截图_20190731182813](https://user-images.githubusercontent.com/13788388/62205170-6e2cca80-b3c1-11e9-9fdf-0ef538d73052.png)

一开始训练，我加载我训好的模型，就出现如图所示打印，显示Pruned size为0，Pruned flops也为0.然后就进入到了训练中
![微信截图_20190731182823](https://user-images.githubusercontent.com/13788388/62205244-9caaa580-b3c1-11e9-9c58-5e369fbd0a87.png)
![微信截图_20190731182840](https://user-images.githubusercontent.com/13788388/62205361-dda2ba00-b3c1-11e9-8208-52812a0d8eba.png)
训练一切正常，每个epoch完事儿也都会进行eval，然后保存checkpoints，但是看不到任何剪枝的效果，config中的剪枝param也完全看不到，训练了十多个epoch，每个checkpoint大小都一模一样，预测结果也几乎相同，请相关技术人员帮忙解答，谢谢。

**Comment by gujingxiao** [comment]
我使用的yaml配置文件如下，只是改动了metric_name: 'map'这里，将原本的acc_top1改为了map，其他地方没有什么变动。
![微信截图_20190731183624](https://user-images.githubusercontent.com/13788388/62205490-1cd10b00-b3c2-11e9-8d87-6006b1e0b2e7.png)

**Comment by zzchust** [comment]
@gujingxiao 同学，你的这个问题解决了没

**Comment by ZiruiChen** [comment]
同问pruned size 和 pruned flops 我也是0 没有剪裁效果

**Comment by gujingxiao** [comment]
剪枝这里我已经趟了一部分坑，目前可以总结一下：1. 我之前发的问题，是我有个地方没有配置对，就是剪枝层名字，那里配对了，其实从理论上说就可以进行剪枝了。 2. 但实际上，改好了也会出问题，具体问题有，如果bn层和对应的conv层在定义权重名字时，只是单纯定义了层的名字，而没有定义具体prattr的名字时，会导致axis不正确的问题，导致剪枝出错，但是程序还是会按照原始网络进行训练，这时与正常训练无异 3. 当进行ssd剪枝，如果要裁剪的层，与loss或者multi box这种特殊处理层相连时，会出现our of index的情况，如果要裁剪的层只是正常进行上下层卷机或池化连接，则没有问题。4. 所以要使用ssd正常进行剪枝，不仅要把对应的weights名字取好，还要设计好架构，这一切目前都需要用户自行修改，修改后当然也就没有了预训练模型，相信询问这类问题的朋友都是参加百度之星的，所以这个坑很大，我看了好几天的源代码才发现了这些问题，所以还请官方能够根据广大参赛选手的诉求和疑问，进行特定辅导或者代码修正。

**Comment by wanghaoshuang** [comment]
@gujingxiao 首先，很抱歉没能及时关注到您的这个issue. 感谢您对Paddle的支持。

>2. 但实际上，改好了也会出问题，具体问题有，如果bn层和对应的conv层在定义权重名字时，只是单纯定义了层的名字，而没有定义具体prattr的名字时，会导致axis不正确的问题，导致剪枝出错，但是程序还是会按照原始网络进行训练，这时与正常训练无异 

- 如果只定义层的名字
这一层的parameter命名为在层名字上添加后缀，比如`conv2d(name="resnet_conv1")`, 对应这一层的(filter weight)的名字为`resnet_conv1.w_0`, bias的名字为`resnet_conv1.b_0`。
- 如果不指定层的名称，则会自动命名。
- 指定param_attr的名字：则该层的parameters的名字就是用户指定的名称。

PaddleSlim中的剪切功能依赖网络中parameters的命名。您可以通过以下方式查看您所定义网络的所有parameters的名称。

```
program = fluid.default_main_program() // 或其它用户自定义的program
for param in program.global_block().all_parameters():
    print("param name: {}".format(param.name))
```


>3. 当进行ssd剪枝，如果要裁剪的层，与loss或者multi box这种特殊处理层相连时，会出现our of index的情况，如果要裁剪的层只是正常进行上下层卷机或池化连接，则没有问题。

因为对卷积的channel进行裁剪，会影响到下一个卷积层或其它操作，所以，并不是所有卷积层都适合裁剪，所以需要用户指定裁剪的范围。目前PaddleSlim主要通过匹配parameters的名字来确定裁剪范围。如果您有更好的建议，可以一起交流下。

>4. 所以要使用ssd正常进行剪枝，不仅要把对应的weights名字取好，还要设计好架构，这一切目前都需要用户自行修改，修改后当然也就没有了预训练模型

关于预训练模型，您说的有道理，目前PaddleSlim只支持带个通配符指定要裁剪的parameters, 或许用一个list来表示裁剪范围的方式会更合理些，多谢您的提醒。

**Comment by zzchust** [comment]
![image](https://user-images.githubusercontent.com/6135871/63398669-e30f8500-c400-11e9-9b21-3a8028a8a739.png)

![image](https://user-images.githubusercontent.com/6135871/63398951-b6a83880-c401-11e9-808e-fb3c63f53a12.png)

![image](https://user-images.githubusercontent.com/6135871/63399068-ef481200-c401-11e9-90d2-0c891ff60980.png)

报一个bug，对mobilenet-ssd进行剪纸时，使用uniform_filter是正常的，使用sen_filter就有问题。

敏感度剪裁配置
version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            '*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    sensitive_pruning_strategy:
        class: 'SensitivePruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        delta_rate: 0.1
        target_ratio: 0.5
        num_steps: 1
#        eval_rate: 0.2
        pruned_params: '.*_sep_weights'
        sensitivities_file: 'mobilenet_acc_top1_sensitive.data'
        metric_name: 'map'
compressor:
    epoch: 120
    #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
    checkpoint_path: './output/checkpoints_prune/'
    strategies:
        - sensitive_pruning_strategy

均匀剪裁配置
version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            '*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    uniform_pruning_strategy:
        class: 'UniformPruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        target_ratio: 0.5
        pruned_params: '.*_sep_weights'
        metric_name: 'map'
compressor:
    epoch: 120
    #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
    checkpoint_path: './output/checkpoints_prune/'
    strategies:
        - uniform_pruning_strategy
~

**Comment by wanghaoshuang** [comment]
@zzchust 感谢反馈，这个错误是算法内部对方程求解没有处理特殊情况，我们会尽快修复下这个问题。多谢。

**Comment by ZiruiChen** [comment]
> ![image](https://user-images.githubusercontent.com/6135871/63398669-e30f8500-c400-11e9-9b21-3a8028a8a739.png)
> 
> ![image](https://user-images.githubusercontent.com/6135871/63398951-b6a83880-c401-11e9-808e-fb3c63f53a12.png)
> 
> ![image](https://user-images.githubusercontent.com/6135871/63399068-ef481200-c401-11e9-90d2-0c891ff60980.png)
> 
> 报一个bug，对mobilenet-ssd进行剪纸时，使用uniform_filter是正常的，使用sen_filter就有问题。
> 
> 敏感度剪裁配置
> version: 1.0
> pruners:
> pruner_1:
> class: 'StructurePruner'
> pruning_axis:
> '_': 0 criterions: '_': 'l1_norm'
> strategies:
> sensitive_pruning_strategy:
> class: 'SensitivePruneStrategy'
> pruner: 'pruner_1'
> start_epoch: 0
> delta_rate: 0.1
> target_ratio: 0.5
> num_steps: 1
> # eval_rate: 0.2
> 
> ```
>     pruned_params: '.*_sep_weights'
>     sensitivities_file: 'mobilenet_acc_top1_sensitive.data'
>     metric_name: 'map'
> ```
> 
> compressor:
> epoch: 120
> #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
> checkpoint_path: './output/checkpoints_prune/'
> strategies:
> - sensitive_pruning_strategy
> 
> 均匀剪裁配置
> version: 1.0
> pruners:
> pruner_1:
> class: 'StructurePruner'
> pruning_axis:
> '_': 0 criterions: '_': 'l1_norm'
> strategies:
> uniform_pruning_strategy:
> class: 'UniformPruneStrategy'
> pruner: 'pruner_1'
> start_epoch: 0
> target_ratio: 0.5
> pruned_params: '.*_sep_weights'
> metric_name: 'map'
> compressor:
> epoch: 120
> #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
> checkpoint_path: './output/checkpoints_prune/'
> strategies:
> - uniform_pruning_strategy
> ~
为什么同样的配置剪完我map接近零呢 
metric_name: 这个可以默认吗

**Comment by ZiruiChen** [comment]
为什么我同样的配置剪裁完map是零呢
metric_name: 这个可以默认吗

> ![image](https://user-images.githubusercontent.com/6135871/63398669-e30f8500-c400-11e9-9b21-3a8028a8a739.png)
> 
> ![image](https://user-images.githubusercontent.com/6135871/63398951-b6a83880-c401-11e9-808e-fb3c63f53a12.png)
> 
> ![image](https://user-images.githubusercontent.com/6135871/63399068-ef481200-c401-11e9-90d2-0c891ff60980.png)
> 
> 报一个bug，对mobilenet-ssd进行剪纸时，使用uniform_filter是正常的，使用sen_filter就有问题。
> 
> 敏感度剪裁配置
> version: 1.0
> pruners:
> pruner_1:
> class: 'StructurePruner'
> pruning_axis:
> '_': 0 criterions: '_': 'l1_norm'
> strategies:
> sensitive_pruning_strategy:
> class: 'SensitivePruneStrategy'
> pruner: 'pruner_1'
> start_epoch: 0
> delta_rate: 0.1
> target_ratio: 0.5
> num_steps: 1
> # eval_rate: 0.2
> 
> ```
>     pruned_params: '.*_sep_weights'
>     sensitivities_file: 'mobilenet_acc_top1_sensitive.data'
>     metric_name: 'map'
> ```
> 
> compressor:
> epoch: 120
> #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
> checkpoint_path: './output/checkpoints_prune/'
> strategies:
> - sensitive_pruning_strategy
> 
> 均匀剪裁配置
> version: 1.0
> pruners:
> pruner_1:
> class: 'StructurePruner'
> pruning_axis:
> '_': 0 criterions: '_': 'l1_norm'
> strategies:
> uniform_pruning_strategy:
> class: 'UniformPruneStrategy'
> pruner: 'pruner_1'
> start_epoch: 0
> target_ratio: 0.5
> pruned_params: '.*_sep_weights'
> metric_name: 'map'
> compressor:
> epoch: 120
> #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
> checkpoint_path: './output/checkpoints_prune/'
> strategies:
> - uniform_pruning_strategy
> ~
