### ISSUE TITLE
models/dygraph 下的实现是否可以给出示例任务在 paddle release 版本下性能的 benchmark 

### ISSUE THREAD

**Issue by nbcc** [PaddlePaddle/models#2993]
特别关注 models/dygraph/transformers 相较于静态图在多卡/多机下的性能对比

**Comment by JiabinYang** [comment]
我们会尽快测试

**Comment by DDDivano** [comment]
目前release版本和 dev版本多卡加速比有一定的差距。
![image](https://user-images.githubusercontent.com/10734244/62342671-4ac96300-b51a-11e9-85a5-dea68a0ce7a1.png)
![Uploading image.png…]()

**Comment by nbcc** [comment]
> 目前release版本和 dev版本多卡加速比有一定的差距。
> image
> Uploading image.png…

是基于开源代码直接测试的结果对吧？

针对这个实现 https://github.com/PaddlePaddle/models/blob/ff28150ad982cd96eb4af6ee717813c8f72f6700/dygraph/transformer/train.py#L1136

是否数据并行？是否是 pyreader？是否使用 multi_process ?

贴一下配置吧。

**Comment by DDDivano** [comment]
使用官方源码，官方模型库代码，没有改动

**Comment by DDDivano** [comment]
> > 目前release版本和 dev版本多卡加速比有一定的差距。
> > image
> > Uploading image.png…
> 
> 是基于开源代码直接测试的结果对吧？
> 
> 针对这个实现
> 
> https://github.com/PaddlePaddle/models/blob/ff28150ad982cd96eb4af6ee717813c8f72f6700/dygraph/transformer/train.py#L1136
> 
> 是否数据并行？是否是 pyreader？是否使用 multi_process ?
> 
> 贴一下配置吧。

这个是应RD要求，加速比只算的是计算时间的速度比，没有包括Reader的时间
