### ISSUE TITLE
PaddleSlim对MobileNet进行Uniform剪切报错

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/models#2998]
Windows环境下使用PaddleSlim示例对MobileNet进行Uniform剪切报错
![image](https://user-images.githubusercontent.com/7035538/62279838-70545f00-b47d-11e9-93c8-17f07357e040.png)

Paddle的问题有点多。。。

**Comment by wanghaoshuang** [comment]
抱歉，PaddleSlim没有在windows下测试过，看着像pickle在windows下的编码有问题，导致不能正常load checkpoint, 我这边找环境尝试复现下该问题。

**Comment by A1exy** [comment]
@wanghaoshuang   ubuntu下可以，如果没时间修复就关掉这个issue吧
但是Pruning后的模型  Windows下无法Inference
![image](https://user-images.githubusercontent.com/7035538/62336475-0b434c80-b503-11e9-8e7a-02d11828ace0.png)
