### ISSUE TITLE
PaddleSlim对Uniform剪切后的MobileNet模型进行infer.py报错

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/models#3009]
在Unbutu16.04下，对Uniform剪切后的MobileNet模型进行inference:
![image](https://user-images.githubusercontent.com/7035538/62347533-984ecb80-b52c-11e9-9bc6-6b208c1e3c17.png)
![image](https://user-images.githubusercontent.com/7035538/62347558-abfa3200-b52c-11e9-9fa1-5905d7590ee8.png)

问题真的多，有点醉人。。。

**Comment by wanghaoshuang** [comment]
hi, 你看下你的`checkpoints`路径下是不是有一个`model`文件夹?

`checkpoints`下的`model`保存的是`weights`数据, `strategies`保存的是压缩策略相关的中间数据。load checkpoints的时候要指定到`model`路径。

**Comment by A1exy** [comment]
@wanghaoshuang 
![image](https://user-images.githubusercontent.com/7035538/62516674-48d40c80-b858-11e9-857d-5b8a7f4cbf01.png)
只有输出的模型，用的是默认的配置

**Comment by A1exy** [comment]
![image](https://user-images.githubusercontent.com/7035538/62516753-7c169b80-b858-11e9-9e71-89b4f2610d84.png)
有的

**Comment by A1exy** [comment]
但是Infer找不到操作
![image](https://user-images.githubusercontent.com/7035538/62516832-a9fbe000-b858-11e9-9c9c-c49887870f9e.png)

**Comment by wanghaoshuang** [comment]
infer的脚本贴出来看一下？

**Comment by A1exy** [comment]
用的是models/PaddleCV/image_classification/infer.py，改了下网络配置等东西
![image](https://user-images.githubusercontent.com/7035538/62517279-a74dba80-b859-11e9-82ae-4df998759d4d.png)

**Comment by A1exy** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/infer.py

**Comment by wanghaoshuang** [comment]
有两个问题：

1. 在infer.py里要设置`pretrained_model`为`{your path}/checkpoints/7/model`, 才能招到保存的模型的权重文件。

2. 直接用models/PaddleCV/image_classification/infer.py这个脚本load PaddleSlim产出的weights会有shape不一致的问题。原因如下：
     a. infer.py中定义的卷积的shape为被裁剪之前的
     b. 被load的权重文件中的卷积层的参数是裁剪之后的
   可以按如下方式解决shape不一致问题：

## 通过compressor保存inference model

在[compress.py](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/compress.py#L142)中，使用[save_inference_mode](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#save-inference-model)接口保存裁剪后的网络结构和权重文件：
```
peuned_program = compress_pass.eval_graph.program
fluid.io.save_inference_model("./pruned_model", feeded_var_names=[image.name, label.name], target_vars=[acc_top1], executor, main_program=peuned_program)
```
在infer.py中，使用[load_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#load-inference-model)接口load上边保存的网络结构和权重：
```
infer_program, feed_target_names, fetch_vars = fluid.io.load_inference_model("./pruned_model", exe)
```
然后执行infer_program, 具体细节可参考：https://github.com/PaddlePaddle/models/blob/550a0e2e8764f273eb294b082b721ed5ea3ab14d/PaddleNLP/unarchived/text_classification/infer.py#L27

## load checkpoints for inference

目前直接通过infer.py加载checkpoints有点问题。需要提PR修复一下。

**综上，PaddleSlim需要添加易用的save mode和inference相关的接口。**

**Comment by A1exy** [comment]
@wanghaoshuang  pretrained_model我在命令行里设置了。

**Comment by A1exy** [comment]
@wanghaoshuang  裁剪完确实有问题，按照你说的试一试。
![image](https://user-images.githubusercontent.com/7035538/62520433-2a720f00-b860-11e9-896e-42dbb3d3f518.png)

**Comment by A1exy** [comment]
@wanghaoshuang    
按照你说的方法通过fluid.io.load_inference_model保存的模型：
![image](https://user-images.githubusercontent.com/7035538/62535526-38368d00-b87e-11e9-963a-f60af1cb1341.png)

然后通过fluid.io.load_inference_model调用（主要代码如下）：
results = exe.run(inference_program, feed={feed_target_names[0]: im2}, fetch_list=fetch_targets)
ret = fluid.io.load_inference_model(dirname='./pruned_model', executor=exe)
inference_program, feed_target_names, fetch_targets = ret
with fluid.program_guard(inference_program):
        results = exe.run(inference_program, feed={feed_target_names[0]: im2}, fetch_list=fetch_targets)

但还是报错了：
![image](https://user-images.githubusercontent.com/7035538/62535671-94011600-b87e-11e9-9e0c-a8717cbe14dd.png)

**Comment by wanghaoshuang** [comment]
@slf12 你在做yolov3的时候，帮忙看一下剪切的inference?

按[这个方法](https://github.com/PaddlePaddle/models/issues/3009#issuecomment-518533047)看能否复现[这个问题](https://github.com/PaddlePaddle/models/issues/3009#issuecomment-518626101)

**Comment by A1exy** [comment]
@wanghaoshuang @baiyfbupt    请问这个问题是存在的吗？

**Comment by zzchust** [comment]
请问paddle-slim到底能否正常使用“剪切”？  看了相关issue，我都不敢用了。

**Comment by A1exy** [comment]
@zzchust   我这边实验是能剪切，不能Inference 。然后百度的人也不确认问题也不回复，建议先别用。

**Comment by zzchust** [comment]
@A1exy  我帮你问一下

**Comment by wanghaoshuang** [comment]
>我这边实验是能剪切，不能Inference 。然后百度的人也不确认问题也不回复，建议先别用。

关于infer的问题：
以下代码为保存剪枝后的MobileNetV1模型，然后再做infer

## 保存模型

```
    com_pass = Compressor(
        place,
        fluid.global_scope(),
        fluid.default_main_program(),
        train_reader=train_reader,
        train_feed_list=train_feed_list,
        train_fetch_list=train_fetch_list,
        eval_program=val_program,
        eval_reader=val_reader,
        eval_feed_list=val_feed_list,
        eval_fetch_list=val_fetch_list,
        teacher_programs=teacher_programs,
        train_optimizer=opt,
        distiller_optimizer=distiller_optimizer)
    com_pass.config(args.compress_config)
    com_pass.run()

    pruned_prog = com_pass.eval_graph.program

    fluid.io.save_inference_model("./pruned_model/", [image.name, label.name], [acc_top1], exe, main_program=pruned_prog)
    
    # check the shape of parameters
    for param in pruned_prog.global_block().all_parameters():
        print("name: {}; shape: {}".format(param.name, param.shape))
```

## load inference model

以下代码修改自：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/infer.py
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import time
import sys
import math
import numpy as np
import argparse
import functools

import paddle
import paddle.fluid as fluid
import reader_cv2 as reader
import models
import utils
from utils.utility import add_arguments, print_arguments, check_gpu

parser = argparse.ArgumentParser(description=__doc__)
# yapf: disable
add_arg = functools.partial(add_arguments, argparser=parser)
add_arg('use_gpu',          bool, True,                 "Whether to use GPU or not.")
add_arg('class_dim',        int,  1000,                 "Class number.")
add_arg('image_shape',      str,  "3,224,224",          "Input image size")
add_arg('resize_short_size', int, 256,                  "Set resize short size")
# yapf: enable


def infer(args):
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model("/root/workspace/models/PaddleSlim/pruned_model", exe)
    test_batch_size = 1
    test_reader = reader.val(settings=args, batch_size=test_batch_size)
    feeder = fluid.DataFeeder(place=place, feed_list=feed_target_names, program=inference_program)
    TOPK = 1
    for batch_id, data in enumerate(test_reader()):
        result = exe.run(inference_program,
                         fetch_list=fetch_targets,
                         feed=feeder.feed(data))
        print(result)
        sys.stdout.flush()
def main():
    args = parser.parse_args()
    print_arguments(args)
    check_gpu(args.use_gpu)
    infer(args)


if __name__ == '__main__':
    main()
```

输出如下：
```
[array([0.], dtype=float32)]
[array([0.], dtype=float32)]
[array([0.], dtype=float32)]
[array([0.], dtype=float32)]
...
```

后续，我们会再实验下MobileNetSSD。

**Comment by zzchust** [comment]
@A1exy  MobileNetSSD采用剪枝后模型进行infer，我这边是正常的。只是剪枝失败，相关[issue](https://github.com/PaddlePaddle/models/issues/3110)已经有人在这里回复了。

**Comment by A1exy** [comment]
@zzchust    好的，谢谢。
