### ISSUE TITLE
Failed to download the Chinese LM 

### ISSUE THREAD

**Issue by lispc** [PaddlePaddle/models#301]
The DeepSpeech2 LM cannot be downloaded. I tried `download_lm_ch.sh` or `wget -c 'http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e' -O ./zh_giga.no_cna_cmn.prune01244.klm` directly more than five times yesterday and today from baiduyun server and my own server, every downloading task will fail after exact 60s. Is there any downloading related limit on the download server side?   
The error msg is like below:
```bash
bash -x download_lm_ch.sh
+ source ../../utils/utility.sh
+ URL='http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e'
+ MD5=29e02312deb2e59b3c8686c7966d4fe3
+ TARGET=./zh_giga.no_cna_cmn.prune01244.klm
+ echo 'Download language model ...'
Download language model ...
+ download 'http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e' 29e02312deb2e59b3c8686c7966d4fe3 ./zh_giga.no_cna_cmn.prune01244.klm
+ URL='http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e'
+ MD5=29e02312deb2e59b3c8686c7966d4fe3
+ TARGET=./zh_giga.no_cna_cmn.prune01244.klm
+ '[' -e ./zh_giga.no_cna_cmn.prune01244.klm ']'
++ awk '-F[ ]' '{print $1}'
++ md5sum ./zh_giga.no_cna_cmn.prune01244.klm
+ md5_result=f9daaa02705421bd5450fdfece0ea819
+ '[' 29e02312deb2e59b3c8686c7966d4fe3 == f9daaa02705421bd5450fdfece0ea819 ']'
+ wget -c 'http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e' -O ./zh_giga.no_cna_cmn.prune01244.klm
--2017-09-20 12:21:10--  http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e
Resolving cloud.dlnel.org (cloud.dlnel.org)... 202.108.23.203
Connecting to cloud.dlnel.org (cloud.dlnel.org)|202.108.23.203|:80... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from cloud.dlnel.org attempted to set domain to baidu.com
Length: unspecified [application/force-download]
Saving to: ‘./zh_giga.no_cna_cmn.prune01244.klm’

./zh_giga.no_cna_cmn.prune01244.klm           [                                                                 <=>                  ] 453.00M  8.66MB/s    in 60s     

2017-09-20 12:22:27 (7.54 MB/s) - ‘./zh_giga.no_cna_cmn.prune01244.klm’ saved [475003342]

+ '[' 0 -ne 0 ']'
++ awk '-F[ ]' '{print $1}'
++ md5sum ./zh_giga.no_cna_cmn.prune01244.klm
+ md5_result=36e444b6aefa4f2286e40923dbe9e432
+ '[' '!' 29e02312deb2e59b3c8686c7966d4fe3 == 36e444b6aefa4f2286e40923dbe9e432 ']'
+ return 1
+ '[' 1 -ne 0 ']'
+ echo 'Fail to download the language model!'
Fail to download the language model!
+ exit 1
```

**Comment by llxxxll** [comment]
Thanks for your reporting. From your log, it seems the downloading is interrupted but the exit code for wget is still 0. I have tried using our internal server and everything works well. I will check whether there's flow meter limitation for outside connection. If possible, please try to use some  more powerful tools with resuming function temporarily.

**Comment by Yancey0623** [comment]
It looks like the MD5 does not match,  maybe the models on the Cloud has changed? @pkuyym

**Comment by pkuyym** [comment]
@Yancey1989 Not really, I think there's some problem for the downloading. From the log, we can see that the downloading was interrupted, so the file wasn't complete.

**Comment by typhoonzero** [comment]
This may be the default settings of nginx: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

Will change the settings of our dlnel.org server.

**Comment by typhoonzero** [comment]
Seems our DNS forwarding limits the download, you can set /etc/hosts file mannually adding: 
```
180.76.189.142  cloud.dlnel.org
```

and try download again.

**Comment by lispc** [comment]
Great! Solved!
