### ISSUE TITLE
Cannot allocate GPU memory.

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/models#3011]
Hello, I have a problem.

I successfully run ResNet50 with batch_size 64 on Titan V card (12gb). Even with batch_size 96 it works well, but with batch_size 128 it stops working.

I tried shrinking FLAGS_fraction_of_gpu_memory_to_use from 0.98 (default) even to 0.1 but it doesn't work...

`Cannot malloc 49.0002 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.1. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0.`

What's the problem here? Can you help me with that?

**Comment by wzzju** [comment]
Must you use the batch size value 128? If 96 is OK, can you use it?

**Comment by yw1991** [comment]
> Hello, I have a problem.
> 
> I successfully run ResNet50 with batch_size 64 on Titan V card (12gb). Even with batch_size 96 it works well, but with batch_size 128 it stops working.
> 
> I tried shrinking FLAGS_fraction_of_gpu_memory_to_use from 0.98 (default) even to 0.1 but it doesn't work...
> 
> `Cannot malloc 49.0002 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use or FLAGS_initial_gpu_memory_in_mb or FLAGS_reallocate_gpu_memory_in_mbenvironment variable to a lower value. Current FLAGS_fraction_of_gpu_memory_to_use value is 0.1. Current FLAGS_initial_gpu_memory_in_mb value is 0. Current FLAGS_reallocate_gpu_memory_in_mb value is 0.`
> 
> What's the problem here? Can you help me with that?

change batch_size

**Comment by ghost** [comment]
@wzzju @yw1991 I'd like to use bs128. I know that smaller batch size is ok and I have no problem with that.

Could you at least tell me why it doesn't work? Even if I set `FLAGS_fraction_of_gpu_memory_to_use=0.1` and look at `nvidia-smi` I see that Paddle tries to allocate about 1/10 of memory but the suddenly it tries to allocate all of it and next thing - it crashes with error. So my question is will that be fixed? Is this a bug (like a memory leak) or is it a "feature" that you cannot fix right now?

**Comment by zhhsplendid** [comment]
@gfilipekint , Hi Gabriel

It is a "feature", let me explain it. CUDA API cudaMemAlloc is slow, so PaddlePaddle uses a memory pool to pre-malloc a large GPU spaces and then allocate memory pieces from the pool (in this way, we avoid calling cudaMemAlloc each time). The FLAGS_fraction_of_gpu_memory_to_use=0.1 here means taking the 1/10 of GPU memory to the pool. 

However, if your program takes a large chunk of memory that is more than the pool, PaddlePaddle will still try to get it using  cudaMemAlloc (Although slower than malloc from the pool). That was why you saw it tried to allocate all of GPU and then crashed (no enough GPU even if we allocate out of the pool)

**Comment by ghost** [comment]
Ok I understand. Thank you for your explanation.
