### ISSUE TITLE
yolov3 backbone修改为shufflenetv2后报错

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/models#3018]
修改yolov3代码库中的[basemodel](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/yolov3/models/yolov3.py#L125) 为[shufflenetv2](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/models/shufflenet_v2.py)

错误信息：
![image](https://user-images.githubusercontent.com/6135871/62452916-b70ac780-b7a3-11e9-8a5f-8e16140d8182.png)

错误定位：
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/models/shufflenet_v2.py#L138

**Comment by zzchust** [comment]
貌似已解决，请paddle同学确认。

yolov3 将输入参数random_shape默认设置为True，这导致在read训练数据时，同一batch imagesize相同，不同batch imagesize不同。见[readre.py](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/yolov3/reader.py#L250)

而shufflenetv2中的reshape层似乎不支持这种不同batchsize imagesize不同的情况。 （darknet、mobilenetv1中没有reshape层，所有不会出现错误）。 这里将random_shape设置为False就可以了。

不知道是不是这样的？ 希望paddle同学能解答一下。

**Comment by heavengate** [comment]
reshape里面的height和width是静态的，build_model的时候就确定了的，不支持在训练过程中变化，如果要用reshape的话把random_shape置成False吧

**Comment by zzchust** [comment]
> reshape里面的height和width是静态的，build_model的时候就确定了的，不支持在训练过程中变化，如果要用reshape的话把random_shape置成False吧

最新的动态图构建方式是否支持reshape在训练过程中变化呢？

**Comment by heavengate** [comment]
动态图支持的
