### ISSUE TITLE
Python3 + fluid1.5环境下报错

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/models#3020]
该项目在Python3.5 + fluid1.5 环境下报错：

Traceback (most recent call last):
  File "paragraph_extraction.py", line 198, in <module>
    print(json.dumps(sample, encoding='utf8', ensure_ascii=False))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'

并且，显示无法使用GPU。本地已安装并配置GPU相关环境。

**Comment by wangguibao** [comment]
请您具体描述一下系统环境，例如：
CPU型号
操作系统版本
paddle版本
python版本
GPU型号，GPU驱动版本，CUDA版本
。。
这些会帮助我们定位问题，谢谢

**Comment by wangguibao** [comment]
```
并且，显示无法使用GPU。本地已安装并配置GPU相关环境。
```
这个位置的报错信息也贴一下哈

**Comment by wangguibao** [comment]
Hi，该issue已经2个月了，我先关闭了。如有需要，可以提供一下更详细的出错信息，再重新打开issue
