### ISSUE TITLE
Enforce failed. Expected numel() >= 0, but received numel():-1179648 < 0:0.

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#3021]
when i use PaddleCV/ocr_recognize to train my own dataset, it occurs error as follow:
________________________________________________________________________________________________________
![image](https://user-images.githubusercontent.com/13143336/62462996-74ed8000-b7bb-11e9-9c56-cab63545c8eb.png)
![image](https://user-images.githubusercontent.com/13143336/62463047-92224e80-b7bb-11e9-87bf-c38d7835f3bc.png)
![image](https://user-images.githubusercontent.com/13143336/62463060-99e1f300-b7bb-11e9-8c9b-f07ac00d20e8.png)
![image](https://user-images.githubusercontent.com/13143336/62463090-b0884a00-b7bb-11e9-91a3-c5c4c28d9762.png)
![image](https://user-images.githubusercontent.com/13143336/62463105-bb42df00-b7bb-11e9-8705-9a4df401d7fe.png)
![image](https://user-images.githubusercontent.com/13143336/62463114-c3028380-b7bb-11e9-897b-c94038341163.png)
![image](https://user-images.githubusercontent.com/13143336/62463127-ca299180-b7bb-11e9-8121-368c49d42563.png)
__________________________________________________________________________________________
I don't know why..

**Comment by wangguibao** [comment]
Hi, would you please copy error info in text format into this issue, I'm having trouble reading the text in your screen snapshots...

But don't worry, I'm looking into it at my best

**Comment by wangguibao** [comment]
Also, please describe in detail your training steps and command in each step, including downloading data, downloading pretrained model, training etc.

**Comment by wangguibao** [comment]
Hi，该issue已经2个月时间了，我先关闭了。如有需要可以提供一下文字的出错信息，再重新打开此issue。谢谢
