### ISSUE TITLE
句法分析

### ISSUE THREAD

**Issue by AnShengqiang** [PaddlePaddle/models#3022]
您好，是否可以提供基于ERNIE的句法分析模型？

**Comment by xyzhou-puck** [comment]
您好，目前暂时没有句法分析模型，请问是什么类型的句法分析？

**Comment by AnShengqiang** [comment]
> 您好，目前暂时没有句法分析模型，请问是什么类型的句法分析？

您好，感谢您的回复。我想提取中文句子的主谓宾，就想到了先用句法分析去分析中文句子，得到句子结构，然后根据句子结构去提取主谓宾。

目前一些开源句法分析的准确率不太够，就想着用ERNIE来做。

请问您能给一些建议吗？

**Comment by AnShengqiang** [comment]
请问以后会有吗？
百度会坚持做paddle及其相关的开源吗？
值得信任吗？

**Comment by xyzhou-puck** [comment]
抱歉回复晚了，百度一定会坚持做paddle和其周边的开源项目的。

**Comment by xyzhou-puck** [comment]
目前还缺少使用ernie做句法分析的算法，如果方便的话，能否详细描述一下场景，想要解决的问题，句法分析怎么发挥作用等内容？

**Comment by AnShengqiang** [comment]
得到您的回复就够了，虽然没有句法分析，但我会继续使用paddle的。
谢谢。
