### ISSUE TITLE
NeXtVLAD模型使用cpu进行预测时（use_gpu=False）出现错误：RuntimeError: code is too big

### ISSUE THREAD

**Issue by GeTai** [PaddlePaddle/models#3023]
我在gpu环境下，能够正确运行NeXtVLAD模型进行预测，但是选择使用cpu（use_gpu=False）后，会出现RuntimeError: code is too big

**Comment by wangguibao** [comment]
帮用户补充一些信息：
我在gpu环境下，能够正确运行NeXtVLAD模型进行预测，但是选择使用cpu（use_gpu=False）后，会出现以下错误：
![1](https://user-images.githubusercontent.com/1445888/62470236-9014bb80-b7cc-11e9-8e96-a5d5d854cb64.png)

在使用cpu预测的话，需要特殊的配置吗？

**Comment by wangguibao** [comment]
![2](https://user-images.githubusercontent.com/1445888/62470256-a0c53180-b7cc-11e9-9b9b-ad08e74814d1.PNG)

**Comment by gavin1332** [comment]
> 在使用cpu预测的话，需要特殊的配置吗？

使用CPUPlace？

**Comment by GeTai** [comment]
> > 在使用cpu预测的话，需要特殊的配置吗？
> 
> 使用CPUPlace？

已经使用CPUPlace

**Comment by SunGaofeng** [comment]
目前排查是cpu版的sequnce pool op报的这个错误，正在查找具体原因

**Comment by ucas010** [comment]
@GeTai 
大佬请问下推断用的哪个模型啊？是final吗？
对图像帧进行读取，需要修改哪里啊？
多谢
