### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by mamingjie-China** [PaddlePaddle/models#3030]
文档链接：https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/docs/usage.md
![d66ddfa2fecad0a18a853043d4fe2edd](https://user-images.githubusercontent.com/52770436/62527062-09fc8180-b86d-11e9-9402-4a45e96737fc.png)
这里应为『该』
![a039de6a479f3a41ec32a02127f1c6b2](https://user-images.githubusercontent.com/52770436/62527095-1a146100-b86d-11e9-8852-1ce3597909a4.png)
这里多了个字

**Comment by baiyfbupt** [comment]
感谢反馈，我们会尽快修正
