### ISSUE TITLE
CTR Demo Bug

### ISSUE THREAD

**Issue by Fangkey** [PaddlePaddle/models#305]
In train.py line 89, dataset.test(args.test_data_path) will set the data file path to test data. For in line 105, train function use the same dataset object, after one call for `__event_handler__` `if event.batch_id % 1000 == 0`, the dataset will change to test data permanently and the following training iteration will use test data. That is not what we expect, check please.

**Comment by lcy-seso** [comment]
@ranqiu92 would you please help to check this. Thank you very much.

**Comment by ranqiu92** [comment]
It's a bug of reader.py, and now we have fixed it.
https://github.com/PaddlePaddle/models/pull/313
