### ISSUE TITLE
百度之星Demo(int 8量化)baseline model量化后map很低

### ISSUE THREAD

**Issue by ZiruiChen** [PaddlePaddle/models#3057]

**Comment by ZiruiChen** [comment]
![D79DF0DEA5340A158019EC15CFEFA562](https://user-images.githubusercontent.com/50459712/62682703-254bc600-ba00-11e9-81b1-645e540b0e47.png)
载入了baselinemodel的参数 loss值5开始 然后保持在十左右 符合demo的输出 但是到evaluation 部分 map很低

**Comment by ZiruiChen** [comment]
![1AC97C9F24BF5F08957CBA8DDA3CD7B5](https://user-images.githubusercontent.com/50459712/62682856-765bba00-ba00-11e9-85e9-70c87a60e46c.png)

**Comment by adaxi987** [comment]
@ZiruiChen 这个内容可以描述的再清晰点吗，比如跑的什么模型，环境系统配置，这样才能更好的debug问题哈

**Comment by ZiruiChen** [comment]
> @ZiruiChen 这个内容可以描述的再清晰点吗，比如跑的什么模型，环境系统配置，这样才能更好的debug问题哈

  谢谢 我已经解决了
