### ISSUE TITLE
PaddleSlime量化后的模型是否对server-intelCPU的inference有加速作用

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/models#3072]
如题。

目前针对server-intelCPU进行速度优化，希望之后经过paddleslim量化的model，使用paddle-cpu版本进行inference是否会有加速作用？

针对server-intelCPU， paddle有哪些加速策略？
我能想到的： 小型化模型、剪枝、mkldnn加速库

**Comment by tensor-tang** [comment]
您好，抱歉回复晚了。

是的。
我们与Intel一起合作完成了量化方案，量化的模型可以采用Intel int8的算子，会使用MKL-DNN加速以获取更高的加速效果。

同时，我们与Intel也是长期稳定的合作伙伴，我们的量化模型在其新架构上也可以发挥非常好的性能。

**Comment by zzchust** [comment]
嗯，感谢回复。

是否有量化后的速度对比呢？（GPU/手机端/CPU端），目前只看到了准确度和模型大小的对比。

**Comment by wzzju** [comment]
> 嗯，感谢回复。
> 
> 是否有量化后的速度对比呢？（GPU/手机端/CPU端），目前只看到了准确度和模型大小的对比。

可以在paddle的release note里看到int8的性能数据：https://github.com/PaddlePaddle/Paddle/releases （搜索关键字“量化”）。Intel cpu目前支持量化训练产出的模型运行在Intel int8 kernels上。在7个模型上（GoogleNet, MobileNetV1, MobileNetV2, VGG16, VGG19, ResNet50, ResNet101），Intel int8预测引擎推理结果和在FP32 kernels上模拟int8运行相比，精度变化在0.1%以内。然而，量化训练模型在intel cpu上进行推理的性能仍在优化中，目标是与离线量化的性能对齐。目前，离线量化目前的性能为：INT8量化后的ResNet-50/MobileNet v1模型，相比原始FP32模型，性能分别提升至3.7倍/3.0倍 （在支持AVX512-DL Boost指令集的至强 6271服务器上）。

**Comment by zzchust** [comment]
> > 嗯，感谢回复。
> > 是否有量化后的速度对比呢？（GPU/手机端/CPU端），目前只看到了准确度和模型大小的对比。
> 
> 可以在paddle的release note里看到int8的性能数据：https://github.com/PaddlePaddle/Paddle/releases （搜索关键字“量化”）。Intel cpu目前支持量化训练产出的模型运行在Intel int8 kernels上。在7个模型上（GoogleNet, MobileNetV1, MobileNetV2, VGG16, VGG19, ResNet50, ResNet101），Intel int8预测引擎推理结果和在FP32 kernels上模拟int8运行相比，精度变化在0.1%以内。然而，量化训练模型在intel cpu上进行推理的性能仍在优化中，目标是与离线量化的性能对齐。目前，离线量化目前的性能为：INT8量化后的ResNet-50/MobileNet v1模型，相比原始FP32模型，性能分别提升至3.7倍/3.0倍 （在支持AVX512-DL Boost指令集的至强 6271服务器上）。

了解了。 希望后续能在针对量化使用有具体的demo。 
之前在object-detection的repo中有过，后来这个repo被删除了。

paddleslim的封装层次又太高，使用起来也不灵活。
