### ISSUE TITLE
SSD模型加载预训练模型准确率很低

### ISSUE THREAD

**Issue by liuzengzhen1** [PaddlePaddle/models#3080]
1.根据文档下载pascalvoc数据，以及预训练模型
2.调试相应参数执行train.py 

-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 8
data_dir: D:/untitled/pratice/ssd/data/pascalvoc
dataset: pascalvoc
enable_ce: False
epoc_num: 1000
image_shape: 3,300,300
learning_rate: 0.001
mean_BGR: 127.5,127.5,127.5
model_save_dir: D:\untitled\pratice\ssd\model
parallel: 0
pretrained_model: D:\untitled\pratice\ssd\pretrained\mobilenet_v1_imagenet
use_gpu: 0
-------------------------------------
3.执行结果：
Batch 10, map [0.00233454]
Batch 20, map [0.00179878]
Batch 30, map [0.00124445]
Batch 40, map [0.00154742]
Batch 50, map [0.00117008]
Batch 60, map [0.00101512]
Batch 70, map [0.0009321]
Batch 80, map [0.00084877]
Batch 90, map [0.00079377]
Batch 100, map [0.00078082]
Batch 110, map [0.00077564]
Batch 120, map [0.00079855]
Batch 130, map [0.00077792]
Batch 140, map [0.00077779]
Batch 150, map [0.00077369]
Batch 160, map [0.00073959]
Batch 170, map [0.00072543]
Batch 180, map [0.00071779]
Batch 190, map [0.00069148]
Batch 200, map [0.00067471]
Batch 210, map [0.00065191]
Batch 220, map [0.00062474]
Batch 230, map [0.00062316]
Batch 240, map [0.00062389]

请问执行准确率这么低是什么原因？，是我操作传入参数有问题么？另外这个模型提供预训练模型，我想看下实际的准确率情况能否直接infer.py，将model_dir更改为预训练模型路径？我尝试了下报错，是不能这样验证么？

**Comment by qingqing01** [comment]
1. 如果是训练，参考文档，https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/README_cn.md#%E4%B8%8B%E8%BD%BD%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B

 建议下载COCO的预训练模型，我们最终release的73.32%的模型，是2个GPU，如下方式训练:


```
./pretrained/download_coco.sh
python -u train.py --batch_size=64 --dataset=pascalvoc --pretrained_model=pretrained/ssd_mobilenet_v1_coco/
```


2.  想看下实际的准确率，可以下载最后发布的模型，下载模型 http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz (见文档的最后) ，参考模型评估部分:

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/README_cn.md#%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0

```
python eval.py --dataset=pascalvoc --model_dir=ssd_mobilenet_v1_pascalvoc  --data_dir=data/pascalvoc
```

另外，也推荐使用PaddleDetection  https://github.com/PaddlePaddle/models/tree/release/1.5/PaddleCV/PaddleDetection

**Comment by liuzengzhen1** [comment]
@qingqing01 我就是参照那个文档做的训练，但是迭代下来准确率很低我上面提供的那样，这样是正常么，我理解在pretrained_model的基础上做训练应该不能这么低吧？数据集就是用的pascalvoc下的VOC2007，按您的建议已经将pretrained_model 改成 pretrained/ssd_mobilenet_v1_coco/，但是效果依然是之前那样？

**Comment by qingqing01** [comment]
@liuzengzhen1  ` pretrained/ssd_mobilenet_v1_coco/` 这不是一个完整的模型，只包含backbone的MobileNet部分，直接用这个做评估，mAP会很低。

看log您是做评估，而不是训练吧？ 


下面是我复现的结果:

训练的话，用这个做初始化，batch size=64 (保证BatchNorm所需的batch size不能太小), ssd_mobilenet_v1_coco也加载正常的话，log如下，在VOC数据上第一轮的loss大约在39左右:

env CUDA_VISIBLE_DEVICES=0,1 python train.py --data_dir=data/

```
-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 64
data_dir: data/pascalvoc/
dataset: pascalvoc
enable_ce: False
epoc_num: 120
image_shape: 3,300,300
learning_rate: 0.001
mean_BGR: 127.5,127.5,127.5
model_save_dir: model
parallel: True
pretrained_model: pretrained/ssd_mobilenet_v1_coco/
use_gpu: True
use_multiprocess: True
------------------------------------------------

Epoc 0, batch 0, loss 39.210991, time 0.02125
Epoc 0, batch 10, loss 11.298708, time 0.41876
Epoc 0, batch 20, loss 8.089873, time 0.39140
Epoc 0, batch 30, loss 7.519194, time 0.37615
```
如果，您是CPU训练，设置 `export CPU_NUM=2`，再启动训练，并加--use_gpu=False，但CPU训练比较慢。


直接用发布的模型评估，结果也没问题:

```
wget  http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz
env CUDA_VISIBLE_DEVICES=0 python eval.py --model_dir=ssd_mobilenet_v1_pascalvoc


-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 32
data_dir:
dataset: pascalvoc
mean_value_B: 127.5
mean_value_G: 127.5
mean_value_R: 127.5
model_dir: ssd_mobilenet_v1_pascalvoc
nms_threshold: 0.45
resize_h: 300
resize_w: 300
test_list:
use_gpu: True
------------------------------------------------

Batch 0, map [0.80286217]
Batch 10, map [0.75623477]
Batch 20, map [0.7377805]
Batch 30, map [0.73261887]
Batch 40, map [0.7335851]
Batch 50, map [0.73700464]
Batch 60, map [0.7365286]
Batch 70, map [0.7336825]
Batch 80, map [0.7370831]
Batch 90, map [0.7375254]
Batch 100, map [0.7382971]
Batch 110, map [0.73366314]
Batch 120, map [0.73528475]
Batch 130, map [0.7328397]
Batch 140, map [0.7332184]
Batch 150, map [0.7329098]
Test model ssd_mobilenet_v1_pascalvoc, map [0.7332185]
```

**Comment by liuzengzhen1** [comment]
@qingqing01 非常感谢，我是win10环境，训练的时候Can't pickle local object 'multiprocess_reader.<locals>._read_into_queue'，我看之前有人提过这个issue，是因为多进程reader目前在win上还没有支持所以报错，导致没办法train训练，请问这个问题有修复么，或者更改哪里可以避免这个错误正常训练

**Comment by liuzengzhen1** [comment]
有木有绕行方案

**Comment by qingqing01** [comment]
@liuzengzhen1 最新版本的代码支持设置设置 --use_multiprocess=False

<img width="1090" alt="图片" src="https://user-images.githubusercontent.com/7845005/62857644-bab1c780-bd2a-11e9-93f5-c15a96b0ff86.png">
