### ISSUE TITLE
PaddleDetection  使用 save_infer_model 后的模型infer报错 

### ISSUE THREAD

**Issue by xuzhm** [PaddlePaddle/models#3085]
Enforce failed. Expected out_h > 0, but received out_h:0 <= 0:0   

_upsample  时， out_shape 为0 ， 怀疑save_infer_model 没有保存获取 shape 的操作 shape_nchw = fluid.layers.shape(input)  导致

**Comment by wopeizl** [comment]
贴一下代码吧

**Comment by xuzhm** [comment]
![image](https://user-images.githubusercontent.com/6814767/62851584-36a31400-bd19-11e9-880d-d37c207b04bf.png)
这是save_infer_model  代码， 使用的https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/tools/infer.py

![image](https://user-images.githubusercontent.com/6814767/62851593-41f63f80-bd19-11e9-8f79-590f2ae7820f.png)

**Comment by qingqing01** [comment]
@xuzhm 请问您保存模型是如何保存的，输入的shape是多少？ 默认是608x608，您给的输入数据是多大？

**Comment by xuzhm** [comment]
用示例代码保存的， 输入 shape 是   1， 3，  608， 608

**Comment by heavengate** [comment]
未复现该问题，请检查下你做infer的时候数据读取是否正确，feed数据的shape是否正确

**Comment by xuzhm** [comment]
使用最新版 so  >= 1.5  解决问题，infer 正常
