### ISSUE TITLE
GPU is not fully utilized

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#3096]
when I use PaddleCV/ocr_recognition to train a recognition model, I found my four GPU only used one, other three GPU not be fully used, the result is as follows:

![7610aacf88d8b1906a36bf597](https://user-images.githubusercontent.com/13143336/62868851-27d45580-bd49-11e9-940e-247faec3f936.png)

Can anyone help to solve this problem?

**Comment by SunGaofeng** [comment]
By default, PaddleCV/ocr_recognition will run in single GPU. If you want to use multiple GPUs, please use the following command line to start training program.

    env CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --parallel=True

For more details please refer to the document     
 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/README.md

**Comment by endy-see** [comment]
Thank you very much! I found that I only set CUDA_VISIBLE_DEVICES=0,1,2,3, but I not set --parallel=True, so It's my fault. Thanks again!
