### ISSUE TITLE
win10 YOLOv3 安装COCO-API报错

### ISSUE THREAD

**Issue by liuzengzhen1** [PaddlePaddle/models#3098]
1.参照介绍文档安装报错
`$ make install
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
make: *** [Makefile:8: install] Error 1
`
2.根据百度提示需要安装visual Studio 环境可以避免，在电脑安装Visual Studio 2015依然无法解决
<img width="332" alt="微信图片_20190813145530" src="https://user-images.githubusercontent.com/52186737/62921247-bd6bf580-bdda-11e9-938e-8a0540e61128.png">

3.python 版本3.5.2

**Comment by heavengate** [comment]
win10安装pycocotools可参考https://blog.csdn.net/dreamer_18/article/details/88065411

**Comment by liuzengzhen1** [comment]
安装Windows10SDK和.NET框架，默认安装Microsoft Visual 不好使 ，非常感谢支持@heavengate
