### ISSUE TITLE
关于fluid.layers.detection 中函数使用的疑问

### ISSUE THREAD

**Issue by WangTaoSpace** [PaddlePaddle/models#3116]
detection_output 这个函数的功能是否等同于  box_coder（解码）+ multiclass_nms
我针对官方ssd模型的输出利用上面两种方法获取nms_out进行比较发现差距比较大。部分代码如下
1. 
```
image = fluid.layers.data(name='image', shape=[3,300,300], dtype='float32')
locs, confs, box, box_var = mobilenet_ssd.build_mobilenet_ssd(image, 81, [3,300,300])
boxes = fluid.layers.box_coder(box,box_var,locs,code_type="decode_center_size")
scores = fluid.layers.transpose(confs,perm=[0,2,1])
nms_out = fluid.layers.multiclass_nms(
            bboxes=boxes,
            scores=scores,
            score_threshold=0.01,
            nms_top_k=-1,
            nms_threshold=0.45,
            keep_top_k=-1,
            normalized=False)
```
2.
```
image = fluid.layers.data(name='image', shape=[3,300,300], dtype='float32')
locs, confs, box, box_var = mobilenet_ssd.build_mobilenet_ssd(image, 81, [3,300,300])
nms_out = fluid.layers.detection_output(
            locs, confs, box, box_var, nms_threshold=0.45)
```
如果第一种方法有误，望指点正确的操作，谢谢。

**Comment by sandyhouse** [comment]
![image](https://user-images.githubusercontent.com/6737864/63141591-e7aaf680-c018-11e9-8599-a1847450aada.png)
detection_output本身的实现也是通过box_coder和multiclass_nms实现的。可以对比下方法1的实现是否有diff。

**Comment by sandyhouse** [comment]
decoded_box = box_coder(
        prior_box=prior_box,
        prior_box_var=prior_box_var,
        target_box=loc,
        code_type='decode_center_size')
    scores = nn.softmax(input=scores)
    scores = nn.transpose(scores, perm=[0, 2, 1])
    scores.stop_gradient = True
    nmsed_outs = helper.create_variable_for_type_inference(
        dtype=decoded_box.dtype)
    helper.append_op(
        type="multiclass_nms",
        inputs={'Scores': scores,
                'BBoxes': decoded_box},
        outputs={'Out': nmsed_outs},
        attrs={
            'background_label': 0,
            'nms_threshold': nms_threshold,
            'nms_top_k': nms_top_k,
            'keep_top_k': keep_top_k,
            'score_threshold': score_threshold,
            'nms_eta': 1.0
        })
    nmsed_outs.stop_gradient = True
    return nmsed_outs

**Comment by WangTaoSpace** [comment]
感谢，GitHub上有源码我竟然没看，麻烦了。
