### ISSUE TITLE
DeepCTR 的数据读取问题

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/models#3123]
如题，DeepCTR的reader是不是针对raw data写的，而不是preprocess写的，使用preprocess处理过数据后，数据存储的格式和raw data不一样，但是reader的读取方式看起来应该时读取raw data的方式~

**Comment by ceci3** [comment]
您说的preprocess指的是？

**Comment by wwjjy** [comment]
这个项目提供的preprocess脚本啊，https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/preprocess.py 这个

**Comment by ceci3** [comment]
<img width="683" alt="屏幕快照 2019-08-16 下午7 57 43" src="https://user-images.githubusercontent.com/29245900/63166166-23b57a00-c060-11e9-82bc-ff4732d2f480.png">
这个文件好像是集群训练时用到的

**Comment by ceci3** [comment]
这是中文版的readme   https://github.com/PaddlePaddle/models/blob/develop/PaddleRec/ctr/README.cn.md

**Comment by wwjjy** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/20850734/63166326-a9392a00-c060-11e9-84fb-db838d8d9710.png">
那希望可以在这里明确一下~  本地的训练不需要这一步

**Comment by ceci3** [comment]
好的，我记录一下~ 这个issue我先关闭了，有问题您可以再打开。
