### ISSUE TITLE
更换optimizer恢复训练

### ISSUE THREAD

**Issue by fengchun1213** [PaddlePaddle/models#3137]
先使用Adadelta训练，使用save_persistables保存模型，现在想换adam继续训练，但是由于adam参数多了，比如moment，那么请问应该怎么加载之前训练的模型呢？

**Comment by liupluswei** [comment]
可以用https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#load-params

**Comment by fengchun1213** [comment]
> 可以用https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#load-params

多谢！！！
