### ISSUE TITLE
如何将pretrained-model的参数名称与模型配置文件中的层一一对应

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/models#3148]
现有一模型的配置文件以及对应的pretrained model，pretrained model的参数名称由系统默认赋予。
 
现在修改模型的配置文件，对每层的参数赋予自定义名称，如何将这些自定义的名称pretrained model参数一一对应起来呢？

**Comment by wanghaoshuang** [comment]
建议您在修改模型的配置文件之前，用以下方式打印出所有参数：
```
for block in default_main_program().blocks:
    for param in block.all_parameters():
        print param.name
```
上述脚本输出存入文件： ori_names.data

然后修改模型的配置文件，对每层的参数赋予自定义名称，然后在用上述脚本将修改后的参数名存入文件：new_names.data

最后，merge `ori_names.data`和`new_names.data`就是你要找的映射关系了。

理论上，parameters的遍历都是有序的，如果你不放心，可以根据经验review下映射关系是否正确。

**Comment by wanghaoshuang** [comment]
[models/PaddleCV/image_classification](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification)下release的pretrained model都是把每个parameter存为了一个文件, 你按刚才得到的映射关系重命名下文件名就行。

**Comment by zzchust** [comment]
谢谢，明白了。
