### ISSUE TITLE
failed to install swig_decoders

### ISSUE THREAD

**Issue by zhaifly** [PaddlePaddle/models#315]
hi!
when i run 'models/deep_speech_2/setup.sh'
it always says ''module' object has no attribute 'ccompiler'' and failed to install swig_decoders
![image](https://user-images.githubusercontent.com/6188797/30797554-101ed616-a209-11e7-9992-0297e9d812e4.png)

my env:
 centos:7.3
 python:2.7.5
 gcc: 4.8.5

also: when i run 'python setup.py install --num_processes 4' in 'models/deep_speech_2/decoders/swig'
the following error comes:
![image](https://user-images.githubusercontent.com/6188797/30799129-63ead984-a20e-11e7-917e-38576e02390d.png)

anyone can help me!
very thanks!

**Comment by pkuyym** [comment]
Could you provide the version of your ```distutils``` package?

**Comment by zhaifly** [comment]
thanks  very much for your reply!

![image](https://user-images.githubusercontent.com/6188797/30809317-e7462bf6-a233-11e7-9549-04d1c0a7984b.png)

**Comment by kuke** [comment]
Can you import ```ccompiler``` from terminal?

**Comment by pkuyym** [comment]
Sorry for this error. It seems that ```ccompiler``` is deprecated in newer version of distutils. Our test environment is python 2.7.3 and will find some solutions.

**Comment by zhaifly** [comment]
@kuke cannot import ccompiler
@pkuyym thanks and i will try python 2.7.3 later!

**Comment by pkuyym** [comment]
I just found that python2.7.10 contains ```distutils.ccompiler.CCompiler.compile```. Please make sure after importing ```from setuptools import setup, Extension, distutils```, ```distutils.ccompiler.CCompiler.compile``` can be found. Maybe some dependencies are missing like one of ```setup, Extension```

**Comment by zhaifly** [comment]
@pkuyym distutils.ccompilser.CCompiler.compile can be found with python 2.7.13
but still flailed to install swig_decoders
![image](https://user-images.githubusercontent.com/6188797/30811914-10aa146e-a23c-11e7-82e7-128a3a5b18bb.png)

**Comment by pkuyym** [comment]
Please goto ```decoders/swig``` to run ```sh setup.sh``` and you will see more detailed information.

**Comment by zhaifly** [comment]
here is the output log after run 'sh setup.sh'
[log.txt](https://github.com/PaddlePaddle/models/files/1329785/log.txt)

**Comment by kuke** [comment]
Seems that you have installed ```swig_decoders``` successfully

**Comment by zhaifly** [comment]
@kuke I rebuild paddle with python 2.7.10, and re-setup deep_speech_2, but still have this issue
![image](https://user-images.githubusercontent.com/6188797/30840795-ebb85f4c-a2ab-11e7-9a9d-3b6c6a6a5056.png)

![image](https://user-images.githubusercontent.com/6188797/30840937-90167650-a2ac-11e7-97ac-0fc37ca65be8.png)

**Comment by zhaifly** [comment]
@kuke when I run 'swig -python -c++ ./decoders.i'
swig version:2.0.10
error occurs!
![image](https://user-images.githubusercontent.com/6188797/30844385-679ae782-a2c1-11e7-952b-5a16e3aab5ed.png)

**Comment by zhaifly** [comment]
thanks you all @pkuyym @kuke 
this issue is relevant to swig, after upgrade from 2.0.10 to 3.0.12, everything goes well

**Comment by rituraj17** [comment]
@zhaifly how were you able to change the swig version from 2.0.10 to 3.0.12

I have downloaded the swig 3.0.12 from this link http://www.swig.org/download.html
and the followed the below process to install which is given in this link http://swig.org/svn.html

even after it successfully installed it gives the below  output

```
[root@redhat-7 test120]# swig -version
bash: /bin/swig: No such file or directory
```

**Comment by dancinghui** [comment]
@rituraj17  I install successfully following the README file in the download from this link http://www.swig.org/download.html
