### ISSUE TITLE
量化后模型的保存问题

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/models#3162]
在使用paddle slim进行量化训练时，发现量化后保存的模型结构如下图所示：
<img width="513" alt="image" src="https://user-images.githubusercontent.com/20850734/63481361-c8ecaa00-c4c7-11e9-98aa-f7a8d9ba63b9.png">
训练阶段有没有哪个参数可以让模型保存的时候，保持原来的模型结构不变，也就是不保存图中的fake_quantize_abs_max和fake_dequantize_abs_max。或者可以在模型load进来后，通过哪种操作可以达到上述目的。

**Comment by wzzju** [comment]
您好！您做了量化就需要这些fake_quantize op，这些op提供了int8计算所需的scale，在fluid中load量化模型无法删除fake_quantize_abs_max和fake_dequantize_abs_max等op，因为删除了也不能正确运行量化模型。如果您有特殊需求，您需要修改加载进来的模型，在删除fake_quantize_abs_max和fake_dequantize_abs_max这些op时需要将这些op中提供的scale传入相应的int8计算kernel。我们的PaddlLite预测库加载量化训练得到的模型时会使用[QuantDequantFusePass](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/core/mir/fusion/quant_dequant_fuse_pass.cc)和[QuantDequantOpFuser](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/core/mir/fusion/quant_dequant_op_fuser.cc)将这些fake_quantize op进行融合以进行加速量化预测过程。

**Comment by wwjjy** [comment]
@wzzju  您好，『如果您有特殊需求，您需要修改加载进来的模型，在删除fake_quantize_abs_max和fake_dequantize_abs_max这些op时需要将这些op中提供的scale传入相应的int8计算kernel』能不能详细的说明一下具体怎么做嘞，辛苦您啦

**Comment by wzzju** [comment]
> @wzzju 您好，『如果您有特殊需求，您需要修改加载进来的模型，在删除fake_quantize_abs_max和fake_dequantize_abs_max这些op时需要将这些op中提供的scale传入相应的int8计算kernel』能不能详细的说明一下具体怎么做嘞，辛苦您啦

抱歉，我具体也没有这么做过。您具体可以参考PaddlLite预测库中与您的特殊需求相关的代码：[QuantDequantFusePass](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/core/mir/fusion/quant_dequant_fuse_pass.cc)和[QuantDequantOpFuser](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/core/mir/fusion/quant_dequant_op_fuser.cc)。
