### ISSUE TITLE
YoloV3的Darknet53有了，什么时候可以上线一个Tiny-yolo？

### ISSUE THREAD

**Issue by kiols6** [PaddlePaddle/models#3165]
YoloV3的Darknet53有了，什么时候可以上线一个Tiny-yolo？

**Comment by qingqing01** [comment]
@kiols6 感谢关注， 在PaddleDetection 中 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/MODEL_ZOO.md#yolo-v3-on-pascal-voc  我们提供了 MobileNet-Yolov3, ResNet34 Yolov3。  Tiny-Yolo我们内部讨论下看。

**Comment by kiols6** [comment]
谢谢，那请问如何替换网络结构的部分
