### ISSUE TITLE
PaddleDetection 中的 test_architectures.py 存在路径错误

### ISSUE THREAD

**Issue by snowhou** [PaddlePaddle/models#3172]
运行`python ppdet/modeling/tests/test_architectures.py`出现如下错误
![image](https://user-images.githubusercontent.com/38153092/63576862-aa69da00-c5bf-11e9-8e2e-54facb9ccae8.png)
**下图`test_architectures.py`中`ssd_mobilenet_v1_voc.yml`的路径应改为`configs/ssd/ssd_mobilenet_v1_voc.yml`**
![image](https://user-images.githubusercontent.com/38153092/63576693-50691480-c5bf-11e9-857e-d02d8e290bfe.png)
修改后测试 OK
![image](https://user-images.githubusercontent.com/38153092/63576781-7f7f8600-c5bf-11e9-8292-58d853773149.png)

**Comment by ysh329** [comment]
好的 已解决，后续我们会按照您的修改意见完善代码
