### ISSUE TITLE
PaddleDetection eval 时内存溢出

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#3179]
在进行se154的模型eval.py的时候，电脑的内存使用不断增长，最终内存使用完毕，电脑死机，过一段时间自动killed。

**Comment by MRXLT** [comment]
你好，请问你的电脑内存是多少呢

**Comment by qingqing01** [comment]
@Universea 请问您使用的是GPU还是CPU？ 是什么机器？具体环境是啥？

**Comment by universea** [comment]
你好，环境是ubuntu18.04 ，内存16G , GPU是1080ti

**Comment by jerrywgz** [comment]
可以先尝试下 export FLAGS_eager_delete_tensor_gb=0 这个flag
