### ISSUE TITLE
stnet网络模型的infer.list制作

### ISSUE THREAD

**Issue by LALAliyao** [PaddlePaddle/models#3180]
请问在paddlevideo中使用stnet模型训练完毕后，怎样制作infer.ist进行推断？同时为什么在aistudio上面保存的checkpoints文件打不开？

**Comment by MRXLT** [comment]
![image](https://user-images.githubusercontent.com/16594411/63665909-f73bf380-c7ff-11e9-8515-3bd7fc22b4b6.png)
你好，请问infer.list是指的filelist吗还是预测接口

**Comment by LALAliyao** [comment]
预测时，还要上传pkl文件进行预测，那预测的pkl里面如果没有标签的话会报错，所以封装pkl的时候还是要把标签打包进pkl对吗

**Comment by SunGaofeng** [comment]
1、在stnet的reader程序里面，预测的时候，标签是视频的id，以便将视频id和预测结果对应起来。
2、预测的时候，支持使用文件list，或者指定单个视频源文件（mp4或者mkv格式等）

**Comment by SunGaofeng** [comment]
预测的时候，标签是视频id，便于将视频id和预测结果对应起来

**Comment by LALAliyao** [comment]
好的，谢谢解答



---原始邮件---
发件人: "SunGaofeng"<notifications@github.com&gt;
发送时间: 2019年8月27日(星期二) 下午4:36
收件人: "PaddlePaddle/models"<models@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"LALAliyao"<1907381057@qq.com&gt;;
主题: Re: [PaddlePaddle/models] stnet网络模型的infer.list制作 (#3180)



预测的时候，标签是视频id，便于将视频id和预测结果对应起来
