### ISSUE TITLE
mobilenetSSD剪裁后map降低很多

### ISSUE THREAD

**Issue by ZiruiChen** [PaddlePaddle/models#3185]
mobilenetssd能加载预训练模型，通过打印parameter以及计算MAdds也能反映剪裁成功，加载预训练模型单纯量化训练的map值为0.19, 加入剪裁策略后得到模型预测map趋于0
![图片](https://user-images.githubusercontent.com/50459712/63667915-cb793780-c818-11e9-9c9c-0b308f1c7ec6.png)

**Comment by ZiruiChen** [comment]
@slf12 @wanghaoshuang

**Comment by slf12** [comment]
请问是裁剪之后直接预测map为0还是经过一段时间训练map为0？

**Comment by ZiruiChen** [comment]
> 请问是裁剪之后直接预测map为0还是经过一段时间训练map为0？

直接预测map接近0， finetuned 15个epoches之后还是0.01

**Comment by slf12** [comment]
您在邮件里描述的“裁剪率越高，map越低“是正常的，感觉这不像是裁剪出了问题，裁剪之后，模型结构就确定了，训练15个epoch map没有涨是不是应该是超参数设置的不准确呢？

**Comment by ZiruiChen** [comment]
> 您在邮件里描述的“裁剪率越高，map越低“是正常的，感觉这不像是裁剪出了问题，裁剪之后，模型结构就确定了，训练15个epoch map没有涨是不是应该是超参数设置的不准确呢？

是剪裁率越高 训练时loss越高 但结果的map都接近0

**Comment by slf12** [comment]
那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？

**Comment by ZiruiChen** [comment]
> 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？

能否看下config配置里metrics_name 在检测框架中是否有不同使用要求

**Comment by ZiruiChen** [comment]
> 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？

![图片](https://user-images.githubusercontent.com/50459712/63680171-646a7b80-c836-11e9-843a-f5bf9f8ae079.png)
对于剪裁率是0.01 （1个finetuned epoch）
map：从0.19下降至0.16，剪裁效果： MAdds从603下降至597

**Comment by slf12** [comment]
> > 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？
> 
> 能否看下config配置里metrics_name 在检测框架中是否有不同使用要求

metrics_name对应的是fetch_list[key, value]里那个key

**Comment by slf12** [comment]
> > 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？
> 
> ![图片](https://user-images.githubusercontent.com/50459712/63680171-646a7b80-c836-11e9-843a-f5bf9f8ae079.png)
> 对于剪裁率是0.01 （1个finetuned epoch）
> map：从0.19下降至0.16，剪裁效果： MAdds从603下降至597

这个结果来看，应该是检测模型对裁剪比较敏感，可能你逐渐增加裁剪率比较好，不要一下剪的太多，那可能map不好训上去了

**Comment by ZiruiChen** [comment]
> > > 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/50459712/63680171-646a7b80-c836-11e9-843a-f5bf9f8ae079.png)
> > 对于剪裁率是0.01 （1个finetuned epoch）
> > map：从0.19下降至0.16，剪裁效果： MAdds从603下降至597
> 
> 这个结果来看，应该是检测模型对裁剪比较敏感，可能你逐渐增加裁剪率比较好，不要一下剪的太多，那可能map不好训上去了

因为貌似有人可以剪裁成功 所以我觉得会不会是配置的问题导致没有只是把冗余的参数剪掉
https://github.com/PaddlePaddle/models/issues/2985#issuecomment-523274322

**Comment by ZiruiChen** [comment]
> > > 那把裁剪率调到0.01这样更小的值试下呢？测试下裁剪后的模型和原模型非常相近的情况下map值是多少？
> > 
> > 
> > 能否看下config配置里metrics_name 在检测框架中是否有不同使用要求
> 
> metrics_name对应的是fetch_list[key, value]里那个key

测试了metrics_name为eval_fetch_list的key('map'), 剪裁后依旧严重影响到了结果模型的map

**Comment by morgan-bc** [comment]
请问最后是怎么解决的呢，我按照 #2985 (comment) 中配置剪裁率设为0.5，最后的 map 就趋于零，设为0.1 也会下降很多
