### ISSUE TITLE
ocr_recognition

### ISSUE THREAD

**Issue by geng007** [PaddlePaddle/models#3206]
> et environment variable LD_LIBRARY_PATH on Linux是什么意思呢
>>![图片](https://user-images.githubusercontent.com/38428867/63821321-22008600-c97f-11e9-95f7-ec33d59c6db3.png)

**Comment by wangchaochaohu** [comment]
可以尝试 export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
应该是在环境变量种无法找到相应的库导致的

**Comment by geng007** [comment]
> 可以尝试 export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
> 应该是在环境变量种无法找到相应的库导致的

> 加了，但没效果诶
>>![图片](https://user-images.githubusercontent.com/38428867/63838655-52ace380-c9b0-11e9-8f33-8e4cad0f0c22.png)

**Comment by wangchaochaohu** [comment]
请问下你的操作系统是？ cupti是否正确安装？去cd /usr/local/cuda/extra/CUPTI/lib64/目录下是否能找到相应的so文件？

**Comment by geng007** [comment]
> 请问下你的操作系统是？ cupti是否正确安装？去cd /usr/local/cuda/extra/CUPTI/lib64/目录下是否能找到相应的so文件？

>ubuntu, cupti需要另外安装吗
```
bash: cd: /usr/local/cuda-9.0/extras/CUPTI/lib64: 没有那个文件或目录
```

**Comment by geng007** [comment]
> 请问下你的操作系统是？ cupti是否正确安装？去cd /usr/local/cuda/extra/CUPTI/lib64/目录下是否能找到相应的so文件？

> 我的lib64里没有CUPTI
>>![图片](https://user-images.githubusercontent.com/38428867/64022470-ddd0d980-cb68-11e9-9438-e61c1d6143be.png)

**Comment by geng007** [comment]
> 请问下你的操作系统是？ cupti是否正确安装？去cd /usr/local/cuda/extra/CUPTI/lib64/目录下是否能找到相应的so文件？

> 这个是需要CUDA 8 吗，我用的是CUDA 9
