### ISSUE TITLE
attention ocr 的训练数据图片宽和高的设置,以及label长度有什么要求吗?

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#3218]
首先感谢你们开源了代码; 我在使用attention ocr时候发现你们提供的训练数据宽和高分别设置为384和48, 应该是进行了预处理; 但DataGenerator的reader()函数里面, 似乎是根据每个batch的第一张图片的宽度来作为整个batch所有图片缩放的宽度的; 这样的话如果我自己的训练数据没有进行预处理, 那么不同图片的宽度不是统一的, 不同batch的图片宽度也会不一样,这样对训练的结果影响大不大? 第二个问题是 label的长度有没有什么限制?比如我的训练样本里面多数label长度为8-15个汉字, 但还有一批label长度超过20个汉字的图片,这些图片如果缩放到(宽:384,高:48)的尺寸, 有可能产生形变, 这种情况下是否对训练结果造成影响?

**Comment by qingqing01** [comment]
> 那么不同图片的宽度不是统一的, 不同batch的图片宽度也会不一样,这样对训练的结果影响大不大? 

首先开源这个模型是按行做识别，输入的图片的height都是一样的， 同一个batch的width不同的话padding 0，padding到同样大小。 补0对训练结果可能稍有影响，但不大。

可以将图片按照width排序，使得width接近的组batch，这样可以减少padding、可提升训练效率。

>  第二个问题是 label的长度有没有什么限制?比如我的训练样本里面多数label长度为8-15个汉字, 但还有一批label长度超过20个汉字的图片,这些图片如果缩放到(宽:384,高:48)的尺寸, 有可能产生形变, 这种情况下是否对训练结果造成影响?

如上，要求图片输入的height是固定，可以等比例对图片做resize，这样图片上的字符height和width比例不变。 对label长度没有限制。

**Comment by wenston2006** [comment]
@qingqing01 谢谢, 明白了.

**Comment by wenston2006** [comment]
@qingqing01 训练数据是否大部分应由标签等长的数据构成? 我目前训练数据标签长度不一,从长度2到长度40不均等分布; 有20万条训练样本; 训练batch_size=16, 训练前3万次, 训练loss都在下降, train_acc和test_acc都在上升,但训练到3.5万次时, 训练loss陡增(从loss=4.8陡增到loss=32), 接着train_acc和test_acc陡降; 这种情况下应如何调整参数? 训练数据如何调整?
