### ISSUE TITLE
models网站序列标注示例的Web页面图片显示问题

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/models#322]
models网站序列标注示例页面中图片没有显示出来 http://models.paddlepaddle.org/2017/04/21/sequence-tagging-for-ner-README.html

![image](https://user-images.githubusercontent.com/14105589/30852042-0f7592fc-a2dd-11e7-93c0-d064e6014ae0.png)

**Comment by lcy-seso** [comment]
@Superjom Would you please help us to check this, thank you very much.

**Comment by Superjomn** [comment]
应该是 img 的html 标签有问题，我直接改下

**Comment by Superjomn** [comment]
done
