### ISSUE TITLE
ernie的代码过于陈旧，不能infer，请将ERNIE项目的代码进行同步

### ISSUE THREAD

**Issue by wang001** [PaddlePaddle/models#3220]
infer时报错，没有task.reader.py 中_convert_example_to_record函数报label_id不存在

**Comment by tianxin1860** [comment]
> infer时报错，没有task.reader.py 中_convert_example_to_record函数报label_id不存在
请问跑的哪个数据集？

**Comment by wang001** [comment]
自己的数据集

**Comment by wang001** [comment]
分类任务

**Comment by tianxin1860** [comment]
> 分类任务

请贴一下自己数据集的表头格式

**Comment by wang001** [comment]
测试集：text_a	text_b，训练集和验证集：text_a	text_b	label
我发现在ERNIE中也是这样的，但是ERNIE项目专门提供了一个predict_classifier.py文件来预测，如果直接在参数中加上infer的话，必须要有label。

**Comment by wang001** [comment]
我觉得要么对infer部分去掉label要求，或者是写一个专门用来推理的文件。（我可以帮忙写一个）

**Comment by tianxin1860** [comment]
> 我觉得要么对infer部分去掉label要求，或者是写一个专门用来推理的文件。（我可以帮忙写一个）

我们提供了[推理脚本](https://github.com/PaddlePaddle/ERNIE/blob/develop/classify_infer.py), 这个可以满足你的需求;

**Comment by tianxin1860** [comment]
> 测试集：text_a	text_b，训练集和验证集：text_a	text_b	label
> 我发现在ERNIE中也是这样的，但是ERNIE项目专门提供了一个predict_classifier.py文件来预测，如果直接在参数中加上infer的话，必须要有label。

可以 pull 下最新代码，做 infer 的时候，输入格式是 text_a \t text_b(可选)

**Comment by wang001** [comment]
好的，谢谢，能不能把我在ERNIE中发现的BUG给顺便合了。
