### ISSUE TITLE
使用paddle slim的filter_pruning_uniform裁剪后，应用inference报错

### ISSUE THREAD

**Issue by Tristan-Hao** [PaddlePaddle/models#3233]
使用原始filter_pruning_uniform.yaml文件，对数据集Stanford Dogs进行训练MobileNet模型并裁剪。
训练裁剪完成后，模型大小剪为6.7M。
在应用该裁剪模型时报错：
![b95fcc9001811ede38935e261f8767e4](https://user-images.githubusercontent.com/41142435/63996419-3df65a00-cb2e-11e9-9022-fd59bca62efa.png)
请问是哪里的问题？谢谢
另外，如果用原始的mobilenetv1_resnet50_distillation.yaml训练裁剪也提示错误，但仍能继续，只是最后没有看到有最终大小有被裁剪：
![96c6d7f564a69e9945b272aa60273631](https://user-images.githubusercontent.com/41142435/63996766-28356480-cb2f-11e9-9bb8-799432ce3b24.png)

**Comment by wanghaoshuang** [comment]
@Tristan-Hao 
1. 第一个问题：models下给出的例子默认产出的只有权重文件，没有保存裁剪后的网络，可以参考这里保存网络结构和权重文件：https://github.com/PaddlePaddle/models/issues/3110#issuecomment-523732510

2. 第二个问题：抱歉，该问题正在一个pr修复，还没有merge。https://github.com/PaddlePaddle/Paddle/pull/19580
您可以现在本地环境按pr中修改更新下python脚本。

**Comment by Tristan-Hao** [comment]
赞~谢谢

**Comment by Tristan-Hao** [comment]
赞~谢谢
