### ISSUE TITLE
nonlocal模型的问题请教

### ISSUE THREAD

**Issue by wwjjy** [PaddlePaddle/models#3241]
您好，请教个问题，为什么nonlocal模型在预测的时候crop的size会从224变成256。使用训练阶段一样的224+fc的模式会有什么问题？
当我在进行预测时，由于输入大小为256*256，所以经过（7 * 7）的pooling后tensor的shape变为了（-1, 2048, 1, 2, 2），此时使用（10, 2048, 1, 1, 1）的卷积进行预测是否合理。此时网络的输出如下：
<img width="649" alt="image" src="https://user-images.githubusercontent.com/20850734/64089354-4641d580-cd78-11e9-8deb-f26bdcdb8c11.png">
看起来也不是很像softmax后的输出，此时还是选择最大值对应的类别最为分类结果吗？

**Comment by SunGaofeng** [comment]
1、train的时候是从256中random crop出224的，测试的时候使用crop_size=256一般情况下可以提升性能。使用训练阶段一样的224+fc的模式也可以进行测试，我们这边没有试过，您那边可以验证下效果。
2、经过（7 * 7）的pooling后tensor的shape变为了（-1, 2048, 1, 2, 2），此时使用（10, 2048, 1, 1, 1）的卷积进行预测。
您这里总共是10个类别吗？使用此卷积后输出feature map是(-1, 10, 1, 2, 2)，然后会对10这个维度做softmax，最后会对 T, H, W这三个维度做reduce_mean，预测概率的维度是(-1, 10)

![182f0478779f19d6ddf9866ed0ffeaeb](https://user-images.githubusercontent.com/26536764/64101578-bcf2c900-cda0-11e9-9686-e11130e265cf.png)
