### ISSUE TITLE
[BUG] document is broken

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/models#3248]
right here: [Paddle模型压缩工具库算法原理介绍](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/docs/tutorial.md)

It shows something like `$$ r = min(max(x, a), b)$$ $$ s = \frac{b - a}{n - 1} $$ $$ q = \left \lfloor \frac{r - a}{s} \right \rceil $$`

**Comment by gongweibao** [comment]
试试浏览器安装插件MathJax？

**Comment by jeng1220** [comment]
Thanks for reply. It works.
