### ISSUE TITLE
attention ocr调小学习率后,仍出现loss=nan

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#3264]
我用attention ocr 训练中文识别,我的样本都是些标签长度不均一的中文短语; 最初将attention_model. py 中的学习率LR设置为0.1, 训练了1.8万次, 开头train_acc, test_acc一直在上升, 但突然loss变为nan; 我将LR降低为0.01后,训练了1000次, loss就为nan了;这种情况下是否学习率应该调高而不是降低?请问LR可调范围大约是多少?此外decoder_size, word_vector_dim这几个参数对训练影响大吗?应如何调整?

**Comment by wanghaoshuang** [comment]
hi， 我们发现Paddle1.5版本下很容易出现NAN, 建议使用Paddle1.4版本，我们会继续排查Paddle1.5上的问题。
在Paddle1.4上，正常训练也会有loss=nan的现象，但是在变nan之前就能得到不错的结果。

>这种情况下是否学习率应该调高而不是降低?

这个应该没有必然关系；一般在loss边nan前若干epoch将lr decay一个数量级。

>此外decoder_size, word_vector_dim这几个参数对训练影响大吗

这个用默认的就行，与loss=nan现象关系不大。

**Comment by wenston2006** [comment]
@wanghaoshuang 谢谢回复, 我确实用的1.5的版本;
