### ISSUE TITLE
cascade rcnn

### ISSUE THREAD

**Issue by pandaxue** [PaddlePaddle/models#3266]
![44444](https://user-images.githubusercontent.com/50400428/64246857-307f0c80-cf40-11e9-8520-61ebfdb1f180.png)
这是什么原因啊，我没有修改过train的代码

**Comment by jerrywgz** [comment]
可以麻烦贴下报错信息吗

**Comment by pandaxue** [comment]
> 可以麻烦贴下报错信息吗

上面那张图就是我的报错信息，Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 66, in main
    devices_num = fluid.core.get_cuda_device_count()
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'

**Comment by jerrywgz** [comment]
在https://github.com/PaddlePaddle/models/issues/3267 中回复

**Comment by houboowen** [comment]
> ![44444](https://user-images.githubusercontent.com/50400428/64246857-307f0c80-cf40-11e9-8520-61ebfdb1f180.png)
> 这是什么原因啊，我没有修改过train的代码

解决了吗？  我在centos7遇到类似问题
