### ISSUE TITLE
求训练cascade的完整步骤

### ISSUE THREAD

**Issue by pandaxue** [PaddlePaddle/models#3267]
在哪里有训练cascade rcnn的详细步骤啊，我想用自己的数据跑一下cascade_rcnn可形变卷积，以前用mmdetection框架跑过，只试过voc数据集，现在用paddle不知道从哪开始修改class

**Comment by jerrywgz** [comment]
在https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/dcn/cascade_rcnn_dcn_r50_fpn_1x.yml 中有相关配置文件可以参考，num_classes需要修改这个值

**Comment by pandaxue** [comment]
> 在https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/dcn/cascade_rcnn_dcn_r50_fpn_1x.yml 中有相关配置文件可以参考，num_classes需要修改这个值

只需要更改num_class的类别数？老实讲你给的那个链接里的东西我看过看的不是大明白，我就问的在详细点吧，
这里只能用Coco格式的数据集吗？我以前都是用voc格式的，Coco集这里只用生成训练集和验证集的json文件就可以了吗，就是instance_train2017.json和instance_val2017.json是吗？

**Comment by pandaxue** [comment]
> 在https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/dcn/cascade_rcnn_dcn_r50_fpn_1x.yml 中有相关配置文件可以参考，num_classes需要修改这个值

只需要更改num_class的类别数？老实讲你给的那个链接里的东西我看过看的不是大明白，我就问的在详细点吧，
这里只能用Coco格式的数据集吗？我以前都是用voc格式的，Coco集这里只用生成训练集和验证集的json文件就可以了吗，就是instance_train2017.json和instance_val2017.json是吗？

**Comment by jerrywgz** [comment]
coco和voc数据格式都是支持的，如果coco数据集的话改json就可以；这里https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection/docs/config_example 有举了几个例子，里面有详细的配置信息和对应的注释，ssd模型里面就是voc的数据集格式。另外你是希望通过我们训好的模型做finetune吗？

**Comment by pandaxue** [comment]
> coco和voc数据格式都是支持的，如果coco数据集的话改json就可以；这里https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection/docs/config_example 有举了几个例子，里面有详细的配置信息和对应的注释，ssd模型里面就是voc的数据集格式。另外你是希望通过我们训好的模型做finetune吗？
是的，我想用你们的模型跑一下我自己的数据，不知道怎么操作了，网上没有教程

**Comment by yghstill** [comment]
目前rcnn系列model已同时支持COCO与VOC训练，如果在VOC数据集上训练cascade-rcnn-dcn，只需要将你的TrainFeed改成：
`dataset:      
    dataset_dir: dataset/voc      
    annotation: VOCdevkit/VOC_all/ImageSets/Main/val.txt      
    image_dir: VOCdevkit/VOC_all/JPEGImages      
    use_default_label: true`
如果你想自定义voc数据集，请将use_default_label设为false，修改ImageSets/Main/label_list.txt，然后修改config里的num_classes即可

因data reader正在重构，官方自定义数据集教程还尚未具备，预计9月底发布。如果你要采用全新的数据集格式，请阅读参考ppdet/data中相应COCO与VOC模块进行扩充即可。

**Comment by pandaxue** [comment]
> 目前rcnn系列model已同时支持COCO与VOC训练，如果在VOC数据集上训练cascade-rcnn-dcn，只需要将你的TrainFeed改成：
> `dataset: dataset_dir: dataset/voc annotation: VOCdevkit/VOC_all/ImageSets/Main/val.txt image_dir: VOCdevkit/VOC_all/JPEGImages use_default_label: true`
> 如果你想自定义voc数据集，请将use_default_label设为false，修改ImageSets/Main/label_list.txt，然后修改config里的num_classes即可
> 
> 因data reader正在重构，官方自定义数据集教程还尚未具备，预计9月底发布。如果你要采用全新的数据集格式，请阅读参考ppdet/data中相应COCO与VOC模块进行扩充即可。

python -u tools/train.py -c configs/cascade_rcnn_r50_fpn_1x.yml
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 66, in main
    devices_num = fluid.core.get_cuda_device_count()
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'
请问这是什么原因

**Comment by jerrywgz** [comment]
请问是使用docker环境吗，可以查看下cuda cudnn是否在LD_LIBARAY_PATH中

**Comment by pandaxue** [comment]
> 请问是使用docker环境吗，可以查看下cuda cudnn是否在LD_LIBARAY_PATH中

![2019-09-06 13-29-11屏幕截图](https://user-images.githubusercontent.com/50400428/64403277-87085a00-d0aa-11e9-9078-dedd5535dfe4.png)
你看我这是在吧，我以前都没问题呀

**Comment by pandaxue** [comment]
> > 目前rcnn系列model已同时支持COCO与VOC训练，如果在VOC数据集上训练cascade-rcnn-dcn，只需要将你的TrainFeed改成：
> > `dataset: dataset_dir: dataset/voc annotation: VOCdevkit/VOC_all/ImageSets/Main/val.txt image_dir: VOCdevkit/VOC_all/JPEGImages use_default_label: true`
> > 如果你想自定义voc数据集，请将use_default_label设为false，修改ImageSets/Main/label_list.txt，然后修改config里的num_classes即可
> > 因data reader正在重构，官方自定义数据集教程还尚未具备，预计9月底发布。如果你要采用全新的数据集格式，请阅读参考ppdet/data中相应COCO与VOC模块进行扩充即可。
> 
> python -u tools/train.py -c configs/cascade_rcnn_r50_fpn_1x.yml
> Traceback (most recent call last):
> File "tools/train.py", line 204, in
> main()
> File "tools/train.py", line 66, in main
> devices_num = fluid.core.get_cuda_device_count()
> AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'
> 请问这是什么原因

这个问题解决了。又有新问题了，ModuleNotFoundError: No module named 'ppdet'

**Comment by jerrywgz** [comment]
在PaddleDetection目录下 export PYTHONPATH=$PYTHONPATH:.

**Comment by huey0528** [comment]
> > > 目前rcnn系列model已同时支持COCO与VOC训练，如果在VOC数据集上训练cascade-rcnn-dcn，只需要将你的TrainFeed改成：
> > > `dataset: dataset_dir: dataset/voc annotation: VOCdevkit/VOC_all/ImageSets/Main/val.txt image_dir: VOCdevkit/VOC_all/JPEGImages use_default_label: true`
> > > 如果你想自定义voc数据集，请将use_default_label设为false，修改ImageSets/Main/label_list.txt，然后修改config里的num_classes即可
> > > 因data reader正在重构，官方自定义数据集教程还尚未具备，预计9月底发布。如果你要采用全新的数据集格式，请阅读参考ppdet/data中相应COCO与VOC模块进行扩充即可。
> > 
> > 
> > python -u tools/train.py -c configs/cascade_rcnn_r50_fpn_1x.yml
> > Traceback (most recent call last):
> > File "tools/train.py", line 204, in
> > main()
> > File "tools/train.py", line 66, in main
> > devices_num = fluid.core.get_cuda_device_count()
> > AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'
> > 请问这是什么原因
> 
> 这个问题解决了。又有新问题了，ModuleNotFoundError: No module named 'ppdet'

我也遇到了这个问题 AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'
想问问你是怎么解决的呀？
