### ISSUE TITLE
PaddleDetection中训练的模型能否进行视频目标检测？

### ISSUE THREAD

**Issue by MaxWellerVladimir** [PaddlePaddle/models#3270]

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleVideo/models/ctcn 目前paddle在视频库中提供了一个视频动作定位模型ctcn，是时间维度上的检测

**Comment by MaxWellerVladimir** [comment]
好的谢谢！
在2019年9月5日 10:03，wangguanzhong<notifications@github.com> 写道：

https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleVideo/models/ctcn 目前paddle在视频库中提供了一个视频动作定位模型ctcn，是时间维度上的检测
