### ISSUE TITLE
fluid.layers.cross_entropy 可否支持权重系数

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#3293]
fluid.layers.cross_entropy 可否支持权重系数，指定每个类别占loss的权重

**Comment by tensor-tang** [comment]
你好，按照[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#cross-entropy)定义，当前是不支持权重的。

**Comment by dbcool** [comment]
嗯嗯，感谢回复
