### ISSUE TITLE
SE_ResNeXt50_32x4d_vd预训练模型

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#3319]
看见SE_ResNet50_vd预训练模型已经提供了，不知道SE_ResNeXt50_32x4d_vd预训练模型近期能否提供呢?

**Comment by shippingwang** [comment]
[所有的模型都在这里](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/README.md#%E5%B7%B2%E5%8F%91%E5%B8%83%E6%A8%A1%E5%9E%8B%E5%8F%8A%E5%85%B6%E6%80%A7%E8%83%BD)， SE_ResNeXt50_32x4d_vd 没有

**Comment by cuicheng01** [comment]
目前还没有，如果有需求的话，可以考虑训练

**Comment by cuicheng01** [comment]
可以先用相近的模型代替，这个模型下次发布吧

**Comment by dbcool** [comment]
好的，感谢回复！
