### ISSUE TITLE
image_classification训练报warning

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#3320]
您好，用最新的分类代码训练，warning一直报，

WARNING:root:
     Detect that memory optimize or inplace is enabled, but the some variables in the fetch
     list is not persistable, you may get wrong fetched value, or an exeception may be thrown
     about cannot find variable of the fetch list.
     TO FIX this:
         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None)
         # if you need to fetch conv1, then:
         conv1.persistable = True

**Comment by ysh329** [comment]
这是哪里的代码呀，能给出具体文件吗，我们好方便分析给你建议和修改

**Comment by dbcool** [comment]
models/PaddleCV/image_classification下的代码，我用自己的数据进行训练，
 python train.py \
    --model=SE_ResNet50_vd \
    --pretrained_model=terror/pretrain_model_imgcls/SE_ResNet50_vd_pretrained/ \
    --batch_size=32 \
    --data_dir=./terror/data/terror_general/ \
    --num_epochs=100 \
    --total_images=578263 \
    --class_dim=6 \
    --image_shape=3,224,224 \
    --model_save_dir=terror/output/ \
    --lr_strategy=piecewise_decay \
    --step_epochs=10 \
    --lr=0.001
然后报错了

**Comment by ysh329** [comment]
> models/PaddleCV/image_classification下的代码，我用自己的数据进行训练，
> python train.py 
> --model=SE_ResNet50_vd 
> --pretrained_model=terror/pretrain_model_imgcls/SE_ResNet50_vd_pretrained/ 
> --batch_size=32 
> --data_dir=./terror/data/terror_general/ 
> --num_epochs=100 
> --total_images=578263 
> --class_dim=6 
> --image_shape=3,224,224 
> --model_save_dir=terror/output/ 
> --lr_strategy=piecewise_decay 
> --step_epochs=10 
> --lr=0.001
> 然后报错了

我看warning给了解决方法，你尝试改，可以避免这个warning嘛，后续我们会修，请持续关注呦~

**Comment by qingqing01** [comment]
@dbcool Sorry, the code in develop branch is for version 1.6.  You can remove  

```
build_strategy.enable_inplace = True
```

in https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/utility.py#L371

We will fix it soon.

**Comment by shippingwang** [comment]
用最新版本的paddle

**Comment by dbcool** [comment]
嗯嗯，非常感谢，已经没有warning
