### ISSUE TITLE
怎么总是下载不了，下载到一半就说网络错误，下载也很慢

### ISSUE THREAD

**Issue by szfranciszhao** [PaddlePaddle/models#3325]
怎么总是下载不了，下载到一半就说网络错误，下载也很慢

**Comment by wangguibao** [comment]
请问能具体说一下下载什么位置的数据时出错吗

**Comment by szfranciszhao** [comment]
下载这两个网址错误：
https://github.com/PaddlePaddle/models
https://github.com/PaddlePaddle/book


用浏览器下载zip文件，总是失败。用gitbash下载，只能看到  .git文件夹生成，总体进度大概19%就出错了
今天用科学上网，下载成功了。但这一还是很不方便，为什么git不能直接好好地下载呢？


------------------ 原始邮件 ------------------
发件人: "Wang Guibao"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 上午10:03
收件人: "PaddlePaddle/models"<models@noreply.github.com>;
抄送: "牧之"<312109499@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/models] 怎么总是下载不了，下载到一半就说网络错误，下载也很慢 (#3325)




请问能具体说一下下载什么位置的数据时出错吗

**Comment by wangguibao** [comment]
唉可能是网络抖动吧
