### ISSUE TITLE
PaddleDetection的eval.py出错 

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#3329]
您好，我在用PaddleDetection进行eval.py的时候，出错:  
**File "/data/daibing/model-factory/logo_detection/ppdet/utils/voc_eval.py", line 73, in bbox_eval
    gt_boxes = t['gt_box'][0]
KeyError: u'gt_box'**
应该是下面这段代码出错
   for t in results:
        bboxes = t['bbox'][0]
        bbox_lengths = t['bbox'][1][0]
        if bboxes.shape == (1, 1) or bboxes is None:
            continue
        gt_boxes = t['gt_box'][0]
可否帮忙解答一下

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/tools/eval.py
是执行这个文件出错吗？

**Comment by dbcool** [comment]
是滴，你可以看下results是模型的返回结果，里面并没有gt_box的信息，

**Comment by jerrywgz** [comment]
可以看下你这边的配置文件吗

**Comment by dbcool** [comment]
启动指令:
python tools/train.py \
    -c configs_proj/logo/faster_rcnn_x101_vd_64x4d_fpn_1x_voc.yml \
    --eval
配置文件faster_rcnn_x101_vd_64x4d_fpn_1x_voc.yml:
architecture: FasterRCNN
train_feed: FasterRCNNTrainFeed
eval_feed: FasterRCNNEvalFeed
test_feed: FasterRCNNTestFeed
max_iters: 200000
snapshot_iter: 1
use_gpu: true
log_smooth_window: 20
save_dir: output
pretrain_weights: pretrain_model/ResNeXt101_vd_64x4d_pretrained
weights: output/faster_rcnn_x101_vd_64x4d_fpn_1x/model_final
metric: VOC
num_classes: 2

FasterRCNN:
  backbone: ResNeXt
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNeXt:
  depth: 101
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  group_width: 4
  groups: 64
  norm_type: affine_channel
  variant: d

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    anchor_sizes: [4, 8, 16, 32, 64, 128]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

TwoFCHead:
#  num_chan: 1024
   mlp_dim: 1024

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
    values: null
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

FasterRCNNTrainFeed:
  # batch size per device
  batch_size: 1
  dataset:
    dataset_dir: dataset/logo
    image_dir: VOCdevkit_logo5k/VOC_all/JPEGImages
    annotation: VOCdevkit_logo5k/VOC_all/ImageSets/Main/train.txt
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  num_workers: 2
  shuffle: true

FasterRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/logo
    annotation: VOCdevkit_logo5k/VOC_all/ImageSets/Main/val.txt
    image_dir: VOCdevkit_logo5k/VOC_all/JPEGImages
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  num_workers: 2

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: dataset/logo/VOCdevkit_logo5k/VOC_all/ImageSets/Main/labels.txt
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  num_workers: 2
  shuffle: false

**Comment by dbcool** [comment]
同学，可以hi找我把，daibing, 这个需求目前比较急，谢谢哈

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/pull/3344 问题已修复
