### ISSUE TITLE
PaddleGAN 模型测试中的参数 --net_G 的含义与使用方法

### ISSUE THREAD

**Issue by linshuliang** [PaddlePaddle/models#3333]
模型测试中的参数 --net_G 的含义及其使用方法，README 中没有相关说明

**Comment by ceci3** [comment]
`add_arg('net_G',             str,   "resnet_9block",   "Choose the CycleGAN and Pix2pix generator's network, choose in [resnet_9block|resnet_6block|unet_128|unet_256]")
`
CycleGAN和Pix2Pix两个模型中都有多个生成网络结构可以选择，是选择这两个模型中需要用的生成网络结构的
