### ISSUE TITLE
error: function dynload::cuptiActivityFlushAll(CUPTI_ACTIVITY_FLAG_FLUSH_FORCED) failed with error CUPTI_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#3360]
我这边用ocr_recognition跑识别训练时碰见了如下问题，麻烦帮忙看一下
![paddle_err](https://user-images.githubusercontent.com/13143336/65122203-f4a97400-da22-11e9-9280-b018830648ad.png)

**Comment by shippingwang** [comment]
提供下环境信息？CUDA CUDNN nccl paddle版本

**Comment by endy-see** [comment]
cuda 9.0.176 , cudnn 7.4.2.24 , nccl 2.4.2, paddle 1.5.0

**Comment by wanghaoshuang** [comment]
log的意思是cupti和cuda driver不匹配。
你用类似以下命令确认下你的cupti的版本？
```
find  /home/work/cuda-9.0/ -name libcupti*
```
另外，确认下你的LD_LIBRARY_PATH是否指向了正确的libcupti.so

**Comment by endy-see** [comment]
![paddle_err](https://user-images.githubusercontent.com/13143336/65144464-02262480-da4a-11e9-8277-ff12e6a689fd.png)

**Comment by yanmeizhao** [comment]
> log的意思是cupti和cuda driver不匹配。
> 你用类似以下命令确认下你的cupti的版本？
> 
> ```
> find  /home/work/cuda-9.0/ -name libcupti*
> ```
> 
> 另外，确认下你的LD_LIBRARY_PATH是否指向了正确的libcupti.so

换了个libcupti.so，可以正常运行了，感谢~

**Comment by endy-see** [comment]
> log的意思是cupti和cuda driver不匹配。
> 你用类似以下命令确认下你的cupti的版本？
> 
> ```
> find  /home/work/cuda-9.0/ -name libcupti*
> ```
> 
> 另外，确认下你的LD_LIBRARY_PATH是否指向了正确的libcupti.so

换了个libcupti.so，可以正常运行了，感谢~
