### ISSUE TITLE
could not broadcast input array from shape (3,128,58) into shape (3,128)

### ISSUE THREAD

**Issue by qwertyuiop194** [PaddlePaddle/models#3368]
训练完一轮报以上错误，程序还可以继续运行，但每运行完一轮就会报错；
但一直不提示错误在哪里；
这个是什么原因

**Comment by heavengate** [comment]
麻烦贴一下全量报错信息和关键代码

**Comment by qwertyuiop194** [comment]
一直在运行；中间会出现错误；似乎是测试阶段出的错误？

Pass 3, trainbatch 300, loss 1.30312,                             acc1 0.20000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 310, loss 1.31770,                             acc1 0.40000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 320, loss 1.61041,                             acc1 0.20000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 330, loss 1.47342,                             acc1 0.30000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 340, loss 1.40169,                             acc1 0.10000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 350, loss 1.46174,                             acc1 0.30000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 360, loss 1.51653,                             acc1 0.20000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 370, loss 1.38937,                             acc1 0.30000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 380, loss 1.36059,                             acc1 0.20000, acc5 1.00000, lr 0.09978, time 0.23 sec
Pass 3, trainbatch 390, loss 1.47107,                             acc1 0.10000, acc5 1.00000, lr 0.09978, time 0.23 sec
Exception in thread Thread-71:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 596, in __provider_thread__
    raise ex
ValueError: could not broadcast input array from shape (3,128,58) into shape (3,128)

Pass 3,testbatch 0,loss 1.76424,                         acc1 0.00000,acc5 1.00000,time 0.10 sec
End pass 3, train_loss 1.37445, train_acc1 0.30525, train_acc5 1.00000, test_loss 1.76424, test_acc1 0.00000, test_acc5 1.00000
Pass 4, trainbatch 0, loss 1.36105,                             acc1 0.20000, acc5 1.00000, lr 0.09961, time 0.43 sec
Pass 4, trainbatch 10, loss 1.60807,                             acc1 0.10000, acc5 1.00000, lr 0.09961, time 0.23 sec
Pass 4, trainbatch 20, loss 1.21768,                             acc1 0.40000, acc5 1.00000, lr 0.09961, time 0.23 sec
Pass 4, trainbatch 30, loss 1.32614,                             acc1 0.20000, acc5 1.00000, lr 0.09961, time 0.23 sec
Pass 4, trainbatch 40, loss 1.23863,                             acc1 0.30000, acc5 1.00000, lr 0.09961, time 0.23 sec

**Comment by heavengate** [comment]
报错在io里面，应该是模型有一个shape (3,128)的输入，你写的reader之前一直yield的也是shape(3,128)的数据，突然有一个iter yield的是shape (3,128,58)的数据，请排查一下reader代码

**Comment by qwertyuiop194** [comment]
好的，我看一下，感谢
