### ISSUE TITLE
ocr attention 模型可否提供基于dygraph版本的?

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#3393]
目前提供的是静态图版本的,调试起来比较困难.

**Comment by sandyhouse** [comment]
请参考：https://github.com/PaddlePaddle/models/tree/develop/dygraph/ocr_recognition

**Comment by wenston2006** [comment]
@sandyhouse 谢谢

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by wenston2006** [comment]
@sandyhouse 尝试了一下dygraph文件夹中的ocr_recognition, 没看到模型保存的代码, 请问保存模型是否需要额外添加代码?

**Comment by sandyhouse** [comment]
你确认下吧，如果确定没有保存模型代码的话，还是需要额外添加代码的。比如paddle.fluid.dygraph.save_persistables
