### ISSUE TITLE
light_nas search 遇到大模型显存超限

### ISSUE THREAD

**Issue by mmglove** [PaddlePaddle/models#3394]
报错信息：
![image](https://user-images.githubusercontent.com/38800877/65475893-c1983200-deb3-11e9-8f9f-4aef936025a2.png)
这是在5个epoch后，计算的MobileNetV2 reward:0.454199999571,latency:27.92442;尝试新的token训练时报上面的错误，
配置：
![image](https://user-images.githubusercontent.com/38800877/65475928-dbd21000-deb3-11e9-9043-d338d685be25.png)
batch_size=256 ,4张P40，开启GC：
![image](https://user-images.githubusercontent.com/38800877/65476023-2489c900-deb4-11e9-8de2-ec9cb8bf1a29.png)

**Comment by wanghaoshuang** [comment]
这个错误是因为搜到的模型太大了，通过调小target_flops可以一定程度降低该问题出现的频率。
另外可以通过设置出错前一步搜到的tokens为init_tokens, 然后调整init_temperature，恢复搜索任务。

当然，我们会尝试从框架角度来解决该问题。请您谅解。
