### ISSUE TITLE
face_detection的速度问题

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#3403]
您好，这边有两个疑问:
一是face_detection的infer只用det0 = detect_face(image, shrink)，fps=5左右，是否可以提高
二是face_detection的infer目前只支持单张图像的infer，是否可以设置batchsize=10这样

**Comment by FDInSky** [comment]
1. 如果换成c++ api进行infer，速度能快点，但不会产生质的影响；
2. 目前库里没有写，但理论上可以，可以参考PaddleDetection eval写法

**Comment by qingqing01** [comment]
@dbcool 我们近期会在PaddleDetection中release BlazeFace和Faceboxes模型，从速度上比PyramidBox有很大优势。Python的Infer也可以批量预测。

**Comment by lyw615** [comment]
请问现在批量预测的代码有更新上来吗？我好像没找到。我的输入图像是2400*2500的，预测完一张需要1.4秒，请问官方有预测时间的标准吗
