### ISSUE TITLE
PaddleSlim classification pruning问题

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/models#3419]
如链接所示 https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/classification/pruning
![image](https://user-images.githubusercontent.com/7035538/65605075-0c609980-dfdb-11e9-8dde-6166adae44e4.png)
然而在Paddle官网上并没有找到1.6版本的Paddle，是不是代表这个功能暂时还用不了。
Paddle1.5.2报错了，还有请问Pruning测试的结果大概什么时候可以公布。
@wanghaoshuang

**Comment by A1exy** [comment]
@JiabinYang @wzzju

**Comment by ceci3** [comment]
是的，可以源码编译develop版本试下

**Comment by wanghaoshuang** [comment]
@A1exy 这是准备在Paddle1.6版本发布的工作，Paddle1.6版本预计10月中旬发布。
在这之前，您可以编译paddle develop试用。另外，你可以把Paddle1.5.2报错贴一下么？

**Comment by A1exy** [comment]
@wanghaoshuang  好的，多谢回复，那我10月多再试试这个功能。
1.5.2我按照你的设置执行，报错信息如下：

-----------  Configuration Arguments -----------
batch_size: 1
config_file: ./configs/mobilenet_v2.yaml
model: MobileNetV2
pretrained_model: /home/hpc/ccx/code/Model_Compress/models/PaddleCV/image_classification/output/MobileNetV2_x1_0/199
use_gpu: 0
------------------------------------------------
Traceback (most recent call last):
  File "compress.py", line 103, in <module>
    main()
  File "compress.py", line 99, in main
    compress(args)
  File "compress.py", line 91, in compress
    train_optimizer=opt)
TypeError: __init__() got an unexpected keyword argument 'save_eval_model'

**Comment by wanghaoshuang** [comment]
>Traceback (most recent call last):
File "compress.py", line 103, in 
main()
File "compress.py", line 99, in main
compress(args)
File "compress.py", line 91, in compress
train_optimizer=opt)
TypeError: init() got an unexpected keyword argument 'save_eval_model'

`save_eval_model`是Paddle1.6版本新加的一个参数，为了用户更方便的保存infer model和evaluation model，在Paddle1.6发布之前还不可用。具体细节可参考代码：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/core/compressor.py#L289-L295
