### ISSUE TITLE
about the nextvlad input size 

### ISSUE THREAD

**Issue by Usernamezhx** [PaddlePaddle/models#3427]
I read the 2d youtube-8m nextvlad tensorflow code: https://github.com/linrongc/youtube-8m/blob/4810b4e7763c9aa2430ee0cc45b86ad72faecc7b/nextvlad.py#L26, the input is such as [1, 300, 1024] which means the [batch, frames, feature_size] I think it only support batch_size: 1. so I want to know. the padlepaddle version suppot other num batch_size ? I mean the input size:https://github.com/PaddlePaddle/models/blob/554d8864eb0ec9416c06357a7bca1789fc750f78/PaddleCV/PaddleVideo/models/nextvlad/nextvlad_model.py#L43

**Comment by SunGaofeng** [comment]
Yes, PaddlePaddle support bathsize >= 1. 
BTW: in the above tf repository you showed, the author used batchsize=80, you can check the tf code or contact with the author to confirm this.

**Comment by Usernamezhx** [comment]
@SunGaofeng ok thanks for your reply. I set a breakpoint at the nextvlad function entry of the tf version nextvlad with batchsize=80. it show me that: 
`-> input = slim.fully_connected(input, self.expansion * self.feature_size,  activation_fn=None`
`(Pdb) p input`
`<tf.Tensor 'map/while/tower/video_VLAD/strided_slice:0' shape=(1, 300, 1024) dtype=float32>
`
I will read the code carefully. thank you

**Comment by wanglc2008** [comment]
> Yes, PaddlePaddle support bathsize >= 1.
> BTW: in the above tf repository you showed, the author used batchsize=80, you can check the tf code or contact with the author to confirm this.
           https://github.com/PaddlePaddle/models/blob/554d8864eb0ec9416c06357a7bca1789fc750f78/PaddleCV/PaddleVideo/models/nextvlad/nextvlad_model.py#L44
hi,what is shape of "input"? (batch, frame, feature_size)?
What is the number of frame?

**Comment by ucas010** [comment]
大佬说的是，tf的模型的输入限制了，只能单个图处理，这很慢。
然后循环处理得到的每个图的特征，再经过NeXt VLAD
