### ISSUE TITLE
关于pyramidbox中的感受野

### ISSUE THREAD

**Issue by foralliance** [PaddlePaddle/models#3430]
您好！
在PyramidBox中，为了避免过大感受野带来的影响，在特征融合时，并没有融合高层的特征．
但是在CPM模块，又使用了3*3的conv，这又会增大感受野．
感觉有点矛盾．

麻烦了！

**Comment by zhaoyuchen2018** [comment]
麻烦模型同学帮忙解答下@qingqing01

**Comment by tangxuvis** [comment]
实际上，对于小脸来说，感受野尽可能的大，比人脸尺寸大较多。对于大脸来说，感受野不需要太大。

**Comment by tangxuvis** [comment]
可以类比最近好几篇人脸检测论文提出的模块，比如dsfd，srn，retinaface等等。 @foralliance

**Comment by 924175302** [comment]
@tangxuvis 
我想用PyramidBox应用在别的小目标检测上，请问可以吗，有没有指导的文档教程？谢谢

**Comment by 924175302** [comment]
@qingqing01
我有个想法，不知道能不能实现，希望您能解答下，我想将这个CPM模块用在小目标检测里，利用上下文信息检测小目标，不知道能不能实现？
