### ISSUE TITLE
transformer模型预测时怎么使用PaddlePredictor？

### ISSUE THREAD

**Issue by tianjie491** [PaddlePaddle/models#3431]
模型已经训练完成并保存为inference model，现在需要进行预测。
预测方法为：
def prediction(predictor, predict_data_generator):
    for sample in predict_data_generator():
        max_seq_len = sample[0].shape[1]
        src_word = fake_input(sample[0], PaddleDType.INT64)
        src_pos = fake_input(sample[1], PaddleDType.INT64)
        src_slf_attn_bias = fake_input(sample[2], PaddleDType.FLOAT32)
        trg_word = fake_input(sample[3], PaddleDType.INT64)
        init_score = fake_input(sample[4], PaddleDType.FLOAT32)
        init_idx = fake_input(sample[5], PaddleDType.INT32)
        trg_src_attn_bias = fake_input(sample[6], PaddleDType.FLOAT32)
        seq_ids, seq_scores = predictor.run([
            src_word,
            src_pos,
            src_slf_attn_bias,
            trg_word,
            init_score,
            init_idx,
            trg_src_attn_bias])
        return seq_ids, seq_scores
def fake_input(ids, dtype):
    data = PaddleTensor()
    data.name = "data"
    data.shape = list(ids.shape)
    data.dtype = dtype
    data.data = PaddleBuf(ids.flatten().tolist())
    return data
但是sample[3]和sample[4]为lod_tensor没办法用fake_input方法进行转换，那对于lod_tensor应该怎么办呢？

**Comment by tianjie491** [comment]
对于Lod_tensor的转化，写了个方法，请看下对不对，
def lod_tensor_input(ids, dtype):
    array = np.array(ids)
    tensor = PaddleTensor()
    tensor.name = "data"
    tensor.lod = ids.lod()
    tensor.shape = list(array.shape)
    tensor.dtype = dtype
    tensor.data = PaddleBuf(array.flatten().tolist())
    return tensor

能预测出数据，但是数据类型为paddletensor，请问怎么转化为lod_tensor呢？

**Comment by zhaoyuchen2018** [comment]
paddleTensor转lodtensor可以参考下:https://github.com/PaddlePaddle/Paddle/blob/e89b12884afa24a54a5a3d94754dd4cf461dc213/paddle/fluid/inference/api/analysis_predictor.cc#L265

**Comment by tianjie491** [comment]
seq_ids_data = seq_ids.data
    seq_ids_data = PaddleBuf.int64_data(seq_ids_data)
    seq_ids_lod = seq_ids.lod
可以用PaddleBuf.int64_data或者PaddleBuf.float_data等方法将PaddleBuf转化为list后使用。
感谢@zhaoyuchen2018的帮助

**Comment by tianjie491** [comment]
@zhaoyuchen2018 还有一个问题需要帮助，
预测时一条数据在CPU上预测需要3-5秒，在GPU上也需要1-2秒，预测时间消耗太大，请问有没有优化方法？

**Comment by zhaoyuchen2018** [comment]
> @zhaoyuchen2018 还有一个问题需要帮助，
> 预测时一条数据在CPU上预测需要3-5秒，在GPU上也需要1-2秒，预测时间消耗太大，请问有没有优化方法？

要profile下才知道瓶颈在哪里，你可以尝试下打开--profile=true看看哪里耗时比较多。

**Comment by tianjie491** [comment]
最终发现推理速度慢的原因是因为输出最大长度设置的256，太长了，改为100的话预测时间为0.5秒左右，还是有点慢。transformer-xl对于推理速度据说有300-1800倍的提升，请问你们有发布transformer-xl模型的计划吗？

**Comment by zhaoyuchen2018** [comment]
> 最终发现推理速度慢的原因是因为输出最大长度设置的256，太长了，改为100的话预测时间为0.5秒左右，还是有点慢。transformer-xl对于推理速度据说有300-1800倍的提升，请问你们有发布transformer-xl模型的计划吗？

@guoshengCS 知会下transformer-xl，貌似提升很多，看看是不是有发布计划
