### ISSUE TITLE
如何实现Wide&Deep中，用FTRL优化wide, 用Adam优化Deep

### ISSUE THREAD

**Issue by stasi009** [PaddlePaddle/models#3439]
经典的wide & deep中，需要使用到两个optimizer，用FTRL优化wide, 用Adam优化Deep。

TensorFlow中用是用tf.group，将两个optimize ops合并成一个。

在PaddlePaddle中，如何实现在一个program中使用两个optimizer?

**Comment by zhaoyuchen2018** [comment]
paddle 目前没有这种功能，建议你用两个不同的program，只要参数名字一样，他们都是共享的。

**Comment by stasi009** [comment]
谢谢
