### ISSUE TITLE
优雅的重置auc

### ISSUE THREAD

**Issue by stasi009** [PaddlePaddle/models#3441]
几乎所有的有关分类的代码，都有如下重置auc的代码
auc_states_names = ['_generated_var_0','_generated_var_1','_generated_var_2', '_generated_var_3']
                for name in auc_states_names:
                    set_zero(name)

我实在搞不清楚，难道无论谁写的paddle程序，auc的变量都叫那几个名字？？？

一看那些variable的名字，就是paddle自动生成的。

那么，我自己写的代码，如果要重置auc，应该使用哪些变量名？我怎么才能知道，我应该用哪些变量名？？

**Comment by zhaoyuchen2018** [comment]
麻烦@wilhelmzh看下这个问题

**Comment by wilhelmzh** [comment]
你好，这里的写法确实不太好问题，建议参考下面写法，使用layers.auc的第三个返回值auc_states。

```python
# network.py
auc_var, batch_auc_var, auc_states = fluid.layers.auc(input=predict_2d,label=label_int,
     slide_steps=0)
```

```python
# infer.py
def set_zero(var_name, scope=fluid.global_scope(), place=fluid.CPUPlace(),
           param_type="int64"):
    param = scope.var(var_name).get_tensor()
    param_array = np.zeros(param._get_dims()).astype(param_type)
    param.set(param_array, place)

for var in auc_states:  # reset auc states
    set_zero(var.name, scope=inference_scope, place=place)
```

PaddleRec下的代码之后会更新，感谢反馈。

**Comment by stasi009** [comment]
感谢回复
