### ISSUE TITLE
paddleDetection中SSD的mean和std不一致情况

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/models#3451]
在使用PaddleDetection配置ssd mean和std参数时，发现和以前的ssd库的参数不同，而且查了一下PaddleDetection ssd的几个示例配置文件，也不太一样。请问是哪一个是标准的训练参数？这些不同设置有何影响？

**以前的ssd:**
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py
   **mean_value=[127.5, 127.5, 127.5],
   std=0.007843**

**PaddleDetection** :
ssd_vgg16_512.yml
![image](https://user-images.githubusercontent.com/20673237/65827960-4b873700-e2c8-11e9-9475-077d2f625072.png)

ssd_vgg16_512_voc.yml
![image](https://user-images.githubusercontent.com/20673237/65827979-6eb1e680-e2c8-11e9-8169-8e166d598079.png)

而mobilenet_ssd_v1_voc.yml中使用默认参数
![image](https://user-images.githubusercontent.com/20673237/65827989-796c7b80-e2c8-11e9-8aa6-e9349392e0a7.png)

DecodeImage中都设置了to_rgb=True，所以都应该转为 rgb格式了。

**Comment by yghstill** [comment]
@ellinyang   VGG-SSD是数据预处理方式是按照caffe原版[链接](https://github.com/weiliu89/caffe/tree/ssd) 进行处理的，其中mean应该为[104,117,123]或[123,117,104]均可。mobilenet-ssd是参考tensorflow官方设置，所以和VGG-SSD设置有所不同

**Comment by ellinyang** [comment]
> 处理

还有两个疑惑，希望您能解答：
1.PaddleCV中的mobilenet_ssd https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py 中的std 为何与PaddleDetection中mobilenet_ssd的不同？

2. [104,117,123]或[123,117,104] 两者设置在实际操作中，会导致输入的数据不同，那训练结果会有影响吗？特别是小数据集的情况，其中一个设置肯定与预训练权重时的设置不同。

**Comment by ellinyang** [comment]
> @ellinyang VGG-SSD是数据预处理方式是按照caffe原版[链接](https://github.com/weiliu89/caffe/tree/ssd) 进行处理的，其中mean应该为[104,117,123]或[123,117,104]均可。mobilenet-ssd是参考tensorflow官方设置，所以和VGG-SSD设置有所不同

还有两个疑惑，希望您能解答：

1.PaddleCV中的mobilenet_ssd https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py 中的std 为何与PaddleDetection中mobilenet_ssd的不同？

2.你们预训练 vgg_ssd 时mean设的是 [104,117,123]还是[123,117,104]？担心在小数据集上这两个设置因为和预训练保持一致，而有较大误差？

**Comment by yghstill** [comment]
> > 处理
> 
> 还有两个疑惑，希望您能解答：
> 1.PaddleCV中的mobilenet_ssd https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py 中的std 为何与PaddleDetection中mobilenet_ssd的不同？
> 
> 1. [104,117,123]或[123,117,104] 两者设置在实际操作中，会导致输入的数据不同，那训练结果会有影响吗？特别是小数据集的情况，其中一个设置肯定与预训练权重时的设置不同。

std是一致的，ssd的repo下std是1/127的结果，PaddleDetection下std是127，处理方式不同，一个乘一个除，https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/transform/operators.py#L343
这个我们做过严格对齐。
关于mean值不一样的情况，可以在你的数据集上进行测试，每个数据集的mean值分布不同，会导致结果不同，但是[104,117,123]是比较通用的处理方式。

**Comment by ellinyang** [comment]
> > > 处理
> > 
> > 
> > 还有两个疑惑，希望您能解答：
> > 1.PaddleCV中的mobilenet_ssd https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/reader.py 中的std 为何与PaddleDetection中mobilenet_ssd的不同？
> > 
> > 1. [104,117,123]或[123,117,104] 两者设置在实际操作中，会导致输入的数据不同，那训练结果会有影响吗？特别是小数据集的情况，其中一个设置肯定与预训练权重时的设置不同。
> 
> std是一致的，ssd的repo下std是1/127的结果，PaddleDetection下std是127，处理方式不同，一个乘一个除，https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/transform/operators.py#L343
> 这个我们做过严格对齐。
> 关于mean值不一样的情况，可以在你的数据集上进行测试，每个数据集的mean值分布不同，会导致结果不同，但是[104,117,123]是比较通用的处理方式。

好的，感谢

**Comment by ellinyang** [comment]
@still-wait 好的，感谢！
