### ISSUE TITLE
paddleSlim量化shufflenet模型后finetune loss为nan

### ISSUE THREAD

**Issue by Verazjy** [PaddlePaddle/models#3474]
采用cpu版本的paddlepaddle，Python3.6.4
采用paddleslim量化shufflenet时，可以进行eval操作，量化后finetune损失为nan
减小学习率和bachsize没有效果
希望有大神能给解决
![CCD9491DD7F5155764FA72A0DAFE0A4C](https://user-images.githubusercontent.com/35206066/66375615-63ee0480-e9e0-11e9-8650-7de88b28dd61.JPG)

**Comment by Verazjy** [comment]
shufflenet网络定义和与训练模型是从paddleCV中的定义和readme列出的shufflenetV2模型

**Comment by baiyfbupt** [comment]
您好，能否贴下您用的量化配置文件*.yml

**Comment by Verazjy** [comment]
> 您好，能否贴下您用的量化配置文件*.yml
就是网站中公布的配置文件，仅仅修改给epoch参数
