### ISSUE TITLE
 labelme2coco.py将labelme转换为coco数据集问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3511]
Generating dataset from: /Users/shuxsu/Downloads/cityscape/gtFine_trainvaltest/gtFine/train/ccc/.json
Traceback (most recent call last):
  File "labelme2coco.py", line 246, in <module>
    main()
  File "labelme2coco.py", line 223, in main
    args.json_input_dir)
  File "labelme2coco.py", line 117, in deal_json
    with open(label_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shuxsu/Downloads/cityscape/gtFine_trainvaltest/gtFine/train/ccc/.json'
会正常运行几个之后就会出现这样的错误，数据集使用为cityscape数据集，但是数据集本身无imagePath属性，为自己添加。错误提示就是这个，检查了每一个json文件，确认格式以及imagePath均正确

**Comment by SunAhong1993** [comment]
@shuxsu 你好~该问题可能是由于图像文件夹下出现了不是图像格式的文件，而在遍历文件夹时，非图像格式文件也会被当做图像文件处理并寻找其对应的json文件，所以导致出错。建议在[原代码125行](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/tools/labelme2coco.py#L125)处加入下述代码，可解决问题。
```
if img_file.split('.')[-1] not in ['jpg', 'jpeg', 'png']:
    continue
```

**Comment by shuxsu** [comment]
> @shuxsu 你好~该问题可能是由于图像文件夹下出现了不是图像格式的文件，而在遍历文件夹时，非图像格式文件也会被当做图像文件处理并寻找其对应的json文件，所以导致出错。建议在[原代码125行](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/tools/labelme2coco.py#L125)处加入下述代码，可解决问题。
> 
> ```
> if img_file.split('.')[-1] not in ['jpg', 'jpeg', 'png']:
>     continue
> ```

感谢大佬  可以了
