### ISSUE TITLE
paddleDection operators注释有问题？

### ISSUE THREAD

**Issue by ronghaoLee** [PaddlePaddle/models#3521]
![image](https://user-images.githubusercontent.com/46473363/66695946-d53bf900-ecf9-11e9-93d5-844e0e40aa50.png)

Hi 同学，

       我在使用PaddleCV/PaddleDetection时候，注意到了ExpandImage如截图红框这边的注释，请问是想要表述为“Scale the image width and height”的意思吗？还是我理解有误？

多谢啦

**Comment by MyPandaShaoxiang** [comment]
你好，经查看是注释有误，可以参考注释中第2条，后续会进行修正，感谢反馈。
