### ISSUE TITLE
没有训练，直接使用官方提供的weights的YOLOV3模型进行infer报错。

### ISSUE THREAD

**Issue by dhdljd** [PaddlePaddle/models#3528]
我在云服务器上ubuntu18.04和windows主机上，进行YOLOV3试用，没有训练，直接使用官方提供的weights进行infer，均报错，报错的截图如下：
![image](https://user-images.githubusercontent.com/53200354/66698554-839f6880-ed11-11e9-9fef-4e3c9ba98ca3.png)
![image](https://user-images.githubusercontent.com/53200354/66698562-931eb180-ed11-11e9-9a8e-b62a25fe7aa3.png)
请问，这是什么原因？

**Comment by heavengate** [comment]
![131abbd2e7fba6755be7b02ef630c2fc](https://user-images.githubusercontent.com/12605721/66700785-73928380-ed27-11e9-9e2b-fc3d80f91e5d.png)
权重没有正确导入，请检查权重是否正确下载和解压，权重路径是否指定正确

**Comment by dhdljd** [comment]
谢谢，使用默认的权重导入路径，就没有问题了。我前面权重导入路径有问题。

> 权重没有正确导入，请检查权重是否正确下载和解压，权重路径是否指定正确

**Comment by heavengate** [comment]
> 谢谢，使用默认的权重导入路径，就没有问题了。我前面权重导入路径有问题。
> 
> > 权重没有正确导入，请检查权重是否正确下载和解压，权重路径是否指定正确

鉴于问题解决，当前issue关闭，感谢对PaddlePaddle的支持~
