### ISSUE TITLE
run KT-NET 时候，ema.update()报 ‘dict’ object has no attribute 'has_key' 

### ISSUE THREAD

**Issue by euphratica** [PaddlePaddle/models#3538]
环境：ubuntu16  cuda9.0   cudnn 7.3 python3.7
paddle是按照官网通过pip安装的
在执行 sh ./run_record_twomemory_finetune.sh 时候报如下错误
Traceback (most recent call last):
  File "src/run_record_twomemory.py", line 628, in <module>
    train(args)
  File "src/run_record_twomemory.py", line 429, in train
    ema.update()
  File "/home/thj18/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 2624, in update
    if self._ema_vars.has_key(param.name + '.master'):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by chenwhql** [comment]
您好，这个是由于Python3 dict不再支持`has_key`这个接口导致的错误，官方文档如下：
`Removed dict.has_key() – use the in operator instead.`
出错的框架代码：`if self._ema_vars.has_key(param.name + '.master'):`需要改为`if param.name + '.master' in self._ema_vars:`
我们最新的代码库已经修正了这个bug，https://github.com/PaddlePaddle/Paddle/blob/bd99df715a6baa1b75c99ca87f8c0acd3f6878d2/python/paddle/fluid/optimizer.py#L2940

现在建议您尝试以下几种方法处理这个问题：
1. 安装Python2.7版本的paddle试一下
2. 可以安装开发版的paddle试一下：https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/Tables.html/#ciwhls
3. 如果不急，我们马上发布1.6版本了，届时这个问题就不存在了

**Comment by euphratica** [comment]
目前不急，我修改了一下报错部分paddle源码，能跑了，谢谢
