### ISSUE TITLE
Linux环境下对PaddleSeg 进行C++预测库部署的时候，在最后进行编译生成可执行文件时遇到的问题，希望大神能帮忙解答一下

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/models#3540]
会报出以下的错误：（本人系统为ubuntu18.04 GCC/G++ 版本为4.8.5 CUDA版本10.0）
/root/projects/opencv3/lib64/libopencv_core.a(hal_internal.cpp.o)：在函数‘lapack_QR32f(float*, unsigned long, int, int, int, float*, unsigned long, float*, int*)’中：
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x250)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x2bc)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x6e9)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x751)：对‘sgels_’未定义的引用
/root/projects/opencv3/lib64/libopencv_core.a(hal_internal.cpp.o)：在函数‘lapack_QR64f(double*, unsigned long, int, int, int, double*, unsigned long, double*, int*)’中：
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x295)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x325)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x5ee)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x63e)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x8de)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x96f)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0xb14)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0xb64)：对‘sgels_’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/demo.dir/build.make:131: recipe for target 'demo' failed
make[2]: *** [demo] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/demo.dir/all' failed
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenwhql** [comment]
您好，我google了一下这个错误，看起来和LAPACK有关，您试试加上编译选项`-DWITH_LAPACK=OFF`试试可以吗？

相关参考：
https://github.com/opencv/opencv/issues/7970
http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=12&t=3336
