### ISSUE TITLE
可否提供flownet, flownet2, PWC net等光流估计的模型？pytorch有写cuda的第三方库，paddle可否也提供一些correlation layer？

### ISSUE THREAD

**Issue by zhhezhhe** [PaddlePaddle/models#3558]
pytorch实现时有一些第三方自己写的cuda代码，例如nvidia的
```
https://github.com/NVIDIA/flownet2-pytorch/tree/master/networks/correlation_package
```
在paddle中如何实现？可否提供一些参考。

**Comment by zhupengyang** [comment]
1、感谢您的建议~ 我们会对新的模型进行评估，然后决定是否支持~
2、自己添加OP可以参考链接https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/development/new_op/index_cn.html 有如何增加cuda实现的相关说明和示例
