### ISSUE TITLE
采用win10笔记本电脑跑YOLOV3模型推理的耗时2.4s

### ISSUE THREAD

**Issue by dhdljd** [PaddlePaddle/models#3571]
![image](https://user-images.githubusercontent.com/53200354/66791489-3bf22a00-ef27-11e9-88c6-1e249207b095.png)

屏幕截图如上，其中，used_time：4.438s代表从模型加载到推理完成的时间，model_interpreter_time：2.407s代表从模型开始推理到结束的时间。
采用官方提供的infer文件、权重。
环境是：
联想x1笔记本电脑；
noGPU
酷睿i5CPU
win10系统。
请问，这样的耗时是否正常？是否需要在什么地方做优化？

---------------------------

另外，在同样的平台，采用opencv+YOLOV3模型，耗时在500~1000ms之间，调用的opencv语句是：
label = 'Inference time: %.2f ms' % (t * 1000.0 / cv.getTickFrequency())
截图如下：
![image](https://user-images.githubusercontent.com/53200354/66792110-d5224000-ef29-11e9-957c-1ec3258dcd86.png)

-----------------------------
在同样的平台，采用tensorflow跑lite模型，耗时基本上也要在500ms以上。

**Comment by willthefrog** [comment]
已assign给相关同学跟进。

**Comment by qingqing01** [comment]
@dhdljd 请问下:    1. OpenCV的YOLOv3模型也是DarkNet53的backbone吗？   2. 两者测试的时间，时间统计的start和end是否一样？ Paddle的Infer时间统计能否跳过前几轮预测的时间？ 因为系统的启动也有一定的耗时 3. Paddle的预测其实有另外一套经过优化的C++预测引擎，infer.py的并没有走那套经过优化的(比如采用mkl的cpu优化库、算子融合的).

**Comment by dhdljd** [comment]
> @dhdljd 请问下: 1. OpenCV的YOLOv3模型也是DarkNet53的backbone吗？ 2. 两者测试的时间，时间统计的start和end是否一样？ Paddle的Infer时间统计能否跳过前几轮预测的时间？ 因为系统的启动也有一定的耗时 3. Paddle的预测其实有另外一套经过优化的C++预测引擎，infer.py的并没有走那套经过优化的(比如采用mkl的cpu优化库、算子融合的).

1、OpenCV的YOLOV3模型以及它的测试时间，我需要再确认一下，上述用的是已经封装好的一个函数；
[https://github.com/dhdljd/learnopencv/tree/master/ObjectDetection-YOLO](url)
2、Paddle的时间统计，我不知道怎么跳过前几轮，这个时间的启动和停止点就设置在exe.run这个函数的前后；
        model_interpreter_start_time = time.time()
        outputs = exe.run(fetch_list=[v.name for v in fetch_list],
                          feed=feeder.feed(data),
                          return_numpy=False)
        model_interpreter_time += time.time() - model_interpreter_start_time
3、您说的这套优化的预测引擎，我哪儿可以看到？我其实主要是想确认，在x86cpu这个平台上，这个时间是不是正常，还是我的程序有问题。：）

**Comment by qingqing01** [comment]
下面是我们同学测的数据，在 Xeon(R) CPU E5-2650 v4 @ 2.20GHz 。

|模型 | 输入shape |   CPU-fluid(ms/image)(8-thread)|
|-- | -- | --|
MobileNet-V1-Yolov3-COCO | 3x320x320 |  38.744
MobileNet-V1-Yolov3-COCO | 3x416x416 | 59.575
MobileNet-V1-Yolov3-COCO | 3x608x608 |  116.555
MobileNet-V1-Yolov3-VOC | 3x320x320 | 35.647
MobileNet-V1-Yolov3-VOC | 3x416x416 | 55.305
MobileNet-V1-Yolov3-VOC | 3x608x608 |  109.992
DarkNet53-Yolov3-COCO | 3x320x320 |  99.161
DarkNet53-Yolov3-COCO | 3x416x416 | 156.565
DarkNet53-Yolov3-COCO | 3x608x608 | 321.187
DarkNet53-Yolov3-VOC | 3x320x320 |  96.734
DarkNet53-Yolov3-VOC | 3x416x416 | 154.248
DarkNet53-Yolov3-VOC | 3x608x608 |  308.17
ResNet34-Yolov3-COCO | 3x320x320 | 65.893
ResNet34-Yolov3-COCO | 3x416x416 | 101.758
ResNet34-Yolov3-COCO | 3x608x608 | 204.422
ResNet34-Yolov3-VOC | 3x320x320 |  61.128
ResNet34-Yolov3-VOC | 3x416x416 | 98.567
ResNet34-Yolov3-VOC | 3x608x608 | 198.011

针对第2个问题:

可以调用exe.run()多运行几次之后，再统计执行时间，也可以尝试在run接口加 `use_program_cache=True`看看有没有改进。

针对第3个问题:

主要文档在 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/index_cn.html

1. 使用Python+ 优化的C++预测引擎的话，可以参考如下代码，需要先save_inference_model:

```
import os
import numpy as np
from PIL import Image

import paddle.fluid as fluid
import time

def create_config(model_path, mode='fluid', batch_size=1, use_gpu=True):
    model_file = os.path.join(model_path, '__model__')
    params_file = os.path.join(model_path, '__params__')
    config = fluid.core.AnalysisConfig(model_file, params_file)
    if use_gpu:
      config.enable_use_gpu(100, 0)
      config.enable_tensorrt_engine(
            workspace_size=1 << 30,
            max_batch_size=batch_size,
            min_subgraph_size=40,
            precision_mode=fluid.core.AnalysisConfig.Precision.Float32,
            use_static=False)
        print('Run inference by TRT FP32.')
    return config


def create_tensor(np_data, dtype):
    dtype_map = {
        'float32': fluid.core.PaddleDType.FLOAT32,
        'int64': fluid.core.PaddleDType.INT64,
        'int32': fluid.core.PaddleDType.INT32
    }

    t = fluid.core.PaddleTensor()
    t.dtype = dtype_map[dtype]
    t.shape = np_data.shape
    buf = np_data.flatten().tolist()
    t.data = fluid.core.PaddleBuf(buf)
    return t

# 注意下面代码是从faster-rcnn的预测改的，你可能需要仔细的改正确
data = np.load('im.npy').reshape(1, 3, 608, 608)  # 或者读图片，resize之后的shape
im_shape = np.array([608., 608.]).astype('int32').reshape(1,2)   # 原图的shape

model_path='yolov3_darknet'
config = create_config(model_path)
predict = fluid.core.create_paddle_predictor(config)
inputs = [create_tensor(data, 'float32')]
inputs += [create_tensor(im_shape, 'int32')]

for i in range(5):
    outs = predict.run(inputs)

t1 = time.time()
for i in range(10):
    outs = predict.run(inputs)
t2 = time.time()
ms = (t2 - t1) * 1000.0 / float(10)
print("Inference: {} ms per image".format(ms))
```

2. 这个PR里正在PaddleDetection里加C++的预测引擎示例: https://github.com/PaddlePaddle/models/pull/3553

**Comment by dhdljd** [comment]
> 下面是我们同学测的数据，在 Xeon(R) CPU E5-2650 v4 @ 2.20GHz 。
> 
> 模型	输入shape	CPU-fluid(ms/image)(8-thread)
> MobileNet-V1-Yolov3-COCO	3x320x320	38.744
> MobileNet-V1-Yolov3-COCO	3x416x416	59.575
> MobileNet-V1-Yolov3-COCO	3x608x608	116.555
> MobileNet-V1-Yolov3-VOC	3x320x320	35.647
> MobileNet-V1-Yolov3-VOC	3x416x416	55.305
> MobileNet-V1-Yolov3-VOC	3x608x608	109.992
> DarkNet53-Yolov3-COCO	3x320x320	99.161
> DarkNet53-Yolov3-COCO	3x416x416	156.565
> DarkNet53-Yolov3-COCO	3x608x608	321.187
> DarkNet53-Yolov3-VOC	3x320x320	96.734
> DarkNet53-Yolov3-VOC	3x416x416	154.248
> DarkNet53-Yolov3-VOC	3x608x608	308.17
> ResNet34-Yolov3-COCO	3x320x320	65.893
> ResNet34-Yolov3-COCO	3x416x416	101.758
> ResNet34-Yolov3-COCO	3x608x608	204.422
> ResNet34-Yolov3-VOC	3x320x320	61.128
> ResNet34-Yolov3-VOC	3x416x416	98.567
> ResNet34-Yolov3-VOC	3x608x608	198.011
> 针对第2个问题:
> 
> 可以调用exe.run()多运行几次之后，再统计执行时间，也可以尝试在run接口加 `use_program_cache=True`看看有没有改进。
> 
> 针对第3个问题:
> 
> 主要文档在 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/index_cn.html
> 
> 1. 使用Python+ 优化的C++预测引擎的话，可以参考如下代码，需要先save_inference_model:
> 
> ```
> import os
> import numpy as np
> from PIL import Image
> 
> import paddle.fluid as fluid
> import time
> 
> def create_config(model_path, mode='fluid', batch_size=1, use_gpu=True):
>     model_file = os.path.join(model_path, '__model__')
>     params_file = os.path.join(model_path, '__params__')
>     config = fluid.core.AnalysisConfig(model_file, params_file)
>     if use_gpu:
>       config.enable_use_gpu(100, 0)
>       config.enable_tensorrt_engine(
>             workspace_size=1 << 30,
>             max_batch_size=batch_size,
>             min_subgraph_size=40,
>             precision_mode=fluid.core.AnalysisConfig.Precision.Float32,
>             use_static=False)
>         print('Run inference by TRT FP32.')
>     return config
> 
> 
> def create_tensor(np_data, dtype):
>     dtype_map = {
>         'float32': fluid.core.PaddleDType.FLOAT32,
>         'int64': fluid.core.PaddleDType.INT64,
>         'int32': fluid.core.PaddleDType.INT32
>     }
> 
>     t = fluid.core.PaddleTensor()
>     t.dtype = dtype_map[dtype]
>     t.shape = np_data.shape
>     buf = np_data.flatten().tolist()
>     t.data = fluid.core.PaddleBuf(buf)
>     return t
> 
> # 注意下面代码是从faster-rcnn的预测改的，你可能需要仔细的改正确
> data = np.load('im.npy').reshape(1, 3, 608, 608)  # 或者读图片，resize之后的shape
> im_shape = np.array([608., 608.]).astype('int32').reshape(1,2)   # 原图的shape
> 
> model_path='yolov3_darknet'
> config = create_config(model_path)
> predict = fluid.core.create_paddle_predictor(config)
> inputs = [create_tensor(data, 'float32')]
> inputs += [create_tensor(im_shape, 'int32')]
> 
> for i in range(5):
>     outs = predict.run(inputs)
> 
> t1 = time.time()
> for i in range(10):
>     outs = predict.run(inputs)
> t2 = time.time()
> ms = (t2 - t1) * 1000.0 / float(10)
> print("Inference: {} ms per image".format(ms))
> ```
> 
> 1. 这个PR里正在PaddleDetection里加C++的预测引擎示例: #3553

您好，非常感谢回复！我的结果怎么和您贴的测试结果差别那么大！是因为多线程处理的问题吗？您同学测试用的程序是什么？这里8个线程，是指把图片分批在多个线程里面做处理，然后最后算一个平均数吗？

**Comment by OliverLPH** [comment]
这个8线程应该是[set_cpu_math_library_num_threads](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_api.h#L314) 这个api，设置CPU数学计算的线程数。

> 这里8个线程，是指把图片分批在多个线程里面做处理，然后最后算一个平均数吗？

不是分批在多个线程里处理，就是直接在设置config的地方，添加如下代码。
```python
config.set_cpu_math_library_num_threads(8)
```

**Comment by dhdljd** [comment]
> 这个8线程应该是[set_cpu_math_library_num_threads](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_api.h#L314) 这个api，设置CPU数学计算的线程数。
> 
> > 这里8个线程，是指把图片分批在多个线程里面做处理，然后最后算一个平均数吗？
> 
> 不是分批在多个线程里处理，就是直接在设置config的地方，添加如下代码。
> 
> ```python
> config.set_cpu_math_library_num_threads(8)
> ```

在这个平台上。设置8个线程。
_C.SetCpuMathLibraryNumThreads = 8
没有根据上面的建议进行C++优化；
优化启动时间：运行了5次exe.run以后，重新运行10次exe.run，并计时。
模型和输入应该是这个：DarkNet53-Yolov3-COCO	3x608x608
结果如下：
![image](https://user-images.githubusercontent.com/53200354/66995992-7663ee80-f102-11e9-896a-4de4f9a27aae.png)
![image](https://user-images.githubusercontent.com/53200354/66996381-381aff00-f103-11e9-8a8c-d18c25e1ac88.png)
感觉，主频上去以后，再经过优化，估计能够和上述同学的测试结果大致一致。
