### ISSUE TITLE
关于训练模型的配置信息问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3577]
想知道关于训练的  epoch  step这些配置信息参数的问题 是在哪修改 是在模型.yml文件吗
类似这种吗？ 还有  有些信息都是缩写  实在是搞不懂都代表什么含义  是否有中文文档呢？能否提供一下 终端训练过程中  好多简写 缩写 实在是搞不懂含义 也不知道训练到第几个周期了。。
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml

**Comment by willthefrog** [comment]
PaddleDetection训练使用step而不是epoch的方式计数，配置文件可以参考文档里的示例。
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/config_example/mask_rcnn_r50_fpn_1x.yml

**Comment by shuxsu** [comment]
> PaddleDetection训练使用step而不是epoch的方式计数，配置文件可以参考文档里的示例。
> https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/config_example/mask_rcnn_r50_fpn_1x.yml

训练结束后 生成的文件夹里面试一堆文件   如何进行测试呢  有没有相关文档呢   辛苦了

**Comment by willthefrog** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/GETTING_STARTED_cn.md

可以参考这里的eval和test的部分，默认是加载output/[模型名称]/model_final里的权重，也可以用 -o weights=[path to weights]指定路径

**Comment by shuxsu** [comment]
> https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/GETTING_STARTED_cn.md
> 
> 可以参考这里的eval和test的部分，默认是加载output/[模型名称]/model_final里的权重，也可以用 -o weights=[path to weights]指定路径

我加载了指定路径的权重信息 为什么报文件不存在呢
weights: /Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/tools/output/model_final
运行后报错   这是什么原因呢   辛苦您了


EnforceNotMet: Invoke operator load error.
C++ Call stacks: 
Cannot parse tensor desc at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor_util.cc:466]
PaddlePaddle Call Stacks: 
0         0x1a207a8f8cp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1         0x1a207a8cbbp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2         0x1a21bb6e30p paddle::framework::TensorFromStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 1248
3         0x1a218c0b0fp paddle::framework::DeserializeFromStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 431
4         0x1a20b191d1p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::LoadLodTensor(std::__1::basic_istream<char, std::__1::char_traits<char> >&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 97
5         0x1a20b18a83p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 627
6         0x1a20b187d0p std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&) + 32

**Comment by willthefrog** [comment]
请确认你的运行目录，默认不会存到tools下面吧。。。

**Comment by shuxsu** [comment]
> 请确认你的运行目录，默认不会存到tools下面吧。。。

没没 刚刚那个问题是我的疏忽  现在这个问题是关键！！！大佬！

**Comment by willthefrog** [comment]
请完整描述下你的运行环境，运行的命令等等。。。

**Comment by shuxsu** [comment]
> 请确认你的运行目录，默认不会存到tools下面吧。。。

没没 刚刚那个问题是我的疏忽  现在这个问题是关键！！！大佬！

> 请完整描述下你的运行环境，运行的命令等等。。。



运行 命令：
(base) shuxsudeMacBook-Pro:tools shuxsu$ python infer.py -c=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml -o weights=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/tools/output/mask_rcnn_r50_1x/model_final --infer_img=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/demo/test1.png


错误信息：
libprotobuf ERROR /home/teamcity/work/ef54dc8a5b211854/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: (cannot determine missing fields for lite message)
Traceback (most recent call last):
  File "infer.py", line 319, in <module>
    main()
  File "infer.py", line 183, in main
    checkpoint.load_checkpoint(exe, infer_prog, cfg.weights)
  File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 89, in load_checkpoint
    fluid.io.load_persistables(exe, path, prog)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
    filename=filename)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
    filename=filename)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 656, in load_vars
    executor.run(load_prog)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 657, in run
    use_program_cache=use_program_cache)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 755, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Call stacks: 
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1774, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 641, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
    filename=filename)
  File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
    filename=filename)
  File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 89, in load_checkpoint
    fluid.io.load_persistables(exe, path, prog)
  File "infer.py", line 183, in main
    checkpoint.load_checkpoint(exe, infer_prog, cfg.weights)
  File "infer.py", line 319, in <module>
    main()
C++ Call stacks: 
Cannot parse tensor desc at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor_util.cc:466]
PaddlePaddle Call Stacks: 
0         0x1a26508f8cp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1         0x1a26508cbbp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2         0x1a27916e30p paddle::framework::TensorFromStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 1248
3         0x1a27620b0fp paddle::framework::DeserializeFromStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 431
4         0x1a268791d1p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::LoadLodTensor(std::__1::basic_istream<char, std::__1::char_traits<char> >&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 97
5         0x1a26878a83p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 627
6         0x1a268787d0p std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&) + 32
7         0x1a278d52c5p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 485
8         0x1a278d5038p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 488
9         0x1a278d17f4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 324
10        0x1a2667e27fp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 319
11        0x1a2667dd2cp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) + 172
12        0x1a265706fdp void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_84, void, paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_84&&, void (*)(paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 301
13        0x1a264eda38p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
14         0x10b2cc10ap _PyCFunction_FastCallDict + 362
15         0x10b253171p _PyObject_FastCallKeywords + 385
16         0x10b3a1718p call_function + 392
17         0x10b39f175p _PyEval_EvalFrameDefault + 46837
18         0x10b3928c9p _PyEval_EvalCodeWithName + 425
19         0x10b3a1a8ap fast_function + 362
20         0x10b3a167cp call_function + 236
21         0x10b39f225p _PyEval_EvalFrameDefault + 47013
22         0x10b3928c9p _PyEval_EvalCodeWithName + 425
23         0x10b3a1a8ap fast_function + 362
24         0x10b3a167cp call_function + 236
25         0x10b39f175p _PyEval_EvalFrameDefault + 46837
26         0x10b3928c9p _PyEval_EvalCodeWithName + 425
27         0x10b3a1a8ap fast_function + 362
28         0x10b3a167cp call_function + 236
29         0x10b39f225p _PyEval_EvalFrameDefault + 47013
30         0x10b3928c9p _PyEval_EvalCodeWithName + 425
31         0x10b3a1a8ap fast_function + 362
32         0x10b3a167cp call_function + 236
33         0x10b39f225p _PyEval_EvalFrameDefault + 47013
34         0x10b3928c9p _PyEval_EvalCodeWithName + 425
35         0x10b3a1a8ap fast_function + 362
36         0x10b3a167cp call_function + 236
37         0x10b39f175p _PyEval_EvalFrameDefault + 46837
38         0x10b3a19dcp fast_function + 188
39         0x10b3a167cp call_function + 236
40         0x10b39f175p _PyEval_EvalFrameDefault + 46837
41         0x10b3a19dcp fast_function + 188
42         0x10b3a167cp call_function + 236
43         0x10b39f175p _PyEval_EvalFrameDefault + 46837
44         0x10b3928c9p _PyEval_EvalCodeWithName + 425
45         0x10b3eb55cp PyRun_FileExFlags + 252
46         0x10b3eaa34p PyRun_SimpleFileExFlags + 372
47         0x10b4117c6p Py_Main + 3734
48         0x10b242f59p main + 313
49      0x7fff715d73d5p start + 1
50                 0x6p

**Comment by willthefrog** [comment]
`-o` 设置必须在命令行的最后

**Comment by shuxsu** [comment]
> `-o` 设置必须在命令行的最后

python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml \
                         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_fruit.tar \
                         --infer_img=demo/orange_71.jpg 我是按照教程写的啊

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/QUICK_STARTED_cn.md

**Comment by shuxsu** [comment]
> `-o` 设置必须在命令行的最后

shuxsu$ python infer.py -c=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml --infer_img=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/demo/test1.png -o weights=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/tools/output/mask_rcnn_r50_1x/model_final  这样报错一样

**Comment by shuxsu** [comment]
> `-o` 设置必须在命令行的最后
python infer.py -c=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml --infer_img=/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/demo/test1.png

运行命令这样 报错也是一样 。。。

**Comment by willthefrog** [comment]
我看新开了一个，那这个先close了
