### ISSUE TITLE
model_optimize_tool转PyramidBox发布的模型出错

### ISSUE THREAD

**Issue by yyf1986** [PaddlePaddle/models#3586]
环境：Ubuntu 18.04.3
下载的这个模型http://paddlemodels.bj.bcebos.com/PyramidBox_WiderFace.tar.gz

./model_optimize_tool --model_dir=PyramidBox_WiderFace --optimize_out_type=naive_buffer --optimize_out=PyramidBox_WiderFace222 --valid_targets=arm --prefer_int8_kernel=false
[I 10/15 20:31:46.884 ...5/github/Paddle-Lite/lite/api/cxx_api.cc:96 Build] load from memory 0
[F 10/15 20:31:47. 20 .../github/Paddle-Lite/lite/core/program.cc:141 Build] Check failed: op: no Op found for depthwise_conv2d_transpose

**Comment by willthefrog** [comment]
看上去像是paddle lite不支持该模型中使用的depthwise_conv2d_transpose op，建议将本issue转提到paddle lite的repo
