### ISSUE TITLE
测试过程中报错ImportError: cannot import name 'ColorTTY'

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3589]
输出原图片
另外想咨询一下 mask_rcnn_r50_1x.yml   mask_rcnn_r50_fpn_1x.yml 这些是不是都是模型  我修改了 r50是不是不需要修改第二个   因为我是用 mask_rcnn_r50_1x.yml进行训练的  但是现在输出结果是没有标注框的  我的训练集是cityscape数据集  不知道什么原因

**Comment by qingqing01** [comment]
mask_rcnn_r50_1x.yml
mask_rcnn_r50_fpn_1x.yml 
分别是不同的模型，不同的算法，fpn是在第一个基础上加了FPN模块。

您修改了r50的config，不需要需求带fpn。

更换数据之后，确保config里的类别数修正确，你训练cityscape数据的话，也可以采用coco预训练模型做初始化，可以参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/TRANSFER_LEARNING_cn.md 。然后看下训练得到的模型的mAP如何，最中间模型做一些预测可视化看看，模型训练的是否正常。



> 测试过程中报错ImportError: cannot import name 'ColorTTY' 

参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/INSTALL_cn.md#paddledetection ，确保安装时:

pip install -r requirements.txt

**Comment by shuxsu** [comment]
> mask_rcnn_r50_1x.yml
> mask_rcnn_r50_fpn_1x.yml
> 分别是不同的模型，不同的算法，fpn是在第一个基础上加了FPN模块。
> 
> 您修改了r50的config，不需要需求带fpn。
> 
> 更换数据之后，确保config里的类别数修正确，你训练cityscape数据的话，也可以采用coco预训练模型做初始化，可以参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/TRANSFER_LEARNING_cn.md 。然后看下训练得到的模型的mAP如何，最中间模型做一些预测可视化看看，模型训练的是否正常。
> 
> > 测试过程中报错ImportError: cannot import name 'ColorTTY'
> 
> 参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/INSTALL_cn.md#paddledetection ，确保安装时:
> 
> pip install -r requirements.txt

可通过在 YMAL 配置文件中通过设置 finetune_exclude_pretrained_params字段 这个ymal配置是yml配置文件吧 而且这个字段：finetune_exclude_pretrained_params 全局搜索并没有找到 
我看里面的字段值  忽略参数的字段  搜索到了 mask_head.py  这些代码里面的参数也要修改吗  里面的num_classes=81 这个是需要修改 其余的呢  感觉好乱 训练自己的数据集 除了修改eval里面 还要修改哪些呢   有没有比较详细的文档啊   乱乱的  我之前训练普通的mask rcnn  感觉没这么乱 现在我也不知道训练都需要修改哪些东西  而且没修改上面提到的mask_head.py  中的num_classes=81  训练也成功了 总之就很懵逼。。。。

**Comment by qingqing01** [comment]
1. finetune_exclude_pretrained_params的用法文档里已经说明了， 可以yaml config配置，也可以明命令里配置。 config里配置参考:   https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/yolov3_mobilenet_v1_fruit.yml#L15 

2. num_classes字段只需要在你的yaml config文件里正确设置即可，不需要修改源码。 
例如修改 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/faster_rcnn_r101_1x.yml#L13 着的 num_classes。

3.  通常情况下，如果您不改算法结构，不过度定制。  只是换数据只需要写个yaml config即可。

**Comment by shuxsu** [comment]
> * finetune_exclude_pretrained_params的用法文档里已经说明了， 可以yaml config配置，也可以明命令里配置。 config里配置参考:   https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/yolov3_mobilenet_v1_fruit.yml#L15
> * num_classes字段只需要在你的yaml config文件里正确设置即可，不需要修改源码。
>   例如修改 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/faster_rcnn_r101_1x.yml#L13 着的 num_classes。
> * 通常情况下，如果您不改算法结构，不过度定制。  只是换数据只需要写个yaml config即可。

我修改了那个yml配置 然后修改了coco_eval里面的类别  但是把里面的steps改成了50 把max_iters改18000  pre_nms_top_n:改 2000  milestones: [12000, 16000]也做了修改  但是测试时候就是输入和输出一样 但是我测试之前的模型  就能在jupyter上得到结果  用终端就是会报错 错误信息还是https://github.com/PaddlePaddle/models/issues/3584 这个错误  现在也不知道具体什么原因  不用我自己训练好的模型 用你们网站提供的  jupyter测试成功  终端测试就是不行

**Comment by shuxsu** [comment]
> * finetune_exclude_pretrained_params的用法文档里已经说明了， 可以yaml config配置，也可以明命令里配置。 config里配置参考:   https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/yolov3_mobilenet_v1_fruit.yml#L15
> * num_classes字段只需要在你的yaml config文件里正确设置即可，不需要修改源码。
>   例如修改 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/configs/faster_rcnn_r101_1x.yml#L13 着的 num_classes。
> * 通常情况下，如果您不改算法结构，不过度定制。  只是换数据只需要写个yaml config即可。

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/utils/coco_eval.py 这个文件我也修改了 这个应该是必须的吧

**Comment by qingqing01** [comment]
@shuxsu coco_eval.py 这个文件你修改了啥？ 实际用户不需要修改，在config里指定annotation等即可。例如提供的车辆检测的 https://github.com/PaddlePaddle/models/pull/3559/files 新增加的代码，没有修改任何代码， 提供 `vehicle.json` label信息。

**Comment by shuxsu** [comment]
修改了类别啊 我现在训练的cityscape数据集成有些类别 coco没有啊 我修改了 从原来的81类改成34 映射id改了 名字标签改了 现在测试完就是没数据……您能留给联系方式吗 或者有detection的群吗  加了paddle的群 但是大家不怎么搞这个

**Comment by shuxsu** [comment]
> @shuxsu coco_eval.py 这个文件你修改了啥？ 实际用户不需要修改，在config里指定annotation等即可。例如提供的车辆检测的 https://github.com/PaddlePaddle/models/pull/3559/files 新增加的代码，没有修改任何代码， 提供 `vehicle.json` label信息。

修改了类别啊 我现在训练的cityscape数据集成有些类别 coco没有啊 我修改了 从原来的81类改成34 映射id改了 名字标签改了 现在训练是不报错误的 但是用训练后的weights 去测试数据的时候 是没有结果的 输出还是原图 并没有结果……您能留给联系方式吗 或者有detection的群吗 加了paddle的群 但是大家不怎么搞这个  而且我之前的提问 就是我跑demo中的ipynb_mask那个再jupyter中就可以测试  我用cpu笔记本终端测试 infer.py就报错  用带gpu的工作站就不报错 但是都是没有结果 想知道原因
错误信息连接：https://github.com/PaddlePaddle/models/issues/3584

**Comment by shuxsu** [comment]
> @shuxsu coco_eval.py 这个文件你修改了啥？ 实际用户不需要修改，在config里指定annotation等即可。例如提供的车辆检测的 https://github.com/PaddlePaddle/models/pull/3559/files 新增加的代码，没有修改任何代码， 提供 `vehicle.json` label信息。

另外想咨询一下 训练数据集时候 loss:'nan' bbox:'nan' loss_cls:'nan‘是什么原因

**Comment by qingqing01** [comment]
@shuxsu 抱歉，我们自己加车辆检测、行人检测也好，都可以顺利的预测。我们联系你，提供下你们的数据加脚本，我们看下问题。

**Comment by shuxsu** [comment]
之前的问题是学习率过高估计导致nan 昨天训练的模型 测试的时候会有框 但是预测的标签并不是我自己数据集的 是coco上的标签 并且框的也不准确

**Comment by shuxsu** [comment]
> @shuxsu 抱歉，我们自己加车辆检测、行人检测也好，都可以顺利的预测。我们联系你，提供下你们的数据加脚本，我们看下问题。

之前的问题是学习率过高估计导致nan 昨天训练的模型 测试的时候会有框 但是预测的标签并不是我自己数据集的 是coco上的标签 并且框的也不准确 这个原因是训练的过于少吗 还是说我图片的原因 大小问题呢  我的数据集图片都是2048*1024的

**Comment by jerrywgz** [comment]
经过和用户的沟通，目前所遇到的问题做下总结：
1. 模型加载报bn参数不存在问题：由于models代码版本较老，处于未加入finetune功能的版本导致
2. 使用检测库提供脚本将数据转为coco格式后，训练仅有一个类的问题：经沟通发现原数据格式为cityscape格式，而检测库提供脚本为labelme格式，并不兼容cityscape格式，目前已经将问题修复并提pr，将转换脚本改名为x2coco.py https://github.com/PaddlePaddle/models/pull/3760/files
3. 训练参数问题：在对小数据集finetune时，将pretrain_weights设置为paddle release模型链接，并可以将迭代轮数降低；num_classes设置为（类别个数+背景类）
4. resize问题：maskrcnn中默认训练时resize到800，1333大小，infer时不对图片做resize，如果效果不够理想可以对sample_transform进行调整
