### ISSUE TITLE
PaddleSeg：在自定义的数据准备时通过labelme生成了原图对应的.json文件，但是在数据格式转换时报错ModuleNotFoundError: No module named 'labelme'

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/models#3637]
如题，原图和对应文件都已经准备好，labelme也已经安装好，但是在数据格式转换的时候报错
Traceback (most recent call last):
  File "labelme2seg.py", line 15, in <module>
    import labelme
ModuleNotFoundError: No module named 'labelme'
这个文件中我已经import了，也试着加上了sys.path.append('path')，但是还是会提示找不到这个labelme模块，请问下大神们这是什么缘由？

**Comment by LutaoChu** [comment]
你好，有可能是不同python解释器的问题。可以确认一下安装labelme的python解释器和运行文件的解释器是否一致。

另外，关于paddleseg的issue建议以后提到https://github.com/PaddlePaddle/PaddleSeg这个仓库里，可以更快让我们看到。

**Comment by eddieheyutong** [comment]
> 你好，有可能是不同python解释器的问题。可以确认一下安装labelme的python解释器和运行文件的解释器是否一致。
> 
> 另外，关于paddleseg的issue建议以后提到[https://github.com/PaddlePaddle/PaddleSeg这个仓库里，可以更快让我们看到。](https://github.com/PaddlePaddle/PaddleSeg%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E9%87%8C%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%9B%B4%E5%BF%AB%E8%AE%A9%E6%88%91%E4%BB%AC%E7%9C%8B%E5%88%B0%E3%80%82)

您好，我这个问题提在了您说的这个地方，然后这个labelme2seg文件我查看了并没有写python版本，您说的这个安装labelme的python解释器和运行文件的解释器该如何来核对是否一致呢？

**Comment by eddieheyutong** [comment]
@LutaoChu 您好，我这个问题提在了您说的这个地方，然后这个labelme2seg文件我查看了并没有写python版本，您说的这个安装labelme的python解释器和运行文件的解释器该如何来核对是否一致呢？

**Comment by LutaoChu** [comment]
你好，我的意思是你会不会安装labelme的python和运行labelme2seg的python不是同一个，比如在python2上安装labelme，在python3上运行的labelme2seg。
之前也有用户碰到了这个问题。请先核对一下

**Comment by qingqing01** [comment]
在 https://github.com/PaddlePaddle/PaddleSeg/issues/63 中跟进
