### ISSUE TITLE
There is no params of batch norm in model /weights/mask_rcnn_r50_1x.

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3681]
训练命令：python train.py -c=/home/shuxsu/PaddleDetection/configs/mask_rcnn_r50_1x.yml -d=/home/shuxsu/PaddleDetection/dataset/coco

错误信息：2019-10-21 11:55:16,802-INFO: Found /home/shuxsu/.cache/paddle/weights/mask_rcnn_r50_1x
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    main()
  File "train.py", line 160, in main
    checkpoint.load_and_fusebn(exe, train_prog, cfg.pretrain_weights)
  File "/home/shuxsu/PaddleDetection/ppdet/utils/checkpoint.py", line 253, in load_and_fusebn
    path))
ValueError: There is no params of batch norm in model /home/shuxsu/.cache/paddle/weights/mask_rcnn_r50_1x.
在yml配置里添加了finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']

**Comment by qingqing01** [comment]
@shuxsu 这个问题是由于加载的模型是用affine_channel训练，不是batch norm。加在模型时不用fuse-bn， tools/train.py中改下加载参数的分支，使用`checkpoint.load_params`分支，您可以先自己改下代码

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/tools/train.py#L203

我们排查并优化下，感谢~

**Comment by qingqing01** [comment]
另外，我改动测试: 

```
git diff configs/mask_rcnn_r50_1x.yml
diff --git a/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml b/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
index 6c3dd84..52ee014 100644
--- a/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
+++ b/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
@@ -7,10 +7,12 @@ max_iters: 180000
 snapshot_iter: 10000
 log_smooth_window: 20
 save_dir: output
-pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
+#pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
+pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
 metric: COCO
 weights: output/mask_rcnn_r50_1x/model_final
 num_classes: 81
+finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']

 MaskRCNN:
   backbone: ResNet
```

```
python tools/train.py -c configs/mask_rcnn_r50_1x.yml
```

 我测试没问题的。 Anyway,  我们可以再优化下体验。

**Comment by shuxsu** [comment]
> 另外，我改动测试:
> 
> ```
> git diff configs/mask_rcnn_r50_1x.yml
> diff --git a/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml b/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
> index 6c3dd84..52ee014 100644
> --- a/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
> +++ b/PaddleCV/PaddleDetection/configs/mask_rcnn_r50_1x.yml
> @@ -7,10 +7,12 @@ max_iters: 180000
>  snapshot_iter: 10000
>  log_smooth_window: 20
>  save_dir: output
> -pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
> +#pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
> +pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
>  metric: COCO
>  weights: output/mask_rcnn_r50_1x/model_final
>  num_classes: 81
> +finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']
> 
>  MaskRCNN:
>    backbone: ResNet
> ```
> 
> ```
> python tools/train.py -c configs/mask_rcnn_r50_1x.yml
> ```
> 
> 我测试没问题的。 Anyway, 我们可以再优化下体验。

你们的代码肯定是没问题的  主要是我是初学者 就很多地方搞不懂。。。麻烦了

**Comment by qingqing01** [comment]
@shuxsu 嗯，理解，也感谢使用，我们会尽力解决的你的问题。 https://github.com/PaddlePaddle/models/pull/3735 这个PR做了一些优化，也可以review下。

**Comment by jerrywgz** [comment]
该问题可通过更新models代码解决
