### ISSUE TITLE
Add three trained image classification models on ImageNet.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#369]
Add three trained models for image classification. Update the documentation to add three trained models on ImageNet:

ResNet50: http://cloud.dlnel.org/filepub/?uuid=f63f237a-698e-4a22-9782-baf5bb183019
ResNet101: http://cloud.dlnel.org/filepub/?uuid=3d5fb996-83d0-4745-8adc-13ee960fc55c
Vgg16：http://cloud.dlnel.org/filepub/?uuid=aa0e397e-474a-4cc1-bd8f-65a214039c2e

**Comment by zgplvyou** [comment]
这个链接点进去是502啊，打不开！
