### ISSUE TITLE
PaddleDetection训练私有数据检测数据集显存利用率较低

### ISSUE THREAD

**Issue by ronghaoLee** [PaddlePaddle/models#3715]
Hi 您好，

     我在使用ppdet训练私有数据集时，出现了显存利用率过低的情况，希望可以帮助定位计算速度的瓶颈在哪。
     使用版本：paddle 1.5.1
     使用的配置文件：frcnn_r50_1x, ssd_500（图片预处理修改至1024*1024, 根据数据集情况修改过anchor设置）
     数据集情况：50张图，每张图分辨率1024*1024，上面总共存在1w个小型boundingbox
     使用体验：训练yolo_darknet_v3时明显比训练frcnn_r50和ssd_500快很多，而且在训练frcnn&ssd时，GPU的平均显存利用率很低。

希望可以定位到计算瓶颈所在，多谢啦！

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/models/blob/9d4345501df987c804b56bea7ec9802ed445edb9/PaddleCV/PaddleDetection/configs/yolov3_darknet.yml#L68
配置文件里面的TrainDataFeed里面开一下多进程reader，即`use_process`设置为`True`试下

**Comment by ronghaoLee** [comment]
好的 谢谢啦～
