### ISSUE TITLE
多进程训练时内存占用过高导致训练程序崩溃

### ISSUE THREAD

**Issue by Yogurt2019** [PaddlePaddle/models#3729]
使用近期更新的models/PaddleCV/image_classification中的多进程训练进行训练时，在validate过程中会出现内存迅速占满128G导致程序崩溃问题，之前在训练的时候就已经占很高了，我的训练环境及参数是:
自己的数据34万张图
batchsize 120
3张tesla v100
128G内存
py_reader的容量为4
reader_thread为6
reader_bufsize为1024
train_num为3
请问应该如何调整参数，以使训练时内存占用不会过大?

**Comment by Yogurt2019** [comment]
使用的是paddlepaddle1.6rc最新版本
num_trainer为3 上面说错了

**Comment by wanghaoshuang** [comment]
您好，可以设置显存管理相关的FLAGS: 
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/flags/memory_cn.html#id1

建议将`fraction_of_gpu_memory_to_use`设置小点试试。

**Comment by Yogurt2019** [comment]
> 您好，可以设置显存管理相关的FLAGS:
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/flags/memory_cn.html#id1
> 
> 建议将`fraction_of_gpu_memory_to_use`设置小点试试。

你好，这个我设置成了0.98，我的意思是内存占满而不是显存

**Comment by Yogurt2019** [comment]
> 您好，可以设置显存管理相关的FLAGS:
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/flags/memory_cn.html#id1
> 
> 建议将`fraction_of_gpu_memory_to_use`设置小点试试。

而且我刚才看了一下代码，FLAGS_eager_delete_tensor_gb=0.0已经设置了，这个是在示例的python文件里就已经自动启用的，还是会把整整128g内存全部占满，是内存不是显存

**Comment by wanghaoshuang** [comment]
非常抱歉，我理解错您意思了。
内存占用应该是和data reader中多线程读取数据有关的，你可以调整下这两个参数：
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/utility.py#L123-L124
减小并行处理数据的线程数，和bufferszie

如果还不能解决问题，只能减小batch size了

**Comment by Yogurt2019** [comment]
> 非常抱歉，我理解错您意思了。
> 内存占用应该是和data reader中多线程读取数据有关的，你可以调整下这两个参数：
> https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/utility.py#L123-L124
> 减小并行处理数据的线程数，和bufferszie
> 
> 如果还不能解决问题，只能减小batch size了

好的，这些估计还需要调参来解决，谢谢!
