### ISSUE TITLE
使用PaddleDetection进行模型训练出现cudaGetLastError

### ISSUE THREAD

**Issue by ronghaoLee** [PaddlePaddle/models#3730]
Hi，
        我在使用faster rcnn/ssd训练非公开数据集时，会出现‘cudaGetLastError’报错，请问可能是什么原因呢？
       示例如下：使用修改后的faster_rcnn_r50_fpn_1x的配置文件（优化器使用adadelat），会出现以下情况：【注：调小学习率可能会避免这种情况，但是模型收敛效果不能保证】
![image](https://user-images.githubusercontent.com/46473363/67368406-dbf42700-f5a9-11e9-8935-57492086aee9.png)

**Comment by qingqing01** [comment]
@ronghaoLee  在自己的数据集上训练时，是有可能需要调整学习率的。 另外，batch size和卡数的改变，也注意调整学习率。 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/GETTING_STARTED_cn.md#faq

> 调小学习率可能会避免这种情况，但是模型收敛效果不能保证

在COCO数据集上，适当调小warmup阶段的学习率，没有影响最终的收敛效果。另外，我们在更换一些backbone时，有时候也会适当的调整学习率。 所以这个方法是可以尝试的。

**Comment by jerrywgz** [comment]
从log来看您使用的应该是2卡，我们在配置文件中所给出的学习率是对应八卡的学习率，可以根据上述链接中的文档来修改学习率相关配置

**Comment by ronghaoLee** [comment]
好的 多谢哈
