### ISSUE TITLE
使用faster_rcnn_dcn_r50_vd_fpn_2x_voc转tensorrt后，infer报错

### ISSUE THREAD

**Issue by pangr** [PaddlePaddle/models#3731]
在使用tensorrt的方法做faster_rcnn_dcn_r50_vd_fpn_2x_voc的infer时会出现下面的问题
<img width="1326" alt="MacHi 2019-10-23 16-33-19" src="https://user-images.githubusercontent.com/5838111/67373827-dd761d00-f5b2-11e9-89dc-5f5e5c245c7a.png">

环境：
tensorrt 5.1
cuda9.0
paddle1.5

**Comment by qingqing01** [comment]
@pangr 请注意，使用TensorRT预测时，输入图片的shape必需和保存的model里的shape一致。 另外，对于rcnn系列，由于TensorRT对定长的限制，min_subgraph_size设置40。

**Comment by pangr** [comment]
@qingqing01 非常感谢您的回复。请问一下，检测代码如何存固定大小的model，我看公开的检测代码中存model的代码没有关于输入大小的设定

**Comment by qingqing01** [comment]
参考文档:  https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/EXPORT_MODEL.md

```
# 如果您代码没跟新，是tools/infer.py --infer_img=demo/000000014439.jpg -c config....
# 主要是通过XXTestFeed.image_shape设置
python tools/export_model.py -c configs/faster_rcnn_r50_1x.yml \
        --output_dir=./inference_model \
        -o weights=output/faster_rcnn_r50_1x/model_final \
           FasterRCNNTestFeed.image_shape=[3,800,1333]
```
