### ISSUE TITLE
Pose estimation seems to work only for single person

### ISSUE THREAD

**Issue by xueeinstein** [PaddlePaddle/models#3739]
https://github.com/PaddlePaddle/models/blob/8aa202ade1a142d6476a67a65baf8160ad9e4b70/PaddleCV/human_pose_estimation/utils/utility.py#L341

@qingqing01  @KaiyuYue This postprocessing operation only gets max keypoints prediction from the heatmap. What if there are multiple persons? Is there any way to get multi-person pose?

**Comment by Noplz** [comment]
Hi xueeinstein，since “Simple Baselines” is a top-down pose estimation method，it can not estimate multi-person pose by a single forward. I think you can try some bottom-up methods (e.g. OpenPose, but is not available in Paddle for now) or use another human detector to get some proposal regions.

**Comment by xueeinstein** [comment]
Hi @Noplz, Thanks for your reply. I see the limitation of the "Simple Baselines". As I know, MPII dataset contains annotations for multi-person. I just wonder if it is possible to parse the heatmap and extract multi-person as well. 

I'd like to close this issue now. Feel free to comment on any solution! Also, looking forward to seeing the implementation of OpenPose in Paddle.
