### ISSUE TITLE
fluid中是否有nll_criterion计算？

### ISSUE THREAD

**Issue by Yogurt2019** [PaddlePaddle/models#3744]
需求中需要自己搭建loss，其中之前在pytorch上使用了nll_criterion，请问在paddle上是否有这种算子？
另外问一下有没有类似pytorch的masked_select这种方法？谢谢！

**Comment by LielinJiang** [comment]
> 需求中需要自己搭建loss，其中之前在pytorch上使用了nll_criterion，请问在paddle上是否有这种算子？
> 另外问一下有没有类似pytorch的masked_select这种方法？谢谢！

log_soft_max + nll_loss 等价于softmax + cross_entropy，可否用后者代替？不行的话也可以用基础的乘，加算子组合一个。
masked_select在paddle中没有对应的算子，不过可以用where+gather+reshape实现

**Comment by Yogurt2019** [comment]
> > 需求中需要自己搭建loss，其中之前在pytorch上使用了nll_criterion，请问在paddle上是否有这种算子？
> > 另外问一下有没有类似pytorch的masked_select这种方法？谢谢！
> 
> log_soft_max + nll_loss 等价于softmax + cross_entropy，可否用后者代替？不行的话也可以用基础的乘，加算子组合一个。
> masked_select在paddle中没有对应的算子，不过可以用where+gather+reshape实现

好的，原来paddle中的nll就是cross_entropy，还有一个cross_entropy_with_softmax，谢谢！
