### ISSUE TITLE
compress.py 压缩报错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/models#3747]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/slim/quantization/compress.py
运行:
!python compress.py \
                    -s yolov3_mobilenet_v1_slim.yaml \
                    -c yolov3_mobilenet_v1_voc.yml
错误日志:
Traceback (most recent call last):
  File "compress.py", line 50, in <module>
    from ppdet.utils.check import check_gpu, check_version
ImportError: cannot import name 'check_version' from 'ppdet.utils.check' (../../ppdet/utils/check.py)

**Comment by wanghaoshuang** [comment]
抱歉，您可以暂时注释掉这两行：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/slim/quantization/compress.py#L50
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/slim/quantization/compress.py#L120

**Comment by wanghaoshuang** [comment]
同时，建议您用models 1.6分支： https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleCV/PaddleDetection/slim/quantization/compress.py
