### ISSUE TITLE
PaddleDetection数据transform这个地方代码有问题吧

### ISSUE THREAD

**Issue by wangxicoding** [PaddlePaddle/models#3768]
这地方代码有些问题吧
https://github.com/PaddlePaddle/models/blob/361e10fb542c2c90966f8ee77a411d7e21c88932/PaddleCV/PaddleDetection/ppdet/data/transform/__init__.py#L70

用format时{是转义，'{{}}'输出的就是'{}了
代码应该是
```python
  op_repr.append('{{{}}}'.format(str(o)))  # or op_repr.append('{}'.format(str(o)))
```
![image](https://user-images.githubusercontent.com/10208305/67550554-4dd98700-f6f6-11e9-985f-ec120c10654e.png)

**Comment by qingqing01** [comment]
@wangxicoding Thanks!
