### ISSUE TITLE
用自己的VOC数据训练Cascade RCNN

### ISSUE THREAD

**Issue by ShenChen96** [PaddlePaddle/models#3773]
我已经将Config cascade_rcnn_r50_fpn_1x.yml中相应的参数设置为：

metric: VOC

FasterRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/voc
    annotation: VOCdevkit/VOC_all/ImageSets/Main/train.txt
    image_dir: VOCdevkit/VOC_all/JPEGImages
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  drop_last: false
  num_workers: 2

FasterRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/voc
    annotation: VOCdevkit/VOC_all/ImageSets/Main/val.txt
    image_dir: VOCdevkit/VOC_all/JPEGImages
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: VOCdevkit/VOC_all/ImageSets/Main/test.txt
  batch_transforms:
可是在使用脚本python tools/train.py -c configs/cascade_rcnn_r50_fpn_1x.yml训练时报错显示：
 consumer failed with error: failed to map consumer[%s], error: [Errno 2] No such file or directory: 'dataset/voc/VOCdevkit/VOC_all/JPEGImages/15524713780796.json'
请问，使用自己的VOC数据训练CascadeRCNN我还需要修改哪些内容。

**Comment by qingqing01** [comment]
@CrazyRockWZJ 

PaddleDetection里对VOC的数据下载，并做了合并:

```
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
# Extract the data.
echo "Extracting..."
tar -xf VOCtrainval_11-May-2012.tar
tar -xf VOCtrainval_06-Nov-2007.tar
tar -xf VOCtest_06-Nov-2007.tar

echo "Creating data lists..."
python -c 'from ppdet.utils.voc_utils import merge_and_create_list; merge_and_create_list("VOCdevkit", ["2007", "2012"], "VOCdevkit/VOC_all")'
```

即需要再dataset/voc目录下运行： 

```
cd PaddleDetection
export PYTHONPATH=`pwd`:$PYTHONPATH

cd dataset/voc  # 下面有你的数据， 或者到你VOC数据目录下。

python -c 'from ppdet.utils.voc_utils import merge_and_create_list; merge_and_create_list("VOCdevkit", ["2007", "2012"], "VOCdevkit/VOC_all")'
```

**Comment by ShenChen96** [comment]
OK之前的问题解决了，可是我遇到了新的问题。。】
在开始训练后，显示报错并停止：
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
这是因为数据的问题还是其他的配置问题？同样的数据我使用mmdetection可以跑起来。
请问我该如何解决

**Comment by ShenChen96** [comment]
当我按照提示做了之后，依然显示报错“No such file or directory: 'dataset/voc/VOCdevkit/VOC_all/JPEGImages/15524713780796.json'”，很奇怪，明明指定了VOC数据，却要求我在JPEGImages下放入JSON。。。
当我把相应的JSON格式的标注文件全部放入JPEGImages文件夹之后，又报错
error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by qingqing01** [comment]
@CrazyRockWZJ 

这个错误还是图片没读取正确。

数据组织格式如下：

```

dataset/voc/VOCdevkit/VOC_all/
|-- Annotations
|   |-- 000001.xml
|   |-- 000002.xml
|   |-- 000003.xml
|   |-- 000004.xml
|   | ...
|   `-- 2011_003276.xml
|-- ImageSets
|   `-- Main
|       |-- test.txt
|       |-- train.txt
|       `-- val.txt
`-- JPEGImages
    |-- 000001.jpg
    |-- 000002.jpg

```

配置改变如下，我测试了下是可以。

```
git diff configs/cascade_rcnn_r50_fpn_1x.yml

--- a/PaddleCV/PaddleDetection/configs/cascade_rcnn_r50_fpn_1x.yml
+++ b/PaddleCV/PaddleDetection/configs/cascade_rcnn_r50_fpn_1x.yml
@@ -107,9 +107,12 @@ OptimizerBuilder:
 FasterRCNNTrainFeed:
   batch_size: 2
   dataset:
-    dataset_dir: dataset/coco
-    annotation: annotations/instances_train2017.json
-    image_dir: train2017
+    #dataset_dir: dataset/coco
+    #annotation: annotations/instances_train2017.json
+    #image_dir: train2017
+    dataset_dir: dataset/voc
+    annotation: VOCdevkit/VOC_all/ImageSets/Main/train.txt
+    image_dir: VOCdevkit/VOC_all/JPEGImages
   batch_transforms:
   - !PadBatch
     pad_to_stride: 32

```

我们会在优化下VOC的数据组方式，将会支持原始下载数据，不合并的方式。

**Comment by ShenChen96** [comment]
好的，我再尝试一下，谢谢
