### ISSUE TITLE
关于PLATO训练过程中负样本的构造问题

### ISSUE THREAD

**Issue by jiqiujia** [PaddlePaddle/models#3779]
从源代码上看(https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleNLP/Research/Dialogue-PLATO/models/unified_transformer.py#L326)，负样本的构造貌似是直接将正样本做了个反转？
如果是这样的话，基于反转构造的负样本会不会太简单了，导致这是个trivial loss？

**Comment by sserdoubleh** [comment]
构造batch之前，每个epoch经过random sampler，整个数据集已经随机打乱了；只要保证batch_size为偶数，那么这样构造就相当于随机负采样了

**Comment by jiqiujia** [comment]
soga，我想错了，谢谢
