### ISSUE TITLE
paddle slim模型保存在哪里？

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/models#3790]
用paddle slim例子 做模型蒸馏训练，五个小时训练完成，中间没有日志，最后模型也没有保存，请问是什么原因？

**Comment by wanghaoshuang** [comment]
麻烦您把配置文件和脚本贴一下？

**Comment by 1145520074** [comment]
> 麻烦您把配置文件和脚本贴一下？

就是官方配置文件，没有任何修改

**Comment by baiyfbupt** [comment]
经过排查，已确认是用户环境问题。暂时关闭该Issue，如有需要可以随时reopen~
