### ISSUE TITLE
models-develop版本的inference跑yolov3模型出错

### ISSUE THREAD

**Issue by spiritsky123** [PaddlePaddle/models#3829]
按照https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection/inference
上的指引去做，linux平台和windows平台都试了下，自带的模型可以，但是用paddlehub上下下来的yolov3_coco2017，就跑出错，是不是对yolov3的支持都不太好？或者没有测试过？

**Comment by jerrywgz** [comment]
现在paddlehub上的yolov3模型是基于https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/yolov3 这个目录下比较老的实现了，期间修改过一次resize实现，具体参考
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/yolov3/models/yolov3.py#L70
 会导致模型结构改变了，我们会更新下paddlehub的支持

**Comment by spiritsky123** [comment]
用1.5版本的PaddleCV/PaddleDetection/下的yolov3的配置，是不是也是一样的？也跑不下来。
是否要用develop的版本重新跑一次模型？

**Comment by jerrywgz** [comment]
想问下，你这边用的用于inference的模型是怎么得到的？可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/EXPORT_MODEL.md 这个文档将训练好的模型导出为预测需要的模型。如果希望用老的inference模型，可能需要修改下models的代码 https://github.com/PaddlePaddle/models/commit/958b08cd82fa30d0baf0ee760378fe5008ea154f 参考这里，将代码改回原始版本

**Comment by spiritsky123** [comment]
我用的模型是在1.5的models版本，用PaddleDetection你的train.py训练产生的，然后再用当时的infer.py可以save_inference_model。
如果说develop版本的预测代码不匹配，是否2种方式都可以，要么将develop的相应的代码改回去，要么用develop的版本再重新产生模型？

**Comment by jerrywgz** [comment]
是的，只要用相同版本的代码，训练+save_inference就是可以的
