### ISSUE TITLE
dialogue_general_understanding 是否支持ERNIE中文预训练模型

### ISSUE THREAD

**Issue by linuxsong** [PaddlePaddle/models#3843]
dialogue_general_understanding 是否支持ERNIE中文预训练模型？
文档中写的支持的预训练模型中只列出来了ERNIE, english。没有ERNIE, chinese,不知是否支持。

**Comment by jerrywgz** [comment]
dialogue_general_understanding这个里面都是英文任务

**Comment by linuxsong** [comment]
那再问下，是否有中文的支持计划？

**Comment by jerrywgz** [comment]
目前好像还没有，我们可以记录下作为一个需求

**Comment by linuxsong** [comment]
希望能够早日支持，如果仅仅支持英文，那对国内用户的实用性就会大打折扣了。

**Comment by jerrywgz** [comment]
好的，感谢您的反馈

**Comment by xyzhou-puck** [comment]
您好，感谢您的关注，会支持中文的，请关注我们下个版本。
