### ISSUE TITLE
ImportError: No module named soundfile in latest docker

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#386]
docker 使用latest，运行test.py ，提示：
ImportError: No module named soundfile

**Comment by lezasantaizi** [comment]
![image](https://user-images.githubusercontent.com/7878465/31698317-98eeb8be-b382-11e7-8b7d-6bd6cfc08c97.png)

**Comment by lezasantaizi** [comment]
![image](https://user-images.githubusercontent.com/7878465/31698342-b7d7eb9c-b382-11e7-8b86-fb9c507fe7cd.png)

**Comment by kuke** [comment]
hi @lezasantaizi， 你所用的docker镜像只是paddle的开发镜像，没有包含deep speech 2的依赖，请用这个镜像：paddlepaddle/models:deep-speech-2

**Comment by lezasantaizi** [comment]
赞！可以啦！
但是遇到core了

![image](https://user-images.githubusercontent.com/7878465/31700473-3a5ec642-b38f-11e7-9924-f95bdfac1450.png)

**Comment by lezasantaizi** [comment]
谢谢你的建议，已经解决！
