### ISSUE TITLE
fluid1.5.0 mobilenetSSD nms输出坐标不在0-1之间

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/models#3867]
硬件环境：GPU v100
软件环境：fluid1.5.0 ，batch=12, input_size=640
问题：用fluid1.5.0 mobilenetSSD640训练模型时，训练集mAP1.0,测试集0.0;打印fluid.layers.detection_output 结果，发现很多坐标超出0-1范围, 请问detection_output内部会限制0-1范围吗？为什么会出现这种情况？
lodTensor转Numpy输出结果：
![image](https://user-images.githubusercontent.com/20673237/68101009-5e63db80-ff06-11e9-90d3-0bdbea9aedba.png)

**Comment by qingqing01** [comment]
@ellinyang detection_output不会对输出做clip，需要在外面做clip_bbox，可以参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/infer.py#L121

```
def clip_bbox(bbox):
    xmin = max(min(bbox[0], 1.), 0.)
    ymin = max(min(bbox[1], 1.), 0.)
    xmax = max(min(bbox[2], 1.), 0.)
    ymax = max(min(bbox[3], 1.), 0.)
    return xmin, ymin, xmax, ymax

```
如果您用的PaddleDetection，clip是在: https://github.com/PaddlePaddle/PaddleDetection/blob/1f5b8d5c4c46ca52374723123268403d8f471008/ppdet/utils/coco_eval.py#L220

如果是ssd的目录，是在:  https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ssd/infer.py#L121

**Comment by ellinyang** [comment]
@qingqing01 好的，谢谢。
