### ISSUE TITLE
检测模型YOLOv3卷积通道剪裁，使用自己的数据集时，报缺缺‘im_id’错误

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/models#3872]
![image](https://user-images.githubusercontent.com/18586273/68128026-f2a76000-ff51-11e9-8d3e-801ad829e805.png)
我查看源码，在eval.py中，以及results的每一个item的dict中，就是缺少‘im_id’
![image](https://user-images.githubusercontent.com/18586273/68128114-14084c00-ff52-11e9-9ffc-a605f0637034.png)
我自己尝试修改eval_run方法，但没有任何效果

**Comment by slf12** [comment]
> 我查看源码，在eval.py中，以及results的每一个item的dict中，就是缺少‘im_id’

> 我自己尝试修改eval_run方法，但没有任何效果

‘image' , 'im_size', im_id'是在create_feed函数里创建的，data_feed.py里也说了feed的数据是有'im_id‘的
![image](https://user-images.githubusercontent.com/8036226/68388373-6daf8700-019b-11ea-8b34-a0208677b068.png)

您可以看一下您在用自己的数据集时是否feed了'im_id'

而且，我们在写检测的slim时是以voc数据集为标准的，去除了一些不必要的东西，在tools/eval.py，
是有判断的，所以也有可能是没有fetch 'im_id'
![image](https://user-images.githubusercontent.com/8036226/68388709-3b525980-019c-11ea-85c1-7135998de67b.png)

**Comment by wanghaoshuang** [comment]
您将这两行改一下试试？https://github.com/PaddlePaddle/PaddleDetection/blob/master/slim/eval.py#L150-L153
```
eval_keys = ['bbox', 'gt_box', 'gt_label', 'is_difficult', 'im_id']
eval_values = [
        'multiclass_nms_0.tmp_0', 'gt_box', 'gt_label', 'is_difficult', 'im_id'
    ]
```

另外还要在这儿添加一行：https://github.com/PaddlePaddle/PaddleDetection/blob/master/slim/eval.py#L85
```
outs.append(data['im_id'])
```

**Comment by Ezra-Yu** [comment]
谢谢解答，问题解决了
