### ISSUE TITLE
deep_speech_2 中test.py 遇到的问题

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#388]
下载了paddlepaddle/models:deep-speech-2 ,直接运行了test.py,找不到以下这个文件，我需要如何获取这个数据？
IOError: [Errno 2] No such file or directory: 'data/librispeech/mean_std.npz'

**Comment by luotao1** [comment]
这个文件是算出来的，请参考：https://github.com/PaddlePaddle/models/tree/develop/deep_speech_2#compute-mean--stddev-for-normalizer

**Comment by xinghai-sun** [comment]
也可以参考 [Getting Started](https://github.com/PaddlePaddle/models/tree/develop/deep_speech_2#getting-started) ，以及里面提到的 `./examples/librispeech/run_data.sh`，该脚本包含了`tools/compute_mean_std.py`的调用。

**Comment by lezasantaizi** [comment]
多谢两位！
现在tiny的compute_mean_std.py运行没有问题，但是data/librispeech/manifest.train的有问题，
运行data/librispeech/librispeech.py，有库找不到，感觉import的路径不对


```
“
For how to generate such manifest files, please refer to data/librispeech/librispeech.py, which will download data and generate manifest files for LibriSpeech dataset.

Compute Mean & Stddev for Normalizer

To perform z-score normalization (zero-mean, unit stddev) upon audio features, we have to estimate in advance the mean and standard deviation of the features, with some training samples:

python tools/compute_mean_std.py \
--num_samples 2000 \
--specgram_type linear \
--manifest_paths data/librispeech/manifest.train \
--output_path data/librispeech/mean_std.npz
It will compute the mean and standard deviation of power spectrum feature with 2000 random sampled audio clips listed in data/librispeech/manifest.train and save the results to data/librispeech/mean_std.npz for further usage.


”
```
按照上面描述运行，出现如下错误，请问这里是不是import的路径不对了？

**Comment by lezasantaizi** [comment]
![Uploading image.png…]()

**Comment by lezasantaizi** [comment]
```
root@f847eff80985:/paddle# python data/librispeech/librispeech.py
Traceback (most recent call last):
  File "data/librispeech/librispeech.py", line 19, in <module>
    from data_utils.utility import download, unpack
ImportError: No module named data_utils.utility
```

**Comment by lezasantaizi** [comment]
修改了data/librispeech/librispeech.py，
加了一句：sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + '../../'))，把目录跳转到上上级
```
import distutils.util
import os
import sys
import argparse
import soundfile
import json
import codecs
sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + '../../'))
from data_utils.utility import download, unpack
```

**Comment by john81529** [comment]
楼主你的问题解决了吗？我也是docker下运行，也是这个错误，怎么都解决不了

**Comment by sivagururaman** [comment]
@kuke 
I am also facing the issue of ImportError: No module named data_utils.utility
when i ran sh run_data.sh. Can you help me with this issue?

**Comment by seethagithub** [comment]
Hi, Im facing a similar issue. Is there a wirkaround to this? 
Traceback (most recent call last):
  File "data/librispeech/librispeech.py", line 19, in <module>
    from data_utils.utility import download, unpack
