### ISSUE TITLE
texcnn finetune是不是限制了只能三分类

### ISSUE THREAD

**Issue by shiwl0329** [PaddlePaddle/models#3891]
在做二分类task的时候，发现报错如下：
![image](https://user-images.githubusercontent.com/13725297/68285017-792a8180-00b9-11ea-8b49-567701484ba6.png)

**Comment by heavengate** [comment]
应该是你在做二分类的finetun，但是导入了三分类的weight，你在load weight的时候把最后那层与类别数有关的weight不要导入，或者直接在weight里面把那个和类别数输出相关的权重删掉就可以了

**Comment by shiwl0329** [comment]
> 应该是你在做二分类的finetun，但是导入了三分类的weight，你在load weight的时候把最后那层与类别数有关的weight不要导入，或者直接在weight里面把那个和类别数输出相关的权重删掉就可以了

这个在哪指定呢？并不很清楚相关的api，我理解的finetune model应该是与label无关的weight param，我用ernie finetune就不会出现这种问题。或者在paddle qq群指导一下，让大家也知道这个问题

**Comment by heavengate** [comment]
一般是网络最后一层，每一层都有名字的，你可以在pretrain里面把包含网络租后一层权重的文件删掉

**Comment by shiwl0329** [comment]
确实OK，谢谢，但这种有点略显笨重，用ernie finetune直接就可以train model，不像这个，还不知道什么原因导致的~

**Comment by heavengate** [comment]
应该是ernie发布的pretrain权重里面不包含输出层

**Comment by shiwl0329** [comment]
应该是的，但是这种pretrain model，为何把label限定死了，这个用户想做个多分类都难，哈哈
