### ISSUE TITLE
can not import ppdet.core.workspace

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/models#3893]
在PaddleDetection目录下，直接运行，提示无法导入，运行python，再导入，是没问题的，想问下这是什么问题呢？

![image](https://user-images.githubusercontent.com/14270174/68285650-a1ff4680-00ba-11ea-8ec8-ba39555e16c6.png)

**Comment by heavengate** [comment]
第一次运行之前有 `export PYTHONPATH=`pwd`:$PYTHONPATH` 么

**Comment by littletomatodonkey** [comment]
嗯嗯之前没有，运行之后可以了，感谢感谢（不过我在本地好像不用这样export..）

**Comment by heavengate** [comment]
python识别当前目录作为PYTHONPATH不同环境和版本，还有本身系统配置上会不同，估计是运行了python之后能识别当前目录了。。。
