### ISSUE TITLE
模型剪裁后，fps降低了，是什么原因

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/models#3895]
![image](https://user-images.githubusercontent.com/18586273/68352027-221bbf80-0140-11ea-8750-34a57ccc6e77.png)

我跑了yolo，backbone是mobileNet，在剪裁后模型的fps由69.8降低为54.8，就很奇怪。
其他参数都很正常

**Comment by Ezra-Yu** [comment]
我仔细看了下，没裁减之前用的model测得fps，裁减后用的eval_model测得fps，这样fps速度就正常了！
大概没裁减为46.7，裁减后为52.7
这就有新的问题了，为什么eval_model会比model慢，model的磁盘占用空间一般是eval_model的两倍。

**Comment by wanghaoshuang** [comment]
>没裁减之前用的model, 裁减后用的eval_model

>没裁减为46.7, 裁减后为52.7

>为什么eval_model会比model慢

请问您这三句话什么意思？看起来是矛盾的。

**Comment by wanghaoshuang** [comment]
![image](https://user-images.githubusercontent.com/7534971/68672319-4c301000-058c-11ea-9b31-ad15a8f504dc.png)
这是我们这边的测试结果
