### ISSUE TITLE
Imagenet图像分类工程，内存一直不停增长直到占满

### ISSUE THREAD

**Issue by Yogurt2019** [PaddlePaddle/models#3899]
你好，我使用的是github上最新1.6版本的models工程PaddleCV中的image_classification，PaddlePaddle版本1.6，工程基本没有改动，使用我自己的数据集，在多进程训练时，内存会一直不停增长，直到内存全部占满。
我的内存大小是128G，使用的显卡是Tesla V100
**另外我尝试调整过reader_thread、reader_buf_size和batch size，已经调整到足够小了，再小的话会影响性能，reader_thread为6，reader_buf_size为512，PyReader的capacity调整为4，而且我开启了FLAGS_eager_delete_tensor_gb=0，打开inplace策略等，内存还是会一直不停增长，直到128G内存全部占满。**
请问这种情况如何解决？

我刚刚试了一下，使用imagenet数据集来训练，内存会一直不断的上涨，我的训练参数是：
python -m paddle.distributed.launch train.py
--model=ResNet34
--batch_size=300
--reader_thread=12
--reader_buf_size=2048
其他全部为默认值，内存依然不断上涨，内存已经占超过70G了
![image](https://user-images.githubusercontent.com/49382659/68395704-3d6fe480-01ab-11ea-9df2-ae57f9f06107.png)

**Comment by LielinJiang** [comment]
请问你使用的训练命令是？

**Comment by Yogurt2019** [comment]
> 请问你使用的训练命令是？

python -m paddle.distributed.launch train.py

**Comment by LielinJiang** [comment]
> > 请问你使用的训练命令是？
> 
> python -m paddle.distributed.launch train.py

能给下完整的运行参数吗？我先复现一下

**Comment by Yogurt2019** [comment]
> > > 请问你使用的训练命令是？
> > 
> > 
> > python -m paddle.distributed.launch train.py
> 
> 能给下完整的运行参数吗？我先复现一下

您好，可以加您QQ说么？我的QQ是563738456，谢谢！
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m paddle.distributed.launch train.py \
       --model=ResNet34 \
       --batch_size=120 \
       --total_images=490000 \
       --class_dim=6671 \
       --image_shape=3,672,672 \
       --model_save_dir=output/ \
       --lr_strategy=piecewise_decay \
       --reader_thread=6 \
       --reader_buf_size=512 \
       --lr=0.1

**Comment by LielinJiang** [comment]
好的~
