### ISSUE TITLE
关于语音识别模型：BaiduCN1.2k Model

### ISSUE THREAD

**Issue by cyy0523xc** [PaddlePaddle/models#3905]
你好，请问该模型是使用DeepSpeech2训练出来的吗？

https://github.com/PaddlePaddle/DeepSpeech/blob/develop/README_cn.md

**Comment by sandyhouse** [comment]
是的。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
