### ISSUE TITLE
paddle_detection 配置文件中class_aware_sampling意义？

### ISSUE THREAD

**Issue by ronghaoLee** [PaddlePaddle/models#3909]
同学您好：
        我发现paddle_detection中新增了config/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml文件，请问文件中 “FasterRCNNTrainFeed”中的 “class_aware_sampling” 是什么意义呢？或者有没有相关的参考资料。多谢啦

**Comment by ceci3** [comment]
这个是在读数据的时候的一种特殊处理方法，会根据每个类别的样本数的比例进行采样 https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/data/source/class_aware_sampling_roidb_source.py#L95 可以参考这里

**Comment by qingqing01** [comment]
@ronghaoLee 可以参考文档 https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/CACascadeRCNN.md#%E6%96%B9%E6%B3%95%E6%8F%8F%E8%BF%B0

**Comment by ronghaoLee** [comment]
好的 多谢您！
