### ISSUE TITLE
数组访问除了切片访问,是否支持以数组为索引,来批量访问不同位置的数据?

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#3928]
比如我有数组A[10], 现在要访问第1,3,5,6,9这几个数据, 假设Id = [1,3,5,6,9], 可否通过A[Id]来访问第1,3,5,6,9这几个数据?

**Comment by zhaoyuchen2018** [comment]
可以试下scatter：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/scatter_cn.html#scatter

**Comment by wenston2006** [comment]
@zhaoyuchen2018 谢谢回复, 上面的问题是在一维数组中取数据; 我现在还有另一个矩阵访问的问题: 现在我有矩阵A[5, 20], 对A的5行分别取第1,3,5,6,9这几列的数据, 也就是说我想获取的数据为B = [A[0, 1], A[1,3], A[2,5], A[3,6], A[4,9]] 请问有什么办法可以不通过for循环来访问?

**Comment by zhaoyuchen2018** [comment]
你这个是访问不同行的不同列吧，目前好像没有直接支持的OP

**Comment by wenston2006** [comment]
@zhaoyuchen2018  谢谢回复,明白了
