### ISSUE TITLE
models/legacy/generate_sequence_by_rnn_lm 代码使用新版paddle 1.6.1无法使用

### ISSUE THREAD

**Issue by skriser** [PaddlePaddle/models#3934]
models/legacy/generate_sequence_by_rnn_lm 代码使用新版paddle 1.6.1无法使用。
代码都是老代码，根本没有办法进行运行测试

**Comment by zhaoyuchen2018** [comment]
你好，该模型目前已经不再维护，推荐使用https://github.com/PaddlePaddle/models#PaddleNLP下面的模型

**Comment by skriser** [comment]
我看新的model里面只有翻译的，可以给个新的文本生成的代码吗

**Comment by zhaoyuchen2018** [comment]
可以参考下面的模型：

https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/PaddleTextGEN/seq2seq， https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/PaddleTextGEN/variational_seq2seq
