### ISSUE TITLE
similarity net什么时候可以提供基于预训练模型的微调功能？

### ISSUE THREAD

**Issue by linuxsong** [PaddlePaddle/models#3936]
similarity net目前好像不支持基于预训练模型的微调功能，如果能提供基于预训练模型下针对自己的业务数据进行微调功能，效果应该会提升很多吧。

**Comment by liupluswei** [comment]
你好，我咨询了一下相关模型的负责人，目前这个是支持的：
![image](https://user-images.githubusercontent.com/46661762/68925751-bf20cd00-07be-11ea-8ae1-c4b46bc508f3.png)

**Comment by linuxsong** [comment]
之前没有注意到这里，非常感谢。
