### ISSUE TITLE
ctr 下的dcn模型求助

### ISSUE THREAD

**Issue by LBSIX** [PaddlePaddle/models#3944]
我的环境是win7 系统  最新的fluid版本，是在python版本是3.6.5.是在pycharm 中直接运行local_train.py文件的，数据集用的和原数据集一致。
 exe.train_from_dataset(
            program=fluid.default_main_program(),
            dataset=dataset,
            fetch_list=[
                dcn_model.loss, dcn_model.avg_logloss, dcn_model.auc_var,dcn_model.net_input
            ],
            fetch_info=['total_loss', 'avg_logloss', 'auc'],
            debug=False,
            print_period=1)
我想看训练输出结果  但是为什么没输出呢

**Comment by JiaXiao243** [comment]
ctr下的dcn模型目前不支持windows，只支持linux环境运行～

**Comment by LBSIX** [comment]
收到了，还有个疑问，如何查看，网络中的各个中间变量呢，如self.net_input等。相关函数资料太少了( ˙˘˙ )------------------ 原始邮件 ------------------
发件人: "贾晓"<notifications@github.com>
发送时间: 2019年11月19日(星期二) 下午4:29
收件人: "PaddlePaddle/models"<models@noreply.github.com>;
抄送: "LBSIX"<1952865431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/models] ctr 下的dcn模型求助 (#3944)



ctr下的dcn模型目前不支持windows，只支持linux环境运行～
 
&mdash;

**Comment by ysh329** [comment]
建议用动态图方式，具体见文档

动态图机制-DyGraph-使用文档-PaddlePaddle深度学习平台
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/dygraph/DyGraph.html

**Comment by LBSIX** [comment]
> 建议用动态图方式，具体见文档
> 
> 动态图机制-DyGraph-使用文档-PaddlePaddle深度学习平台
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/dygraph/DyGraph.html

您的意思是  我用动图机制重构dcn模型吗

**Comment by ysh329** [comment]
或者您用静态图吧想要获取的结果放到fetch_list就好

**Comment by ysh329** [comment]
@JiaXiao243 回复一下吧

**Comment by wilhelmzh** [comment]
你好，可以用像上面说的改成动态图。或者尝试使用下面两种方式
1.  直接在网络中用fluid.layers.Print(net_input)打印输出。
2. 在train_from_dataset里设置fetch_list和fetch_info。

**Comment by shuDaoNan9** [comment]
这个DCN模型我下载到Windows10上面运行dist_data这个小数据集，结果如下：
INFO:fluid:TEST --> batch: 9 loss: [0.6760486] auc_val: [0.5264826]
The last log info is the total Logloss and AUC for all test data. 
跟readme说的0.8的auc差距好大哦

**Comment by LBSIX** [comment]
目前仅支持 linux环境运行，而且我跑的是0.79


 
---原始邮件---
发件人: "JWenBin"<notifications@github.com&gt;
发送时间: 2019年12月5日(星期四) 下午4:12
收件人: "PaddlePaddle/models"<models@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"LBSIX"<1952865431@qq.com&gt;;
主题: Re: [PaddlePaddle/models] ctr 下的dcn模型求助 (#3944)



这个DCN模型我下载到Windows10上面运行dist_data这个小数据集，结果如下：
 INFO:fluid:TEST --&gt; batch: 9 loss: [0.6760486] auc_val: [0.5264826]
 The last log info is the total Logloss and AUC for all test data.
 跟readme说的0.8的auc差距好大哦

**Comment by shuDaoNan9** [comment]
为啥我的Windows10能运行？跟Linux有差别吗？

**Comment by LBSIX** [comment]
不知道了------------------ 原始邮件 ------------------
发件人: "JWenBin"<notifications@github.com>
发送时间: 2019年12月5日(星期四) 下午4:30
收件人: "PaddlePaddle/models"<models@noreply.github.com>;
抄送: "LBSIX"<1952865431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/models] ctr 下的dcn模型求助 (#3944)



为啥我的Windows10能运行？
 
&mdash;
