### ISSUE TITLE
训练ssd demo内存占用随着pass增加而增加

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/models#397]
如题，每次跑到20左右pass的时候就因为内存不足被kill掉，pass0 pass2之类的占用还是5%左右，到了pass7就到了30%了，越到后面，内存占用不停地变多

             total       used       free     shared    buffers     cached
Mem:      24519888   24356632     163256          0      49744   15330580
-/+ buffers/cache:    8976308   15543580
Swap:            0          0          0

**Comment by pkuyym** [comment]
你用的PaddlePaddle版本是？是自己源码编译还是使用的docker镜像

**Comment by bushidonggua** [comment]
昨天新拉的paddle dev最新版，自己编译的

**Comment by pkuyym** [comment]
这个有可能是由于卷积层引起的，你可以尝试显式指定img_conv的类型，具体是通过增加layer_type='exconv'

**Comment by bushidonggua** [comment]
解决了，谢谢！

**Comment by lcy-seso** [comment]
@bushidonggua 请问是怎样解决的呢，是因为卷积类型引起的吗？通过指定 layer_type='exconv' 解决吗？
