### ISSUE TITLE
PaddleCV/image_classification/下的脚本在CPU版的paddle报错

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/models#3988]
涉及到两个脚本
1：reader.py 271行
batch_size = settings.batch_size / paddle.fluid.core.get_cuda_device_count() 
2：utils/utility.py 419行
exec_strategy.num_threads = fluid.core.get_cuda_device_count()

**Comment by cyj1986** [comment]
为什么会用CPU版的paddle跑带GPU的程序呢？

**Comment by shippingwang** [comment]
你好，这个问题已经在最新的[PR](https://github.com/PaddlePaddle/models/pull/3951)解决，感谢指正
