### ISSUE TITLE
能否在image_classification的训练脚本里面增加visualdl可视化输出？

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/models#3989]
现在的脚本训练时只能在控制台看输出，无法可视化看效果

**Comment by linshuliang** [comment]
相比VisualDL, tb-paddle + tensorboard 的功能更强大，且更美观。目前可在 SCALAR栏目记录 loss/acc1/acc5, IMAGE 记录图片， GRAPH 记录计算图。 等协商核对后，即可添加。

**Comment by zouxiaodong** [comment]
现在已经支持了tensorboard了吗？我在image_classification下训练自定义的数据集，怎么用tensorboards查看？
python train.py \
       --data_dir=/root/paddle/lemon/data/ \
       --model=ResNet50 \
       --batch_size=8 \
       --total_images=6390 \
       --class_dim=3 \
       --image_shape=3,900,900 \
       --model_save_dir=/root/paddle/lemon/train_model/ \
       --lr_strategy=piecewise_decay \
       --lr=0.1 \
       --reader_thread=8 \
       --use_gpu=false

**Comment by linshuliang** [comment]
目前还不支持，已列入下一步计划。

**Comment by zouxiaodong** [comment]
OK，期待中
