### ISSUE TITLE
image_classification 训练自定义数据集batch问题

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/models#3995]
数据集总共:6390，训练集有 5112行记录，batch_size设置为8,训练脚本输出的batch,train 和 test 只到70+

![image](https://user-images.githubusercontent.com/46236818/69712327-98a74e00-113d-11ea-8a6f-7fc9394f62f8.png)

执行的脚本如下：
python train.py \
       --data_dir=/root/paddle/lemon/data/ \
       --model=ResNet50 \
       --batch_size=8 \
       --total_images=6390 \
       --class_dim=3 \
       --image_shape=3,900,900 \
       --model_save_dir=/root/paddle/lemon/train_model/ \
       --lr_strategy=piecewise_decay \
       --lr=0.1 \
       --reader_thread=8 \
       --use_gpu=false

**Comment by zouxiaodong** [comment]
数据集;
[data.tar.gz](https://github.com/PaddlePaddle/models/files/3896202/data.tar.gz)

**Comment by xyoungli** [comment]
您好，把total images设置成训练集大小5112测试一下，tatol images是指训练集的数据大小

**Comment by zouxiaodong** [comment]
@xyoungli ，您好，设置为5112后，train和test还是70+个batch，请问这个70+ 是怎么来的啊，我理解应该是5112/8(batch_size)个batch吧？

 test_batch_size : 16
             total_images : 5112
              upper_ratio : 1.3333333333333333
                   use_aa : False
                  use_ema : False
                  use_gpu : 0
      use_label_smoothing : False
                use_mixup : False
                   use_se : True
                 validate : 1
           warm_up_epochs : 5.0
----------------------------------------------------
Finish initing model from /root/paddle/lemon/train_model/ResNet50_bak/119
I1128 10:44:56.898684 23203 parallel_executor.cc:421] The number of CPUPlace, which is used in ParallelExecutor, is 8. And the Program will be copied 8 copies
W1128 10:44:57.571743 23203 fuse_all_reduce_op_pass.cc:72] Find all_reduce operators: 161. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 160.
I1128 10:44:57.600435 23203 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1128 10:44:58.508209 23203 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1128 10:44:58.721208 23203 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
[Pass 0, train batch 0]         loss 0.27105, acc1 0.92188, acc5 0.92188, lr 0.10000, elapse 15.4330 sec
[Pass 0, train batch 10]        loss 0.28126, acc1 0.92188, acc5 0.92188, lr 0.10000, elapse 8.9609 sec
[Pass 0, train batch 20]        loss 0.41547, acc1 0.81250, acc5 0.81250, lr 0.10000, elapse 8.9909 sec
[Pass 0, train batch 30]        loss 0.27856, acc1 0.90625, acc5 0.90625, lr 0.10000, elapse 8.8661 sec
[Pass 0, train batch 40]        loss 0.24455, acc1 0.90625, acc5 0.90625, lr 0.10000, elapse 8.7948 sec
[Pass 0, train batch 50]        loss 0.28105, acc1 0.89062, acc5 0.89062, lr 0.10000, elapse 8.7400 sec
[Pass 0, train batch 60]        loss 0.27648, acc1 0.89062, acc5 0.89062, lr 0.10000, elapse 8.6651 sec
[Pass 0, train batch 70]        loss 0.35871, acc1 0.87500, acc5 0.87500, lr 0.10000, elapse 8.8297 sec
[Pass 0, test  batch 0]         loss 0.14715, acc1 1.00000, acc5 1.00000, elapse 2.0655 sec
[Pass 0, test  batch 10]        loss 0.31711, acc1 0.87500, acc5 0.87500, elapse 1.8151 sec

**Comment by xyoungli** [comment]
请问数据集中有train和val文件夹吗？

**Comment by zouxiaodong** [comment]
@xyoungli 您好， 数据集没有train和val文件夹，只有train_list.txt val_list.txt test_list.txt 和3个class目录cls1 cls2 cls3
数据集的几个txt文件如下
[data.tar.gz](https://github.com/PaddlePaddle/models/files/3900947/data.tar.gz)

![image](https://user-images.githubusercontent.com/46236818/69794831-ef785a80-1205-11ea-9219-225daef62643.png)

**Comment by shippingwang** [comment]
你好，先设置 print_step设置为1查看下，到底跑了多少batch结束的

**Comment by zouxiaodong** [comment]
@xyoungli  你好，我现在的总训练数据为6915，batch为108次，我研究了下应该是和reader和cpu个数相关，108*8 = 6915/8 ，这样刚好对上
![image](https://user-images.githubusercontent.com/46236818/69840524-dc619b00-1296-11ea-9891-81aa446d6d97.png)
