### ISSUE TITLE
example configuration for LTR task.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#4]
In this example, we would like to show how to do LTR task in PaddlePaddle. Usually, there are three ways:
1. pointwise (a simple regression/classification task, so we do not consider this situation in this example)
2. pairwise, please refer to [this](https://github.com/lcy-seso/paddle_confs_v1/blob/master/ltr/pairwise_ltr.conf) configuration file written in old PaddlePaddleAPI.
3. listwise, please refer to [this](https://github.com/lcy-seso/paddle_confs_v1/blob/master/ltr/listwise_ltr.conf) configuration file written in old PaddlePaddleAPI.

The example also must include *how to predict*. Note that in LTR task, training and testing network is different.

I suggest to use [movielens](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/movielens.py) dataset.

Please pull your codes and docs into the [ltr](https://github.com/PaddlePaddle/models/tree/develop/ltr)  directory.

**Comment by dzhwinter** [comment]
TODO:
fix this project.

**Comment by llxxxll** [comment]
@dzhwinter 已认领
