### ISSUE TITLE
调用image_classification的eval.py脚本报错

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/models#4012]
训练时输入shape为3，900，900
python eval.py \
       --data_dir=/root/paddle/lemon/data/augmentation/ \
       --model=ResNet50 \
       --batch_size=8 \
       --class_dim=3 \
       --image_shape=3,900,900 \
       --crop_size=900 \
       --use_gpu=false \
       --pretrained_model=/root/paddle/lemon/new_train_model/ResNet50/119/

==错误信息如下：
-------------  Configuration Arguments -------------
               batch_size : 8
                class_dim : 3
                crop_size : 900
                 data_dir : /root/paddle/lemon/data/augmentation/
               image_mean : [0.485, 0.456, 0.406]
              image_shape : 3,900,900
                image_std : [0.229, 0.224, 0.225]
            interpolation : None
                    model : ResNet50
             padding_type : SAME
         pretrained_model : /root/paddle/lemon/new_train_model/ResNet50/119/
          reader_buf_size : 2048
            reader_thread : 8
        resize_short_size : 256
                  use_gpu : 0
                   use_se : True
----------------------------------------------------
Traceback (most recent call last):
  File "eval.py", line 154, in <module>
    main()
  File "eval.py", line 150, in main
    eval(args)
  File "eval.py", line 119, in eval
    feed=feeder.feed(data))
  File "/root/miniconda3/envs/lemon/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 296, in feed
    ret_dict[each_name] = each_converter.done()
  File "/root/miniconda3/envs/lemon/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 105, in done
    arr = numpy.array(self.data, dtype=self.dtype)
ValueError: could not broadcast input array from shape (3,256,297) into shape (3)
terminate called without an active exception
W1202 11:51:39.412518 13898 init.cc:205] *** Aborted at 1575258699 (unix time) try "date -d @1575258699" if you are using GNU date ***
W1202 11:51:39.416721 13898 init.cc:205] PC: @                0x0 (unknown)
FATAL: exception not rethrown

![image](https://user-images.githubusercontent.com/46236818/69926451-8176b080-14ef-11ea-8514-a934e92e4db0.png)

**Comment by willthefrog** [comment]
`image_shape`指的是预处理后输入网络的大小，一般是224，256，288。你确定输入是900？

**Comment by zouxiaodong** [comment]
@willthefrog 您好，训练是用的如下参数，输入的大小是900
python train.py \
       --data_dir=/root/paddle/lemon/data/augmentation/ \
       --model=ResNet50 \
       --batch_size=8 \
       --total_images=6915   \
       --resize_short_size=900 \
       --class_dim=3 \
       --image_shape=3,900,900 \
       --model_save_dir=/root/paddle/lemon/new_train_model/ \
       --lr_strategy=piecewise_decay \
       --lr=0.1 \
       --reader_thread=8 \
       --use_gpu=False \
       --print_step=1

**Comment by shippingwang** [comment]
image_shape=3,900,900
crop_size=900 
resize_short_size=900 都加上试试

**Comment by zouxiaodong** [comment]
@shippingwang  加上去运行正常了，谢谢
![image](https://user-images.githubusercontent.com/46236818/69936709-8c433c80-1513-11ea-8a6d-bc3cf5badf4c.png)
