### ISSUE TITLE
reshape输出shape的问题

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/models#4013]
在reshape中，如果参数shape是lodtensor的话，那么编译时，所有值都是-1，而conv2d要求channel必须是明确的值(>0)，感觉这一块需要修改一下，不然每次用tensor进行reshape的话，编译时就会报错~

**Comment by liym27** [comment]
因为编译期Tensor的值是无法确定的（运行期才可以确定），所以参数`shape`是`Tensor`时，reshape的output 的shape所有值都是-1。

**Comment by littletomatodonkey** [comment]
那就是说其实没法用tensor作为reshape的shape？（不然conv2d会报错）

**Comment by liym27** [comment]
> 那就是说其实没法用tensor作为reshape的shape？（不然conv2d会报错）

目前确实是这样的。因为`conv2d`的channel值在编译期必须明确。 若channel值不确定，会影响conv2d 中 filter的创建。
如果reshape中`shape`的部分值是确定的，可以在编译期传入。如`shape = [tensor1, 3, tensor2]`，其中3是已知值。

**Comment by littletomatodonkey** [comment]
好的，这个之后会做出修改吗？比如说强制reshape的shape参数类型或者取消assertion之类的？不然其实是无法用tensor去做reshape的。

**Comment by littletomatodonkey** [comment]
> > 那就是说其实没法用tensor作为reshape的shape？（不然conv2d会报错）
> 
> 目前确实是这样的。因为`conv2d`的channel值在编译期必须明确。 若channel值不确定，会影响conv2d 中 filter的创建。
> 如果reshape中`shape`的部分值是确定的，可以在编译期传入。如`shape = [tensor1, 3, tensor2]`，其中3是已知值。

好的，暂时只能这样先写了，这个之后会做出修改吗？感觉现在这样用的话比较繁琐~

**Comment by liym27** [comment]
> 好的，这个之后会做出修改吗？比如说强制reshape的shape参数类型或者取消assertion之类的？不然其实是无法用tensor去做reshape的。

感谢建议。在您不修改现有代码的情况下，还无法达到您期望的效果。建议暂时用替代方案。另外，
- 关于 强制reshape的shape参数类型：
  - reshape的参数`shape`可以是一个Tensor，也可以是list/tuple，list/tuple中可以有Tensor。可以将部分确定值传到`shape`中。
  - reshape支持2个参数`shape`和`actual_shape`，这2个参数可以同时使用。`actual_shape`可传入Tensor类型的值，`shape`可以传list，在编译期使用参数`shape`，运行期使用`actual_shape`。参考[API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/reshape_cn.html)

- 关于 取消assertion之类的，暂不可行：
  - 您现在使用conv2d时， `filter` 在conv2d内部创建，通过传入conv2d的参数`num_filters`, `filter_size` 以及 `input`的 **channel维度**值确定filter的大小。为了能正确创建filter，需要input的**channel维度已知**。
  - 如果`filter`由用户自行创建后 再传入conv2d，那么就不必强制channel维度已知。这个功能目前在测试阶段，还未开放。

**Comment by littletomatodonkey** [comment]
好的，谢谢
