### ISSUE TITLE
在训练过程中配置是默认存在resize的吗？在测试过程中并没有resize？是否会影响输出结果

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#4016]
使用的PaddleDetection的mask rcnn模型 发现在configs中默认存在resize
我的图片尺寸过大都是2048.1024
默认配置的resize后测试时是否会影响我的结果？

**Comment by willthefrog** [comment]
测试过程中也需要resize。另外 `PaddleDetection` 请移步 https://github.com/PaddlePaddle/PaddleDetection
