### ISSUE TITLE
多方向文字识别如何实现？目前的ocr model好像只能用于水平方向文字识别

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#4026]
比如现在有一行文字，里面的每个字顺时针或逆时针旋转了９０度（这种情况是存在的，比如一列中文汉字旋转到水平方向）；这中情况下应如何处理？由于目前的模型都是针对行文本设计的，是否应该再针对顺时针或逆时针旋转，分别训练两个文字识别模型？

**Comment by wanghaoshuang** [comment]
hi, 目前Paddle模型库只发布了行文本识别模型，暂时没有满足您需求的模型。

如果每个字的旋转角度一样，且还是在一行的话，还是用行文字识别模型训练的，但是要保证要训练数据旋转角度一样。

**Comment by wenston2006** [comment]
＠ｗａｎｇhaoshuang 明白了，谢谢回复
