### ISSUE TITLE
图像分类DALI出错

### ISSUE THREAD

**Issue by dbcool** [PaddlePaddle/models#4027]
进行图像分类时使用DALI出错
配置:nvidia-dali:0.16.0, paddle:1.6.1, gcc:5.4,cuda10
我的运行指令:
export CUDA_VISIBLE_DEVICES=0,1,2,3 
export FLAGS_fraction_of_gpu_memory_to_use=0.80
python -m paddle.distributed.launch train.py \
    --model=SE_ResNet50_vd \
    --pretrained_model=pretrain_model/SE_ResNet50_vd_pretrained/ \
    --batch_size=200 \
    --data_dir=data/terror_detail/ \
    --num_epochs=60 \
    --total_images=437462 \
    --class_dim=14 \
    --model_save_dir=terror/output_terror_detail/ \
    --lr_strategy=cosine_decay_warmup \
    --use_label_smoothing=True \
    --use_mixup=True \
    --use_dali=True \
    --reader_thread=4 \
    --lr=0.01
错误是:
                 validate : 1
           warm_up_epochs : 5.0
----------------------------------------------------
W1204 09:21:20.665040  4048 device_context.cc:235] Please NOTE: device: 3, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1204 09:21:20.671504  4048 device_context.cc:243] device: 3, cuDNN Version: 7.6.
W1204 09:21:20.693971  4045 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1204 09:21:20.700013  4045 device_context.cc:243] device: 0, cuDNN Version: 7.6.
W1204 09:21:20.711027  4046 device_context.cc:235] Please NOTE: device: 1, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1204 09:21:20.716599  4046 device_context.cc:243] device: 1, cuDNN Version: 7.6.
W1204 09:21:20.730718  4047 device_context.cc:235] Please NOTE: device: 2, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1204 09:21:20.735841  4047 device_context.cc:243] device: 2, cuDNN Version: 7.6.
W1204 09:21:22.707733  4045 init.cc:205] *** Aborted at 1575451282 (unix time) try "date -d @1575451282" if you are using GNU date ***
W1204 09:21:22.709415  4045 init.cc:205] PC: @                0x0 (unknown)
W1204 09:21:22.709626  4045 init.cc:205] *** SIGSEGV (@0x0) received by PID 4045 (TID 0x7fa1d202c740) from PID 0; stack trace: ***

**Comment by shippingwang** [comment]
1.检查paddle.fluid.install_check.run_check()确定paddle可用
2.务必注意：[三个注意事项](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by dbcool** [comment]
执行.fluid.install_check.run_check()，最后几行是:
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

gcc版本:
gcc version 5.4.0 (GCC)

nvidia-dali版本:
nvidia-dali-nightly 0.17.0.dev20191202

设置过FLAGS_fraction_of_gpu_memory_to_use:
export FLAGS_fraction_of_gpu_memory_to_use=0.8

还是报错:
W1205 05:14:24.196503   618 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1205 05:14:24.201333   618 device_context.cc:243] device: 0, cuDNN Version: 7.6.
W1205 05:14:26.075039   618 init.cc:205] *** Aborted at 1575522866 (unix time) try "date -d @1575522866" if you are using GNU date ***
W1205 05:14:26.076762   618 init.cc:205] PC: @                0x0 (unknown)
W1205 05:14:26.076963   618 init.cc:205] *** SIGSEGV (@0x0) received by PID 618 (TID 0x7f7525deb740) from PID 0; stack trace: ***

**Comment by shippingwang** [comment]
注意用>gcc54编译

**Comment by dbcool** [comment]
嗯嗯，用hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev镜像编译了paddle，并重新安装了一下
执行指令:
export CUDA_VISIBLE_DEVICES=0,1,2,3 
python -m paddle.distributed.launch train.py \
    --model=SE_ResNet50_vd \
    --pretrained_model=pretrain_model/SE_ResNet50_vd_pretrained/ \
    --batch_size=100 \
    --data_dir=data \
    --num_epochs=60 \
    --total_images=839981 \
    --class_dim=6 \
    --model_save_dir=terror/output_terror_detail/ \
    --lr_strategy=cosine_decay_warmup \
    --use_label_smoothing=True \
    --reader_thread=4 \
    --use_dali=True \
    --lr=0.01
报错:
 File "train.py", line 180, in train
    train_fetch_vars[0], exe)
  File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/utility.py", line 428, in best_strategy_compiled
    dist_utils.prepare_for_multi_process(exe, build_strategy, program)
  File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/dist_utils.py", line 91, in prepare_for_multi_process
    nccl2_prepare_paddle(trainer_id, startup_prog, train_prog)
  File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/dist_utils.py", line 76, in nccl2_prepare_paddle
    program=main_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 571, in transpile
    wait_port=self.config.wait_port)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 355, in _transpile_nccl2
    self.config.hierarchical_allreduce_inter_nranks
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2483, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1763, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1645, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "gen_nccl_id" has not been registered.

**Comment by zhiqiu** [comment]
> 嗯嗯，用hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev镜像编译了paddle，并重新安装了一下
> 执行指令:
> export CUDA_VISIBLE_DEVICES=0,1,2,3
> python -m paddle.distributed.launch train.py
> --model=SE_ResNet50_vd
> --pretrained_model=pretrain_model/SE_ResNet50_vd_pretrained/
> --batch_size=100
> --data_dir=data
> --num_epochs=60
> --total_images=839981
> --class_dim=6
> --model_save_dir=terror/output_terror_detail/
> --lr_strategy=cosine_decay_warmup
> --use_label_smoothing=True
> --reader_thread=4
> --use_dali=True
> --lr=0.01
> 报错:
> File "train.py", line 180, in train
> train_fetch_vars[0], exe)
> File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/utility.py", line 428, in best_strategy_compiled
> dist_utils.prepare_for_multi_process(exe, build_strategy, program)
> File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/dist_utils.py", line 91, in prepare_for_multi_process
> nccl2_prepare_paddle(trainer_id, startup_prog, train_prog)
> File "/home/daibing/cncert-source/daibing/terror_general_dali_SE_ResNet50_vd/utils/dist_utils.py", line 76, in nccl2_prepare_paddle
> program=main_prog)
> File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 571, in transpile
> wait_port=self.config.wait_port)
> File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 355, in _transpile_nccl2
> self.config.hierarchical_allreduce_inter_nranks
> File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2483, in append_op
> attrs=kwargs.get("attrs", None))
> File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1763, in **init**
> proto = OpProtoHolder.instance().get_op_proto(type)
> File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1645, in get_op_proto
> raise ValueError("Operator "%s" has not been registered." % type)
> ValueError: Operator "gen_nccl_id" has not been registered.

请确认下CMAKE选项是否设置-DWITH_DISTRIBUTE=TRUE了？

**Comment by shippingwang** [comment]
嗯 编译需要加-DWITH_DISTRIBUTE=TRUE
