### ISSUE TITLE
resnet34 yolov3 paddleslim pruning问题

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/models#4029]
@wanghaoshuang 
您好，mobilenetv1 yolov3按照示例是可以pruning成功的，infer也正常。我想在resnet34 yolov3上编写配置文件进行pruning，报错了，仔细核对了代码，没找出问题出在哪里，可以帮忙看一下吗，多谢！
配置文件如下：
![image](https://user-images.githubusercontent.com/7035538/70142120-7c725680-16d3-11ea-9844-bfe6db75dfa5.png)
进行Pruning报错如下：
![image](https://user-images.githubusercontent.com/7035538/70142168-9875f800-16d3-11ea-8f30-865291cb2bd0.png)

**Comment by A1exy** [comment]
ps：编写配置文件进行darknet yolov3 pruning时也报的该错误。

**Comment by wanghaoshuang** [comment]
你好，配置文件中`target_ratio`是指模型整体的flops被剪裁掉的比例，PaddleSlim会根据这个比例二分搜出一组剪切率。
您log中显示，目前搜出来的一组剪切率是100%，也就是所指定的参数全部剪掉，所以报错了。

原因是设置的`target_ratio`太大了，即使所指定的参数全裁掉也满足不了要求，所以您可以适当调小`target_ratio`。

**Comment by A1exy** [comment]
多谢   问题解决关闭。
