### ISSUE TITLE
landmark模型测试出现问题，如下

### ISSUE THREAD

**Issue by Julyliying** [PaddlePaddle/models#4043]
在测试landmark recognition模型时，pypredict编译通过，但是运行inference时，                        
  python infer_recognition.py test_cls test_data/0.jpg res152_softmax_v2,
出现如下问题，请问是什么原因？？怎样解决？？
ImportError: ./so/PyCNNPredict.so: undefined symbol: _ZN6paddle14AnalysisConfig18EnableAnakinEngineEiSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIiSaIiEESt4lessIS7_ESaISt4pairIKS7_SA_EEEiNS0_9PrecisionEbS8_IS7_SaIS7_EESK_

**Comment by dyning** [comment]
想问下您用的Paddle版本是哪个？机器运行环境是Cudnn >= 7, CUDA 9, PaddlePaddle version >= 1.3, python version 2.7

**Comment by Julyliying** [comment]
您好！ Paddle版本是1.6.1， Cudnn 7.6， cuda10， python2.7   必须使用cuda9吗？？？

**Comment by Superjomn** [comment]
> ImportError: ./so/PyCNNPredict.so: undefined symbol:

这是用的paddle 官方的预测库吗？

**Comment by dyning** [comment]
这个应该不是官方的，当时临时编译的

> > ImportError: ./so/PyCNNPredict.so: undefined symbol:
> 
> 这是用的paddle 官方的预测库吗？

**Comment by dyning** [comment]
> 您好！ Paddle版本是1.6.1， Cudnn 7.6， cuda10， python2.7 必须使用cuda9吗？？？

之前使用的是临时编译的so版本，我们最近升级一下，更新到官方版，尽请期待。

**Comment by Julyliying** [comment]
> 这个应该不是官方的，当时临时编译的
> 
> > > ImportError: ./so/PyCNNPredict.so: undefined symbol:
> > 
> > 
> > 这是用的paddle 官方的预测库吗？



> > 您好！ Paddle版本是1.6.1， Cudnn 7.6， cuda10， python2.7 必须使用cuda9吗？？？
> 
> 之前使用的是临时编译的so版本，我们最近升级一下，更新到官方版，尽请期待。

**Comment by Julyliying** [comment]
> > 您好！ Paddle版本是1.6.1， Cudnn 7.6， cuda10， python2.7 必须使用cuda9吗？？？
> 
> 之前使用的是临时编译的so版本，我们最近升级一下，更新到官方版，尽请期待。
请问什么时候可以更新一下呢？？？ @dyning

**Comment by dyning** [comment]
@Julyliying ,不好意思让你等这么久。提供的代码目前只支持cuda9， python2.7。更新到官方版预测，需要大量验证工作，为了避免不一致，没有更新。

如果需要支持cuda10，python2.7，需要修改pypredict/build.sh中的fluid预测库的包的地址，即
wget https://paddle-inference-lib.bj.bcebos.com/1.4.1-gpu-cuda9-cudnn7-avx-mkl/fluid_inference.tgz

飞桨提供一些预测库最新的编译好的候选列表，见页面https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/build_and_install_lib_cn.html
可以使用ubuntu14.04_cuda10.0_cudnn7_avx_mkl预测包的地址
https://paddle-inference-lib.bj.bcebos.com/1.6.3-gpu-cuda10-cudnn7-avx-mkl/fluid_inference.tgz
满足cuda10环境，更新上面wget的地址，然后尝试重新build.sh，如有问题，请及时反馈。

inference使用的paddle最好与上面版本对应，即1.6.3

再次抱歉这么迟回复。
