### ISSUE TITLE
How about the time cost of per image inferring for pyramidbox?

### ISSUE THREAD

**Issue by lyw615** [PaddlePaddle/models#4059]
Could you provide your time **cost details** when inferring? Just like average per image inferring **time** , average image size ,and Gpu type. If it's convenient for you, i will be appreciate a lot.

**Comment by lyw615** [comment]
Because my input images arrange from 2400~2500 cost 1.3s per image, in 1080ti. So i want to check the problem

**Comment by liym27** [comment]
Relevant developers are following this issue

**Comment by qingqing01** [comment]
@lyw615   Sorry, we don't have Pyramidbox performance on GPU now.  This model is actually time-consuming.  If use Python to infer, better use the Python API of c++ inference.

**Comment by lyw615** [comment]
How to achieve this?

**Comment by lyw615** [comment]
In this paper's Runtime Speed part , the speed seems  just ok compared with other model.[https://zhuanlan.zhihu.com/p/35856534](url)

**Comment by qingqing01** [comment]
@lyw615  PyramidBox is also based on SSD. If your project does not require high real-time performance and require high accuracy, you can choose this model.  This model is very good on small face.  Otherwise, you can choose faceboxes or BlazeFace

**Comment by lyw615** [comment]
How much does these operations matters  the infer results?
`
det0 = detect_face(image, shrink)
    print("type of det {}".format(type(det0)))
    if args.use_gpu:
        det1 = flip_test(image, shrink)
        [det2, det3] = multi_scale_test(image, max_shrink)
        det4 = multi_scale_test_pyramid(image, max_shrink)
        det = np.row_stack((det0, det1, det2, det3, det4))
        dets = bbox_vote(det)
    else:
        # when infer on cpu, use a simple case
        dets = det0
`
If just set dets=det0 here when infer with gpu,the  process time will be less and keep same precision?

**Comment by lyw615** [comment]
Does the prediction time include pre-processing of the image and post-processing time of the prediction result?

**Comment by qingqing01** [comment]
@lyw615  There is no need to use multi-scale in the depolyment. Only one scale testing is ok.
