### ISSUE TITLE
image classification分类的batch计算问题

### ISSUE THREAD

**Issue by chenqiuhui** [PaddlePaddle/models#4068]
跑训练时，单卡时，train和test跑的batch数==图片数/batch_size；不是单卡时，test的batch数正常，而train的batch数==num_gpu*训练图片数/train_batch_size；请问为什么？

**Comment by FrostML** [comment]
多卡训练时，会把 ( batch_size/卡数 ) 来进行训练

**Comment by shippingwang** [comment]
现在（19/12/20）代码中，分类中batch_size参数是指所有卡的 
close this issue now
