### ISSUE TITLE
PaddleCV/face_detection/widerface_eval.py

### ISSUE THREAD

**Issue by EthanZBY** [PaddlePaddle/models#4082]
models/PaddleCV/face_detection/widerface_eval.py 
Line 307
    max_shrink = get_round(min(max_shrink_v1, max_shrink_v2), 2) - 0.3

This will generate a negative value when the image size is bigger and make the execution crashed.

**Comment by MrChengmo** [comment]
I have told the relevant developers to follow up on this issue：@still-wait

**Comment by EthanZBY** [comment]
Thanks and waiting for your good news.

**Comment by EthanZBY** [comment]
Tested, two bugs mentioned in paddlehub have been fixed.
