### ISSUE TITLE
关于cudnn版本问题

### ISSUE THREAD

**Issue by zhanghongruiupup** [PaddlePaddle/models#4085]
你好，我是在用cudnn7.5.0训练stnet，看到您之前回复的issue说是用cudnn5。
我需要下降cudnn版本到5进行训练吗？谢谢

**Comment by MrChengmo** [comment]
请问您之前提的issue链接可否提供一下？

**Comment by zhanghongruiupup** [comment]
> 请问您之前提的issue链接可否提供一下？

https://github.com/PaddlePaddle/models/issues/1758#issue-411321578
谢谢

**Comment by SunGaofeng** [comment]
请问您用的paddle版本是多少？
在1.5及之后的paddle版本上，不需要换成cudnn5的，可以用cudnn7训练。

**Comment by zhanghongruiupup** [comment]
> 请问您用的paddle版本是多少？
> 在1.5及之后的paddle版本上，不需要换成cudnn5的，可以用cudnn7训练。

牛逼plus！谢谢
我发现stnet的loss只用了softmax 的交叉熵损失cross_entropy就能得到这么好的效果，尝试用
fg_num = fluid.data(name='fg_num',shape=[1],dtype='int32')
fluid.layers.sigmoid_focal_loss(self.network_outputs[0],self.label_input,fg_num,gamma=2,alpha=0.25)
然后会报错：info: holder_ should not be null  Tensor holds no memory.
请问您有什么建议吗？期待你的回信

**Comment by zhanghongruiupup** [comment]
那个paddle用的最新版本，cudnn7.5.0，所以没纠结版本问题了

**Comment by MrChengmo** [comment]
> > 请问您用的paddle版本是多少？
> > 在1.5及之后的paddle版本上，不需要换成cudnn5的，可以用cudnn7训练。
> 
> 牛逼plus！谢谢
> 我发现stnet的loss只用了softmax 的交叉熵损失cross_entropy就能得到这么好的效果，尝试用
> fg_num = fluid.data(name='fg_num',shape=[1],dtype='int32')
> fluid.layers.sigmoid_focal_loss(self.network_outputs[0],self.label_input,fg_num,gamma=2,alpha=0.25)
> 然后会报错：info: holder_ should not be null Tensor holds no memory.
> 请问您有什么建议吗？期待你的回信

fluid.layers.sigmoid_focal_loss 的错误可以在 https://github.com/PaddlePaddle/Paddle/issues 下提一个相应的issue，会有负责该api的同学跟进
