### ISSUE TITLE
Does anyone else feel unconvenient scanning so many repositories?

### ISSUE THREAD

**Issue by Ailing-Zou** [PaddlePaddle/models#4086]

**Comment by Ailing-Zou** [comment]
Advise: It is really so hard to find issues related to my questions 建议：这么多模型混到一起，找相关issue实在是非常困难
搜索功能实在不好用，而且问题也不一定是针对相关model，真诚建议把这些东西采取个什么方式稍微分开？ 不然issue只有越来越冗长的结果

**Comment by MrChengmo** [comment]
感谢您的建议，我们会讨论相关优化改进的措施。
