### ISSUE TITLE
sequence_tagging_for_ner训练过程F1为什么一直是0？

### ISSUE THREAD

**Issue by utopiar** [PaddlePaddle/models#411]
```
[INFO 2017-11-01 18:49:00,898 train.py:83] Pass 0, Batch 0, Cost 15.435392, {'ner_chunk.precision': 0.02575107291340828, 'ner_chunk.F1-score': 0.03539822995662689, 'ner_chunk.recall': 0.056603774428367615, 'error': 0.8953229188919067}
[INFO 2017-11-01 18:49:05,185 train.py:87]
Test with Pass 0, Batch 0, {'ner_chunk.precision': 0.019510731101036072, 'ner_chunk.F1-score': 0.029499361291527748, 'ner_chunk.recall': 0.06044403091073036, 'error': 0.9291946291923523}
[INFO 2017-11-01 18:49:05,246 train.py:83] Pass 0, Batch 1, Cost 11.822507, {'ner_chunk.precision': 0.0, 'ner_chunk.F1-score': 0.0, 'ner_chunk.recall': 0.0, 'error': 0.24517905712127686}
[INFO 2017-11-01 18:49:09,545 train.py:87]
Test with Pass 0, Batch 1, {'ner_chunk.precision': 0.0, 'ner_chunk.F1-score': 0.0, 'ner_chunk.recall': 0.0, 'error': 0.16679592430591583}
[INFO 2017-11-01 18:49:09,601 train.py:83] Pass 0, Batch 2, Cost 10.640020, {'ner_chunk.precision': 0.0, 'ner_chunk.F1-score': 0.0, 'ner_chunk.recall': 0.0, 'error': 0.29411765933036804}
[INFO 2017-11-01 18:49:13,849 train.py:87]
Test with Pass 0, Batch 2, {'ner_chunk.precision': 0.0, 'ner_chunk.F1-score': 0.0, 'ner_chunk.recall': 0.0, 'error': 0.16679592430591583}
```
除了第一个Batch的F1不是0，以后一直是0，请教这是什么问题呢？

**Comment by guoshengCS** [comment]
是否可以等多训练一些pass再看下，sequence_tagging_for_ner这个例子里使用的evaluator是Chunk Evaluator，`ner_chunk.precision`、`ner_chunk.recall`和`ner_chunk.F1-score`这几个指标都是以chunk为单位评估计算的，可以参考下[Chunk Evaluator文档](https://github.com/PaddlePaddle/Paddle/blob/f80fea8d0a55cf21d95defea41c43fcf2c3264a8/python/paddle/trainer_config_helpers/evaluators.py#L420) ，感觉初期是会比较低，其表现也不会和Cost完全一致

**Comment by utopiar** [comment]
嗯，谢谢回答，晚上多跑几个pass看看，目前看预测出来的全都是“O”，不知道您有没有训练这个模型的经验，一般训练多少pass会收敛，能够正确识别chunk呢？

**Comment by JenningsL** [comment]
@utopiar 我也遇到了类似的问题，你现在用了多少数据量，batch_size 和 passnum 分别是？现在问题解决了吗？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
