### ISSUE TITLE
BMN/BSN模型评估时报错

### ISSUE THREAD

**Issue by li-900406** [PaddlePaddle/models#4110]
错误如下：
Process Process-13:
Traceback (most recent call last):
  File "D:\Anaconda\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs
  File "G:\models-develop\PaddleCV\PaddleVideo\models\bsn\bsn_utils.py", line 124, in video_process
    result_dict[video_name[2:]] = proposal_list
NameError: name 'result_dict' is not defined
[INFO: metrics_util.py:  420]: [EVAL] eval finished.    Loss = nan
W1223 18:39:51.984580 17320 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
W1223 18:39:51.997812 17320 device_context.cc:244] device: 0, cuDNN Version: 7.6.

请问该怎么解决，谢谢！
![捕获](https://user-images.githubusercontent.com/59164417/71354279-665f0400-25b6-11ea-95b9-abab41c2abce.PNG)

**Comment by wilhelmzh** [comment]
辛苦 @huangjun12 帮忙看下

**Comment by huangjun12** [comment]
result_dict是在bsn_utils.py文件的bsn_post_processing函数中定义的global变量，报错信息提示未找到该变量。为方便定位问题，建议贴一下配置环境、执行的命令及所有的报错信息~  
另外BSN模型分TEM、PGM和PEM三个模块，各模块执行顺序有要求，详情参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleVideo/models/bsn/README.md

**Comment by li-900406** [comment]
环境为 windows10 cuda 9.0 cudnn7.6 paddlepaddle是在官网下载的对应版本
执行命令为 bash run.sh predict BMN ./configs/bmn.yaml
结果如下
![捕获1](https://user-images.githubusercontent.com/59164417/71406882-6cb3b580-2674-11ea-932d-2dbb20c39e19.PNG)
![捕获2](https://user-images.githubusercontent.com/59164417/71406884-6de4e280-2674-11ea-9d4d-04557f2fadc5.PNG)

**Comment by huangjun12** [comment]
感谢反馈！这是由于python多进程模块multiprocessing在unix与windows下的底层处理机制不同导所致，详细原因可参考:https://stackoverflow.com/questions/6596617/python-multiprocess-diff-between-windows-and-linux。
解决方案：将主程的global变量显式地传入各子进程，修改方法参考https://github.com/PaddlePaddle/models/pull/4134/files，代码将于近期合入develop。
