### ISSUE TITLE
sequence_tagging_for_ner 测试集上的 F1-score 一直没有变化

### ISSUE THREAD

**Issue by JenningsL** [PaddlePaddle/models#412]
我在 sequence_tagging_for_ner 示例代码的基础上增加了几列特征，但是没有改变模型结构。在训练时，训练集上的 Cost, error, 以及其他指标都有变化，但是测试集上的F1-score 等指标从第一个batch开始就是一个非零值，并且没有任何变化。
`
[INFO 2017-11-01 19:25:05,183 train.py:103] Pass 9, Batch 0, Cost 11.496690, {'ner_chunk.precision': 0.7249544858932495, 'ner_chunk.F1-score': 0.8158245086669922, 'ner_chunk.recall': 0.9327396154403687, 'error': 0.22525805234909058}
[INFO 2017-11-01 19:25:08,022 train.py:107]
Test with Pass 9, Batch 0, {'ner_chunk.precision': 0.7743763327598572, 'ner_chunk.F1-score': 0.8488954901695251, 'ner_chunk.recall': 0.9392839074134827, 'error': 0.177949458360672}
[INFO 2017-11-01 19:25:36,543 train.py:103] Pass 9, Batch 10, Cost 10.829126, {'ner_chunk.precision': 0.7487720847129822, 'ner_chunk.F1-score': 0.8320754766464233, 'ner_chunk.recall': 0.936234712600708, 'error': 0.20192831754684448}
[INFO 2017-11-01 19:25:39,371 train.py:107]
Test with Pass 9, Batch 10, {'ner_chunk.precision': 0.7743763327598572, 'ner_chunk.F1-score': 0.8488954901695251, 'ner_chunk.recall': 0.9392839074134827, 'error': 0.177949458360672}
[INFO 2017-11-01 19:26:08,431 train.py:103] Pass 9, Batch 20, Cost 9.446608, {'ner_chunk.precision': 0.7925390601158142, 'ner_chunk.F1-score': 0.8627714514732361, 'ner_chunk.recall': 0.9466617703437805, 'error': 0.16465938091278076}
[INFO 2017-11-01 19:26:11,258 train.py:107]
Test with Pass 9, Batch 20, {'ner_chunk.precision': 0.7743763327598572, 'ner_chunk.F1-score': 0.8488954901695251, 'ner_chunk.recall': 0.9392839074134827, 'error': 0.177949458360672}
[INFO 2017-11-01 19:26:33,026 train.py:117]
Test with Pass 9, {'ner_chunk.precision': 0.7743763327598572, 'ner_chunk.F1-score': 0.8488954901695251, 'ner_chunk.recall': 0.9392839074134827, 'error': 0.177949458360672}
`
在调用 infer.py 进行预测时，发现所有标签都预测为 O。

**Comment by guoshengCS** [comment]
`ner_chunk.precision`、`ner_chunk.recall`和`ner_chunk.F1-score`这几个指标是Chunk Evaluator的输出，都是以chunk为单位评估计算的，可以参考下[Chunk Evaluator文档](https://github.com/PaddlePaddle/Paddle/blob/f80fea8d0a55cf21d95defea41c43fcf2c3264a8/python/paddle/trainer_config_helpers/evaluators.py#L420) ，其表现不会和cost(这里是CRF cost)和error（这里是以word分类的错误率）完全一致，感觉相比于以word为单位以chunk为单位评估计算确实会变化的慢一些（chunk命中一定有word命中，而word命中chunk不一定命中）

**Comment by JenningsL** [comment]
@guoshengCS 我理解，但是以chunk为单位评估的指标在几百个batch里面是完全没有变化过，这个应该不符合预期。而且，最终保存下来的参数，也并没有学习到任何东西，无论输入是什么，输出都是同一个标签 O。

**Comment by guoshengCS** [comment]
如果方便的话还请用训练或者测试数据测试看下是否所有都输出标签O，看着在训练和测试数据上准确召回还是比较高的

**Comment by JenningsL** [comment]
我目前使用1w+条训练数据，batch_size=1024, 大约100个pass之后evaluator 的指标开始有变化。但是让我困惑的是，即使在训练集上，预测的结果也非常差（大多数都是O，少数不为O的标签基本没有预测正确的），感觉还是欠拟合？差不多的模型和同样的数据，在之前使用的一个tensorflow的实现上，几个epoch就有不错的表现，想知道造成这种差距的原因可能是什么？

**Comment by guoshengCS** [comment]
不过看上面给出的打印的指标的话确实是还可以的，不排除有一些配置或者使用方面的原因，chunk evaluator在使用上确实也有一些注意事项，这些可以先贴出来看下或者说下，如果确实是另有其他原因有diff可能需要深入排查下

**Comment by guoshengCS** [comment]
这里附上Chunk Evalutor的中文说明，方便查找参考


chunk evaluator用于评估计算segment labelling问题中chunk detection的准确率、召回率和F1值。

为正确使用chunk_eval_op，需要明确如下一些用到的概念：

Chunk对应句子中的word片段，通常带有某种类型即Chunk Type，如命名实体识别任务中的人名PER、组织机构名称ORG等。
Tag用于标识word在chunk中的位置，不同位置对应有不同的Tag Type，如IOBES标注方法中使用B表示chunk的开始、I表示chunk中间的word、E表示chunk的结束、S表示单个word的chunk。

结合Chunk Type和Tag Type可以定义chunk detection所用的label，如B-ORG标签表示ORG类型语块的第一个word。 另外，label的构建还需遵照如下的一些规则：

1、使用如下一种标注方式：
 
Scheme   Description
plain     chunk中的word使用同一个label
IOB	     任意Chunk Type X都对应两种label，B-X标识开始，I-X标识中间
IOE	     任意Chunk Type X都对应两种label，E-X标识结束，I-X标识中间
IOBES   任意Chunk Type X都对应两种label，B-X标识开始，E-X标识结束，I-X标识中间，S-X标识单个word的chunk

这里以命名实体识别NER为例进行进一步说明。假定有组织机构名ORG、人民PER和地名LOC三种Chunk Type，若使用IOB标注方式，则label将包括B-ORG、I-ORG、B-PER、I-PER、B-LOC、I-LOC和O（O用来表示Chunk Type以外的word）。加在Chunk Type之前的前缀B和I即是Tag Type，B-ORG表示ORG类型chunk的开始word，I-ORG表示ORG类型chunk中间的word。

2、在使用label dictionary将label映射为id时，需保证如下所列等式满足，以使得程序能够正确解码出每个word的chunk type和tag type：

tag_type = label % num_tag_type
chunk_type = label / num_tag_type

其中num_tag_type为标注方式中Tag Type的数目，num_chunk_type为Chunk Type的数目，而tag_type在各标注方式中如下所示：


   Scheme Begin Inside End   Single

    plain   0     -      -     -

    IOB    0     1      -     -

    IOE    -     0      1     -

    IOBES  0     1      2     3


仍以上面的NER为例进行说明，为使得以上等式满足label dictionary可以如下所示：
   

   B-ORG  0

    I-ORG  1

    B-PER  2

    I-PER  3

    B-LOC  4

    I-LOC   5

    O      6

以I-LOC为例，I-LOC的label id为5、tag_type（I）为1、chunk_type（LOC）为2，由于num_chunk_type为3、num_tag_type为2，容易验证上面的等式满足。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
