### ISSUE TITLE
图像分类代码问题 killed

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/models#4139]
问题：分类代码运行一段时间，显示killed 程序退出
原因：可能是内存占满
分析方法：在程序运行过程中，实时的监测下内存占用情况，如果程序占用内存一直在涨的话，可能问题出现在reader过程中，不断的缓存数据
解决办法：调整xmapreader的num_thread 和buffer_size，具体调整方法参考：(WIP)

**Comment by hongyuzlx** [comment]
解决办法：调整xmapreader的num_thread 和buffer_size，具体调整方法参考：(WIP)，这里的WIP是什么呢？怎么调整 @shippingwang
