### ISSUE TITLE
为何ocr attention 模型训练出来后，经常将长文本识别错？

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/models#4144]
训练时候验证集上识别率达到８０％多，但实际使用时效果较差，特别是对于长文本识别较差，这是否是训练时过拟合了？

**Comment by XingWu01** [comment]
@wanghaoshuang

**Comment by wanghaoshuang** [comment]
请问您的训练数据中长文本多么？需要根据您的实际使用场景增加训练数据中的长文本样本。

**Comment by wenston2006** [comment]
@wanghaoshuang 好的，我再试试

**Comment by cnzhujg** [comment]
如果过拟合，那就太爽了。
