### ISSUE TITLE
使用 QuantizationFreezePass 量化模型报错

### ISSUE THREAD

**Issue by morgan-bc** [PaddlePaddle/models#4151]
我按照 PaddleDetection 中 `slim\quantization\freeze.py`  量化训练好的 MobileNetV1_SSD 模型，在使用 QuantizationFreezePass  时报错，主要代码如下
```Python
    use_gpu = cfg.model.use_gpu

    place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    test_prog, feed_var_names, fetch_vars = fluid.io.load_inference_model(model_path, exe)
    test_graph = IrGraph(fluid.core.Graph(test_prog.desc), for_test=True)
    
    # ret = eval_run(cfg, exe, test_prog, feed_var_names, fetch_vars)

    freeze_pass = QuantizationFreezePass(fluid.global_scope(), place)
    freeze_pass.apply(test_graph)
    float_prog = test_graph.to_program()

    basename = os.path.basename(model_path)
    tmp_path = os.path.join(output_path, basename+'_float')
    checkpoint.save_inference_model(tmp_path, exe, float_prog, feed_var_names, fetch_vars)
```
错误信息如下
```
Traceback (most recent call last):
  File ".\freeze_model.py", line 91, in quantize
    freeze_pass.apply(test_graph)
  File "C:\Users\morgan\Miniconda3\lib\site-packages\paddle\fluid\contrib\slim\quantization\quantization_pass.py", line 683, in apply
    self._insert_post_dequant_op(graph, op_node)
  File "C:\Users\morgan\Miniconda3\lib\site-packages\paddle\fluid\contrib\slim\quantization\quantization_pass.py", line 789, in _insert_post_dequant_op
    scale_v = self._var_scale_map[original_var_name]
KeyError: 'conv7_1_sep_weights'
```
使用环境为：win10, Python 3.6.8,  paddle 1.6.2.
加载的模型能够正确预测，QuantizationFreezePass 每次报错 KeyError 都不一样，我是新手，请问训练后量化怎么做才是正确的呢？

**Comment by LDOUBLEV** [comment]
收到问题

**Comment by slf12** [comment]
> 量化训练好的 MobileNetV1_SSD 模型
> 我是新手，请问训练后量化怎么做才是正确的呢？

1、请问使用的量化方式是量化训练还是训练后量化（离线量化）？
2、如果是离线量化，不需要freeze
3、如果是量化训练，可先看参数中这个conv7_1_sep_weights 是否存在，如果存在，是否方便发出你的模型结构文件，我帮你看下

**Comment by morgan-bc** [comment]
我想用的是离线量化， conv7_1_sep_weights 这个是存在的，我是按照 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/47741382cf15eda852fefdada6ce83ef86350af6/slim/quantization/freeze.py#L167) 中的例子写的，完整的 Inference 模型和权重传到百度网盘里了，链接: https://pan.baidu.com/s/1BZ7HtvLDxXdKxZTR5wHuNA 提取码: ik1c

**Comment by slf12** [comment]
这里有分类的离线量化示例： https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post， slim\quantization下的教程是使用量化训练的，离线量化不需要再进行freeze_model

**Comment by morgan-bc** [comment]
from paddle.fluid.contrib.slim.quantization import PostTrainingQuantization
我也看见这个例子了，但是 PostTrainingQuantization 这个类不存在啊，上面这个 import 也不成功   请问你用的是哪个版本的 paddle

**Comment by slf12** [comment]
可试下1.6.2或者https://www.paddlepaddle.org.cn/install/doc/tables 这里下载latest版本的饿paddle

**Comment by morgan-bc** [comment]
我用的就是 1.6.2,  windows 和 linux 都没有 PostTrainingQuantization

**Comment by slf12** [comment]
https://www.paddlepaddle.org.cn/install/doc/tables 那你用latest版本吧
