### ISSUE TITLE
目前paddle可以支持以下操作吗

### ISSUE THREAD

**Issue by kebinC** [PaddlePaddle/models#4166]
目前paddle可以支持以下操作吗？
1. 初始化两个相同的网络， 一个（N1）训练，另一个（N2）stop gradient， 更新一次网络参数后，  对N1的网络参数加权累加到N2
2. 初始化一个 buffer， 训练时不更新， 更新一次网络参数后， 再手动修改buffer局部的值

**Comment by gongweibao** [comment]
Hi上已经回复。
