### ISSUE TITLE
机器翻译模型自定义Beam_search情景下，如何避免重复计算

### ISSUE THREAD

**Issue by dpwu1994** [PaddlePaddle/models#417]
生成模式下走训练流程，从源，开始生成第一个词w1， w1 | 源 作为新的输入，生成 w2，w1, w2 | 源，作为新的输入生成 w3 ，以此类推。已生成的前缀在预测的前向网络中重复计算，但是时间上较慢。如何解决？

**Comment by lcy-seso** [comment]
如果是说定制化解码来避免这个重复的计算吗？一定需要修改 RecurrentLayerGroup 里面的[beamSearch](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/RecurrentGradientMachine.cpp#L1439) 函数。

BeamSearch 函数中现在还留下很多回调函数接口，但是使用方法估计不是简单可以解释清楚，需要重写预测接口，在预测接口中来调用这些回调函数。估计只有通过开发这样一个例子，才能让更多人明白这个过程。

Beam Search 现在是嵌入在 RecurrentLayerGroup 前向计算之内，涉及RecurrentLayerGroup相关的一些重组Batch操作（可能会需要相关Layer的计算逻辑能够相互配置），改起来需要对代码有一些了解。

**Comment by dpwu1994** [comment]
你们那边会开发相关的例子吗？

**Comment by lcy-seso** [comment]
暂时没有具体的时间表。。

**Comment by dpwu1994** [comment]
有没有什么wiki什么的详细点资料，我的理解是现在如果要避免重复计算，要变成走预测，但是需要改原来的beam_search实现的C++代码？还有假设已经修改完函数之后，接下来还需要做什么？

**Comment by lcy-seso** [comment]
这部分确实没有wiki和现成的资料。
需要用C++代码专门来重写生成过程，这部分和普通预测的原理一样，加载模型，进行前向计算。
在前向计算部分，需要修改BeamSearch代码来干预对unfinished prefix的排序结果，实现定制化的展开/剪枝。

**Comment by dpwu1994** [comment]
能具体定位一下需要修改代码的范围以及需要理解代码的范围吗

**Comment by dpwu1994** [comment]
在避免重复计算的情况下的话一个query几乎也要3s，这个时间正常吗，有没有什么加速的办法？

**Comment by dpwu1994** [comment]
1个query3s是cpu单线程的速度。

**Comment by lcy-seso** [comment]
最大的计算量可能在最后一层softmax的计算，不知道网络规模和beam size目前是多少。抛开细节，粗暴地讲，不采用加速策略，beam size 较大，3s 在我自己的测试中是一个不算异常的时间。

想要加速的需要在生成过程中避免对归一化分母的计算。

**Comment by dpwu1994** [comment]
paddlepaddle的fluid 版本是否支持beam search的自定义来避免重复计算

**Comment by gongweibao** [comment]
现在还没有。。。。

**Comment by dpwu1994** [comment]
看到paddlepaddle的fluid 版本实现了google的tansformer。换成这个框架下的翻译模型能解决这个问题吗~

**Comment by Superjomn** [comment]
@kuke 这个帮回答下吧

**Comment by guoshengCS** [comment]
如果是说希望缓存已经计算过的状态的话，使用PaddlePaddle中内置的Beam Search是可以避免预测时已生成的前缀在前向网络中重复计算的。在预测时，当前时间步可以只将上一步的预测结果送入计算单元内进行计算，更早之前的内容在计算单元内的状态会进行cache无需重复计算，可以参考[Transformer](https://github.com/PaddlePaddle/models/blob/develop/fluid/neural_machine_translation/transformer/model.py#L638)和[RNN-Search](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_machine_translation.py#L146)模型中beam search decoder部分的代码。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
