### ISSUE TITLE
多显卡服务器中，用单显卡训练图片分类时，出现Pass中batch数不对的问题

### ISSUE THREAD

**Issue by youwei2567** [PaddlePaddle/models#4178]
相关参数设置如下：
`add_arg('total_images',             int,    777,                "The number of total training images.")
add_arg('batch_size',               int,    32,                      "Minibatch size on a device.")
`
具体显示如下：
`[Pass 1, train batch 186]       loss 2.17508, acc1 0.50000, acc5 0.75000, lr 0.00188, elapse 0.0189 sec
[Pass 1, train batch 187]       loss 2.31072, acc1 0.25000, acc5 0.50000, lr 0.00188, elapse 0.0188 sec
[Pass 1, train batch 188]       loss 2.21176, acc1 0.25000, acc5 0.75000, lr 0.00188, elapse 0.0185 sec
[Pass 1, train batch 189]       loss 2.14681, acc1 0.75000, acc5 0.75000, lr 0.00188, elapse 0.0201 sec
[Pass 1, train batch 190]       loss 1.80597, acc1 0.75000, acc5 1.00000, lr 0.00188, elapse 0.0181 sec
[Pass 1, train batch 191]       loss 1.95061, acc1 0.50000, acc5 0.75000, lr 0.00188, elapse 0.0194 sec
[Pass 1, train batch 192]       loss 2.30522, acc1 0.25000, acc5 0.50000, lr 0.00188, elapse 0.0193 sec
[Pass 1, train batch 193]       loss 2.49756, acc1 0.25000, acc5 0.50000, lr 0.00188, elapse 0.0199 sec
`
Pass中的batch数应为24，却有193个batch

**Comment by youwei2567** [comment]
定位出问题在reader.py中271行
`batch_size = settings.batch_size / paddle.fluid.core.get_cuda_device_count()`
断点后发现送入reader的batch_size =4.0
验证阶段也出现相同问题

**Comment by youwei2567** [comment]
连带问题：warm_up_epoch设置为10，却在第二个Pass时，lr warm-up结束
将相关代码注释，并修改为batch_size = settings.batch_size后，该问题也解决了
但治标不治本，还是希望百度尽早解决吧 -^-

**Comment by shippingwang** [comment]
我看你有写 add_arg('batch_size', int, 32, "Minibatch size on a device.") 这个不是最新代码吧，[arguments](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/utility.py#L113)指定的是所有的devices bs大小
麻烦更新代码到最新～
