### ISSUE TITLE
请问deepFM中为什么epoch的时间这么短？

### ISSUE THREAD

**Issue by witness99** [PaddlePaddle/models#4186]
请问在按照deepFM中所说的步骤走的情况下，为什么最后在local_train阶段epoch的时间会这么短？

以下为得到的结果：
args.embedding_size: 10
args.num_field: 39
args.num_feat: 1086460
args.layer_sizes: [400, 400, 400]
args.act: relu
args.reg: 0.0001
---------------------------------------------
epoch1 is finished and takes 0.069958 s
epoch2 is finished and takes 0.030759 s
epoch3 is finished and takes 0.031983 s
epoch4 is finished and takes 0.039973 s
epoch5 is finished and takes 0.032980 s
epoch6 is finished and takes 0.033335 s
epoch7 is finished and takes 0.029980 s
epoch8 is finished and takes 0.029713 s
epoch9 is finished and takes 0.029981 s
epoch10 is finished and takes 0.038977 s
epoch11 is finished and takes 0.044971 s
epoch12 is finished and takes 0.028981 s
epoch13 is finished and takes 0.040977 s
epoch14 is finished and takes 0.037975 s
epoch15 is finished and takes 0.032979 s
epoch16 is finished and takes 0.032980 s
epoch17 is finished and takes 0.030980 s
epoch18 is finished and takes 0.031979 s
epoch19 is finished and takes 0.033981 s
epoch20 is finished and takes 0.032983 s
epoch21 is finished and takes 0.033988 s
epoch22 is finished and takes 0.031253 s
epoch23 is finished and takes 0.033978 s
epoch24 is finished and takes 0.031979 s
epoch25 is finished and takes 0.032640 s
epoch26 is finished and takes 0.032981 s
epoch27 is finished and takes 0.032980 s
epoch28 is finished and takes 0.036979 s
epoch29 is finished and takes 0.031981 s
epoch30 is finished and takes 0.030977 s

Process finished with exit code 0

**Comment by frankwhzhang** [comment]
确认一下数据有没有读进来

**Comment by mmglove** [comment]
麻烦贴一下运行环境和paddle版本信息，另deepFM由于使用Dataset API 加载数据，暂不适用于Windows（在Windows环境下运行不会报错，但未读取数据进行训练，故训练时间较快）
