### ISSUE TITLE
PaddleNLP/PaddleDialogue/dialogue_general_understanding 的 DSTC2 数据building有问题

### ISSUE THREAD

**Issue by huey0528** [PaddlePaddle/models#4189]
测试dstc2数据的时候发现，bash run.sh dstc2 predict 的时候会报错 - data format error。

原因在于你们在build DSTC2 的数据的时候build_dstc2_dataset.py 文件的line 109 和 110
fw.write(u"%s\n" % out.encode('utf8'))
fw_asr.write(u"%s\n" % out_asr.encode('utf8'))
把数据的length合并成1了。读出来的时候也只有一个。。

解决办法可以把 .encode('utf8') 提前。
out = "%s\t%s\1%s\t%s" % (session_id.encode('utf8'), mach.encode('utf8'), user.encode('utf8'), labels_ids)
user_asr = log_turn['input']['live']['asr-hyps'][0]['asr-hyp'].strip()
out_asr = "%s\t%s\1%s\t%s" % (session_id.encode('utf8'), mach.encode('utf8'), user_asr.encode('utf8'), labels_ids)
fw.write(u"%s\n" % out)
fw_asr.write(u"%s\n" % out_asr)

我是这么处理的，可以避开这个错误。

**Comment by xyzhou-puck** [comment]
Hi,

Thanks so much for your suggestion, @xixiaoyao @wangxiao1021 could you guys please take a look at this problem?

Xiangyang

**Comment by xixiaoyao** [comment]
> 原因在于你们在build DSTC2 的数据的时候build_dstc2_dataset.py 文件的line 109 和 110
> fw.write(u"%s\n" % out.encode('utf8'))
> fw_asr.write(u"%s\n" % out_asr.encode('utf8'))
> 把数据的length合并成1了。读出来的时候也只有一个。。

可以麻烦详细解释一下吗？我们在本地测试没有能复现这个错误。另外麻烦您把环境配置说一下吧，包括python版本、cpu/gpu、paddle版本等，另外您跑的是dstc2的官方数据集吗？还是私有数据集呢

**Comment by huey0528** [comment]
我使用的你们的脚本下载的数据，然后python3.6，gpu是Tesla T4，和最新版的paddle。我使用colab跑了一下，链接在下面，你们可以看一下。
https://colab.research.google.com/drive/16JrCU3UX22UHUPLw5i-Pgc7XqGewHthb

**Comment by wangxiao1021** [comment]
> 我使用的你们的脚本下载的数据，然后python3.6，gpu是Tesla T4，和最新版的paddle。我使用colab跑了一下，链接在下面，你们可以看一下。
> https://colab.research.google.com/drive/16JrCU3UX22UHUPLw5i-Pgc7XqGewHthb

已复现问题并解决。感谢提供问题及解决方案。
