### ISSUE TITLE
PaddleSlim载入int8量化模型的问题

### ISSUE THREAD

**Issue by AndrewZhao** [PaddlePaddle/models#4199]
我从链接https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/docs/model_zoo.md下载的ResNet50的int8量化预训练模型，解压以后有三种精度的模型{float, int8, mobile}，在PaddleSlim/classification/eval.py中正确设置了int8模型路径和测试图片路径，运行以后报错，如下图所示
![int8](https://user-images.githubusercontent.com/11373817/72415033-8f864500-37ae-11ea-831c-039768111d33.png)
之后我把模型路径改为float，运行正常。
最后我把模型路径改为mobile，又报错，如下图所示
![mobile](https://user-images.githubusercontent.com/11373817/72415243-fdcb0780-37ae-11ea-8ff1-6487536dc93d.png)
请问这是为什么？该如何解决？请不吝赐教

**Comment by slf12** [comment]
您好，float存储的是参数是int8范围，但是类型是float的模型，如果使用预测库如paddle-lite, 或者paddle中接入的tensorrt来预测的话，是加载float模型的，预测库会把float转成int8，使用int8 kernel计算来加速。而paddle原生api 没有int8 kernel 。可参考https://paddlepaddle.github.io/Paddle-Lite/develop/model_quantization/#%E4%BA%8C%E4%BD%BF%E7%94%A8Paddle-Lite%E8%BF%90%E8%A1%8C%E9%87%8F%E5%8C%96%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86。

int8文件夹下的模型是为了直观看到量化后模型大小，不可被加载。
mobile文件夹是原本用paddle-mobile来加载的模型，paddle-mobile已整合进paddle-lite，且现在可直接加载float文件夹下的模型，因此此文件夹的模型也废弃了。


另，你看的paddleslim文件夹是老接口，为了更方便使用，我们开放了新的低级api， https://github.com/PaddlePaddle/PaddleSlim，文档： https://paddlepaddle.github.io/PaddleSlim/， 欢迎使用我们新的api接口。算法原理可参考：https://paddlepaddle.github.io/PaddleSlim/algo/algo/#1-quantization-aware-training。

如果您的疑问得到解答，请及时关闭issue。

**Comment by AndrewZhao** [comment]
感谢您耐心的回答！不过我有个小问题，我看了一下，您说的PaddleLite好像是在手机端运行的？或者我直说我的诉求吧，我想测试Intel CascadeLake Server CPU使用VNNI指令集时在百度飞桨中运行int8模型推理的速度，我一直找不到测试百度飞桨宣传的支持VNNI指令集的方法，或者说入口

**Comment by slf12** [comment]
支持的，请参考文档，使用预测的api将量化训练产生的模型转化一下
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
https://github.com/PaddlePaddle/Paddle/blob/fbf9eca0d366ad7c2c933ee47580b8f3d8ba79d2/python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
https://github.com/PaddlePaddle/Paddle/blob/fbf9eca0d366ad7c2c933ee47580b8f3d8ba79d2/python/paddle/fluid/contrib/slim/tests/slim_int8_mkldnn_post_training_quantization.md
