### ISSUE TITLE
检测识别使用随机尺寸，图片翻转。

### ISSUE THREAD

**Issue by ViHinh** [PaddlePaddle/models#4231]
新年快乐！我在使用桨检测的时候，不知道如何在识别结果检测中使用随机尺寸，和图片翻转。我英语不好，我使用翻译翻阅了相关文档，并没有看到相关的说明。希望有人能帮我，谢谢！

**Comment by MRXLT** [comment]
你好，可以参考这篇文档https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/DATA_cn.md#apis
