### ISSUE TITLE
请问训练好的识别模型如何导出成__param__和__model__的格式

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4260]
现在训练好的模型是一个整体，无法做c++部署

**Comment by yanmeizhao** [comment]
现在训练好的模型是一个整体，无法做c++部署

**Comment by chenwhql** [comment]
我看源码中现在是仅保存了param，保存至指定的文件
https://github.com/PaddlePaddle/models/blob/22b8805bb5a6a6ee28fb228fc4ce7fee4791bef1/PaddleCV/ocr_recognition/train.py#L149

如果需要同时保存model和param，需要使用save_inference_model接口
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#paddle.fluid.io.save_inference_model

您可以根据API文档，尝试在save_model的时候使用该接口保存模型和参数

**Comment by chenwhql** [comment]
这个我后续反馈一下，是否可以在默认实现中增加存储model的实现

**Comment by yanmeizhao** [comment]
我的模型目前是已经训练好的，就只是想转换一下格式

**Comment by endy-see** [comment]
> 这个我后续反馈一下，是否可以在默认实现中增加存储model的实现

我的模型目前是已经训练好的，就只是想转换一下格式

**Comment by chenwhql** [comment]
那麻烦问下这个训练好的模型之前是用paddle训练的吗？或者是用什么训练的？

**Comment by endy-see** [comment]
> 那麻烦问下这个训练好的模型之前是用paddle训练的吗？或者是用什么训练的？

训练好的模型就是用paddle训练的

**Comment by chenwhql** [comment]
这应该不是转换格式的问题，是保存的方式和内容不太一样，您可以试着用save_inference_model跑一轮把__model__能存下来，然后结合之前训练好的__param__，部署试一下

**Comment by endy-see** [comment]
我这边换一下模型保存格式，目前能够保存部署模型了，代码如下：
![save](https://user-images.githubusercontent.com/13143336/74397944-e421ec00-4e50-11ea-83c5-07e75f879e5c.png)

其中： 
fluid.io.save_inference_model(args.save_model_dir+filename, feeded_var_names=['pixel'], target_vars=fetch_vars, executor=exe, main_program=inference_program, params_filename="__params__")
save_inference_model的定义如下
add_arg('save_inference_model',    bool,     False, "The directory the model to b    e saved to.")
