### ISSUE TITLE
请问如何debug官网上c++部署的demo？

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4272]
官网c++部署部分的地址（包含demo）：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/native_infer.html
我这边已经备好了paddle的部署环境，也能跑通官方的demo（mobilenetv1那个），现在有个问题，就是我对c++代码不是很熟悉，修改一下就时常导致崩溃，有时候也看不到问题原因，这时希望能看一下在执行sh run.sh过程中的debug情况，网上看了一下说用gdb可以实现debug，但是看到的例子都是直接debug cpp文件，没有debug bash脚本的，所以想问一下怎么debug sh run.sh的过程?

**Comment by zhupengyang** [comment]
C++代码里面可以通过添加类似 ```LOG(INFO)<<"xxx";``` 的代码打印自己需要的信息

**Comment by endy-see** [comment]
除了一行一行打，没有别的办法了么？

**Comment by zhupengyang** [comment]
> 除了一行一行打，没有别的办法了么？

打log是目前最常规最常用的方式了

**Comment by endy-see** [comment]
好吧
