### ISSUE TITLE
ocr识别模型部署时遇到ShapeError

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4303]
具体错误如下：
----------------------
Error Message Summary:
----------------------
Error: ShapeError: The number of input channels should be equal to filter channels * groups. But received: the input channels is [3], the shapeof input is [1, 3, 48, 86], the filter channel is [1], the shape of filter is [16, 1, 3, 3],the groups is [1]
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:1.] at (/home/install/Paddle/paddle/fluid/operators/conv_op.cc:94)
  [operator < conv2d_fusion > error]
run_impl.sh: line 28: 32112 Aborted                 (core dumped) ./${DEMO_NAME}
[root@8d7415071953 infer_ocr]#
请问识别模型部署的时候有什么需要注意的么？

**Comment by wanghaoshuang** [comment]
在Paddle/models下提供的ocr模型默认用的是示例数据，示例数据为channel为1的灰度数字图像，所以第一层卷积的filter shape是`[16, 1, 3, 3]`.

您在预测时，输入图像应该是3通道的所以出错了。

建议训练和预测保持一致，训练修改这里：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/data_reader.py#L35

**Comment by endy-see** [comment]
> 在Paddle/models下提供的ocr模型默认用的是示例数据，示例数据为channel为1的灰度数字图像，所以第一层卷积的filter shape是`[16, 1, 3, 3]`.
> 
> 您在预测时，输入图像应该是3通道的所以出错了。
> 
> 建议训练和预测保持一致，训练修改这里：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/data_reader.py#L35
我训练的时候用的是自己的数据集，没有用示例数据

**Comment by endy-see** [comment]
> 在Paddle/models下提供的ocr模型默认用的是示例数据，示例数据为channel为1的灰度数字图像，所以第一层卷积的filter shape是`[16, 1, 3, 3]`.
> 
> 您在预测时，输入图像应该是3通道的所以出错了。
> 
> 建议训练和预测保持一致，训练修改这里：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/ocr_recognition/data_reader.py#L35

把channel变成1以后解决了
