### ISSUE TITLE
关于物品冷启动推荐的问题（PaddleRec, DIN/SSR）

### ISSUE THREAD

**Issue by stevenkwong** [PaddlePaddle/models#4333]
作者你们好，在使用DIN、SSR模型的时候，发现infer都是面向有进入到embedding层字典里面的item的，那么如果推荐系统中新上item，使用这两款模型应该怎么实现推荐呢？

还望不吝赐教~

**Comment by frankwhzhang** [comment]
ssr模型针对的是已有item的训练 可以考虑增量训练新的item
