### ISSUE TITLE
DeepSpeech2 implementation detail not consistent with paper

### ISSUE THREAD

**Issue by lispc** [PaddlePaddle/models#434]
https://github.com/PaddlePaddle/models/blob/develop/deep_speech_2/decoders/scorer_deprecated.py#L67
```
score = self._alpha * np.log(lm) + self._beta * np.log(word_cnt)
```
While in the original paper, there is no `log` with word_cnt.

**Comment by kuke** [comment]
@lispc Please note the ```if...else...``` condition outside this line. Users can set the flag ```log``` to choose whether return the score in log scale or in the original format.  When in log scale, there should be a ```log``` operation with the word insertion term.

**Comment by lispc** [comment]
@kuke 
no. the original formula is 
![image](https://user-images.githubusercontent.com/2833376/32538540-4932a65c-c4a1-11e7-9c97-4ed99515d217.png)
so, maybe the correct code is 
```
if log == False:
    score = np.power(lm, self._alpha) * np.power(10, word_cnt * self._beta) # in exp format
else:
    score = self._alpha * np.log(lm) + self._beta * word_cnt # as is original paper
```
?

**Comment by kuke** [comment]
@lispc I see. 

Actually the deprecated Python decoder is based on the [prefix beam search paper](https://arxiv.org/pdf/1408.2873.pdf), which we have declared in the comments.  For the right code of the formula above, you should refer to [the corresponding line](https://github.com/PaddlePaddle/models/blob/develop/deep_speech_2/decoders/swig/ctc_beam_search_decoder.cpp#L126) in the C++ decoder that we are using. 

They two have difference in the word insertion term.

**Comment by lispc** [comment]
ok. got. Thanks~
