### ISSUE TITLE
ocr_recognition识别模型训练时不能用百度提供的预训练模型

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/models#4340]
我的模型NUM_CLASS是3840, 用attention_ctc，加载前我将fc层stop_gradient 想finetune确总是会报错，You are not allowed to load partial data via load_combine_op, use load_op

**Comment by LDOUBLEV** [comment]
问题出在加载参数的API不支持加载部分参数，可以使用[fluid.load](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/fluid_cn/load_cn.html#load)这个API试一下，在var_list中设置想要读取的参数列表。
