### ISSUE TITLE
LogWriter突然不出图了

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/models#4341]
![image](https://user-images.githubusercontent.com/8415114/75229278-92804680-57ec-11ea-86b0-72dabdd1d1a6.png)

**Comment by cisco08** [comment]
之前都是好的

**Comment by juncaipeng** [comment]
self.summary_logger = LogWriter(os.path.join(self.save_dir, "summary"), sync_cycle=10000)

看代码，你检查是否保存了“summary”？
