### ISSUE TITLE
用TSN视频分类模型进行finetune时的问题

### ISSUE THREAD

**Issue by davidwhite-www** [PaddlePaddle/models#4358]
我想利用paddle提供的已经训练好的TSN等视频模型，对自己的数据集进行finetune并分类。
有两个个问题：
1、在执行train.py时，能否冻结预训练模型的部分或全部卷积层，只训练剩下的卷积层和自己定制的全连接层。
2、在执行predict.py时，如何获得预训练模型的某一层的输出，或者获得输出层的特征向量。

**Comment by huangjun12** [comment]
1.可以的，通过将某一卷积层参数的学习率设为0可以冻结部分或全部卷积层，
示例代码:
conv = fluid.layers.conv2d(param_attr=fluid.param_attr.ParamAttr(learning_rate=0),...)
参考文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/ParamAttr_cn.html#cn-api-fluid-paramattr
2. 要获得某一层的输出，要将该层的输出fetch出来。具体的，
(1)请修改tsn_res_model.py文件的net函数，返回你想要的输出；
(2)修改tsn.py文件的build_model函数，获取相应的返回值；
(3)修改tsn.py文件的fetches函数，得到'infer'模式下的fetch_list变量；
(4) 此时predict.py文件的infer函数中得到的infer_outs变量便存储了你想要的某一层的输出特征。
