### ISSUE TITLE
微调nextvald的参数，如何加载部分参数呢

### ISSUE THREAD

**Issue by aiot-tech** [PaddlePaddle/models#4367]
如果不需要最后一层参数，该怎么进行这种底层操作呢？有没有相关教程，感觉paddlepaddle的教程很少啊，好多都是高级封装好的了，很难进行定制化操作

**Comment by mapingshuo** [comment]
已有重复issue, 一并在另一issue中讨论：https://github.com/PaddlePaddle/Paddle/issues/22812
