### ISSUE TITLE
lac大规模文本分词效率比较低

### ISSUE THREAD

**Issue by yudian931122** [PaddlePaddle/models#4379]

**Comment by baiyfbupt** [comment]
你好，效率低体现在什么方面呢？能否详细描述下

**Comment by yudian931122** [comment]
> 你好，效率低体现在什么方面呢？能否详细描述下

指的是耗时方面，今天我用10万条短文本测试做分词处理，大概300万个词，花费了十多分钟；
尝试了两种方式：10万条一次喂给lac分词、分若干批次喂给lac分词，两种方式下耗时接近；
是我使用的方式有问题吗？

**Comment by kuke** [comment]
@yudian931122 这种情况有可能会发生，硬件设备的计算能力限制了模型的数据吞吐率，因此一样的数据规模，分批次feed和一次性feed的总耗时有可能差不多。
