### ISSUE TITLE
这是否是pyramidbox代码问题？

### ISSUE THREAD

**Issue by sonic-github** [PaddlePaddle/models#4398]
widerface_eval里
函数infer有这么一段代
if image.mode == 'L':
     image = img.convert('RGB')
img我没有找到上下文，个人怀疑应该是image，不知道是不是？

**Comment by huangjun12** [comment]
麻烦提供下代码链接~

**Comment by sonic-github** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/face_detection/widerface_eval.py

**Comment by yghstill** [comment]
@sonic-github 感谢指出语法错误，因为Image.open读取图片格式本身就是RGB，所以if里没有执行，不影响正常使用，img语法错误我们将会修正。

**Comment by sonic-github** [comment]
再给你指一个.... 其实在pycharm里打开项目，这些语法都有红线标识出来:
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/face_detection/visualize.py
函数
def draw_bbox(image, bbox):
......
    draw = ImageDraw.Draw(image)
    xmin, ymin, xmax, ymax = box
box 也是没有上下文的，我想应该是想写bbox?
