### ISSUE TITLE
关于BSN/BMN模型

### ISSUE THREAD

**Issue by li-900406** [PaddlePaddle/models#4411]
BSN/BMN模型中好像只提供了动作提名的部分的实验步骤，请问一下后面动作分类部分的实验步骤是什么？谢谢

**Comment by Chuckie-He** [comment]
同样的问题，请问detection部分的代码开源了吗？谢谢~

**Comment by huangjun12** [comment]
BMN和BSN都是**时序提名生成**模型，只生成proposal，
视频动作定位完整的pipline可参考开源模型**CTCN**的实现:
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleVideo/models/ctcn

**Comment by li-900406** [comment]
请问一下CTCN模型里面结合BSN/BMN模型了吗？因为CTCN没有文章，我并不清楚其原理，可否给一个CTCN模型科普的文章？谢谢~

**Comment by huangjun12** [comment]
> 请问一下CTCN模型里面结合BSN/BMN模型了吗？因为CTCN没有文章，我并不清楚其原理，可否给一个CTCN模型科普的文章？谢谢~

CTCN模型论文请参考: https://arxiv.org/abs/1908.09442

**Comment by xueyingliu** [comment]
CTCN跑的时候报错啦

> [Errno 2] No such file or directory: './data/dataset/ctcn/Activity1.3_val_rgb.listformat'

说是文件没上传，所以到底能不能跑呀

**Comment by huangjun12** [comment]
> CTCN跑的时候报错啦
> 
> > [Errno 2] No such file or directory: './data/dataset/ctcn/Activity1.3_val_rgb.listformat'
> 
> 说是文件没上传，所以到底能不能跑呀

<img width="941" alt="image" src="https://user-images.githubusercontent.com/22365664/82529476-b0e8aa80-9b6d-11ea-8d34-453ad0f1cdad.png">

在下载链接里提供了，请参考数据准备步骤：
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/video/data/dataset/ctcn/README.md

**Comment by xueyingliu** [comment]
@huangjun12 好的，非常感谢

**Comment by liu824** [comment]
BMN 中只有提名生成的实验步骤，但为什么loss中有pem_cls_loss，这个应该是提名分类的loss把，而且这个loss在训练时经常出现nan,使用百度提供的数据集也是如此，是否在计算的时候可以去掉这个loss

**Comment by wwdok** [comment]
我在使用CTCN时遇到报错了([链接](https://github.com/PaddlePaddle/models/issues/5131#issuecomment-751154174)), 伙计们能帮忙看一下吗 ? 谢谢 !
