### ISSUE TITLE
OCR 中数据的label为什么不是从0开始标记的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#4477]
在 https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ocr_recognition 
在这个OCR模型中，提供的数据集的标签是从15开始标记的，而且一共就只有62个类别，但是模型设置却是95个类别，这是为什么呢？

**Comment by LDOUBLEV** [comment]
感谢关注，这个OCR模型训练之初用了另一个数据集，类别数量更全。由于一些原因，该数据集不会公开，OCR模型里提供的数据集只是一部分数据。另外，我们正在准备发布一批新的OCR模型，会逐渐淘汰或重构旧的模型。

如果想优化这个模型，建议将num_classes改成当前数据集的类别数量，并通过fluid.load_program_state   fluid.set_program_state 这两个API 完成模型的fine-tuning。

**Comment by yeyupiaoling** [comment]
@LDOUBLEV 当使用 attention 模型时，label会有一个 `[SOS] + label, label + [EOS]` ,
所以 label 是不是应该要大于等于0？

**Comment by LDOUBLEV** [comment]
> @LDOUBLEV 当使用 attention 模型时，label会有一个 `[SOS] + label, label + [EOS]` ,
> 所以 label 是不是应该要大于等于0？

是大于0

**Comment by yeyupiaoling** [comment]
@LDOUBLEV 谢谢，感谢回答
