### ISSUE TITLE
使用ParallelExecutor单机多核训练，除速度外等价于加大batchsize么？

### ISSUE THREAD

**Issue by bkseastone** [PaddlePaddle/models#4493]
比如，`batchsize = 128`，`CPU_NUM = 8` 时，使用 `ParallelExecutor` 单机训练，除训练速度外，是否等价于 `batchsize = 128 * 8`，`CPU_NUM = 1` 的单机单核训练？

**Comment by luotao1** [comment]
是的。如果能保证代码配置里的batch_size是原来的8倍，那么两者任务量是一致的，也就是等价的。
