### ISSUE TITLE
the focal loss impletation for PaddleCV/image_classification

### ISSUE THREAD

**Issue by zimoqingfeng** [PaddlePaddle/models#4500]
使用PaddleCV/image_classification时候，复现了一个可用于图像分类任务的focal loss

https://github.com/zimoqingfeng/focal_loss_paddle/blob/master/focal_loss_paddle.py

望采纳，有问题随时联系。

**Comment by shippingwang** [comment]
十分感谢您的贡献，日后会加到分类库中 https://github.com/PaddlePaddle/PaddleClassification 欢迎star～
