### ISSUE TITLE
deep_speech_2/examples/tiny run_data.sh报错，无法继续

### ISSUE THREAD

**Issue by harold-yh** [PaddlePaddle/models#451]
RuntimeError: Error opening '/root/.cache/paddle/dataset/speech/libri/test-clean/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac': File contains data in an unimplemented format

另外docker里没有libsndfile-1.0.28,setup.sh也下载不下来，手动安装的，这些应该在docker中打包好的吧？

**Comment by kuke** [comment]
@harold-yh 猜测你用错了docker镜像, 已确认```paddlepaddle/models:deep-speech-2```这个镜像已安装好了相关依赖，运行tiny/run_data.sh, 你会看到如下的输出：

<img width="810" alt="2017-11-13 10 44 29" src="https://user-images.githubusercontent.com/3064195/32707597-f86c8e96-c85f-11e7-8e99-89419823185c.png">
