### ISSUE TITLE
如何得到预训练模型的某一层输出结果？

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/models#4513]
hi,dear
预训练模型[NeXtVLAD](https://paddlemodels.bj.bcebos.com/video_classification/NEXTVLAD.pdparams)的某一层输出结果怎么得到啊？
具体情况请看[这个](https://github.com/PaddlePaddle/models/issues/4510)

多谢

**Comment by heavengate** [comment]
print那一层的输出可以看到那个Variable的名字，然后把这个名字加到`exe.run(...,fetch_list=[var_name])`里的`fetch_list`里面就可以了

**Comment by ucas010** [comment]
这个[模型](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/models/nextvlad/nextvlad.py)的创建也没看到有变量名字啊
写了一堆，感觉有点乱

**Comment by heavengate** [comment]
<img width="484" alt="屏幕快照 2020-04-02 下午6 42 57" src="https://user-images.githubusercontent.com/12605721/78240632-d8c67500-7511-11ea-82a2-3b2272d8e88f.png">
可以类似图中一样你需要打印那层直接用`fluid.layers.Print`打印，这个接口的用法可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print

**Comment by ucas010** [comment]
多谢大佬，我找到了结点名
```
name: "batch_norm_3.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 4096
    }
    lod_level: 0
  }
}
```
这个维度是不是有点吓人啊，

**Comment by heavengate** [comment]
不大，挺正常的，这应该是fc指定了输出size是4096吧，是正常网络结构

**Comment by heavengate** [comment]
如果没有问题，当前issue关闭，如果后续有问题可以reopen此issue或提新issue
