### ISSUE TITLE
文字识别模型 ocr_recognition 变长输入出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#4522]
ocr_recognition 模型：https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/ocr_recognition

在最新的代码下，使用的是输入接口是：
```python
    images = fluid.data(name='pixel', shape=data_shape, dtype='float32')
    label = fluid.data(name='label', shape=[None, 1], dtype='int32', lod_level=1)
```

该接口好像不支持变长输入，为什么不使用`fluid.layers.data()`接口呢？

**Comment by BeyondYourself** [comment]
之前的接口是慢慢会被废弃，新旧接口可以查看paddlepaddle官方接口文档，如果是变长我记得好像是用-1替代吧？？

**Comment by yeyupiaoling** [comment]
@BeyondYourself 除了第一个使用-1作为batch size，其他的不可以这样使用了。我测试过。

**Comment by yeyupiaoling** [comment]
@BeyondYourself 可以这样解决，batch size设置的是None，然后就这样了 [None, 1, 48, -1]
