### ISSUE TITLE
bsn model is missing python training script - train.py

### ISSUE THREAD

**Issue by UCC-team** [PaddlePaddle/models#4528]
bsn model is missing python training script - train.py
(only has bmn training script in dygraph/bmn/train.py)

https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video/models/bsn

![image](https://user-images.githubusercontent.com/35629974/79119802-cc6cd280-7dc3-11ea-9a61-94596a2e4b7f.png)
@qingqing01 @SunGaofeng @huangjun12

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/train.py  Here is the python training script of bsn model. In fact, all models in PaddleCV/video use this train script.
Specially, for bmn model, the extra implementation using paddle dygraph mode  is released in https://github.com/PaddlePaddle/models/tree/develop/dygraph/bmn
