### ISSUE TITLE
README链接失效

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/models#4532]
## Model下README的“基于动态图实现的模型”部分链接失效
https://github.com/PaddlePaddle/models
![图片](https://user-images.githubusercontent.com/46156734/79337787-c2300d00-7f58-11ea-8cc9-e7b968e7e295.png)
![图片](https://user-images.githubusercontent.com/46156734/79337888-ec81ca80-7f58-11ea-8802-a035b0a6c6c4.png)

**Comment by MRXLT** [comment]
感谢反馈，我们会修复一下
