### ISSUE TITLE
推荐算法SR-GNN中建立有向图中np.divide()建议改成np.true_divide()

### ISSUE THREAD

**Issue by jaykay233** [PaddlePaddle/models#4548]
![image](https://user-images.githubusercontent.com/58713995/79696003-e88eca80-822e-11ea-9f95-29ba597bee7c.png)
有向图adj_in和adj_out归一化时官方对应python版本使用了np.divide(),可能会出现adj_in和adj_out全是0矩阵的情况，改成np.true_divide()会使用浮点数除法，才能达到归一化的效果。不知道是否正确？

**Comment by hutuxian** [comment]
感谢您使用Paddle以及PaddleRec模型库。
在SR-GNN的代码中并不会出现这个问题：因为adj数组是从np.zeros()而来，而该函数返回的元素的默认值是float，所以之后进行除法的时候，都会保留小数部分不会产生截断。

**Comment by jaykay233** [comment]
嗯嗯，谢谢
