### ISSUE TITLE
异步数据读取和处理效率不高，导致GPU利用率较低

### ISSUE THREAD

**Issue by yangyangHu** [PaddlePaddle/models#4579]
### 问题描述：

- 试用的代码是paddlepaddle开源的deepspeech2: https://github.com/PaddlePaddle/DeepSpeech

- 硬件环境：paddlepaddle-1.6, 4块GPU-v100, CPU 32core

- 代码里面使用的是异步数据读取：

 reader = fluid.io.DataLoader.from_generator(
                feed_list=inputs,
                capacity=64,
                iterable=False,
                use_double_buffer=True)

- 遇到的问题：
batch_size=64, 4块GPU-v100训练的时候，gpu利用率不到1%
自己排查了io利用率不到20%，磁盘为SSD，cpu只有1-2个core用起来了，其它的30个cpu core都是空闲。

根据paddlepaddle文档 
 (https://www.paddlepaddle.org.cn/documentation/docs/en//advanced_guide/performance_improving/singlenode_training_improving/training_best_practice.html)    提示设置FLAGS_reader_queue_speed_test_mode，关闭数据读取和预处理，纯测试GPU利用率稳定在90%以上，自行排查下来瓶颈应该在异步数据读取和预处理

求帮忙解答。

**Comment by chenwhql** [comment]
您是直接按照DeepSpeech的说明跑起来就这么慢吗？还是您替换了自己的数据集，也做了一些预处理？

**Comment by yangyangHu** [comment]
> 您是直接按照DeepSpeech的说明跑起来就这么慢吗？还是您替换了自己的数据集，也做了一些预处理？

唯一的区别是换了自己的数据集，语音长度为15s，其它的都是按照DeepSpeech的说明来的

**Comment by chenwhql** [comment]
解释下，如果仅使用DataLoader，这个的异步能力是有限的，它里面只有一个子线程用于异步处理（语音从磁盘载入+语音数据预处理+放入训练时取数据的Queue）这个过程，如果这个过程耗时较长，训练过程本身时间又比较短，会导致训练时取数据的消耗速度赶不上子线程数据供应速度，不知道您数据预处理的开销是否会导致这个问题

此外，也麻烦负责的同学确认下 DeepSpeech开发时是否遇到类似的问题 @kuke 

关于如何进一步提高数据读取效率，您可以暂时尝试下外部线程或进程加速是否有效果，Paddle目前也有一些具备类似功能的API：
- 外部线程加速：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/io_cn/xmap_readers_cn.html#xmap-readers
- 外部进程加速：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/io_cn/multiprocess_reader_cn.html#multiprocess-reader

我们已经在从根本上解决这个问题，提供灵活配置并发能力的DataLoader，目前在develop版本中也可以试用，但正式宣传应该在Paddle 2.0版本，您可以了解下
https://github.com/PaddlePaddle/Paddle/blob/50330c6c6d323446744ac65613ea45130e7714b7/python/paddle/fluid/reader.py#L100

如果您有意试用新版的DataLoader，可以安装develop版本的Paddle尝试：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

**Comment by yangyangHu** [comment]
> 解释下，如果仅使用DataLoader，这个的异步能力是有限的，它里面只有一个子线程用于异步处理（语音从磁盘载入+语音数据预处理+放入训练时取数据的Queue）这个过程，如果这个过程耗时较长，训练过程本身时间又比较短，会导致训练时取数据的消耗速度赶不上子线程数据供应速度，不知道您数据预处理的开销是否会导致这个问题
> 
> 此外，也麻烦负责的同学确认下 DeepSpeech开发时是否遇到类似的问题 @kuke
> 
> 关于如何进一步提高数据读取效率，您可以暂时尝试下外部线程或进程加速是否有效果，Paddle目前也有一些具备类似功能的API：
> 
> * 外部线程加速：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/io_cn/xmap_readers_cn.html#xmap-readers
> * 外部进程加速：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/io_cn/multiprocess_reader_cn.html#multiprocess-reader
> 
> 我们已经在从根本上解决这个问题，提供灵活配置并发能力的DataLoader，目前在develop版本中也可以试用，但正式宣传应该在Paddle 2.0版本，您可以了解下
> https://github.com/PaddlePaddle/Paddle/blob/50330c6c6d323446744ac65613ea45130e7714b7/python/paddle/fluid/reader.py#L100
> 
> 如果您有意试用新版的DataLoader，可以安装develop版本的Paddle尝试：
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#whl-dev

赞👍，正如您描述的，我目前的训练瓶颈就在：训练时取数据的消耗速度赶不上子线程数据供应速度。我试试用您提供的改进方式优化下，同时希望你们这个新的Dataloader可以加入Deepspeech代码中，谢谢

**Comment by chenwhql** [comment]
目前2.0正式版已发布，新的DataLoader已经可以使用了，先关闭这个卡片，有问题再打开
