### ISSUE TITLE
优化目录名称

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/models#458]
![image](https://user-images.githubusercontent.com/6836917/32759242-4e46444c-c923-11e7-8b1e-b1546aca24ad.png)
目录存在两个问题：
- 2/6/10/14 目录名称太长，导致右侧导航栏显示不全。
- CopyRight不应该出现在目录中。

准备修改：
- 2/6/10/14 目录分别改成：RNN语言模型，结构化语义模型，自动问答，语音识别
- 在目录中去掉CopyRight

**Comment by luotao1** [comment]
英文目录存在类似问题，可以一起修复

**Comment by lcy-seso** [comment]
英文目录想要压缩到能够被导航栏显示完整难度似乎有点高（英文表意密度比汉语低，标题普遍偏长），这个有什么好的建议吗？

![image](https://user-images.githubusercontent.com/5842774/32760793-8d9a859a-c8b5-11e7-9067-7ba450a487c8.png)

**Comment by luotao1** [comment]
![image](https://user-images.githubusercontent.com/6836917/32761045-39fa7de2-c92c-11e7-95be-5f4f9a4a6d74.png)
英文目录，除了第2个标题之外，其余都还行。第2个标题在全文的显示中也过长，换行了，能否简短一点。
