### ISSUE TITLE
在训练的时候这几个参数['reduce_sum_0.tmp_0', 'reduce_sum_2.tmp_0', 'elementwise_sub_0']其中第一个参数的值为nan这是为什么

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/models#4655]
在训练的时候这几个参数['reduce_sum_0.tmp_0', 'reduce_sum_2.tmp_0', 'elementwise_sub_0']对应的值为 [nan, 4.791813, 5]，其中第一个参数reduce_sum_0.tmp_0的值为nan这是为什么？之前的训练都是正常的，在executor执行run后输出的结果中出现Nan，求解答

**Comment by Aurelius84** [comment]
请问下是使用models里的模型训练吗？辛苦提供下具体的模型代码。

> 之前的训练都是正常的，在executor执行run后输出的结果中出现Nan，求解答

之前训练是正常的？之后做了哪些改动（或添加了哪些layers）开始出Nan的？

**Comment by BeyondYourself** [comment]
这个是用的CV里面的[ocr_recognition](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleCV/ocr_recognition)
用的是CRNN+CTC这个模型进行训练。
`def train_one_batch(data):
        var_names = [var.name for var in fetch_vars]
        if args.parallel:
            results = train_exe.run(var_names,
                                    feed=get_feeder_data(data, place))
            results = [np.array(result).sum() for result in results]
        else:
            results = train_exe.run(feed=get_feeder_data(data, place),
                                    fetch_list=fetch_vars)
            results = [result[0] for result in results]`
在执行train.py这个代码处results处出现nan，也就是fetch_list中的结果，如下是实际的一个输出结果：
[array([nan], dtype=float32), array([4.8362575], dtype=float32), array([5], dtype=int64)]
.训练输入的数据没有nan

**Comment by LDOUBLEV** [comment]
是在一开始训练就出Nan，还是训练一段时间出Nan的？你的训练数据是正常的吗？还有其他改动吗？

---
顺便说下，ocr_recognition 里的算法不打算继续维护了，OCR已经新独立了一个repo，请参考：https://github.com/PaddlePaddle/PaddleOCR

**Comment by BeyondYourself** [comment]
目前是一开始就出现了nan，但是第一个result没有NAN，之后的数据都为nan了，模型没有改动过，我拿之前的可以正常运行的数据集测试现在也不正常了，经常nan

**Comment by LDOUBLEV** [comment]
前后的paddle版本是一样的吗

**Comment by BeyondYourself** [comment]
训练是用的AI Studio上的paddle，版本跟随AI Studio的版本，昨天训练正常，今天一大早最初是在迭代了1W次nan，后来直接启动训练开始就nan

**Comment by LDOUBLEV** [comment]
麻烦发一下AIstudio的项目链接吧， AIstudio 的paddle版本切换到1.6 或者1.7试试，

**Comment by LDOUBLEV** [comment]
建议用最新版的OCR算法吧，repo 链接：https://github.com/PaddlePaddle/PaddleOCR

**Comment by BeyondYourself** [comment]
放在AI studio上的项目没有公开，链接你应该打不开，我试试新的算法，谢谢
