### ISSUE TITLE
请问paddle模型如何一次初始化，多次预测

### ISSUE THREAD

**Issue by lerry-lee** [PaddlePaddle/models#4660]
意思是，一次将模型初始化到内存中，后续多次送入不同的预测数据.
目前是每次预测都要重新加载一次模型文件.

**Comment by qingqing01** [comment]
@lerrylca  是可以加载一次模型，batch预测的。加载模型后，for循环给数据即可。 比如: https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/image_classification/infer.py#L157
