### ISSUE TITLE
lexical_analysis中代码有bug

### ISSUE THREAD

**Issue by AltenLi** [PaddlePaddle/models#4670]
optimizer = fluid.optimizer.Adam(
                learning_rate=args.base_learning_rate, 
                grad_clip=clip)
optimizer.minimize(train_ret["avg_cost"])

-------应该为--------

optimizer = fluid.optimizer.Adam(
                learning_rate=args.base_learning_rate)
optimizer.minimize(train_ret["avg_cost"], 
                grad_clip=clip)

**Comment by guoshengCS** [comment]
在Paddle 1.8版本后optimizer中已经支持设置`grad_clip`参数了，可以更新到Paddle 1.8以后的版本试下。

新版本引入了一些修改代价较小的不兼容升级，对于models repos中提供的代码我们也都升级到了新的接口，带来不便还望见谅。

**Comment by AltenLi** [comment]
感谢
