### ISSUE TITLE
请问视频分类ATTENTION LSTM里的评价指标分别是什么意思？

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/models#4690]
我在做视频分类模型的时候训练LOSS后面有这三个指标，我只想知道分类的准确率，可是好像没有一个是准去率，请问Hit@1 = 0.50, PERR = 0.92, GAP = 0.98这三个指标分别指什么？

**Comment by huangjun12** [comment]
这三个指标是youtube8M数据集官方评估使用的
`Hit@k`  indicates the fraction of test samples that contain at least one of the ground truth labels in the top k predictions.
`PERR` measures the video-level annotation precision when we retrieve the same number of entities per video as there are in the ground-truth. 
`GAP` is the global average precision.
论文参考 https://arxiv.org/abs/1609.08675
具体实现参考 https://github.com/google/youtube-8m/blob/master/eval_util.py

**Comment by Derek-Kun** [comment]
好的感谢！
