### ISSUE TITLE
feed_vars 和fetch_targets for using save_model on blazeface

### ISSUE THREAD

**Issue by kgkzhiwen** [PaddlePaddle/models#4691]
请问我要用save_model来保存blazeface模型，以便在serving上运行，我应该使用什么作为feed_vars 和fetch_targets?

谢谢！

**Comment by heavengate** [comment]
需要用`paddle_serving_client.io.save_model`保存，保存完后可以参考https://github.com/paddlepaddle/serving 下有详细的文档和示例教程

**Comment by kgkzhiwen** [comment]
我知道要用paddle_serving_client.io.save_model。可是要怎么样获取模型的输入和输出的参数结构，这样我才能用save_model把模型保存下来？有什么函数可以获得一个模型的输入和输出的参数结构？

**Comment by heavengate** [comment]
模型的输入输出是网络结构里定义的，各个模型不同，没法直接提供这样的代码，给你定义的`fluid.data`的模型输入和模型的输出的Variable即可
