### ISSUE TITLE
是否支持直接将pytorch模型转换为Paddle Fluid 模型？

### ISSUE THREAD

**Issue by Akeepers** [PaddlePaddle/models#4693]
目标是将[spanbert](https://github.com/facebookresearch/SpanBERT) 中开源的pytorch 版模型转换为paddle fluid 模型用于fine-tune，类似repo中[bert](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT)

已尝试过的方案：

* 利用X2paddle转换模型，但得到的模型不能直接用于fine-tune
* 先将pytorch模型转换为TensorFlow，再利用脚本[convert_params.py](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/pretrain_language_models/BERT/convert_params.py)转换为paddle模型，加载转换后的模型未报错，但fine-tune时不收敛

**Comment by heavengate** [comment]
1. 如果是X2Paddle转换模型，X2Paddle可以生成模型代码，只需要将数据读取，optimizer迁移过来应该是可以训练的
2. 可以排查一下参数名是否一致，参数是否成功导入，以及数据预处理方式是否一致

**Comment by Akeepers** [comment]
1. 针对X2Paddle，已经问过x2paddle的同学，回复是不支持fine-tune
2. 参数名是一致的；任务可以正常跑起来，参数应该是成功导入了；数据预处理应该没有问题

**Comment by heavengate** [comment]
> * 针对X2Paddle，已经问过x2paddle的同学，回复是不支持fine-tune
> * 参数名是一致的；任务可以正常跑起来，参数应该是成功导入了；数据预处理应该没有问题

如果确定数据预处理没有问题的话，可以排查一下是不是batch_size太小或者是learning rate太大之类的问题，还有数据是否有非法数据导致除零之类的

**Comment by Akeepers** [comment]
应该是没有问题，代码用ernie 2.0 和 repo [bert](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT)提供的bert都跑过，且结果正常。

**Comment by heavengate** [comment]
可以试下调小learning rate试下

**Comment by Akeepers** [comment]
我会尝试一下，不过应该不是问题所在，encoder layer lr=1e-5,  task layer lr=2e-4, 都是比较正常的值；猜测可能是转模型的时候出了问题，但我没有办法验证，请问有将bert(pytorch) 直接转为paddle的解决方案吗？

**Comment by heavengate** [comment]
除了X2Paddle没有直接转的方案，可以尝试一下pytorch和paddle用同样的输入，比如前两个sample，加载权重之后对比一下输出是否一致确认一下是不是转模型结构有diff

**Comment by Akeepers** [comment]
好的，那请问一下，这里提供的[bert](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT) ,是利用这个脚本[convert_params.py](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/pretrain_language_models/BERT/convert_params.py)得到的吗

**Comment by heavengate** [comment]
是的
