### ISSUE TITLE
paddle-slim提供的所有量化的模型下载链接都失效了

### ISSUE THREAD

**Issue by ArtyZe** [PaddlePaddle/models#4697]
请问，啥时候可以修复一哈？

**Comment by sandyhouse** [comment]
指的是这个页面的量化模型下载链接吗https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/model_zoo.md？我测试是可用的呀。

**Comment by ArtyZe** [comment]
https://github.com/PaddlePaddle/models/blob/v1.4/PaddleSlim/docs/model_zoo.md
我昨天测试的这个，应该用paddlepaddle的，不好意思，我把问题关闭了，多谢
