### ISSUE TITLE
config中init_model和gan_mode的说明都一样，是不是错了

### ISSUE THREAD

**Issue by wzy-99** [PaddlePaddle/models#4704]
https://github.com/PaddlePaddle/models/blob/08316fb833602f26d718defe2f40b81c1b8bc27a/PaddleCV/gan/util/config.py#L100

这个地方init_model和gan_mode的注释都一样，是不是错了
   add_arg('init_model', str, None, "The init model file of directory.")
   add_arg('gan_mode', str, "vanilla", "The init model file of directory.")

**Comment by ceci3** [comment]
您好，说明是写错了， gan_mode 是模型中gan loss的计算方式，我改下~ 感谢反馈~

**Comment by ceci3** [comment]
resolved in https://github.com/PaddlePaddle/models/pull/4707
