### ISSUE TITLE
关于PyramidBox论文中CPM模块的一些疑问

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/models#4711]
在论文中的Fig3里面，画了一个CPM模块，即背景感知模块，下面是他的图示
![image](https://user-images.githubusercontent.com/42901638/85221637-e50eef80-b3e7-11ea-8d4c-6da33a13d341.png)

在代码里面，也有对应的实现
![image](https://user-images.githubusercontent.com/42901638/85221623-cdd00200-b3e7-11ea-958c-eacba5369004.png)

方法里的cpm方法是构造CPM模块的，但我自己画图发现它的形式应该如下
![image](https://user-images.githubusercontent.com/42901638/85221627-d294b600-b3e7-11ea-8529-6db10f4ca13f.png)

它前面采用的应该是DSSD模块中的一个形式
![image](https://user-images.githubusercontent.com/42901638/85221628-d7596a00-b3e7-11ea-8e15-9d1480d79b9e.png)

后面使用的是人脸检测SSH的上下文模块
![image](https://user-images.githubusercontent.com/42901638/85221631-daecf100-b3e7-11ea-85f1-c15794a12034.png)

与论文里的模块示意图完全不符合。。。希望官方能看下给我回复，谢谢！

**Comment by qingqing01** [comment]
@MARD1NO 

论文3.2章节描述:

```
We design the Context-sensitive Predict Module (CPM), see Fig. 2(b), in which we replace the convolution layers of context module in SSH by the residual prediction module of DSSD
```

也就是说重新设计了下。

**Comment by MARD1NO** [comment]
> @MARD1NO
> 
> 论文3.2章节描述:
> 
> ```
> We design the Context-sensitive Predict Module (CPM), see Fig. 2(b), in which we replace the convolution layers of context module in SSH by the residual prediction module of DSSD
> ```
> 
> 也就是说重新设计了下。

啊这漏看了，十分感谢回答
