### ISSUE TITLE
can you share data for  PaddleRec gnn

### ISSUE THREAD

**Issue by Sandy4321** [PaddlePaddle/models#4715]
can you share data for  PaddleRec gnn
for
https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/gnn

since link to data 
https://cikm2016.cs.iupui.edu/cikm-cup

is broken

**Comment by wangchaochaohu** [comment]
https://paddlerec.bj.bcebos.com/gnn%2Ftrain-item-views.csv  可以通过这个进行下载

**Comment by Sandy4321** [comment]
great thank you very much
by the way does it looks correctly?
![image](https://user-images.githubusercontent.com/11426119/85474813-31426700-b583-11ea-973c-17c2f409b1f7.png)

**Comment by hutuxian** [comment]
correct.

**Comment by Sandy4321** [comment]
but there are many user ids with NA
is it bad data with NAs?
