### ISSUE TITLE
ACL2020 文章Towards Conversational Recommendation over Multi-Type Dialogs咨询

### ISSUE THREAD

**Issue by mengyuanhuang1212** [PaddlePaddle/models#4720]
请问Towards Conversational Recommendation over Multi-Type Dialogs这篇文章的code和dataset路径在哪里？

**Comment by chenwhql** [comment]
您好，询问了下相关同学，这篇文章的code暂时还没有放出来，准确放出时间也还不确定，麻烦您等待下

之后的放出路径应该和论文中地址一样：https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/Research/ACL2020-DuRecDial

**Comment by mengyuanhuang1212** [comment]
好的，期待

**Comment by liuzeming01** [comment]
DuRecDia l: [https://baidu-nlp.bj.bcebos.com/DuRecDial.zip](https://baidu-nlp.bj.bcebos.com/DuRecDial.zip)

**Comment by chenwhql** [comment]
模型已放出，先关闭这个卡片，有问题再打开

**Comment by provence3658** [comment]
> 模型已放出，先关闭这个卡片，有问题再打开

请问模型的路径是？之前论文中的https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/Research/ACL2020-DuRecDial下还是没有
