### ISSUE TITLE
No such file or directory: './data/vangogh2photo/trainB/2014-05-23'

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/models#4722]
在 `trainA` 文件夹中，文件格式为 **数字.jpg** ，例如 **00454.jpg**

在 `trainB` 文件夹中，文件格式为 **日期 时间.jpg** ，例如 **2016-01-20 08:00:45.jpg**

可是 `data_reader.py` 中的代码对于 `trainB` 中的图片只取了 **日期.jpg** 这种格式，导致报错
![image](https://user-images.githubusercontent.com/45918719/85943045-0cbe0480-b960-11ea-9f72-fcd7f478804b.png)

而我将代码中的
```python
if len(line) > 1:
    self.with_label = True
    batch_out_label.append(line[1])
    file = line[0]
```
改成
```python
if len(line) > 1:
    self.with_label = True
    batch_out_label.append(line[1])
    file = line[0] + " " + line[1]
```
后，新的错误又发生了

![image](https://user-images.githubusercontent.com/45918719/85943177-e8165c80-b960-11ea-84b6-edf866cecd67.png)

我不明白是我改动有误还是我一开始理解的不对？

我在AI Studio公开了项目，方便的话可以直接运行复现：https://aistudio.baidu.com/aistudio/projectdetail/597606

期待你们的回复~

**Comment by willthefrog** [comment]
看上去是你文件名中有空格的原因，看代码中写列表时使用了`\t`作为A，B图片的分隔符，但是读取时是按空格split的，所以你的文件名就被split了，建议把文件名改成不带空格的，或者把reader部分改下，使用`\t`split
```python
 line = line.strip('\n\r\t').split('\t')
```

**Comment by shaunhurryup** [comment]
> 看上去是你文件名中有空格的原因，看代码中写列表时使用了`\t`作为A，B图片的分隔符，但是读取时是按空格split的，所以你的文件名就被split了，建议把文件名改成不带空格的，或者把reader部分改下，使用`\t`split
> 
> ```python
>  line = line.strip('\n\r\t').split('\t')
> ```

这个方法的确奏效，感谢！
