### ISSUE TITLE
bmn的输入形状是否可以是其他的值

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/models#4726]
当我使用我的特征进行训练时，出现了下面的错误，我猜测是由于我的输入（433,1024）的.npy文件，与例子中的(100,400)不相同：
[INFO: train.py:  249]: Namespace(batch_size=None, config='models-1.6/PaddleCV/PaddleVideo/configs/bmn.yaml', epoch=None, fix_random_seed=False, learning_rate=None, log_interval=10, model_name='BMN', no_memory_optimize=False, pretrain=None, resume=None, save_dir='./data/checkpoints', use_gpu=True, valid_interval=1)
[INFO: config_utils.py:   70]: ---------------- Train Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:train.json
[INFO: config_utils.py:   74]:     feat_path:work/train/videofeature
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W0629 21:27:22.091398 18762 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0629 21:27:22.095041 18762 device_context.cc:260] device: 0, cuDNN Version: 7.3.
train subset video numbers: 200
validation subset video numbers: 0
[INFO: bmn_proposal_metrics.py:   62]: Resetting train metrics...
[INFO: bmn_proposal_metrics.py:   62]: Resetting valid metrics...
[INFO: train_utils.py:   45]: ------- learning rate [0.], learning rate counter [-1] -----
[WARNING: reader.py: 1155]: Your reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    yield self.feed(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 347, in feed
    ret_dict[each_name] = each_converter.done()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 156, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: could not broadcast input array from shape (1024,379) into shape (1024)

Traceback (most recent call last):
  File "models-1.6/PaddleCV/PaddleVideo/train.py", line 254, in <module>
    train(args)
  File "models-1.6/PaddleCV/PaddleVideo/train.py", line 241, in train
    test_metrics=valid_metrics)
  File "/home/aistudio/models-1.6/PaddleCV/PaddleVideo/utils/train_utils.py", line 90, in train_with_dataloader
    for data in train_dataloader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1102, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by huangjun12** [comment]
可以 对应修改yaml文件里的配置参数即可 https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/video/configs/bmn.yaml

**Comment by liu824** [comment]
是不是修改下面的参数：
MODEL:
    name: "BMN"
    tscale: 100
    dscale: 100
    feat_dim: 400

**Comment by huangjun12** [comment]
> 是不是修改下面的参数：
> MODEL:
> name: "BMN"
> tscale: 100
> dscale: 100
> feat_dim: 400

是的

**Comment by liu824** [comment]
我的理解是tscale是视频总帧数，dscale是action最大时长，feat_dim是特征维度，不知道是不是这样

**Comment by huangjun12** [comment]
> 我的理解是tscale是视频总帧数，dscale是action最大时长，feat_dim是特征维度，不知道是不是这样

是这样的~

**Comment by liu824** [comment]
我尝试过如下设置：
MODEL:
    name: "BMN"
    tscale: 443
    dscale: 100
    feat_dim: 1024
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
    anno_file: "train.json"
    feat_path: 'work/train/videofeature'
同时把batch_size设置为1，在aistudio上仍然内存溢出。我认为我剩下只能减少action最大时长dscale,您有没有其他比较合适的参数，或是其他方法解决这个问题

**Comment by liu824** [comment]
我尝试过如下设置：
MODEL:
name: "BMN"
tscale: 443
dscale: 100
feat_dim: 1024
prop_boundary_ratio: 0.5
num_sample: 32
num_sample_perbin: 3
anno_file: "train.json"
feat_path: 'work/train/videofeature'
同时把batch_size设置为1，但在aistudio上仍然内存溢出。我认为我剩下只能减少action最大时长dscale,您有没有其他比较合适的参数？或是其他方法解决这个问题？

**Comment by huangjun12** [comment]
sample_mask矩阵比较占内存
https://github.com/PaddlePaddle/models/blob/b87761f8100a545e0015046dd55d886ce90c190e/PaddleCV/video/models/bmn/bmn_net.py#L248
可以将num_sample调小试试

**Comment by liu824** [comment]
我现在只能根据论文来推测参数含义，有没有这些参数的说明文档？

**Comment by huangjun12** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/22365664/86124095-205a9e00-bb0d-11ea-99be-40923702254a.png">
后面会添加到代码注释中

**Comment by liu824** [comment]
很抱歉再次打扰您，当我解决了参数量过大的问题之后，我又遇到了下面的问题;
[INFO: eval.py:  152]: Namespace(batch_size=None, config='models-1.6/PaddleCV/PaddleVideo/configs/bmn.yaml', log_interval=1, model_name='BMN', save_dir='data/evaluate_results', use_gpu=True, weights='')
[INFO: config_utils.py:   70]: ----------------  Test Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:433
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:1024
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:16
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:train.json
[INFO: config_utils.py:   74]:     feat_path:work/train/videofeature
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:8
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W0630 20:47:18.624218   332 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0630 20:47:18.627657   332 device_context.cc:260] device: 0, cuDNN Version: 7.3.
[INFO: eval.py:  102]: load test weights from /home/aistudio/.paddle/weights/BMN_final.pdparams
Traceback (most recent call last):
  File "models-1.6/PaddleCV/PaddleVideo/eval.py", line 154, in <module>
    test(args)
  File "models-1.6/PaddleCV/PaddleVideo/eval.py", line 105, in test
    fluid.default_main_program(), place)
  File "/home/aistudio/models-1.6/PaddleCV/PaddleVideo/models/model.py", line 152, in load_test_weights
    fluid.io.load_params(exe, '', main_program=prog, filename=weights)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 819, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((433, 692800)), while the loaded parameter (namely [ sample_mask ]) has a shape of  ((100, 320000)).
我的配置文件如下（其他没变）：
MODEL:
    name: "BMN"
    tscale: 433
    dscale: 100
    feat_dim: 1024
    prop_boundary_ratio: 0.5
    num_sample: 16
    num_sample_perbin: 3
    anno_file: "train.json"
    feat_path: 'work/train/videofeature'

**Comment by liu824** [comment]
您好，我提取的特征tscale不一致，在您的模型中是如何处理特征形状不一致的，通过填充0吗？

**Comment by huangjun12** [comment]
> 您好，我提取的特征tscale不一致，在您的模型中是如何处理特征形状不一致的，通过填充0吗？

一般会resize到定长

**Comment by liu824** [comment]
好的，谢谢

**Comment by liu824** [comment]
您好，关于bmn模型的输入特征resize之后，是否相应的label也要改变呢？

**Comment by PromiseXu1** [comment]
@liu824 请问你使用自己的特征进行训练，是用TSN提取的双流特征吗？我现在也需要用BMN来推断，但是输入特征提取这块卡了好久了
