### ISSUE TITLE
时间序列预测设备故障

### ISSUE THREAD

**Issue by mmmahhhhe** [PaddlePaddle/models#4727]

**Comment by mmmahhhhe** [comment]
### 1月4号损坏，原因"a"，数据如下
|设备名|时间|温度|压力|电流|
|-|-|-|-|-|
|设备1|01-01|10|50|100|
|设备1|01-02|11|51|101|
|设备1|01-03|12|52|102|


---
### 2月6号损坏，原因"b"，数据如下
|设备名|时间|温度|压力|电流|
|-|-|-|-|-|
|设备2|02-01|10|50|100|
|设备2|02-02|11|51|101|
|设备2|02-03|12|52|102|
|设备2|02-04|12|52|102|
|设备2|02-05|12|52|102|

**Comment by phlrain** [comment]
建议使用下序列标注相关的模型，可以参考这个的实现方式
https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis

**Comment by mmmahhhhe** [comment]
主要对于数据的形式怎么构建不太清楚，这种属性值的话需要变成`[batch_size, seq_len, embedding]`这样吗，`seq_len`可以是温度压力电影为3，`batch_size`随便设一个，`embedding`是随便设一个比较大的值吗，主要是这个怎么实现提前预警的问题，就是在没有x的情况下预测未来的y
