### ISSUE TITLE
GAN有继续训练的方法吗？

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/models#4729]
用了下面的代码开始训练
```python
%cd /home/aistudio/gan
!python train.py \
  --model_net="CycleGAN" \
  --dataset="vangogh2photo" \
  --data_dir="data" \
  --epoch=100 \
  --batch_size=14
```
最后checkpoints存了第100次的参数，但是效果不太好。我把前面99次存的都删掉后想继续训练，不过找不到相关的参数设置...

**Comment by ceci3** [comment]
可以通过设置 --init_model 这个参数加载预训练模型

**Comment by shaunhurryup** [comment]
> 可以通过设置 --init_model 这个参数加载预训练模型

感谢！我之前也是用这个参数但是报了奇怪的错误现在也忘记了。
不过能训练了就行哈哈
