### ISSUE TITLE
ERNIE_PRETRAIN  in the `run_ernie.sh` for sentiment classification & expected dimensions

### ISSUE THREAD

**Issue by andreazanetti** [PaddlePaddle/models#4744]
On develop branch, the path to ERNIE_PRETRAIN 
in the `run_ernie.sh` for sentiment classification does not seem to be correct. 
(PaddleNLP/sentiment_classification)
It should be `ERNIE_PRETRAIN=./models/senta_model/ernie_pretrain_model/` and not only `./ernie_pretrain_model/ `as it is in the `run_ernie.sh`.
However, even changing it, if launch `./run_ernie.sh train` I get the following:

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The fed Variable src_ids should have dimensions = 3, shape = [-1, 256, 1], but received fed shape [4, 191, 1]

  [Hint: Expected DimensionIsCompatibleWith(shapes[i], in_dims) == true, but received DimensionIsCompatibleWith(shapes[i], in_dims):0 != true:1.] at (/data/azanetti/Paddle/paddle/fluid/operators/reader/read_op.cc:137)

  [operator < read > error]

Full log here:
[loglog.txt](https://github.com/PaddlePaddle/models/files/4886982/loglog.txt)

**Comment by lidanqing-vv** [comment]
@luotao1 麻烦看一下这个问题，谢谢！

**Comment by juncaipeng** [comment]
好的，联系了ernie负责同学来看下。

**Comment by GaoWei8** [comment]
@xfcygaocan. 帮忙看下这个问题。

**Comment by andreazanetti** [comment]
Very low priority at the moment. Will re-open it or create a new one if this returns to be relevant. Thanks

**Comment by GaoWei8** [comment]
The designer @ChinaLiuHao already found the errors.
