### ISSUE TITLE
lookup_tablev2 and lookup_table difference

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/models#4746]
The Lac GRU model generated by [this page](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis) use lookup_tablev2, and it has 3 dimension output. While using lookup_table (v1) will have 2 dimension output. We think 2 dimension is more reasonable because it will be used as input of fc 

Also the code is changed by this PR https://github.com/PaddlePaddle/models/pull/3823/files, we doubt if it is intended to use lookup_tablev2?

`word_embedding = fluid.layers.embedding` 
was changed to
`word_embedding = fluid.embedding`

**Comment by lidanqing-vv** [comment]
@luotao1

**Comment by juncaipeng** [comment]
@Bond-H

**Comment by Bond-H** [comment]
such is this case,  the shape of input words should be change to ` [None]` while using  lookup_tablev2 @1024er https://github.com/PaddlePaddle/models/blob/b87761f8100a545e0015046dd55d886ce90c190e/PaddleNLP/lexical_analysis/creator.py#L38

> it will be used as input of fc

noticed that the output's dimension is 2 of the fc layers even with the input of 3 dimension,  same as using lookup_tablev1, so the model still works well

**Comment by lidanqing-vv** [comment]
Solved
