### ISSUE TITLE
代码死链问题反馈

### ISSUE THREAD

**Issue by PearLion** [PaddlePaddle/models#4748]
“Enhancing Local Feature Extraction with Global Representation for Neural Text Classification”

请问这篇文章提供的code路径不对呀，没有找到在哪里，可否提供一下呢？感激不尽！

**Comment by mapingshuo** [comment]
你好，这篇文章里提供的是什么code路径？

**Comment by mapingshuo** [comment]
经过查看论文，旧链接为：“Our code will be available at https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/Research/EMNLP2019-GELE. “GELE” is the abbreviation for Global Encoder and Local Encoder, i.e., Encoder1 and Encoder2 respectively.”

**Comment by PearLion** [comment]
> 经过查看论文，旧链接为：“Our code will be available at https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/Research/EMNLP2019-GELE. “GELE” is the abbreviation for Global Encoder and Local Encoder, i.e., Encoder1 and Encoder2 respectively.”

很抱歉麻烦您了，但是这个链接我打不开，显示404，找了Research下其他文件都没有找到，您能打开这个链接吗？

**Comment by mapingshuo** [comment]
> > 经过查看论文，旧链接为：“Our code will be available at https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/Research/EMNLP2019-GELE. “GELE” is the abbreviation for Global Encoder and Local Encoder, i.e., Encoder1 and Encoder2 respectively.”
> 
> 很抱歉麻烦您了，但是这个链接我打不开，显示404，找了Research下其他文件都没有找到，您能打开这个链接吗？
我打不开，正在联络作者

**Comment by mapingshuo** [comment]
请直接邮件联络作者吧：niuguocheng@baidu.com
