### ISSUE TITLE
问题修复：PaddleCV/gan/data_reader.py

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/models#4769]
我在开始训练CycleGAN模型时项目报错，错误信息为：
> FileNotFoundError: [Errno 2] No such file or directory: 'data/vangogh2photo/trainB/2015-05-18'

后来发现在 [data_reader.py](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/gan/data_reader.py#L114) 中对文件名分割错误导致的。

在 `trainB` 文件中，图片的格式为 **日期+时间** ，例如 **2016-01-20 08:00:45.jpg**，但是通过 `line = line.strip('\n\r\t').split(' ')` 代码分割后，日期和时间被作为列表中两个独立的元素，在后来的 `img = Image.open(os.path.join(self.image_dir, file)).convert(` 代码中直接相连，导致无法找到图片。

### 解决方案：
将line = line.strip('\n\r\t').split(' ')
替换成line = line.strip('\n\r\t').split('\t')

### 希望能早日修复

**Comment by kuke** [comment]
一般文件命名不建议加空格，容易带来各种潜在的麻烦

**Comment by shaunhurryup** [comment]
> 一般文件命名不建议加空格，容易带来各种潜在的麻烦

文件是从 `download.py` 中下载来的，没法改变。但是代码部分的 `split(" ")` 如果没有空格，那么生成的line列表也只有1个元素，后面的 line[1] 也显得没有必要了
