### ISSUE TITLE
AssertionError: Parameter file [pretrain_model/ResNet50_pretrained/.pdparams] not exits

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4774]
在训练度量学习模型时，不使用ResNet50的预训练模型的话可以正常训练，如果使用的话就报如下错误：
![image](https://user-images.githubusercontent.com/13143336/88768229-5a22d100-d1ad-11ea-9968-32c772bc23a8.png)
麻烦帮忙看一下，多谢

**Comment by fffyyy415** [comment]
同问     在使用similarity_net，用自己训练好的模型预测也出现同样的情况

**Comment by Superjomn** [comment]
描述下自己的模型，paddle 的版本，使用静态图还是动态图，预训练模型的情况

多提供一些信息吧

**Comment by endy-see** [comment]
> 描述下自己的模型，paddle 的版本，使用静态图还是动态图，预训练模型的情况
> 
> 多提供一些信息吧

没有我自己的模型，我只是从https://paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html
上下载ResNet50的预训练模型，paddle版本1.8（是从release上直接下载的代码），具体动态图还是静态图这个该怎么看？目前还没能训练起来，只要一启动训练就报加载预训练模型出错的问题
![image](https://user-images.githubusercontent.com/13143336/88892612-a0dcfd80-d277-11ea-91b8-cbf7c21b1795.png)

**Comment by littletomatodonkey** [comment]
> > 描述下自己的模型，paddle 的版本，使用静态图还是动态图，预训练模型的情况
> > 多提供一些信息吧
> 
> 没有我自己的模型，我只是从https://paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html
> 上下载ResNet50的预训练模型，paddle版本1.8（是从release上直接下载的代码），具体动态图还是静态图这个该怎么看？目前还没能训练起来，只要一启动训练就报加载预训练模型出错的问题
> ![image](https://user-images.githubusercontent.com/13143336/88892612-a0dcfd80-d277-11ea-91b8-cbf7c21b1795.png)

你好，可以看下pretrain_model/ResNet50_pretrained这个文件夹下有什么内容吗?下载的预训练模型在这里吗？

**Comment by a123b12cd** [comment]
同现象，求解

**Comment by endy-see** [comment]
> > > 描述下自己的模型，paddle 的版本，使用静态图还是动态图，预训练模型的情况
> > > 多提供一些信息吧
> > 
> > 
> > 没有我自己的模型，我只是从https://paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html
> > 上下载ResNet50的预训练模型，paddle版本1.8（是从release上直接下载的代码），具体动态图还是静态图这个该怎么看？目前还没能训练起来，只要一启动训练就报加载预训练模型出错的问题
> > ![image](https://user-images.githubusercontent.com/13143336/88892612-a0dcfd80-d277-11ea-91b8-cbf7c21b1795.png)
> 
> 你好，可以看下pretrain_model/ResNet50_pretrained这个文件夹下有什么内容吗?下载的预训练模型在这里吗？

额，里面的文件很多，但确实是没有pdparam那个文件，我下载模型的地址：https://paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html
你可以自己下载一个呀。。

**Comment by littletomatodonkey** [comment]
好的， 这个是模型加载的问题，感谢你的反馈，我们修复下~

**Comment by endy-see** [comment]
> 好的， 这个是模型加载的问题，感谢你的反馈，我们修复下~

好的

**Comment by littletomatodonkey** [comment]
> > 好的， 这个是模型加载的问题，感谢你的反馈，我们修复下~
> 
> 好的

你好，你升级下Paddle版本试下呢？我这边在paddle >= 1.7.0的情况下，没有复现你的问题，padddle版本可以通过以下方法查看
![image](https://user-images.githubusercontent.com/14270174/88906437-05a15380-d28a-11ea-984a-797acbdc474e.png)

**Comment by yanmeizhao** [comment]
> > > 好的， 这个是模型加载的问题，感谢你的反馈，我们修复下~
> > 
> > 
> > 好的
> 
> 你好，你升级下Paddle版本试下呢？我这边在paddle >= 1.7.0的情况下，没有复现你的问题，padddle版本可以通过以下方法查看
> ![image](https://user-images.githubusercontent.com/14270174/88906437-05a15380-d28a-11ea-984a-797acbdc474e.png)

我的paddle版本是1.6的，1.6到1.7版本差异很大么

**Comment by endy-see** [comment]
> > > 好的， 这个是模型加载的问题，感谢你的反馈，我们修复下~
> > 
> > 
> > 好的
> 
> 你好，你升级下Paddle版本试下呢？我这边在paddle >= 1.7.0的情况下，没有复现你的问题，padddle版本可以通过以下方法查看
> ![image](https://user-images.githubusercontent.com/14270174/88906437-05a15380-d28a-11ea-984a-797acbdc474e.png)

paddle版本升级到1.8以后又出现下面问题：
![image](https://user-images.githubusercontent.com/13143336/88914076-a72da280-d294-11ea-9fb3-a5ce0937e96c.png)
![image](https://user-images.githubusercontent.com/13143336/88914193-d512e700-d294-11ea-983c-76e5d4a97b47.png)

**Comment by littletomatodonkey** [comment]
这个需要清除下当前文件夹下的pyc文件（python生成的临时文件）：
```
find ./* -name "*.pyc"  | xargs rm
```

**Comment by endy-see** [comment]
> 这个需要清除下当前文件夹下的pyc文件（python生成的临时文件）：
> 
> ```
> find ./* -name "*.pyc"  | xargs rm
> ```

感谢，现在情况是能训练了，但是会出警告，这个会印象模型训练的结果么？警告如下：
![image](https://user-images.githubusercontent.com/13143336/88919591-f2987e80-d29d-11ea-9b53-256b17e76f5b.png)

**Comment by littletomatodonkey** [comment]
这个不会，在paddle1.7以后，我们统一了文件保存和加载的方式(都是以*.pdparams形式保存)，之前是零散的小文件，加载的时候 会先去找pdparams文件，如果找不到的话，就会尝试以加载零散文件的方式去加载模型（上面第一个警告），在这里因为fc的维度与分类预训练模型不同，所以fc参数是没有加载的（上面第二个警告），因此不会影响训练的

**Comment by endy-see** [comment]
> 这个不会，在paddle1.7以后，我们统一了文件保存和加载的方式(都是以*.pdparams形式保存)，之前是零散的小文件，加载的时候 会先去找pdparams文件，如果找不到的话，就会尝试以加载零散文件的方式去加载模型（上面第一个警告），在这里因为fc的维度与分类预训练模型不同，所以fc参数是没有加载的（上面第二个警告），因此不会影响训练的

好的，多谢
