### ISSUE TITLE
Pix2Pix Paddle1.8下C++推断报错

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/models#4785]
Paddle1.8下，Pix2Pix使用C++进行预测，使用AnalysisConfig和NativeConfig来CreatePaddlePredictor，均报错如下：

![image](https://user-images.githubusercontent.com/7035538/89271357-2ba26b80-d66f-11ea-9e32-17f3ba14f0d2.png)

请问怎么解决，能给个GAN C++推断的例子参考下吗，谢谢

**Comment by A1exy** [comment]
Paddle 1.8的C++库调用过检测、分类、分割均没问题，所以初步排除C++ Paddle库的问题。

**Comment by jerrywgz** [comment]
可以给下复现样例吗，我们这边排查下问题

**Comment by A1exy** [comment]
@jerrywgz 直接拿Pix2Pix训练出的模型，用C++做Inference就会报错，你这边可以试试。我是在paddle 1.8下弄的

**Comment by jerrywgz** [comment]
可以提供下c++ inference的复现代码吗，可以先尽快解决下你的问题，后续gan的c++预测示例我们会再跟进下
