### ISSUE TITLE
AI Studio环境CUDA出错

### ISSUE THREAD

**Issue by hlzonWang** [PaddlePaddle/models#4802]
训练的模型是SimNet，无任何改动，报下面错误

ExternalError:  Cuda error(38), no CUDA-capable device is detected.
  [Advise: This indicates that no CUDA-capable devices were detected by the installed CUDA driver. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

**Comment by MRXLT** [comment]
你好，看报错信息应该与机器环境有关，请检查一下机器上是否有nvidia gpu以及显卡驱动是否正常
