### ISSUE TITLE
metric learning中的eml loss指的是什么loss？

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4807]
请问metric learning中的eml loss指的是什么loss？有对应的论文推荐嘛？

**Comment by shippingwang** [comment]
一个代价损失函数，用来进行微调～可以google看下相关文章～

**Comment by endy-see** [comment]
> 一个代价损失函数，用来进行微调～可以google看下相关文章～

eml是指Estimated Maximum Loss 这个嘛？

**Comment by littletomatodonkey** [comment]
你好，eml loss是这篇论文：[Large Scale Strongly Supervised Ensemble Metric Learning, with Applications to Face Verification and Retrieval](https://arxiv.org/pdf/1212.6094.pdf)

repo里面也有参考文献的~https://github.com/PaddlePaddle/models/blob/release%2F1.8/PaddleCV/metric_learning/README_cn.md

**Comment by endy-see** [comment]
> 你好，eml loss是这篇论文：[Large Scale Strongly Supervised Ensemble Metric Learning, with Applications to Face Verification and Retrieval](https://arxiv.org/pdf/1212.6094.pdf)
> 
> repo里面也有参考文献的~https://github.com/PaddlePaddle/models/blob/release%2F1.8/PaddleCV/metric_learning/README_cn.md

多谢！
