### ISSUE TITLE
静态图单机多卡训练

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/models#4839]
请教大佬，静态图训练时如何进行单机多卡训练。

**Comment by ForFishes** [comment]
参考：https://github.com/PaddlePaddle/FleetX
可以讲单卡程序改成多卡程序。

**Comment by zhudibo** [comment]
好的，谢谢大佬



---原始邮件---
发件人: "ShenLiang"<notifications@github.com&gt;
发送时间: 2020年9月9日(周三) 下午3:21
收件人: "PaddlePaddle/models"<models@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/models] 静态图单机多卡训练 (#4839)




 
参考：https://github.com/PaddlePaddle/FleetX
 可以讲单卡程序改成多卡程序。
