### ISSUE TITLE
训练小尺寸的分类,比如  3,32,32  这种小图片,程序是否会出错,

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/models#4840]
训练小尺寸的分类,比如  3,32,32  这种小图片,程序是否会出错,
因为我看默认的 crop是 224  不知道在哪里修改或者说 要是训练3.32.32的分类器(小于224) 是不是有一些参数是要修改的 ?
因为我按照默认参数训练了一次是不成功的

**Comment by ForFishes** [comment]
裁剪的代码在这个位置
https://github.com/PaddlePaddle/models/blob/d27cfec8f4033fc72890cd051eef52d593af66ba/PaddleCV/image_classification/reader.py#L55
模型的输入大小也需要修改：
https://github.com/PaddlePaddle/models/blob/1bf7264771fb30b588c426e9c153f9b643256971/PaddleCV/image_classification/legacy/models/resnet.py#L24

**Comment by zjutlzt** [comment]
谢了
