### ISSUE TITLE
PaddleCV/human_pose_estimation test.py代码中的一些问题

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/models#4859]
操作系统: win10
python版本: 3.6.10
问题文件: https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/human_pose_estimation/lib/mpii_reader.py
问题描述:
human_pose_estimation使用mpii数据集test的时候一直没有运行结果。在问题文件186行
`fold = ‘test’`
修改为
`fold = cfg.DATAROOT + '/' + cfg.IMAGEDIR + '/test'`
之后可以运行，因为下一行os.listdir(fold)读取的路径不对，一直没读取到文件。

**Comment by wangxicoding** [comment]
感谢反馈。方便提个PR吗，我叫相关负责人review下

**Comment by a2824256** [comment]
好的

**Comment by a2824256** [comment]
pr已提交
https://github.com/PaddlePaddle/models/pull/4860
