### ISSUE TITLE
从字符串，直接进行推理问题

### ISSUE THREAD

**Issue by LeeYongchao** [PaddlePaddle/models#4863]
官方使用run_ernie_sequence_labeling.py 文件进行推理，发现推理过程是从硬盘读取数据，并封装成数据迭代器实现的，
请问有没有 可以直接从内存上把字符串接过来，直接进行推理呢？

我在内存中的字符串是列表格式的 ['字符串1' ,'字符串2', '字符串3']， 想直接进行推理，分词并返回词性标注，

谢谢！！

**Comment by gongweibao** [comment]
内存的数据是从哪里来的？
如果需要，可以使用paddle serving 直接使用rpc进行推理。
