### ISSUE TITLE
How to train a pascal voc based SSD model from the very beginning without pretrained model?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/models#488]
I did not use the pretrained model and want to train a new model from initialized parameters but I got the Floating point exception (core dumped) error. What should I do.
![image](https://user-images.githubusercontent.com/13977118/33161379-3f365afe-d05e-11e7-9b74-4690804f4f74.png)

**Comment by QiJune** [comment]
@pkuyym Please kindly help look this. Thanks

**Comment by pkuyym** [comment]
The ssd demo have been updated by #491. Please try the new project.

**Comment by wangkuiyi** [comment]
Given that there has not been any update on this issue after @pkuyym pasted a solution, I am closing it.
