### ISSUE TITLE
BMN模型推理出现错误

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/models#4881]
使用BMN模型推理动作识别，输入命令后出现错误
python predict.py --model_name=BMN --config=./configs/bmn.yaml --log_interval=1 --weights=./models/bmn/BMN.pdparams --filelist=./data/dataset/bmn/infer.list --use_gpu=False
出现错误提示：
Optimizer file [./models/bmn/BMN.pdopt] not exits。
请问是怎么回事？

**Comment by huangjun12** [comment]
weights=./models/bmn/BMN 不用写pdparams后缀

**Comment by upenggod** [comment]
> weights=./models/bmn/BMN 不用写pdparams后缀

Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 126, in infer
    args.weights), "Given weight dir {} not exist.".format(args.weights)
AssertionError: Given weight dir ./models/bmn/BMN not exist.
不加后缀又提示上面的错误

**Comment by upenggod** [comment]
python predict.py --model_name=BMN --config=./configs/bmn.yaml --log_interval=1 --weights=./models/bmn/BMN --filelist=./data/dataset/bmn/infer.list --use_gpu=False


> weights=./models/bmn/BMN 不用写pdparams后缀

**Comment by upenggod** [comment]
python predict.py --model_name=BMN --config=./configs/bmn.yaml --log_interval=1 --use_gpu=False会自动下载BMN.pdparams文件，但还是会提示AssertionError: Optimizer file [C:\Users\25310\.paddle\weights\BMN.pdopt] not exits

**Comment by upenggod** [comment]
工程师大佬们能看看吗？

**Comment by huangjun12** [comment]
> > weights=./models/bmn/BMN 不用写pdparams后缀
> 
> Traceback (most recent call last):
> File "predict.py", line 200, in 
> infer(args)
> File "predict.py", line 126, in infer
> args.weights), "Given weight dir {} not exist.".format(args.weights)
> AssertionError: Given weight dir ./models/bmn/BMN not exist.
> 不加后缀又提示上面的错误

可以先把https://github.com/PaddlePaddle/models/blob/f80b766295e4c686d3d6d00858656d8239cea87f/PaddleCV/video/predict.py#L125  这两行的检查先注释掉，然后用weights=./models/bmn/BMN 这种格式启动即可~

**Comment by upenggod** [comment]
#    if args.weights:
#        assert os.path.exists(
#            args.weights), "Given weight dir {} not exist.".format(args.weights)
注释了，错误依然出现

**Comment by upenggod** [comment]
AssertionError: Optimizer file [./models/bmn/BMN.pdopt] not exits

**Comment by thuansb** [comment]
I also facing same issue, please help

**Comment by huangjun12** [comment]
we recommend to use our new repo: https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/model_zoo/localization/bmn.md
