### ISSUE TITLE
language model 里面的模型定义文件怎么找不到

### ISSUE THREAD

**Issue by peterzsj6** [PaddlePaddle/models#4898]
.
├── README.md            # 文档
├── run.sh               # 启动脚本
├── train.py             # 训练代码
├── reader.py            # 数据读取
├── args.py              # 参数读取
└── data                 # 数据下载
../
└── models
    └── language_model
        └── lm_model.py  # 模型定义文件

如上所示的位置并没有找到这个文件

**Comment by lijianshe02** [comment]
现在模型定义文件在下面目录：
![image](https://user-images.githubusercontent.com/48898730/95699007-f3726700-0c75-11eb-96d3-da7278860fac.png)

**Comment by peterzsj6** [comment]
> 现在模型定义文件在下面目录：
> ![image](https://user-images.githubusercontent.com/48898730/95699007-f3726700-0c75-11eb-96d3-da7278860fac.png)

找到了！谢谢
