### ISSUE TITLE
the issue when use the sentiment_classification to paddlelite

### ISSUE THREAD

**Issue by burness** [PaddlePaddle/models#4908]
I use the `sentiment_classification` in my project. It's ok to train, but when I transform it to paddlelite. It seems that the 'sequence_unpad' is not support in th arm platform.
![image](https://user-images.githubusercontent.com/3112825/96208072-4e220080-0f9f-11eb-9fd7-322c83f2c22b.png)

So I want to change the code here [cnn_net](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/shared_modules/models/classification/nets.py#L55)
remove the `sequence_unpad`, and use the [max_seq_len, dim] to be the emb,  but I can't use the `sequence_conv_pool`.
How can I use some conv function here ?

By the way, `sequence_unpad` is not supported in paddle lite, could anyone help implement a version with paddle lite ?

**Comment by zhupengyang** [comment]
- `sequence_pad` is not supported in Paddle-Lite. You may submit a new issue in [Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite) to feedback you probloms(`sequence_pad`). 
- Reference [sequence_conv](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_conv_cn.html#sequence-conv) and [sequence_pool](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pool_cn.html#sequence-pool)

**Comment by burness** [comment]
Yes, I use the `simple_img_conv_pool` instead of `sequence_unpad` to do conv1d.
