### ISSUE TITLE
Seq2Seq 模型库案例里的reader案例为啥给 target language ID加上【1】，【2】

### ISSUE THREAD

**Issue by peterzsj6** [PaddlePaddle/models#4910]
Seq2Seq 模型库案例里的reader 有几个看不懂的地方求助。

> def read_all_line(filenam):
> 
>   data = []
> 
>   with io.open(filename, "r", encoding='utf-8') as f:
> 
>   for line in f.readlines():
> 
>   data.append(line.strip())

filename 好像写错了。

且在 para file to id 中：

def _para_file_to_ids(src_file, tar_file, src_vocab, tar_vocab):

 

  src_data = []

  with io.open(src_file, "r", encoding='utf-8') as f_src:

    for line in f_src.readlines():

    arra = line.strip().split()

    ids = [src_vocab[w] if w in src_vocab else UNK_ID for w in arra]

    ids = ids

 

    src_data.append(ids)

 

  tar_data = []

 with io.open(tar_file, "r", encoding='utf-8') as f_tar:

   for line in f_tar.readlines():

   arra = line.strip().split()

   ids = [tar_vocab[w] if w in tar_vocab else UNK_ID for w in arra]

 

   ids = [1] + ids + [2]

 

   tar_data.append(ids)

 

 return src_data, tar_data

**tar_data的ids=[1]+ ids+[2]**

这里的1和2是什么意思啊，1 和2 不是已经在_build_vocab里分给了两个词了吗

github连接：https://github.com/PaddlePaddle/models/blob/release/1.8/dygraph/seq2seq/reader.py

**Comment by willthefrog** [comment]
@guoshengCS  能否辛苦回答下。

**Comment by peterzsj6** [comment]
> @guoshengCS 能否辛苦回答下。

不好意思，眼拙没看到beam search那里把1和2吃掉了。 不过也算报告下typo把。还有我在paddlepaddle 训练的seq2seq 好像在同超参下对较长sequence效果一般。（我做的是一个字母串倒叙的demo对比）

**Comment by guoshengCS** [comment]
感谢指出~  较长sequence效果一般是否是因为这里的实现没有添加length penalty的处理呢

**Comment by peterzsj6** [comment]
> 感谢指出~ 较长sequence效果一般是否是因为这里的实现没有添加length penalty的处理呢

应该不是，我做的是等长的两个序列倒序在不同框架上的对比。我把beam search去掉了，因为我在其他框架上的seq2seq也都没用beam search。
