### ISSUE TITLE
我在用自己数据集调试video tag的attention lstm模型时遇到点问题...

### ISSUE THREAD

**Issue by dl-lengyan** [PaddlePaddle/models#4962]
我的数据集有8类，也就是8个标签，我想利用你们开源的模型进行预训练，当我把configs/attention_lstm-single.yaml中MODEL下面的num_classes改成8的时候，报错如下：
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((4096, 8)), while the loaded parameter (namely [ output.w_0 ]) has a shape of  ((4096, 3396)).
如果不使用预训练模型，可以跑完训练。请问我想是用你们的预训练模型的话，怎么解决？

**Comment by huangjun12** [comment]
这个参数shape跟类别数有关，可以在加载预训练的时候不加载这个参数。 https://github.com/PaddlePaddle/models/blob/bdacb35542323f72beccde40572a33dd705bd6bb/PaddleCV/video/application/video_tag/models/attention_lstm/attention_lstm.py#L170  这个判断条件里 将output.w_0 和 output.b_0 加上，如下
```
if "fc_0" in name or name == "output.w_0" or name == "output.b_0":
    del xxx
```

**Comment by dl-lengyan** [comment]
谢啦，解决啦
