### ISSUE TITLE
paddlecv/yolov3模型

### ISSUE THREAD

**Issue by B18090229** [PaddlePaddle/models#4966]
paddlecv/yolov3模型是每次需要预测的时候都要重新训练吗？不能够再训练后保存模型，预测的时候直接用吗？

Does the Paddlecv/Yolov3 model have to be retrained every time it needs to be predicted? Can't it save the model after training and use it directly for prediction?

**Comment by qingqing01** [comment]
@B18090229  一般都是可以保存模型，预测时直接用的。 另外 paddlecv/yolov3 这个路径已经不存在。您可以用 PaddleDetection中的YOLOv3 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/docs/MODEL_ZOO_cn.md#yolo-v3
