### ISSUE TITLE
PaddleNLP情感分析infer结果每次都不一致

### ISSUE THREAD

**Issue by KaiyuanGao** [PaddlePaddle/models#4967]
paddle版本：1.8.3
python版本：3.7.1

按照[Readme](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/sentiment_classification) 下载ernie预训练模型与数据进行infer，可以成功运行，同一份测试数据但每次infer的结果不一致，请问是什么问题？
![image](https://user-images.githubusercontent.com/33422503/99939683-9655ef00-2da5-11eb-8e9c-f50d1d39c515.png)
![image](https://user-images.githubusercontent.com/33422503/99939694-99e97600-2da5-11eb-8655-caf313631877.png)

**Comment by qili93** [comment]
需要确认下“同一份测试数据”是否每次inference的时候是在其中取的不同的batch呢？还是每次输入数据都是一致的？

建议可以先用全1输入试试看，如果连全1输入的结果都每次不一样，那就是有问题的。如果每次全1输入的预测结果都一致，那需要看下是否每次预测其实取的是一个数据集中的不同的测试数据。

**Comment by KaiyuanGao** [comment]
> 需要确认下“同一份测试数据”是否每次inference的时候是在其中取的不同的batch呢？还是每次输入数据都是一致的？
> 
> 建议可以先用全1输入试试看，如果连全1输入的结果都每次不一样，那就是有问题的。如果每次全1输入的预测结果都一致，那需要看下是否每次预测其实取的是一个数据集中的不同的测试数据。

试过了，不是这个问题。另外，infer里面shuffle设置的是False，不会出现不同batch问题。

您是官方人员吗？麻烦复现一下看看会不会出现同样的问题，谢谢！

**Comment by Steffy-zxf** [comment]
你好！没能复现你的问题。我这边 同一份数据infer，预测结果都是一样的。请确认下参数`init_checkpoint`是否设置相同。

**Comment by KaiyuanGao** [comment]
@Steffy-zxf 你好，`init_checkpoint` 是用的官网提供的预训练模型
> wget https://baidu-nlp.bj.bcebos.com/sentiment_classification-1.0.0.tar.gz

你也是这份模型吗？
代码没是直接clone的代码库没改，预测脚本：
```
ERNIE_PRETRAIN=./models/senta_model/ernie_pretrain_model/

# run_infer
infer() {
    python -u run_ernie_classifier.py \
        --use_cuda false \
        --verbose true \
        --do_train false \
        --do_val false \
        --do_infer true \
        --use_paddle_hub false \
        --batch_size 4 \
        --init_checkpoint $ERNIE_PRETRAIN/params \
        --test_set $DATA_PATH/test.tsv \
        --vocab_path $ERNIE_PRETRAIN/vocab.txt \
        --max_seq_len 256 \
        --ernie_config_path $ERNIE_PRETRAIN/ernie_config.json \
        --model_type "ernie_base" \
        --num_labels 2
}
```

**Comment by Steffy-zxf** [comment]
你好！预测的时候，`init_checkpoint`需要使用的是fine-tune之后保存的参数路径。即，先将 用 官方提供的 预训练模型参数`wget https://baidu-nlp.bj.bcebos.com/sentiment_classification-1.0.0.tar.gz` 在文本分类数据集上fine-tune，保存fine-tune后的模型参数。之后再使用fine-tune后的模型参数进行预测。

**Comment by KaiyuanGao** [comment]
已解决，谢谢！
