### ISSUE TITLE
使用ETS模型时，如何使用自己的视频来准备数据集

### ISSUE THREAD

**Issue by mc261670164** [PaddlePaddle/models#4968]
您好，
      我想请教一下，在跑ETS模型时，如何将自己的视频数据生成ETS模型能够使用的数据集？谢谢！

**Comment by mc261670164** [comment]
有没有相应的脚本能够自动生成ETS模型可用的数据？

**Comment by qili93** [comment]
建议到Paddle/models repo下提问，谢谢！
https://github.com/PaddlePaddle/models

**Comment by qili93** [comment]
请参照这个readme进行数据转换
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/video/data/dataset/README.md
