### ISSUE TITLE
Do I need to convert the video to the pickle format when I use the TSN net?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/models#4969]
Hi,

I would like to train and predict the TSN net. I would like to know do I need to convert the .mp4 video to the pickle format? 

It seems that the training and evaluation need the pickle format, and the prediction needs the mp4 video?

Many thanks.

**Comment by qili93** [comment]
Please follow the readme here to change the video to the pickle format 
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/video/data/dataset/README.md

The convert script here: https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/video/data/dataset/youtube8m/tf2pkl.py
