### ISSUE TITLE
PaddlePaddleNLP issue

### ISSUE THREAD

**Issue by FYF1997** [PaddlePaddle/models#4981]
How to use the underlying model of the model to train their own data and predict, but only need to label proper terms.
In addition, can incremental training be continued on the basis of the underlying model?model is   https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis。  Thanks！

**Comment by gongweibao** [comment]
Thanks! The author will reply sooner.

**Comment by kinghuin** [comment]
Hi, 

you can organize your data into the structures : https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F
the dataset demo can be see in https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
then modify the `train_data`, `test_data `, `word_dict_path`, `label_dict_path `, `word_rep_dict_path ` to your real path in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10

yes, you can incremental training by setting `--init_checkpoint`, it will load the model in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90

BTW, The LAC model will be upgrade in Dec.20 which is easier to use, welcome to use!

**Comment by FYF1997** [comment]
> Hi,
> 
> you can organize your data into the structures : https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F
> the dataset demo can be see in https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
> then modify the `train_data`, `test_data `, `word_dict_path`, `label_dict_path `, `word_rep_dict_path ` to your real path in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10
> 
> yes, you can incremental training by setting `--init_checkpoint`, it will load the model in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90
> 
> BTW, The LAC model will be upgrade in Dec.20 which is easier to use, welcome to use!
Thanks for your help！In addition, I would like to ask whether new proper nouns can be identified after incremental training if a new proper name tag is added during incremental training. When I conduct incremental training on the interface of Lac, I find that it can not recognize new proper nouns, so I turn to hope that I can get the results I want through the training of the underlying model. Meanwhile I‘m waitting for the better LAC！

**Comment by FYF1997** [comment]
> 你好
> 
> 您可以将数据组织到结构中：[https](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F) : [//github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%E6%A0%BC% E5％BC％8F](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)
> 数据集演示中可以看到https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
> 然后修改`train_data`，`test_data `，`word_dict_path`，`label_dict_path `，`word_rep_dict_path `在你的真实路径[的https：/ /github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10)
> 
> 是的，您可以通过设置进行增量训练`--init_checkpoint`，它将在[https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90中](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90)加载模型[](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90)
> 
> 顺便说一句，LAC模型将在12月20日进行升级，它更易于使用，欢迎使用！

**Comment by FYF1997** [comment]
> > 你好
> > 您可以将数据组织到结构中：[https](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F) : [//github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%E6%A0%BC% E5％BC％8F](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)
> > 数据集演示中可以看到https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
> > 然后修改`train_data`，`test_data `，`word_dict_path`，`label_dict_path `，`word_rep_dict_path `在你的真实路径[的https：/ /github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10)
> > 是的，您可以通过设置进行增量训练`--init_checkpoint`，它将在[https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90中](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90)加载模型
> > 顺便说一句，LAC模型将在12月20日进行升级，它更易于使用，欢迎使用！

BTW, The LAC model will be upgrade in Dec.20 which is easier to use, welcome to use!
Thanks for your help！In addition, I would like to ask whether new proper nouns can be identified after incremental training if a new proper name tag is added during incremental training. When I conduct incremental training on the interface of Lac, I find that it can not recognize new proper nouns, so I turn to hope that I can get the results I want through the training of the underlying model. Meanwhile I‘m waitting for the better LAC！

**Comment by FYF1997** [comment]
> > 你好
> > 您可以将数据组织到结构中：[https](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F) : [//github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%E6%A0%BC% E5％BC％8F](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)
> > 数据集演示中可以看到https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
> > 然后修改`train_data`，`test_data `，`word_dict_path`，`label_dict_path `，`word_rep_dict_path `在你的真实路径[的https：/ /github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10)
> > 是的，您可以通过设置进行增量训练`--init_checkpoint`，它将在[https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90中](https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90)加载模型
> > 顺便说一句，LAC模型将在12月20日进行升级，它更易于使用，欢迎使用！

Thanks for your help！In addition, I would like to ask whether new proper nouns can be identified after incremental training if a new proper name tag is added during incremental training. When I conduct incremental training on the interface of Lac, I find that it can not recognize new proper nouns, so I turn to hope that I can get the results I want through the training of the underlying model. Meanwhile I‘m waitting for the better LAC！

**Comment by kinghuin** [comment]
The new tag should be in the label vocab file, whose path is label_dict_path. You can add the tag in the end of the label vocab file before starting incremental training.
