### ISSUE TITLE
Thanks for your help！In addition, I would like to ask whether new proper nouns can be identified after incremental training if a new proper name tag is added during incremental training. When I conduct incremental training on the interface of Lac, I find that it can not recognize new proper nouns, so I turn to hope that I can get the results I want through the training of the underlying model. Meanwhile I‘m waitting for the better LAC！

### ISSUE THREAD

**Issue by FYF1997** [PaddlePaddle/models#4994]
Hi, 

you can organize your data into the structures : https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/lexical_analysis#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F
the dataset demo can be see in https://baidu-nlp.bj.bcebos.com/lexical_analysis-2.0.0.tar.gz
then modify the `train_data`, `test_data `, `word_dict_path`, `label_dict_path `, `word_rep_dict_path ` to your real path in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/run.sh#L10

yes, you can incremental training by setting `--init_checkpoint`, it will load the model in https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/lexical_analysis/train.py#L90

BTW, The LAC model will be upgrade in Dec.20 which is easier to use, welcome to use!

_Originally posted by @kinghuin in https://github.com/PaddlePaddle/models/issues/4981#issuecomment-740358928_

**Comment by ZeyuChen** [comment]
https://github.com/baidu/lac
@FYF1997 How about try this repo？

**Comment by ZeyuChen** [comment]
@FYF1997 
https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleNLP/examples/lexical_analysis
You can also compare the latest version of PaddleNLP lexical analsyis, it used dynamic graph to imlement BiGRU-CRF algorithm, maybe easy for you to finetune

**Comment by ZeyuChen** [comment]
@FYF1997 https://github.com/baidu/lac/
Try to use this repo for advance usage.
