### ISSUE TITLE
请问稳重提到的preprocess文件在哪里？

### ISSUE THREAD

**Issue by PhenixZhang** [PaddlePaddle/models#5005]
![image](https://user-images.githubusercontent.com/26118845/101714475-9f98c880-3ad4-11eb-9184-2963db2df911.png)

**Comment by phlrain** [comment]
1.8 版本对应的工具在这个目录下
https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/shared_modules/preprocess/tokenizer

**Comment by PhenixZhang** [comment]
> 1.8 版本对应的工具在这个目录下
> https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/shared_modules/preprocess/tokenizer

超级感谢！
