### ISSUE TITLE
自带的flowers下载脚本重复下载数据

### ISSUE THREAD

**Issue by bit1002lst** [PaddlePaddle/models#514]
用自带的分类脚本对flowers数据集分类时，图像压缩包总是重复下载
download后对图像进行md5校验，程序中给出的DATA_MD5和实际下载压缩包的DATA_MD5不同

**Comment by will-am** [comment]
最新版本已修复，请安装最新版本paddle：

# CPU version
pip install paddlepaddle==0.11.0
# GPU version
pip install paddlepaddle_gpu==0.11.0

**Comment by wft8108** [comment]
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
我更新到这个版本依然重复下载

**Comment by wft8108** [comment]
Cache file /Users/wanghongtao/.cache/paddle/dataset/flowers/102flowers.tgz not found, downloading http://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
[===================================================]Cache file /Users/wanghongtao/.cache/paddle/dataset/flowers/102flowers.tgz not found, downloading http://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
