### ISSUE TITLE
动态图多卡训练时 收集各梯度的函数apply_collective_grads运行出错

### ISSUE THREAD

**Issue by HawChang** [PaddlePaddle/models#5146]
系统：CentOS release 6.3
paddle版本：1.8.1.post107
python版本: python2.7

模型代码：
textcnn代码结构参数：
![image](https://user-images.githubusercontent.com/7113823/103125593-8bed8480-46c6-11eb-80c5-7ccb57446e64.png)
训练代码：
![image](https://user-images.githubusercontent.com/7113823/103125565-74ae9700-46c6-11eb-9078-adfe2fcb81d4.png)

出错信息：
![image](https://user-images.githubusercontent.com/7113823/103125644-a9bae980-46c6-11eb-9687-d826123ed5a1.png)

分析：
出错信息中 X's shape是[17964, 512]， 这个应该是embedding层的参数大小，但另一个1409024不知道具体是什么。
为此我查看了出错信息中的代码文件，发现调用paddle/fluid/dygraph/parallel.py中的apply_collective_grads时，遍历模型的参数，当遍历到embeding层时，param的形状为[17964, 512]，到该参数的g_var时，其形状为[2752,512]，恰好就是1409024。
不太明白这其中到底哪里有问题。

![image](https://user-images.githubusercontent.com/7113823/103125787-32398a00-46c7-11eb-9331-3c4266886b26.png)

当去除多卡相关的代码时，该模型和训练代码是能正常单卡训练的。

**Comment by wangchaochaohu** [comment]
你这边reshape前后的大小要一样吧 reshape之后的大小还是要 17694 * 512=9059328

**Comment by HawChang** [comment]
我没有主动做过reshape操作 这是调用apply_collective_grads出的错

**Comment by HawChang** [comment]
已解决，原因是构建textcnn时，embedding层的参数is_sparse设置成了True，梯度更新时将稀疏更新。而查看apply_collective_grads函数中时发现有如下注释：
![image](https://user-images.githubusercontent.com/7113823/103187147-44513d80-48fe-11eb-9855-3e1abfc69ad3.png)
因此猜测是梯度更新时，embedding层为稀疏更新所致。将is_sparse改为False后，代码可正常运行了。
