### ISSUE TITLE
Attention LSTM/Attention Cluster  数据初始化问题

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/models#5171]
如果不使用youtobe8m 数据，只使用Kinetics类似的MP4格式的数据集，如何做训练数据的pkl包转换？ 可否给出类似Kinetics的pkl包(video-id,[frame1, frame2,...,frameN],label)的具体说明

**Comment by liym27** [comment]
请问具体是指哪个模型呢？

**Comment by pele228** [comment]
LSTM Attention 以及Attention Cluster等默认使用youtobe8m数据集的model。

**Comment by liym27** [comment]
Paddle models repo下的哪个模型呢？

**Comment by pele228** [comment]
https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleCV/video/models/attention_lstm

**Comment by chajchaj** [comment]
多谢关注~
AttentionLstm模型我们基于paddle2.0提供了更加易用的版本https://github.com/PaddlePaddle/PaddleVideo/，
关于数据集参考https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/dataset/youtube8m.md

**Comment by pele228** [comment]
> 多谢关注~
> AttentionLstm模型我们基于paddle2.0提供了更加易用的版本[https://github.com/PaddlePaddle/PaddleVideo/，](https://github.com/PaddlePaddle/PaddleVideo/%EF%BC%8C)
> 关于数据集参考https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/dataset/youtube8m.md

你好，可否提供AttentionLstm模型训练的pkl包数据集的具体格式，类似于Kinetics的(video-id,[frame1, frame2,...,frameN],label)，YouTube8m数据集下载难度太大，我想通过mp4文件直接转pkl包。
