### ISSUE TITLE
paddleclas初体验错误，求帮忙看看是哪里没有设置对?

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/models#5179]
参考的官方链接：https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/tutorials/quick_start.md
使用3.1 零基础训练：不加载预训练模型的训练
基于ResNet50_vd模型，训练脚本如下所示。

export CUDA_VISIBLE_DEVICES=0
python -m paddle.distributed.launch \
    --gpus="0" \
    tools/train.py \
        -c ./configs/quick_start/ResNet50_vd.yaml

然后报出的错误如下

`2021-01-07 01:55:54 INFO: valid_interval : 1
2021-01-07 01:55:54 INFO: validate : True
W0107 01:55:54.222257 19002 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 10.0
W0107 01:55:54.225203 19002 device_context.cc:330] device: 0, cuDNN Version: 7.6.
2021-01-07 01:55:56 ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/ppx/Clas/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 771, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

INFO 2021-01-07 01:56:02,351 launch_utils.py:308] terminate all the procs
ERROR 2021-01-07 01:56:02,352 launch_utils.py:546] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-01-07 01:56:05,355 launch_utils.py:308] terminate all the procs
`
总的运行记录如下
[报错.txt](https://github.com/PaddlePaddle/models/files/5777391/default.txt)

**Comment by littletomatodonkey** [comment]
数据路径没问题的话，设置下num_workers为0试下哈，或者拉一下最新代码

https://github.com/PaddlePaddle/PaddleClas/blob/21dc73f724141717c1ee12e0f5415ba7a9442928/configs/quick_start/ResNet50_vd.yaml#L32

https://github.com/PaddlePaddle/PaddleClas/blob/21dc73f724141717c1ee12e0f5415ba7a9442928/configs/quick_start/ResNet50_vd.yaml#L54

**Comment by yizhipipixia** [comment]
> 数据路径没问题的话，设置下num_workers为0试下哈，或者拉一下最新代码
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/21dc73f724141717c1ee12e0f5415ba7a9442928/configs/quick_start/ResNet50_vd.yaml#L32
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/21dc73f724141717c1ee12e0f5415ba7a9442928/configs/quick_start/ResNet50_vd.yaml#L54

经过测试发现错误是为图片路径不对（因为wegt太慢为用idm下载后解压过去的 所以多了一层路径....）
