### ISSUE TITLE
使用paddleclas进行模型预测得到的输出怎样理解？

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/models#5184]
参考的官方链接：https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/tutorials/getting_started.md

自己制作的只有两个分类（0和1两个标签）的图形数据集进行训练得到的关于ResNet50_vd的预训练模型，然后根据手册调用模型进行预测，但是不怎么能理解输出结果top1,top2，top3，以及使用inference模型得到的top-1 class，top-1 score等等的含义，即我应该主要参考输出的什么参数，来判断输入的图片属于什么类型呢？希望能够得到解答。

**1.自己数据集的标签结构（只有0，1两个类别）：**
`photos/2kNifOOKx6HcVtfoskeZDQ.jpg 0
photos/2kOFbSSqFi_vSqWFB1Ukqw.jpg 1`

**2.使用自己训练出的预训练模型进行模型预测**

`python tools/infer/infer.py \
    --image_file ./dataset/yelp/photos/37Wz9h1CqMCPgudoWCmm3g.jpg\
    --model ResNet50_vd \
    --pretrained_model "./output/ResNet50_vd/best_model/ppcls" \
    --use_gpu True \
    --load_static_weights False`

    **输出：**
`/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Callable
W0108 02:58:56.253964  4775 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 10.0
W0108 02:58:56.257138  4775 device_context.cc:330] device: 0, cuDNN Version: 7.6.
/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1245: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 102], but the expected shape is [2048, 1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))

/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1245: UserWarning: Skip loading for out.bias. out.bias receives a shape [102], but the expected shape is [1000].

  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))

Current image file: ./dataset/yelp/photos/37Wz9h1CqMCPgudoWCmm3g.jpg

        top1, class id: 196, probability: 0.0012
        top2, class id: 96, probability: 0.0012
        top3, class id: 772, probability: 0.0012
        top4, class id: 504, probability: 0.0012
        top5, class id: 467, probability: 0.0012
`

**3.使用预训练模型转换的inference模型进行模型推理：**

`python tools/infer/predict.py \
    --image_file ./dataset/tu/_1AVl8QmfnDx1pmTxkFh7A.jpg \
    --model_file "./inference/inference.pdmodel" \
    --params_file "./inference/inference.pdiparams" \
    --use_gpu=True \
    --use_tensorrt=False`

     **输出：**

`/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Callable

Current image file: ./dataset/tu/_1AVl8QmfnDx1pmTxkFh7A.jpg

        top-1 class: 409

        top-1 score: 0.0014189358334988356
`

**Comment by littletomatodonkey** [comment]
你好，根据下面这个信息，看出你训练的时候，类别数设置的是102，因此在infer的时候需要将class_num参数指定为102

```
/home/ppx/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1245: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 102], but the expected shape is [2048, 1000].
```

https://github.com/PaddlePaddle/PaddleClas/blob/8e26493c329f07623438c6c32824bb7bc8e29aa9/tools/infer/utils.py#L56

**Comment by littletomatodonkey** [comment]
如果是2分类，需要把这里改成2

https://github.com/PaddlePaddle/PaddleClas/blob/8e26493c329f07623438c6c32824bb7bc8e29aa9/configs/quick_start/ResNet50_vd_finetune.yaml#L6


同时把topk改为1（topk不能大于类别数）

https://github.com/PaddlePaddle/PaddleClas/blob/8e26493c329f07623438c6c32824bb7bc8e29aa9/configs/quick_start/ResNet50_vd_finetune.yaml#L12

**Comment by yizhipipixia** [comment]
> 如果是2分类，需要把这里改成2
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/8e26493c329f07623438c6c32824bb7bc8e29aa9/configs/quick_start/ResNet50_vd_finetune.yaml#L6
> 
> 同时把topk改为1（topk不能大于类别数）
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/8e26493c329f07623438c6c32824bb7bc8e29aa9/configs/quick_start/ResNet50_vd_finetune.yaml#L12

恩已改，后面发现还要改 export_model.py这个转换程序里的class_idm这个参数！

**Comment by zhangting2020** [comment]
@yizhipipixia 请问是否已解决您的问题？如果已解决，我们将关闭issue

**Comment by yizhipipixia** [comment]
> @yizhipipixia 请问是否已解决您的问题？如果已解决，我们将关闭issue

是的 已解决，多谢帮助
