### ISSUE TITLE
DeepSpeech报错

### ISSUE THREAD

**Issue by DemonWang555** [PaddlePaddle/models#5204]
在提供的容器内进行普通话的训练、预估、评价。
进行推断sh run_infer_golden.sh时报错，应该是paddle.fluid问题。
  File "/DeepSpeech/model_utils/network.py", line 62, in <module>
    class RNNCell(fluid.layers.RNNCell):
AttributeError: 'module' object has no attribute 'RNNCell'

**Comment by iclementine** [comment]
这个目前只能支持 1.8

**Comment by ZeyuChen** [comment]
@wpcbupt 我们即将启动DeepSpeech的2.0版本升级，预计4月份完成。

**Comment by ZeyuChen** [comment]
@wpcbupt https://github.com/PaddlePaddle/DeepSpeech
paddle 2.0版本的DeepSpeech已升级完毕，可以试下给我们反馈，谢谢！
