### ISSUE TITLE
BMN 推断失败

### ISSUE THREAD

**Issue by jishixin** [PaddlePaddle/models#5233]
E:\PythonProject\models\PaddleCV\video> python predict.py --model_name BMN --config configs/bmn.yaml --log_interval 1 --weights .\models\bmn\BMN
DALI is not installed, you can improve performance if use DALI
[INFO: predict.py:  199]: Namespace(batch_size=1, config='configs/bmn.yaml', filelist=None, infer_topk=20, log_interval=1, model_name='BMN', save_dir='data\\predict_results', use_gpu=True, video_path=None, weights='.\\models\\bmn\\BMN')
[INFO: config_utils.py:   69]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:data/dataset/bmn/activitynet_1.3_annotations.json
[INFO: config_utils.py:   74]:     feat_path:data/dataset/bmn/fix_feat_100
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W0126 21:49:35.488451 13780 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.3, Runtime API Version: 10.1
W0126 21:49:35.509438 13780 device_context.cc:330] device: 0, cuDNN Version: 7.6.
test subset video numbers: 5
Traceback (most recent call last):
  File "predict.py", line 201, in <module>
    infer(args)
  File "predict.py", line 125, in infer
    assert os.path.exists(
AssertionError: Given weight dir .\models\bmn\BMN not exist.

运行命令中的 --weights 加不加后缀都试过了

**Comment by huangjun12** [comment]
we recommend to use our new repo: https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/model_zoo/localization/bmn.md
