### ISSUE TITLE
paddle2.0和paddlenlp loss.backward()错误

### ISSUE THREAD

**Issue by littlepan0413** [PaddlePaddle/models#5235]
环境
paddlecloudplatform    3.0.7
paddlehub              1.8.3
paddlenlp              2.0.0b3
paddlepaddle-gpu       2.0.0rc1
paddleslim             1.1.0
![image](https://user-images.githubusercontent.com/6512760/105965697-b57f3e80-60be-11eb-99ab-f605ce238fc7.png)

错误
【dev】step: 0 - loss: 3.521899 precision: 0.000, recall: 0.009, f1: 0.001 current best 0.000
==============================================save best model best performerence 0.000848
Traceback (most recent call last):
  File "sequence_labeling.py", line 235, in <module>
    loss.backward()
  File "<decorator-gen-113>", line 2, in backward
  File "/home/work/mnt/project/.local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/mnt/project/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 223, in __impl__
    return func(*args, **kwargs)
  File "/home/work/mnt/project/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 176, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
2   paddle::operators::DropoutOpGrad::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: GradOp is only callable when is_test is false
  [Hint: Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.] (at /paddle/paddle/fluid/operators/dropout_op.cc:122)

**Comment by ZeyuChen** [comment]
能否提供更多信息？运行的是哪个模型代码示例？@littlepan0413

**Comment by Steffy-zxf** [comment]
你好！根据以上错误信息，
> InvalidArgumentError: GradOp is only callable when is_test is false

应该是在模型训练时没有切换model的训练模式，可以 在评估结束之后，手动改成model.train()。

通过线下沟通，问题已解决。
