### ISSUE TITLE
I can't find the model aboutface recognition

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/models#5248]

**Comment by zgsxwsdxg** [comment]
I am looking forward to your reply，ths.

**Comment by zhwesky2010** [comment]
@zgsxwsdxg 您好，https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleCV/face_detection 这是人脸检测模型

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 您好，https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleCV/face_detection 这是人脸检测模型

谢谢，我指的是人脸识别模型，不是检测

**Comment by zhwesky2010** [comment]
@zgsxwsdxg 目前仓库还没有人脸识别，后面可能会在paddleClas里增加

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 目前仓库还没有人脸识别，后面可能会在paddleClas里增加

谢谢
