### ISSUE TITLE
paddlenlp如何指定GPU训练？

### ISSUE THREAD

**Issue by Minjuner-97** [PaddlePaddle/models#5252]
在运行paddlenlp的mrc任务的时候出现设置CUDA_VISIBLE_DEVICES = 1，训练的时候仍然使用 gpu = 0来训练，请问如何彻底解决这个问题？

**Comment by joey12300** [comment]
> 在运行paddlenlp的mrc任务的时候出现设置CUDA_VISIBLE_DEVICES = 1，训练的时候仍然使用 gpu = 0来训练，请问如何彻底解决这个问题？

你好，如果你执行CUDA_VISIBLE_DEVICES='1' python xxx.py， 实际上是使用了1号卡进行训练，但显示仍然会是0号卡，这个可以通过nvidia-smi查询显存占用情况

**Comment by Minjuner-97** [comment]
谢谢，我的问题可能没有阐述清楚~我想指定第二块GPU进行训练，目前已经解决了。
在所有的GPU都可视的情况下：
paddle.set_device("gpu:0" if args.n_gpu else "cpu")
在这句中，代表指定第0块GPU
若是：paddle.set_device("gpu:1" if args.n_gpu else "cpu")
在这句中，代表指定第1块GPU

**Comment by ZeyuChen** [comment]
@Minjuner-97 https://github.com/PaddlePaddle/PaddleNLP
PaddleNLP以迁移至独立Repo，欢迎在新Repo上给我们反馈关注，谢谢。
