### ISSUE TITLE
一个死链接，请修复

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/models#5275]
死链接：
https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/examples/examples/named_entity_recognition/express_ner

位置：
https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/examples

模型 | 简介
-- | --
BiGRU-CRF

**Comment by ZHUI** [comment]
好的，感谢您的反馈，我们会尽快修复。

另外，PaddleNLP目前独立了新的repo，后续的大部分代码会在这边更新：
 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples

欢迎关注、fork、star！

**Comment by guojiahuiEmily** [comment]
谢谢
