### ISSUE TITLE
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/models/nextvlad/README.md

### ISSUE THREAD

**Issue by Haidong-Kang** [PaddlePaddle/models#5291]
NeXtVLAD模型是第二届Youtube-8M视频理解竞赛中效果最好的单模型，在参数量小于80M的情况下，能得到高于0.87的GAP指标。该模型提供了一种将桢级别的视频特征转化并压缩成特征向量，以适用于大尺寸视频文件的分类的方法。其基本出发点是在NetVLAD模型的基础上，将高维度的特征先进行分组，通过引入attention机制聚合提取时间维度的信息，这样既可以获得较高的准确率，又可以使用更少的参数量。详细内容请参考[NeXtVLAD: An Efficient Neural Network to Aggregate Frame-level Features for Large-scale Video Classification](https://arxiv.org/abs/1811.05014)。

该模型提供了一种将桢级别的视频特征转化并压缩成特征向量->帧级别

**Comment by huangjun12** [comment]
很细节！ 收到~

**Comment by huangjun12** [comment]
该video库已迁移至新的github地址：https://github.com/PaddlePaddle/PaddleVideo 欢迎大家去新的代码仓库中，查看与阅读更多关于视频模型及应用的详细介绍以及新功能。

**Comment by huangjun12** [comment]
修复pr: https://github.com/PaddlePaddle/models/pull/5298
