### ISSUE TITLE
CV video_tag中，3000个标签是什么及模型训练的AUC和准确率是什么

### ISSUE THREAD

**Issue by zhangweijiqn** [PaddlePaddle/models#5296]
想用一下飞桨的视频标签模型，有些疑惑的地方：
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/hub_module/modules/video/classification/videotag_tsn_lstm
![Uploading image.png…]()
需要的是：
1. 3000个标签是哪些
2. 模型训练的AUC和准确率是什么

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleVideo/tree/application/VideoTag  可以参考这里~

**Comment by zhangweijiqn** [comment]
标签找到了，文件路径为：PaddleHub/modules/video/classification/videotag_tsn_lstm/resource/label_3396.txt
