### ISSUE TITLE
paddle该怎么实现类似pytorch中对上下文的局部参数禁止求梯度的功能呢？比如torch._C.set_grad_enabled(False)

### ISSUE THREAD

**Issue by aiot-tech** [PaddlePaddle/models#5314]

**Comment by saxon-zh** [comment]
可以用paddle.set_grad_enabled这个API来操作

**Comment by saxon-zh** [comment]
"""
    :api_attr: imperative

    Create a context which enables or disables dygraph gradient calculation.

    Args:
        mode(bool): whether to enable (`True`), or disable (`False`) grad.

    Examples:
        .. code-block:: python
            x = paddle.ones([3, 2])
            x.stop_gradient = False
            with torch.set_grad_enabled(False):
                y = x * 2
                with torch.set_grad_enabled(True):
                    z = x * 2
            print(y.stop_gradient)   # True
            print(z.stop_gradient)   # False
    """

**Comment by saxon-zh** [comment]
```python
x = paddle.ones([3, 2])
x.stop_gradient = False
with paddle.set_grad_enabled(False):
    y = x * 2
    with paddle.set_grad_enabled(True):
        z = x * 2
print(y.stop_gradient)   # True
print(z.stop_gradient)   # False
```
