### ISSUE TITLE
no have kpi.py

### ISSUE THREAD

**Issue by youdation** [PaddlePaddle/models#5315]
PaddleNLP\pretrain_language_models\BERT 
run ./_run_ce.sh
![image](https://user-images.githubusercontent.com/40634721/120807710-cf53f500-c57a-11eb-9dca-e596754afffe.png)
no share all the code

**Comment by chenxiaozeng** [comment]
您好，没有找到您提到的目录，方便贴一个完整github路径嘛
另外，bert模型可以参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/transformers/bert
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert

**Comment by ZeyuChen** [comment]
Please refer to this repo. https://github.com/PaddlePaddle/PaddleNLP @youdation
