### ISSUE TITLE
release 1.8 下 度量学习无法训练

### ISSUE THREAD

**Issue by Bobo-y** [PaddlePaddle/models#5325]
机器： mac book pro
环境：
 docker 安装 hub.baidubce.com/paddlepaddle/paddle:1.8.0

数据集：Stanford_Online_Products

命令： 
`export CPU_NUM=4`
`python3 train_elem.py --model=ResNet50 --train_batch_size=256  --test_batch_size=4  --lr=0.01  --total_iter_num=30000   --use_gpu=False  --model_save_dir=save_model   --loss_name=arcmargin  --arc_scale=80.0`

报错信息：

root@509278317f3f:/paddle# python3 train_elem.py --model=ResNet50 --train_batch_size=256  --test_batch_size=4  --lr=0.01  --total_iter_num=30000   --use_gpu=False  --model_save_dir=save_model   --loss_name=arcmargin  --arc_scale=80.0
-----------  Configuration Arguments -----------
arc_easy_margin: False
arc_margin: 0.15
arc_scale: 80.0
checkpoint: None
class_dim: 11318
display_iter_step: 10
embedding_size: 0
enable_ce: False
image_shape: 3,224,224
loss_name: arcmargin
lr: 0.01
lr_steps: 15000,25000
lr_strategy: piecewise_decay
model: ResNet50
model_save_dir: save_model
pretrained_model: None
save_iter_step: 1000
test_batch_size: 4
test_iter_step: 1000
total_iter_num: 30000
train_batch_size: 256
use_gpu: 0
------------------------------------------------
train dataset size: 11318
W0716 02:53:18.506563  2099 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0716 02:53:19.158396  2099 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 160. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 160.
/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train_elem.py", line 317, in <module>
    main()
  File "train_elem.py", line 313, in main
    train_async(args)
  File "train_elem.py", line 233, in train_async
    lr, loss, acc1, acc5 = train_exe.run(feed=train_batch,fetch_list=train_fetch_list)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 876, in _run_parallel
    exe.feed_tensors_into_local_scopes(res)
paddle.fluid.core_noavx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::ParallelExecutor::FeedTensorsIntoLocalScopes(std::vector<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > >, std::allocator<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > > > const&)

----------------------
Error Message Summary:
----------------------
UnimplementedError: The feed data number 1 does not match the device number 4. If you are using DataLoader to feed data, this may be because you set drop_last=False in training network. Currently, drop_last=False for DataLoader is not supported for training network. Please set drop_last=True when defining DataLoader.
  [Hint: Expected tensors.size() == member_->local_scopes_.size(), but received tensors.size():1 != member_->local_scopes_.size():4.] at (/paddle/paddle/fluid/framework/parallel_executor.cc:852)

terminate called recursively
terminate called recursively
terminate called recursively
terminate called without an active exception
W0716 02:53:23.828729  2136 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0716 02:53:23.829792  2136 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0716 02:53:23.829843  2136 init.cc:221] The detail failure signal is:

W0716 02:53:23.831596  2136 init.cc:224] *** Aborted at 1626404003 (unix time) try "date -d @1626404003" if you are using GNU date ***
W0716 02:53:23.931061  2136 init.cc:224] PC: @                0x0 (unknown)
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault

代码没有修改，使用的原始代码

**Comment by zhwesky2010** [comment]
@yl305237731 你好，看起来是源码有些强制，这里train_batch是一个长度为1的list，所以就强制了CPU_NUM只能为1

**Comment by Bobo-y** [comment]
@zhouwei25 数据没问题，没用docker 就跑起来了

**Comment by zhwesky2010** [comment]
如果不指定CPU_NUM，则默认为1，可以在docker下去掉export CPU_NUM=4试试
