### ISSUE TITLE
models/docs/ThesisReproduction_CV.md 文档错误

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/models#5353]
第 5 章 5.1 中部分内容存在错误，如下图所示：
![image](https://user-images.githubusercontent.com/34644177/135592825-4a552c7d-8ec6-42d9-81c4-af25f1f928a9.png)

**Comment by littletomatodonkey** [comment]
好的，感谢反馈，在这里修复了哈 #5354
