### ISSUE TITLE
遇到一个问题，Evaluator.cpp:460] Check failed: binIdx <= kBinNum_ bin index [4288776562] out of range, predict value[-0.368997]

### ISSUE THREAD

**Issue by immaster** [PaddlePaddle/models#560]
`F1228 13:33:18.571247  7082 Evaluator.cpp:460] Check failed: binIdx <= kBinNum_ bin index [4288776562] out of range, predict value[-0.368997]
*** Check failure stack trace: ***
    @     0x7fc2943d426d  google::LogMessage::Fail()
    @     0x7fc2943d60df  google::LogMessage::SendToLog()
    @     0x7fc2943d3e13  google::LogMessage::Flush()
    @     0x7fc2943d69fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc2941d486b  paddle::AucEvaluator::evalImp()
    @     0x7fc2941d409b  paddle::Evaluator::eval()
    @     0x7fc2941c0c08  paddle::CombinedEvaluator::eval()
    @     0x7fc29403042e  _wrap_GradientMachine_eval
    @     0x7fc2bc044bb0  PyEval_EvalFrameEx
    @     0x7fc2bc04457d  PyEval_EvalFrameEx
    @     0x7fc2bc046efd  PyEval_EvalCodeEx
    @     0x7fc2bc0443fc  PyEval_EvalFrameEx
    @     0x7fc2bc046efd  PyEval_EvalCodeEx
    @     0x7fc2bc0443fc  PyEval_EvalFrameEx
    @     0x7fc2bc046efd  PyEval_EvalCodeEx
    @     0x7fc2bc047002  PyEval_EvalCode
    @     0x7fc2bc06043f  (unknown)
    @     0x7fc2bc0615fe  PyRun_FileExFlags
    @     0x7fc2bc062889  PyRun_SimpleFileExFlags
    @     0x7fc2bc073a3f  Py_Main
    @     0x7fc2bb299c05  __libc_start_main
    @           0x40071e  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
`

**Comment by immaster** [comment]
运行 models/dssm/train.py 时发生的

**Comment by kangshantong** [comment]
怎么解决的，我也碰到了这个问题，而且只是在进行回归的时候才有这个问题，分类是没有问题的
