### ISSUE TITLE
用alexnet训练图片模型后，如何让模型判断非训练类别的图片

### ISSUE THREAD

**Issue by Datian1993** [PaddlePaddle/models#562]
目前想到的方案是，看模型给该图片在每个类上打的分值，设定一个阈值，低于这个值时，认为是其他分类图片。但这种方案效果不好，希望有更好的方案！

**Comment by sweetsky0901** [comment]
https://www.zhihu.com/question/59942109/answer/185169295
能百度到一些大家的思路，供参考

**Comment by Datian1993** [comment]
补充：该类问题可以认为是非训练类拒绝分类问题，即，训练时有苹果和梨两个类别，现在有一张桃子的照片，期望的结果是该照片不属于这两个类，而不是给出一个分值高的类。
方案：拿到softmax之前的绝对分值，看预测结果每个类的分值是否都很小，且方差也很小，即认为是可拒绝分类的图片。
