### ISSUE TITLE
models/deep_fm使用时报错

### ISSUE THREAD

**Issue by yufengwhy** [PaddlePaddle/models#569]
我用的是另外一个广告数据集[kaggle avazu](https://www.kaggle.com/c/avazu-ctr-prediction/data)。因为只用了类别特征，去掉了连续值特征对应的输入，运行几分钟后报错。谢谢大家的建议~

(paddle) ➜  deep_fm CUDA_VISIBLE_DEVICES=2 python train.py \
        --train_data_path data/train.txt \
        --test_data_path data/valid.txt
I0109 11:21:08.664938 31376 Util.cpp:166] commandline:  --use_gpu=1 --trainer_count=1
I0109 11:21:14.895238 31376 GradientMachine.cpp:94] Initing parameters..
I0109 11:21:14.985219 31376 GradientMachine.cpp:101] Init parameters done.
F0109 11:28:41.559394 31376 Matrix.cpp:653] Not supported
*** Check failure stack trace: ***
    @     0x7fd3475852fd  google::LogMessage::Fail()
    @     0x7fd347588dac  google::LogMessage::SendToLog()
    @     0x7fd347584e23  google::LogMessage::Flush()
    @     0x7fd34758a2be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd3473a6246  paddle::GpuMatrix::mul()
    @     0x7fd34720e8ef  paddle::FullyConnectedLayer::forward()
    @     0x7fd34728af8d  paddle::NeuralNetwork::forward()
    @     0x7fd34728bca3  paddle::GradientMachine::forwardBackward()
    @     0x7fd347561004  GradientMachine::forwardBackward()
    @     0x7fd3470fbad9  _wrap_GradientMachine_forwardBackward
    @     0x7fd3a543cbad  PyEval_EvalFrameEx
    @     0x7fd3a543dc3e  PyEval_EvalCodeEx
    @     0x7fd3a543d1f7  PyEval_EvalFrameEx
    @     0x7fd3a543dc3e  PyEval_EvalCodeEx
    @     0x7fd3a543d1f7  PyEval_EvalFrameEx
    @     0x7fd3a543dc3e  PyEval_EvalCodeEx
    @     0x7fd3a543d1f7  PyEval_EvalFrameEx
    @     0x7fd3a543dc3e  PyEval_EvalCodeEx
    @     0x7fd3a543d1f7  PyEval_EvalFrameEx
    @     0x7fd3a543dc3e  PyEval_EvalCodeEx
    @     0x7fd3a543dd52  PyEval_EvalCode
    @     0x7fd3a545e450  PyRun_FileExFlags
    @     0x7fd3a545e62f  PyRun_SimpleFileExFlags
    @     0x7fd3a5473fd4  Py_Main
    @     0x7fd3a466cf45  __libc_start_main
    @           0x400729  (unknown)
[1]    31376 abort (core dumped)  CUDA_VISIBLE_DEVICES=2 python train.py --train_data_path data/train.txt

**Comment by will-am** [comment]
输入是稀疏的时候deepfm不支持用gpu，把`--use_gpu=1 `改为`--use_gpu=0`应该可以运行了

**Comment by yufengwhy** [comment]
@will-am 谢谢你的回答，好赞，paddle总能够很快得到回复。另外，请问，
python train.py \
        --train_data_path data/train.txt \
        --test_data_path data/valid.txt \
        2>&1 | train.log
运行的时候说zsh command not found train.log
有什么建议吗？谢谢

**Comment by will-am** [comment]
应该是`| tee train.log`

**Comment by yufengwhy** [comment]
https://github.com/PaddlePaddle/models/tree/develop/deep_fm
那你们需要修改这个了

**Comment by will-am** [comment]
是的呢，我修改下

**Comment by yufengwhy** [comment]
@will-am 我刚刚跑了一下[kaggle avazu](https://www.kaggle.com/c/avazu-ctr-prediction/data)，大概4千万samples，估计跑一轮得一天吧。你们知道deepfm用GPU大概多久跑一轮？什么时候paddle退出支持GPU的deepfm？谢谢

**Comment by will-am** [comment]
输入是dense vector的话现在deepfm就支持用GPU，输入是稀疏的话即使能用GPU通常也会比CPU慢，因为稀疏数据几乎无法利用GPU的并行性。
