### ISSUE TITLE
文本分类model的问题

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/models#578]
我按照下面的说明，修改run.sh
```
#!/bin/sh

python train.py \
--nn_type="dnn" \
--batch_size=64 \
--train_data_dir="/root/桌面/baidu/model/text_classification/traindata/" \
--word_dict="/root/桌面/baidu/model/text_classification/worddict/" \
--lable_dict="/root/桌面/baidu/model/text_classification/labledict/" \
--num_passes=10 \
2>&1 | tee train.log
~                      
```
但是执行的时候报错
usage: train.py [-h] [--nn_type NN_TYPE] [--train_data_dir TRAIN_DATA_DIR]
                [--test_data_dir TEST_DATA_DIR] [--word_dict WORD_DICT]
                [--label_dict LABEL_DICT] [--batch_size BATCH_SIZE]
                [--num_passes NUM_PASSES] [--model_save_dir MODEL_SAVE_DIR]
train.py: error: unrecognized arguments:  
run2.sh:行7: --train_data_dir=/root/桌面/baidu/model/text_classification/traindata/: 没有那个文件或目录

这个路径实际是存在的
[root@localhost text_classification]# ls /root/桌面/baidu/model/text_classification/traindata/
train.data

**Comment by JiayiFeng** [comment]
当路径中存在中文时，有出错的可能，请换成纯英文路径尝试
