### ISSUE TITLE
在目标检测的例子上,能否只使用VOC2007数据集

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#588]
这个是目标检测的例子[https://github.com/PaddlePaddle/models/tree/develop/ssd](https://github.com/PaddlePaddle/models/tree/develop/ssd),它使用了VOC2007和VOC2012的数据集,但是VOC2012实在太大了,能否只是用VOC2007?

**Comment by NHZlX** [comment]
把 https://github.com/PaddlePaddle/models/blob/develop/ssd/data/prepare_voc_data.py#L7 中的　`2012` 去掉

**Comment by yeyupiaoling** [comment]
@NHZlX 了解，感谢回答
