### ISSUE TITLE
Please fix this typo

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/models#64]
I don't have permission to revise it.

<img width="972" alt="2eeb7a4593b97ba8d414270b456d8d7a" src="https://cloud.githubusercontent.com/assets/3071933/26715083/d7738bca-47a6-11e7-97f9-b8515dae66c3.png">

**Comment by JiayiFeng** [comment]
I don't have permission either...

**Comment by lcy-seso** [comment]
This has been fixed.
