### ISSUE TITLE
Add sequence labeling model for Fluid.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#644]
Add sequence labeling model which can be tasks like NER or SRL in NLP to https://github.com/PaddlePaddle/models/tree/develop/fluid .

Can take this model https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner as a reference, or any other state-of-art model.

**Comment by guru4elephant** [comment]
get

**Comment by lcy-seso** [comment]
Thank you for taking this work.
