### ISSUE TITLE
场景文字识别的例子中，使用到的神经网络是什么？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#680]
在这个场景文字识别https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition 中，使用到的是什么神经网络模型，告诉我，我好去看相关论文，谢谢

**Comment by peterzhang2029** [comment]
@yeyupiaoling 可以参考 "An End-to-End Trainable Neural Network for Image-based Sequence
Recognition and Its Application to Scene Text Recognition"

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
这个是否可以：http://blog.csdn.net/Quincuntial/article/details/77679419

**Comment by peterzhang2029** [comment]
@yeyupiaoling 可以的

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
您好，请您回答一下这个问题：https://github.com/PaddlePaddle/Paddle/issues/10517
