### ISSUE TITLE
text_classification model, 不支持paddle 0.10 ？报错

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/models#698]
1. 安装了paddle 0.10 
2. git 下载了models
3. 运行text classification. 开始下载数据
4. 报错
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    main(args)
  File "train.py", line 167, in main
    model_save_dir=args.model_save_dir)
  File "train.py", line 101, in train
    paddle.init(use_gpu=False, trainer_count=1)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/v2/__init__.py", line 133, in init
    set_omp_mkl_env_vars(kwargs.get('trainer_count', 1))
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/v2/__init__.py", line 105, in set_omp_mkl_env_vars
    num_cores = num_physical_cores()
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/v2/__init__.py", line 86, in num_physical_cores
    os.popen("lscpu |grep \"Socket\" |awk -F':' '{print $2}'|xargs")
ValueError: invalid literal for int() with base 10: ''
5. 什么都没改...直接git下来的代码就报的这个错

**Comment by luotao1** [comment]
请升级版本，这个错误在0.11.0中已经修复了。

**Comment by VamWolf** [comment]
Thread [140475888629504] Forwarding __fc_layer_0__, 
*** Aborted at 1520479785 (unix time) try "date -d @1520479785" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 16173 (TID 0x7fc31770f700) from PID 0; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7fc2d9a53d6a __kmp_register_root
    @     0x7fc2d9a5e11e __kmp_middle_initialize
    @     0x7fc2d9a47dae __kmp_api_omp_get_num_procs
    @     0x7fc2da17b2ae mkl_serv_get_num_stripes
    @     0x7fc2da030234 mkl_blas_sgemm_host
    @     0x7fc2da000a3b mkl_blas_sgemm
    @     0x7fc2d9f823c3 SGEMM
    @     0x7fc2d9f45881 cblas_sgemm
    @     0x7fc2e32fec69 paddle::gemm<>()
    @     0x7fc2e3327cab paddle::CpuMatrix::mul()
    @     0x7fc2e3334569 paddle::CpuMatrix::mul()
    @     0x7fc2e318b105 paddle::FullyConnectedLayer::forward()
    @     0x7fc2e31f684d paddle::NeuralNetwork::forward()
    @     0x7fc2e31d21d3 paddle::GradientMachine::forwardBackward()
    @     0x7fc2e33be684 GradientMachine::forwardBackward()
    @     0x7fc2e303ce29 _wrap_GradientMachine_forwardBackward
    @     0x7fc317804393 PyEval_EvalFrameEx
    @     0x7fc317806120 PyEval_EvalCodeEx
    @     0x7fc317804491 PyEval_EvalFrameEx
    @     0x7fc317806120 PyEval_EvalCodeEx
    @     0x7fc317804491 PyEval_EvalFrameEx
    @     0x7fc317806120 PyEval_EvalCodeEx
    @     0x7fc317804491 PyEval_EvalFrameEx
    @     0x7fc317806120 PyEval_EvalCodeEx
    @     0x7fc317804491 PyEval_EvalFrameEx
    @     0x7fc317804c46 PyEval_EvalFrameEx
    @     0x7fc317806120 PyEval_EvalCodeEx
    @     0x7fc317806232 PyEval_EvalCode
    @     0x7fc31782061c run_mod
    @     0x7fc3178206f0 PyRun_FileExFlags
    @     0x7fc317821bfc PyRun_SimpleFileExFlag
升级0.11 ，报这个错误

**Comment by ranqiu92** [comment]
可能与paddle版本有关，使用 pip install paddlepaddle 之后运行通过。
