### ISSUE TITLE
能否完善fluid下的OCR的文档

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/models#764]
在这个OCR例子中：https://github.com/PaddlePaddle/models/tree/develop/fluid/ocr_recognition
文档较少，能否完善一下文档，比如说说每个文件的作用。

**Comment by shanyi15** [comment]
Thank you for your suggestion, we'll collect it and refine this doc.

**Comment by yeyupiaoling** [comment]
我看到了文档，就差合并了。

**Comment by shanyi15** [comment]
hi @yeyupiaoling , 目前这个文档还在review程序中，请先参考https://github.com/wanghaoshuang/models/blob/53988dd3fcaecd5d4a84698053cec22c89bae3ff/fluid/ocr_recognition/README.md
谢谢~!

**Comment by yeyupiaoling** [comment]
@shanyi15 好的，非常感谢～
