### ISSUE TITLE
SSD model changing CLASS_NUM leads error

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/models#777]
No matter in PC or PaddleCloud, when I change the CLASS_NUM for the SSD model other than 21（class num of VOC dataset) and use my own dataset, the training cannot run and always occur the similar error:

Thread [0x7fffb74d33c0] Forwarding detection_output, 
*** Aborted at 1522136207 (unix time) try "date -d @1522136207" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fffae6f360a) received by PID 96282 (TID 0x7fffb74d33c0) stack trace: ***
    @     0x7fffae7c6b3a _sigtramp
Floating point exception: 8

Guess something wrong in paddle.layer.detection_output().

**Comment by wanghaoshuang** [comment]
1. 麻烦贴一下network and training scripts
2. 简要描述下你的数据
3. 您用的是paddle v2 API, 还是fluid API？

**Comment by bipedalBit** [comment]
1. models/ssd源码部分
把models/ssd/config/pascal_voc_conf.py第12行的__C.CLASS_NUM=21改为了__C.CLASS_NUM=3；
把models/ssd/train.py中paddle.init()的use_gpu参数置False；
把models/ssd/vgg_ssd_net.py中所有的pool_type参数由paddle.pooling.CudnnMax()替换为paddle.pooling.Max()。
2. 数据部分
在models/ssd/data目录下，以PASCAL数据集的格式及相同目录形式保存了一个2分类的图像检测数据集，将目录下的label_list文本改写为：
background
class1
class2
根据数据集保存形式调整了models/ssd/data/prepare_voc_data.py。
3. API
模型源码基本没改，看了一遍，没用任何fluid API。
P.S. CLASS_NUM = 21时，我们的数据集可以正常训练，但mAP明显比较低。

**Comment by pkuyym** [comment]
> 把models/ssd/vgg_ssd_net.py中所有的pool_type参数由paddle.pooling.CudnnMax()替换为paddle.pooling.Max()。
替换这个的目的是为了在CPU上面训练吗？CPU上无法保证。如果训练自己的数据集，这里有个参考：

https://github.com/PaddlePaddle/Paddle/issues/8530

**Comment by bipedalBit** [comment]
是的，分别在单机和集群上尝试CPU训练，已经尝试过初始化模型的部分parameters，还是会出现FPE问题，准备换gpu环境再做SSD的实验了。

**Comment by bipedalBit** [comment]
CPU集群、CPU单机、GPU单机环境下，将SSD的CLASS_NUM改为3，并参考[PaddlePaddle/Paddle#8530](https://github.com/PaddlePaddle/Paddle/issues/8530)尝试使用自主预训练的模型及paddle官方提供的预训练模型分别对我们的模型的参数进行过初始化，均反复出现浮点数异常，无法进行模型训练，希望尽快提出更健壮的解决方案。

**Comment by pkuyym** [comment]
@bipedalBit 很奇怪，加载预训练模型，理论上训练过程比较平稳，这点在挺多数据集上面有过验证，至于infer过程，可能model训练不充分，导致没有有效结果。
能否贴一下训练过程中的具体log？

**Comment by bipedalBit** [comment]
通常是加载完参数，开始第一个forward时就报PFE了，数据集比较小，只有220个样本，检测目标尺寸比较小，会是极端个例吗？

**Comment by pkuyym** [comment]
@bipedalBit 目标尺寸小的话，有可能有问题，小目标检测是SSD的一个弱点，如果方便的话，可以提供一些数据供复现吗？

**Comment by bipedalBit** [comment]
获得正确剪裁的预训练模型后，模型参数得到了较好初始化，不再出现浮点数异常了。
