### ISSUE TITLE
如何通过mkl_set_num_threads设置mkl线程数？

### ISSUE THREAD

**Issue by Sunny-Dr** [PaddlePaddle/models#778]
线上多线程预测遇到QPS问题，已通过设置环境变量MKL_NUM_THREADS、OMP_NUM_THREADS解决。查阅issue发现还可以通过mkl库提供的API mkl_set_num_threads实现。请问该API应如何调用？

**Comment by wanghaoshuang** [comment]
我个人理解mkl_set_num_threads应该是mkl提供的API，所以你应该去查下mkl文档，然后include相应的头文件就行了。

**Comment by wanghaoshuang** [comment]
应该是不需要重新编译`paddle_shared.so`的.

**Comment by wanghaoshuang** [comment]
mkl_set_num_threads API: https://software.intel.com/en-us/mkl-developer-reference-c-mkl-set-num-threads

**Comment by Sunny-Dr** [comment]
感谢回复，十分有帮助~
