### ISSUE TITLE
models/deep_fm

### ISSUE THREAD

**Issue by yufengwhy** [PaddlePaddle/models#883]
这个实现没有加dropout吧？

没有加dropout，也可以跑到这个实验结果？（After training pass 9 batch 40000, the testing AUC is 0.807178 and the testing cost is 0.445196.）

我试验的时候，没有dropout的时候，deepfm=fm

**Comment by kuke** [comment]
@yufengwhy 这个模型的网络配置中确实没有dropout, 请问你的实验结果是？

**Comment by yufengwhy** [comment]
我没有跑这里的criteo数据集。在一个小数据集上面，deepfm效果并不好，deepfm=fm，所以看看你们怎么实现deepfm的。。

**Comment by kuke** [comment]
@yufengwhy deepfm的实现已经全部在这里了，在小数据集上效果不好可能是参数的问题，你可以在criteo上实际测试一下

**Comment by yufengwhy** [comment]
deepfm论文里面是有dropout的，

**Comment by yufengwhy** [comment]
我想知道，你这里报的结果After training pass 9 batch 40000, the testing AUC is 0.807178 and the testing cost is 0.445196，模型里面有没有dropout？

**Comment by kuke** [comment]
@yufengwhy 这个结果应该是没有加dropout训练出来的
