### ISSUE TITLE
what's mean of light_imdb and tiny_imdb

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/models#906]
Questions from @wojtuss: How can I get the dataset for the 'text_classification' model? It seems that it is imported to the scripts via python modules 'light_imdb' and 'tiny_imdb', but I cant find them anywhere.

@gmcather Could you help fix this problem? Thanks very much!

**Comment by gmcather** [comment]
Sorry for misleading, I refine the code, please refer to my pr. https://github.com/PaddlePaddle/models/pull/907

**Comment by luotao1** [comment]
@wojtuss This issue is fixed, you can update the latest code.
