### ISSUE TITLE
CI of model repo cannot be triggered.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#909]
It seems that the CI in Paddle Model repo cannot be triggered. Some of the PRs are not well formatted if CI cannot be triggered no check will guarantee some basic checks. @panyx0718

**Comment by panyx0718** [comment]
@lcy-seso Can you give a screenshot or more description?
Do you mean the unit tests cannot be triggered or the cpplint cannot be triggered?

**Comment by kuke** [comment]
I checked latest PRs, and find that all the travis-ci are not triggered.

**Comment by kuke** [comment]
Mr. Wang helped to reset the travis-ci, and it works now.

**Comment by panyx0718** [comment]
Thanks @kuke @lcy-seso @wanglei828

**Comment by lcy-seso** [comment]
Thanks, everyone. I close this issue due to the problem is solved.
