### ISSUE TITLE
Do you have a list of layers for all supported networks?

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/models#988]
Hi,

I need to find specific layer pairs which could be fused together into fused MKLDNN primitives with inference_transpiler.

Do you have a list of layers for each neural network topology supported by Paddle? That could save me a lot of time/work.  Or do I need to find out by reading source files or original publications?

**Comment by luotao1** [comment]
Sorry, we don't have specific layer pairs, maybe you should find out by reading original publications.

**Comment by sfraczek** [comment]
Oh, I know what pairs can be fused together. I just need the lists of layers present inside the networks.

**Comment by luotao1** [comment]
All the layers are here:
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#permalink-47-nn
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#permalink-114-ops
