### ISSUE TITLE
标签增强是什么

### ISSUE THREAD

**Issue by helen88** [PaddlePaddle/models#996]
https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/README_cn.md
![image](https://user-images.githubusercontent.com/4593091/41714439-f897fb5a-7582-11e8-8abb-26df7c8c4219.png)
这里的标签增强怎么理解？

**Comment by qingqing01** [comment]
@helen88 非常感谢，我们 https://github.com/PaddlePaddle/models/pull/997 在这里修改了。
